- lib/iris/fileformats/_ff_cross_references.py
- lib/iris/fileformats/ff.py
- lib/iris/tests/integration/test_ff.py
- lib/iris/tests/test_ff.py
Grid 21 is being handled correctly by Iris, it should be on a P grid. The documentation isn't clear but this has been decided as the land sea mask used for the compressing is on unstaggered theta points.
Stash item m01s00i207 wasn't in the STASH to grid type mapping so was getting a warning.
> Updating Iris' handled grids to include grid 21

- setup.py
Removes unnecessary conflict between setup version reference of
multiple branches.  Also Pep8 setup.
**Context:** Working from master and merging v1.7.x branch(es) (PRs yet to be merged) results in annoying conflicts with the version referenced in setup.py.  This PR simply makes setup.py reference the version identifier from the package directly.
> MAINT: Version references packages __init__

- lib/iris/analysis/__init__.py
- lib/iris/analysis/_linear.py
- lib/iris/tests/unit/analysis/linear/test_RectilinearRegridder.py
- lib/iris/tests/unit/analysis/test_Linear.py
First baby step forward to incorporating nearest neighbour regrid via the new API.
Rebrand the `LinearRegridder` as `RectilinearRegridder` akin to `RectilinearInterpolator`, so that we have a consistent API.
> LinearRegridder rebrand.

- lib/iris/analysis/__init__.py
- lib/iris/cube.py
Update the docstrings for `iris.cube.Cube.interpolate` and `iris.cube.Cube.regrid` with changes arising from the ongoing work to improve Iris interpolation and regridding routines.
> Update cube regrid and interpolate methods docstrings

- lib/iris/analysis/__init__.py
- lib/iris/tests/unit/analysis/test_Nearest.py
This PR exposes the `Nearest.regridder` method, thus hooking up the underlying implementation to the new API.
> Expose Nearest.regridder

- docs/iris/src/userguide/interpolation_and_regridding.rst
Updates the userguide chapter "Cube regridding and interpolation". This PR improves only the section on interpolation. The changes include adding a sub-section on caching an interpolator for repeated use, updating the available interpolation schemes and other general changes.
> Update userguide interpolation section

- docs/iris/src/userguide/interpolation_and_regridding.rst
- lib/iris/analysis/__init__.py
Improves the docstrings for the interpolator and regridder schemes `Linear`, `AreaWeighted` and `Nearest` in `iris.analysis`. This adds:
* the word "regridding" into the docstrings where these schemes have been extended to be used as a regridding scheme as well as an interpolation scheme,
* usage examples to each schemes' `regridder` method, and
* a comment on typical usage of the `callable` returned by each scheme's `interpolator` and `regridder` methods to the docstrings of these methods.
> Improve docstrings for interpolator/regridder schemes 

- lib/iris/fileformats/um_cf_map.py
long name 
water_flux_into_sea_water_from_rivers
is a valid standarad name
http://vocab.nerc.ac.uk/standard_name/water_flux_into_sea_water_from_rivers/
> lname>stdname

- conda-requirements.txt
An update to pep8 to 1.6.1 is causing test failures due to assignment of lambda functions etc. This is a short term fix.
> pinning pep8 to v1.5.7

- lib/iris/fileformats/grib/load_rules.py
- lib/iris/tests/unit/fileformats/grib/load_rules/test_convert.py
For Grib1, grib messages with a time range indicator of 2 aren't creating a time coordinate, so I've changed this to do so. 
I've also changed the warning for product definition templates as this is only applicable for grib edition 2.
> Grib1 - create a time coord when timeRangeIndicator is 2

- src/iris/fileformats/pp_packing/pp_packing.c
The underlying C unpack libary is quite slow, so reading data is often CPU-bound. By releasing the GIL we can perform multiple unpack operations in different threads and make much better use of disk read bandwidth. For example, on a machine with 4-cores (8-virtual cores with hyperthreading) and a 100 MB/s disk, running 8 threads that are executing Cube.data easily gets CPU usage above 700%.
> Release GIL when unpacking.

- lib/iris/fileformats/pp_rules.py
- lib/iris/fileformats/um_cf_map.py
- lib/iris/tests/results/pp_rules/rotated_uk.cml
- tools/gen_translations.py
- tools/translator/__init__.py
I have moved the implied stash height constraints our of the PP rules and into the um_cf_map, so that they live alongside the other STASH interpretations
I have updated the translator tools to source this information from the metarelate metOcean knowledge base. 
As the extra information in the knowledge base causes some translations to be lost with the tool on master currently, I have held off the merge of the constraint knowledge awaiting confirmation that these Iris changes are acceptable
https://github.com/metarelate/metOcean/pull/48
> Stash Height Constraints

- lib/iris/analysis/__init__.py
- lib/iris/cube.py
- lib/iris/tests/results/analysis/first_quartile_foo_1d.cml
- lib/iris/tests/results/analysis/first_quartile_foo_2d.cml
- lib/iris/tests/results/analysis/first_quartile_foo_bar_2d.cml
- lib/iris/tests/results/analysis/last_quartile_foo_3d_masked.cml
- lib/iris/tests/results/analysis/last_quartile_foo_3d_notmasked.cml
- lib/iris/tests/results/analysis/third_quartile_foo_1d.cml
- lib/iris/tests/unit/analysis/test_AdditiveAggregator.py
- lib/iris/tests/unit/analysis/test_COUNT.py
- lib/iris/tests/unit/analysis/test_MEAN.py
- lib/iris/tests/unit/analysis/test_PERCENTILE.py
- lib/iris/tests/unit/analysis/test_PROPORTION.py
- lib/iris/tests/unit/analysis/test_PercentileAggregator.py
- lib/iris/tests/unit/analysis/test_RMS.py
- lib/iris/tests/unit/analysis/test_STD_DEV.py
- lib/iris/tests/unit/analysis/test_VARIANCE.py
- lib/iris/tests/unit/cube/test_Cube.py
This PR is a re-factor of #1564. 
This PR extends the capability of the `PERCENTILE` aggregator such that it can calculate more than one percentile at a time, but it also addresses the issues of that functionality bleeding-thru to the `Cube` methods `aggregated_by`, `collapsed` and `rolling_window`, as per #1564.
The bleed-thru issues have pretty much melted away due to re-organising the aggregator class hierarchy, however in doing so, some minor changes to the API were necessary, namely:
* Explicit enforcement of any mandatory aggregator call keyword arguments i.e. the `function` keyword for `PROPORTION` and `COUNT`, and `percent` for `PERCENTILE`.
* The introduction of a `aggregator_shape` method, which is used by the `Cube.aggregated_by` method.
Thoughts on `aggregator_shape` are …
> Additive agg

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
This small pull request is intended to facilitate the situation wherein one wishes to query the data type of a cube without causing the cube's data payload to be loaded into memory, which can be an undesirable side effect for very large datasets which one intends to process later perhaps on a tile-by-tile basis (i.e. domain decomposition).
The current alternative - querying `cube.data.dtype` - appears to suffer from the aforementioned side effect (though with the obvious proviso that no additional time penalty is incurred if the data has already been loaded into memory).
> Added dtype property to iris.cube.Cube class

- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/tests/results/netcdf/netcdf_tmerc_and_climatology.cml
- lib/iris/tests/results/netcdf/save_load_traj.cml
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test__parse_cell_methods.py
- setup.py
This PR addresses #1438 allowing loading of CF-netCDF files with rich cell methods like `time: mean within years time: mean over years` that express climatologies. I've not enhance the `CellMethod` to give atomic access to the components of the multi word method, but I still check the first part of the method is a known. I'm not good at regular expressions so any advice is welcomed.
> Added basic support for climatology cell methods

- docs/iris/src/whatsnew/1.8.rst
A first draft for the what's new for Iris 1.8.
This is missing entries for:
* grib (relevant PRs: 1228 1300 1303 1313 1317 1305 1307 1321 1318 1322 1329 1330 1332 1341 1342 1337 1364 1353 1368 1362 1370 1375 1354 1358 1380 1382 1459 1461 1463 1467 1464 1468 1470 1466 1480 1481 1482 1475 1477 1486 1487 1488 1490 1529 1556)
* Fast structured FF loading (PRs: 1394 1395 1399 1397 1400 1402  1412 1410 1420 1415)
* And all PR's since 1570 (inclusive)
If needed, I have a document of all the PRs related to each bullet point and all the PRs that have not been documented (i.e. typos, changes in testing etc.)
> 1.8 What's New

- lib/iris/fileformats/pp.py
- lib/iris/tests/unit/fileformats/pp/test_PPField.py
Sample UM data from a mesoscale model was encountered with header values BPLAT=90 , BPLON=180.
This data then loads with a rotated pole coordinate system.
In fact, though, a rotated pole system with these settings is *identical* to normal plain lat-lon coordinates (unrotated).
A user complained that when this data was loaded in Iris and saved as GRIB, the resulting grid template was not as expected.
**This change allows Iris to recognise that this kind of data is 'unrotated'.**
Presumably the source of this data produces ouput in an arbitrary rotated system, of which this is the "degenerate case".  This only causes problems because of an oddity in the UM fields encoding :
For some odd reason (presumably historical), the UM fields use BPLAT,BPLON=90,0 as a signature meaning 'unrotated', …
> Treat um fields with BPLAT=90, BPLON=180 as unrotated.

- lib/iris/fileformats/grib/_load_convert.py
- lib/iris/tests/unit/fileformats/grib/load_convert/__init__.py
- lib/iris/tests/unit/fileformats/grib/load_convert/test_other_time_coord.py
- lib/iris/tests/unit/fileformats/grib/load_convert/test_product_definition_template_0.py
Adds support for significanceOfReferenceTime = 2, and fixes the handling of time within PDT0 to allow for the "reference time" coordinate being supplied as either "time" or "forecast_reference_time".
> Improved time handling for PDT0

- lib/iris/coord_systems.py
- lib/iris/tests/unit/coord_systems/test_RotatedPole.py
Provide the north_pole_grid_longitude degree of freedom to cartopy's RotatedGeodetic crs
This requires the cartopy pull request
https://github.com/SciTools/cartopy/pull/479
to function
> lon rotation

- lib/iris/tests/__init__.py
- lib/iris/tests/test_netcdf.py
Discovered while investigating the biggus 0.9 failures in #1560.
> Stop leaking temporary netCDF files.

- lib/iris/fileformats/grib/__init__.py
- lib/iris/fileformats/grib/_message.py
- lib/iris/tests/unit/fileformats/grib/__init__.py
- lib/iris/tests/unit/fileformats/grib/message/test__DataProxy.py
- lib/iris/tests/unit/fileformats/grib/test_load_cubes.py
remove regularise key word from grib load when using strict_grib_load
this is non-functional at present and the behaviour is not wanted so it should be removed before it is released
> remove regularise

- docs/iris/src/developers_guide/documenting/whats_new_contributions.rst
Improves the wording of the contributions page in the developer guide, building on #1583 and #1608.
Specifically this change defines what a contribution is and adjusts the wording of the document based on this definition of a contribution. It also reasserts the necessity that a contribution, as per the definition now added to the file, be ideally limited to a single concise bullet point.
> [DOC] What's new aggregation "contribution" description

- docs/iris/src/whatsnew/1.8.rst
- lib/iris/__init__.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test_save.py
- lib/iris/tests/unit/test_Future.py
added a switch to iris.FUTURE to enable the default unlimited dimension for netCDF sving to be avoided
added deprecation warning for the current default behaviour
> Ncunlimdep

- lib/iris/experimental/um.py
- lib/iris/tests/integration/test_FieldsFileVariant.py
Fixes a bug in iris.experimental.um.FieldsFileVariant (investigating support issue).
The effect is that for files over a certain size, the lookup headers begin to overwrite the data payloads
It doesn't happen for smaller files, because the data-start is rounded up to the next block boundary.
To see the problem:
```
ff_file = um.FieldsFileVariant(test_filepath, mode=um.FieldsFileVariant.UPDATE_MODE)
ff_file.close()
```
This replaces the file with a re-written copy, which is corrupted if the file contains too many fields.
This PR is effectively just a heads-up and placeholder, because it should also contain a test, which I don't currently have time to do.
> Fix bug in um.FieldsFileVariant output (no test yet).

- .travis.yml
- lib/iris/experimental/um.py
- lib/iris/tests/unit/experimental/um/test_FieldsFileVariant.py
This is a simple implementation to override lbrel when IMBI value is given. Setting to current latest value. 'Interactively tested', putting in some unit tests now - but feedback on my implementation would be welcome!
> Added handling for a missing value of lbrel. Tests to follow.

- lib/iris/fileformats/grib/__init__.py
The warning about the deprecated `auto_regularise` keyword was being issued on all loads for the new grib loader. Since it is not supported at all in that loader it is pointless to display the warning. Instead I've added a note to the docstring to explain the keyword has no effect when `iris.FUTURE.strict_grib_load = True` and moved the warning so it is only triggered for the old loader.
> Prevent warning about regularise when using new loader.

- lib/iris/fileformats/netcdf.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/results/integration/netcdf/TestLazySave/lazy_mask_preserve_fill_value.cdl
- lib/iris/tests/results/netcdf/netcdf_save_hybrid_height.cdl
- lib/iris/tests/results/netcdf/netcdf_save_multi_0.cdl
- lib/iris/tests/results/netcdf/netcdf_save_multi_1.cdl
- lib/iris/tests/results/netcdf/netcdf_save_multi_2.cdl
- lib/iris/tests/results/netcdf/netcdf_save_multiple.cdl
- lib/iris/tests/results/netcdf/netcdf_save_ndim_auxiliary.cdl
- lib/iris/tests/results/netcdf/netcdf_save_single.cdl
Currently the `fill_value` keyword argument to [createVariable](https://github.com/SciTools/iris/blob/7890a7292d988e3ce2fbf31559fcb5ba39dbb041/lib/iris/fileformats/netcdf.py#L1447) is not utilised
when writing a NetCDF file when the data is lazy.
Determining the `fill_value` is not straight forward as biggus returns a default value (not None) so how do we differentiate between an ordinary array (pass a `fill_value=None`) and a masked array (pass a  `fill_value = cube.lazy_data().fill_value`) without touching the data??
Here is a simple illustration of the problem if my added integration test is not good enough:
http://nbviewer.ipython.org/gist/cpelley/2da0b8dd347f7a4772e0
> BUG: Lazy cube with mask not saved correctly to NetCDF

- lib/iris/experimental/um.py
- lib/iris/tests/integration/test_FieldsFileVariant.py
- lib/iris/tests/unit/experimental/um/test_Field.py
refactor "almost" -- nothing has changed, except the 're-open' 
(cf. _DataProvider._with_source; idea pinched from https://github.com/pp-mo/iris/pull/14).
A preliminary to fixing the confusion over LBPACK handling in + out.
> Um refactor data providers

- .travis.yml
- lib/iris/tests/runner/_runner.py
This is similar to options included in Cartopy.
Not totally sure about the name of the option, but it seems to work, at least.
> Add option to print failed images as HTML.

- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_cube.py
This PR allows the `flag_masks`, `flag_meanings` and `flag_values` CF-NetCDF attributes to be passed through from the file-format into the associated `cube.attributes` and/or `coordinate.attributes` dictionaries.
The contents of the `attributes` dictionaries are already sourced by the NetCDF saver, thus this metadata can now be maintained losslessly through Iris.
> Pass thru CF-NetCDF flag attributes.

- lib/iris/experimental/um.py
- lib/iris/tests/integration/test_FieldsFileVariant.py
The code where a copy of the lookup is embedded in the data provider was wrong:
https://github.com/SciTools/iris/commit/fc98529d512e5b3f7a4372e054c962bf5cb0e889#diff-9afd04ec6db152872ae76b6a047cb46fL575
Because the 'ints' and 'reals' header values are *arrays* not lists, the '[:]' didn't make a copy.
So then when you set field.lbpack=0, you couldn't read the data anymore (!)
- i.e. field.get_data() fails.
- because changing field.lbpack also changes the lbpack  in the data provider
https://github.com/SciTools/iris/pull/1633 was supposed to have fixed this, but clearly it needed a bit more testing.
The enclosed test does that (fails under old code).
> Um fix lookup copy

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
There is a bug in the cube intersection code where 
```
np.where(pre_wrap_delta != post_wrap_delta)
```
can return a result due to numerical tolerances in the floating point coordinate value
I have trapped this and added a test.  This is a reported bug against 1.8.0, so please may it be targeted at the 1.8.1 milestone?
thank you
> numerical tolerance

- docs/iris/src/whatsnew/contributions_1.9/newfeature_2015-04-23_um_fieldsfiles_retain_packed_data.txt
- lib/iris/experimental/um.py
- lib/iris/tests/integration/test_FieldsFileVariant.py
- lib/iris/tests/unit/experimental/um/test_Field.py
Cope with changing LBPACK values in an update-mode FieldsFileVariant, and then closing to write it out.
Now allows saving : 
* "anything" (new data / unpacked source fields / WGDOS packed source fields) as unpacked 
* packed data as same-method packed (the "pass-through" option)
The 'pass-through' should also speedup updates to 'ordinary' unpacked files, as these can also be copied without interpretation.
NOTE: includes bits of https://github.com/SciTools/iris/pull/1618, which it intends to replace.
> Um packed passthru

- docs/iris/src/userguide/index.rst
- docs/iris/src/userguide/loading_iris_cubes.rst
- docs/iris/src/userguide/saving_iris_cubes.rst
- lib/iris/fileformats/grib/__init__.py
- lib/iris/fileformats/pp.py
- lib/iris/tests/stock.py
- lib/iris/tests/unit/fileformats/grib/test_as_messages.py
- lib/iris/tests/unit/fileformats/grib/test_as_pairs.py
- lib/iris/tests/unit/fileformats/grib/test_save_messages.py
- lib/iris/tests/unit/fileformats/pp/test_as_fields.py
- lib/iris/tests/unit/fileformats/pp/test_as_pairs.py
- lib/iris/tests/unit/fileformats/pp/test_save_fields.py
Deconstructed Save for GRIB and PP
as_messages | as_fields provides an interim step which may be used by users to adapt the field/message prior to saving
The save API is unchanged and all iris.save functionality is intended to be unchanged
Testing strategy: 
unit tests are added for as_fields|as_messages following the pattern from pp.save|grib.save
save unit tests and integration tests are left as is, which then test the save_message|save_field functions
Attempts to replace #1642
> Saver customisation

- lib/iris/fileformats/netcdf.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/results/integration/netcdf/TestSaveMultipleAuxFactories/hybrid_height_cubes.cml
This PR allows multiple individual auxiliary factories to be saved to the same NetCDF file.
This targets the use case where two hybrid height cubes with differing `orography` (aka `surface_altitude`) coordinates, but similar `sigma` and `delta` are saved to the same NetCDF file. The `formula_terms` attribute is attached to an auxiliary vertical coordinate, rather than a dimension coordinate. The NetCDF representation of these cubes should result in two auxiliary vertical coordinates with appropriately different `formula_terms` (due to the `orography` difference).
This PR does not cover the completely nasty case where the `formula_terms` is attached to a dimensional vertical coordinate. The current saver implementation will require to be revisited to support this case.
> Saving multiple individual aux-factories.

- docs/iris/src/whatsnew/1.8.rst
to address 
https://github.com/SciTools/scitools.org.uk/pull/109
@ajdawson please may you have a look and let me know if you think this is sufficient
I have picked fixes from:
https://github.com/SciTools/iris/commits/v1.8.1rc1
starting from Apr 15, 2015  when 1.8.0 was tagged
> 1.8.1 whats new bugs

- lib/iris/fileformats/grib/_save_rules.py
- lib/iris/tests/unit/fileformats/grib/save_rules/test_set_fixed_surfaces.py
new GRIB2 save translation, handling quantities on theta(air_potential_temperature) levels: Isentropic levels http://codes.wmo.int/grib2/codeflag/4.5/107
> theta fixed surface

- lib/iris/tests/integration/test_FieldsFileVariant.py
- lib/iris/tests/unit/experimental/um/test_FieldsFileVariant.py
Fixes a 'little oops' from #1652. The package name is `mo_pack`, not `mo_unpack`. The wrong name meant certain tests were doomed never to run. :fire: :fire_engine:
> Skip tests if they require mo_pack and it isn't found.

- lib/iris/_concatenate.py
- lib/iris/cube.py
I may be wrong about this, but I thought concatenate now plays nicely with deferred data, and hence these warnings are no longer necessary. This should go into the 1.8.1 release ideally.
> Remove warnings about data payload from concatenate.

- lib/iris/fileformats/pp_rules.py
- lib/iris/tests/test_pp_to_cube.py
- lib/iris/tests/unit/fileformats/pp_rules/test__all_other_rules.py
This PR enables a PP compound LBPROC of time mean and zonal(x_coord) mean to be loaded.
The cell method order is not important, as the operations are independent, which is valid within CF
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#statistics-more-than-one-axis
so an arbitrary order is applied
> unordered pp cell methods

- docs/iris/src/userguide/loading_iris_cubes.rst
- docs/iris/src/userguide/subsetting_a_cube.rst
Add a warning about constructing floating-point equalities to the Iris user guide, section 2.2. This is a near duplicate of the warning found in section 4.1.
The rationale for duplicating this warning to this section is that when I went to find the warning I expected to find it in this section and was surprised when I did not find it there. This means our docs are not as usable as they could be for a user.
> [DOC]: Add floating point equality warning

- lib/iris/cube.py
- lib/iris/fileformats/cf.py
The UserDict package is not available in Python 3, and added in 2.7.
> Replace UserDict with collections.MutableMapping.

- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/integration/test_pickle.py
Adds two missing `tests.skip_data` decorators. Running the tests with the `--no-data` option now gives me no errors.
> Add missing skip_test decorators.

- docs/iris/src/whatsnew/contributions_1.9/newfeature_2015-05-26_grib2_gdt30.txt
- lib/iris/fileformats/grib/_load_convert.py
- lib/iris/fileformats/grib/_message.py
- lib/iris/tests/integration/test_grib2.py
- lib/iris/tests/results/integration/grib2/TestGDT30/lambert.cml
- lib/iris/tests/unit/fileformats/grib/load_convert/test_grid_definition_template_30.py
- lib/iris/tests/unit/fileformats/grib/load_convert/test_projection_centre.py
- lib/iris/tests/unit/fileformats/grib/message/test__GribMessage.py
This PR adds load support for GDT-30 (Lambert conformal) to the new GRIB2 loader.
Replaces #1681 because I messed that branch up. @pelson - sorry for the inconvenience!
> Add GRIB2 support for Lambert conformal grids (GDT-30)

- lib/iris/tests/test_analysis.py
- lib/iris/tests/test_cdm.py
- lib/iris/tests/test_cell.py
- lib/iris/tests/test_cf.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/test_coordsystem.py
- lib/iris/tests/test_cube_to_pp.py
- lib/iris/tests/test_file_save.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/test_pp_to_cube.py
- lib/iris/tests/test_util.py
- lib/iris/tests/unit/coords/test_Coord.py
- lib/iris/tests/unit/cube/test_CubeList.py
- lib/iris/tests/unit/experimental/um/test_FieldsFileVariant.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
- lib/iris/tests/unit/fileformats/pp/test_PPField.py
assertEquals is deprecated and raises a warning on Python 3.
> py3k: Replace assertEquals with assertEqual.

- lib/iris/analysis/__init__.py
- lib/iris/tests/unit/analysis/test_WeightedPercentileAggregator.py
I appear to have missed a test in my original weighted percentile aggregator PR #1704.  It would have failed if returned=True.
> Weighted percentile fix

- lib/iris/tests/unit/analysis/test_WPERCENTILE.py
- lib/iris/tests/unit/analysis/test_WeightedPercentileAggregator.py
I pulled this out of #1700 because GitHub was being confusing about the necessary commits. Plus, it slightly muddies what's changed in that PR.
> py3k: Fix range usage in new tests.

- lib/iris/fileformats/pp.py
- lib/iris/tests/unit/fileformats/pp/test__LBProc.py
The value should be converted to an int first, since, e.g., `'-123' < 0` is `False` even though it's invalid. Additionally, `str < int` does not work in Python 3.
> Fix value check in _LBProc constructor.

- docs/iris/src/userguide/saving_iris_cubes.rst
This change copies the warning added in #1691 into the new 'Saving Iris Cubes' page of the Iris User Guide.
> Added warning on overwriting files being used for lazy data.

- lib/iris/analysis/_regrid.py
- lib/iris/analysis/_scipy_interpolate.py
- lib/iris/tests/unit/analysis/scipy_interpolate/test__RegularGridInterpolator.py
Some tests and a small docstring change to the sparse-matrix changes implemented on the decoupler branch.
> Rebase of Sparse-Matrix Interpolation from Decoupler Branch

- lib/iris/analysis/_interpolation.py
- lib/iris/experimental/regrid.py
- lib/iris/tests/unit/experimental/regrid/test_CurviliearRegridder.py
- lib/iris/tests/unit/experimental/regrid/test_PointInCell.py
Added point-in-cell as a regrid scheme. Note that the underlying regridder (`regrid_weighted_curvilinear_to_rectilinear`) still lives in `iris.experimental`, as do the code changes to provide point-in-cell as a regridder.
> Point-in-cell regrid scheme

- lib/iris/analysis/_scipy_interpolate.py
This `map` call added in #1706 does not work on Python 3.
aka, yet another reason to merge #1700.
> py3k: Fix newly added map call.

- lib/iris/fileformats/cf.py
It makes sense to have both elevation (`eta`) and bathymetry (`depth`) promoted to cubes on ocean models.
@rsignell-usgs I am not keen to add `s`, `c`, and `depth_c`.  What do you think?
@rhattersley We still need to type `iris.FUTURE.netcdf_promote = True` to get these cubes.  What are the plans to make that the default behavior?
> Promote netCDF var 'depth'

- lib/iris/experimental/regrid.py
- lib/iris/tests/unit/experimental/regrid/test_PointInCell.py
- lib/iris/tests/unit/experimental/regrid/test__CurvilinearRegridder.py
- lib/iris/tests/unit/fileformats/name_loaders/test__build_cell_methods.py
- lib/iris/tests/unit/fileformats/name_loaders/test__generate_cubes.py
- lib/iris/tests/unit/fileformats/pp/test_PPField.py
> Fix mock assertions

- lib/iris/analysis/cartography.py
- lib/iris/tests/test_analysis.py
- lib/iris/tests/unit/analysis/cartography/test__xy_range.py
Spotted this line whilst skimming the file looking for something else. I am assuming this was just a mistake and always meant to test `x_coord` and `y_coord`...
> Fix typo in iris.analysis.cartography._xy_range.

- docs/iris/src/userguide/cube_maths.rst
- docs/iris/src/userguide/cube_statistics.rst
- docs/iris/src/userguide/interpolation_and_regridding.rst
- docs/iris/src/userguide/iris_cubes.rst
- docs/iris/src/userguide/loading_iris_cubes.rst
- docs/iris/src/userguide/merge_and_concat.rst
- docs/iris/src/userguide/navigating_a_cube.rst
- docs/iris/src/userguide/plotting_a_cube.rst
- docs/iris/src/userguide/subsetting_a_cube.rst
- docs/iris/src/whatsnew/1.0.rst
- docs/iris/src/whatsnew/1.1.rst
- docs/iris/src/whatsnew/1.3.rst
- docs/iris/src/whatsnew/1.5.rst
- docs/iris/src/whatsnew/1.6.rst
- docs/iris/src/whatsnew/1.7.rst
- docs/iris/src/whatsnew/1.8.rst
- docs/iris/src/whitepapers/um_files_loading.rst
- lib/iris/unit.py
Just a few minor things to help with printing compatibility. In order to minimize the changes and avoid using `__future__`, I changed all the `print`s to only output a single item at a time.
> Doctest Python 3 compatibility

- lib/iris/analysis/maths.py
A very minor issue, but it's been bugging me...
The [`iris.analysis.maths.IFunc` documentation](http://scitools.org.uk/iris/docs/latest/iris/iris/analysis/maths.html?highlight=ifunc#iris.analysis.maths.IFunc) has the examples before the class definition, which is confusing.  I rearranged it and added some formatting to the examples.  There is no change to the information itself.
> IFunc docstrings

- lib/iris/fileformats/netcdf.py
Fixed broken link to netcdf conventions on ESRL website.
The link now goes over the line limit, but I wasn't sure whether to keep this in or make a new line halfway through?
> 'fixed broken link in netcdf.py'

- lib/iris/plot.py
- lib/iris/quickplot.py
Added the option to provide 'edgecolors' and 'linewidth' keywords to iris.plot and iris.quicklpot outline functions.
> Added line styling keyword arguments to plot outline functions

- docs/iris/src/whatsnew/1.8.rst
- lib/iris/tests/unit/fileformats/name_loaders/test__build_cell_methods.py
- lib/iris/tests/unit/fileformats/name_loaders/test__generate_cubes.py
- lib/iris/tests/unit/fileformats/pp/test_PPField.py
- lib/iris/unit.py
Addresses #1763 by back-porting 8c952371 into the v1.8.x maintenance branch.
Also back-ports fixes to make the test suite work after updates to mock.
> Backport 8c952371 into v1.8.x

- docs/iris/src/whatsnew/contributions_1.9/bugfix_2015-08-18_partial_pp_constraints.txt
- lib/iris/fileformats/pp.py
- lib/iris/tests/unit/fileformats/pp/test__convert_constraints.py
This PR is in response to a support ticket that found a bug when using an example `iris.AttributeConstraint` found in its documentation. The example constraint is:
iris.AttributeConstraint(STASH=lambda stash: stash.endswith('i005'))
When attempting to load a PP file with this constraint we get the following exception:
TypeError: Expected STASH code MSI string, got <function <lambda> at 0x27061b8>
I believe the bug was introduced in v1.7.x when a PP loading optimisation was made to allow constraints to be applied to STASH codes at load time without actually creating the cube first. The code allows only for constraints to be strings or STASH objects, not callables as above.
After discussion with @marqh we decided it might be good to keep this older functionality and so this PR contains a …
> Changed pp loading filter to accept callables as constraints

- docs/iris/example_code/General/custom_file_loading.py
- lib/iris/fileformats/__init__.py
- lib/iris/fileformats/pp.py
- lib/iris/tests/__init__.py
- lib/iris/tests/experimental/test_raster.py
- lib/iris/tests/test_file_save.py
- lib/iris/tests/test_io_init.py
- lib/iris/tests/test_util.py
- lib/iris/tests/unit/fileformats/pp/test__field_gen.py
- lib/iris/tests/unit/util/test_describe_diff.py
Use explicit binary I/O in several places. This does _not_ yet correctly handle Unicode (that's a much bigger issue.)
> Python3 binary I/O

- lib/iris/__init__.py
- lib/iris/aux_factory.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/grib/_save_rules.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/rules.py
- lib/iris/tests/test_load.py
- lib/iris/tests/unit/fileformats/grib/save_rules/test_set_time_range.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_aux_factory.py
- lib/iris/tests/unit/io/test_run_callback.py
- lib/iris/tests/unit/unit/test_suppress_unit_warnings.py
- lib/iris/tests/unit/util/test_file_is_newer_than.py
- lib/iris/util.py
Some exception text has changed and both exceptions and warnings no longer have a `message` attribute.
> Python 3 exceptions/warnings

- lib/iris/_concatenate.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/fileformats/_structured_array_identification.py
- lib/iris/fileformats/cf.py
- lib/iris/fileformats/pp.py
- lib/iris/unit.py
Several classes must be hashable because they are used as dictionary keys. This is generally implemented as a hash of the same information used for `__eq__`, or if that's not defined, the `id`.
> Python 3 hashing

- lib/iris/fileformats/pp.py
I found some tabs when attempting to install on Python 3. There was also an instance of `basestring`.
> Py3k compatibility fixes for pp

- lib/iris/fileformats/ff.py
Two tests break with NumPy 1.9, since `np.linspace` newly produces a result of the same shape as the input. This now-2D array cannot be concatenated later on.
```python
======================================================================
ERROR: test_decreasing_field_values (iris.tests.unit.fileformats.ff.test_FF2PP.Test__det_border)
----------------------------------------------------------------------
File "/home/elliott/code/conda/envs/iris27/lib/python2.7/site-packages/Iris-1.9.0.dev0-py2.7.egg/iris/tests/unit/fileformats/ff/test_FF2PP.py", line 293, in test_decreasing_field_values
result = ff2pp._det_border(field_x, 1)
File "/home/elliott/code/conda/envs/iris27/lib/python2.7/site-packages/Iris-1.9.0.dev0-py2.7.egg/iris/fileformats/ff.py", line 549, …
```
> NumPy 1.9 fixes

- INSTALL
- conda-requirements.txt
- lib/iris/analysis/maths.py
- lib/iris/tests/unit/cube/test_Cube__operators.py
As noted by @dkillick in #1744, doing basic maths with cubes (adding, subtracting etc) does not currently preserve lazy data. 
I have modified the `iris/analysis/maths.py` file to support lazy data evaluation of cubes using some of the more recent features in biggus (broadcasting etc).
Let me know what you think!
> Lazy cube maths

- lib/iris/_concatenate.py
- lib/iris/_merge.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/fileformats/_structured_array_identification.py
- lib/iris/fileformats/grib/_message.py
For whatever reason, the `__dict__` property does not get inherited, so it needs to be re-implemented in a few classes.
> Python 3 __dict__ inheritance

- docs/iris/src/whatsnew/contributions_1.9/bugfix_2015-18-09_unnecessary_wrap_intersection.txt
- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
This PR stops intersection from wrapping grids for the following situation:
The grid is being split in two at either edge due to the point being a value of (base + period).
This is not at all a neat solution but it yield the desired result.  Any alternate solutions are welcome.
Further context in #1662
> BUG: Tolerant intersection

- lib/iris/analysis/calculus.py
- lib/iris/cube.py
It turns out that the "deprecated" code in `Cube.coord_dims()` is never run so I've just removed it.
Fixes #1790
> Add missing deprecation directives

- docs/iris/src/whatsnew/contributions_1.9/newfeature_2015-07-03_pearsonr_rewrite.txt
- lib/iris/analysis/stats.py
- lib/iris/tests/unit/analysis/stats/test_pearsonr.py
Option to apply a common mask to the two cubes before calculating the correlation in `iris.analysis.stats.pearsonr`.  As discussed in #1534, this is the expected behaviour for some users (including me!) But, as both @niallrobinson  and @ajdawson have pointed out that the _right_ behaviour is arguable, it makes sense to have it as an option (defaulting to False so default behaviour is unchanged).
> pearsonr apply common mask

- .travis.yml
- lib/iris/fileformats/__init__.py
- lib/iris/fileformats/grib/__init__.py
- lib/iris/io/__init__.py
- lib/iris/tests/__init__.py
- lib/iris/tests/integration/format_interop/test_name_grib.py
- lib/iris/tests/integration/format_interop/test_pp_grib.py
- lib/iris/tests/integration/test_grib2.py
- lib/iris/tests/integration/test_pickle.py
- lib/iris/tests/runner/_runner.py
- lib/iris/tests/system_test.py
- lib/iris/tests/test_grib_load.py
- lib/iris/tests/test_grib_phenomenon_translations.py
- lib/iris/tests/test_grib_save.py
- lib/iris/tests/test_grib_save_rules.py
- lib/iris/tests/test_io_init.py
- lib/iris/tests/test_uri_callback.py
- minimal-conda-requirements.txt
NB. This adds a new entry to the test matrix which runs the standard test suite against an installation with a reduced set of dependencies. Currently this is only missing ecmwf_grib but I would expect other dependencies could be removed once the concept is proven.
> Make GRIB API optional.

- lib/iris/util.py
Hello, I was doing a bit of work yesterday and was caught out by a docstring that I *thought* was  a bit deceptive - but it could be my reading.  This is an attempt to tidy the doc string.  Feel free to reject if you think it is just the way I was reading the doc.
Here's the context: I needed to change the labelling on the pseudo_levels of a cube.  The initial values of the labels were monotonic, the new values were not monotonic.  I thought I could do what I the relabel by first demoting pseudo_level to an AuxCoord and then updating the values.  I thought I could use iris.util.demote_dim_coord_to_aux_coord to do this... however it turns out it doesn't do the step of turning the DimCoord into an AuxCoord.  There may be cases where this is the right thing to do - so I haven't changed this. …
> Initial attempt at tidying the demote_dim_coord... docstring

- lib/iris/__init__.py
Hello, this is a small documentation modification.  I think if a constraint is simply a string it matches against cube.name() rather that the standard_name (is that right?)
I'm not completely sure the documentation is the best as I have it - feel free to reject if you think it could be clearer.
Sorry for these small pull requests - but I figure they are more likely to get done if I just do them as I come across them, rather than saving them up.
> iris load documentation - clarify constraint as string

- lib/iris/experimental/regrid.py
Tiny PR to make iris friends with numpy 1.10.0 (actually `'1.10.0.post2'` for some reason) .
> Safer _NP_VERSION

- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
I have a netCDF file containing data variables that have a `cell_methods` attribute with the value `time : mean` (note there is a space before and after the colon). When I run CF Checker on the netCDF file there are no errors. In addition, even though the [CF Conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#cell-methods) state "[the `cell_methods` attribute of the variable] is a string attribute comprising a list of blank-separated words of the form `name: method`", I would argue that the amount of whitespace in this form is unimportant as there is no direct mention of it.
Please let me know if this change will be approved and I will write some appropriate tests :)
> Optional whitespace before the colon in the 'cell_methods' regular expression

- docs/iris/src/whatsnew/contributions_1.9/incompatiblechange_2015-10-12_GRIB_optional_Python3_unavailable.txt
replacing #1774 for now, noting the lack of support for GRIB in Python3
> Grib Py3 whats new 

- docs/iris/src/whitepapers/um_files_loading.rst
Hello,
I think you had a small typo in the white paper on UM file loading.  This corrects it, and adds a little more UM speak (sorry).
https://code.metoffice.gov.uk/doc/um/vn10.2/papers/umdp_F03.pdf
Jamie
> Update white paper documentation about pseudo level interpretation

- lib/iris/experimental/um.py
- lib/iris/fileformats/ff.py
- lib/iris/tests/test_ff.py
- lib/iris/tests/unit/fileformats/ff/test_FF2PP.py
**<del>CAUTION!</del>**
We've seen some WGDOS unpacking failures recently where they look like they are running out of data ... so this is a quick hack to get rid of a mysterious (*1) `-1` in the FieldsFile data length calculation and see if it helps. @bjlittle & @mo-g - this might be of use to you!
*1) No one can remember how it got into the code.
**NB.** Even though the tests pass, please don't merge this PR unless it fixes the unpack failures we've seen and can be shown that it doesn't muck up the reading of other real FieldsFiles! (The FieldsFiles in the test data are probably too artificial to be trusted on their own.)
> Update WGDOS payload length.

- lib/iris/_concatenate.py
Removes an incorrect data load warning from concatenate documentation. Lazy data concatenate has been around for a while (see the [whatsnew v1.8 document](http://scitools.org.uk/iris/docs/latest/whatsnew/1.8.html)).
Also updates the TODO at the top of the module to remove the scalar coordinate promotion and data load points.
> [DOC] Correct concatenate docstring

- lib/iris/analysis/calculus.py
- lib/iris/tests/test_analysis_calculus.py
Rotated pole cubes tend to have the coord names 'grid_latitude' and 'grid_longitude'. These names aren't currently being allowed in the curl calculation despite it saying it handles rotated pole cubes.
> Allow calculation of curl for cubes with 'grid_latitude' and 'grid_longitude' coords

- docs/iris/src/whatsnew/contributions_1.9/deprecate_2015-11-01_unit-module.txt
- lib/iris/unit.py
Deprecation warning added to code so that a `UserWarning` is raised when `iris.unit` is imported. Deprecation directive added to module-level docs. Whatsnew entry added.
Addresses #1821.
> Add deprecation warnings for `iris.unit`

- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_Coord.py
A step towards an alternative version of #1782 which conserves existing Python 2 behaviour : see [comment there](https://github.com/SciTools/iris/pull/1782#issuecomment-154050680)
An adjusted version of @QuLogic
["f9cc0f9 py3k: Use Unicode in coord collapse."](https://github.com/QuLogic/iris/commit/f9cc0f93330624179094eaeb7f673f2cfdcd7354)
Make it unicode only in Python 3.
TO TEST :
```python3 -m unittest iris.tests.unit.coords.test_Coord.Test_collapsed``` fails before this, succeeds after
NOTE :
As the second commit effectively reverts some changes from the first one,  it probably makes good sense to squish before merging.
> Py3k unicode collapse

- lib/iris/fileformats/rules.py
An attempt to fix the problems discussed in [this problem comment](https://github.com/SciTools/iris/pull/1826#issuecomment-156031183)
**This should fix the current intermittent test failures.**
I tried to tidy the nastiness in the rules code a wee bit, rather than just work around it (e.g. by simply renaming the 'rules.config' variable).
I haven't removed the use of 'exec', or avoided the "```from xx import *```" equivalents, but at least it is no longer polluting the namespace of ```iris.fileformats.rules``` itself (which caused the bug).
I also switched it to using a blank 'locals' in the exec calls, as the current use of locals() (as see e.g. [here](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/rules.py#L323)) is not needed and not really a very good idea.  I …
> Fix rules global usage.

- lib/iris/cube.py
A step towards an alternative version of #1782 which conserves existing Python 2 behaviour : see [comment there](https://github.com/SciTools/iris/pull/1782#issuecomment-154050680)
An adjusted version of @QuLogic ["b759876 py3k: Correctly handle string input to slicers. "](https://github.com/QuLogic/iris/commit/b7598762531c727bb6939a2017c15fa6cac86183)
The implementation is somewhat rewritten, as I previously suggested : [comment on #1782](https://github.com/SciTools/iris/pull/1782#discussion_r43653959)
This should make *no* functional difference.
TO TEST :
```python3 -m unittest iris.tests.unit.cube.test_Cube``` fails before this, succeeds after
NOTE :
As the second commit efffectively reverts some changes from the first one,  it probably makes good sense to squish before merging.
> Py3k unicode slicers

- lib/iris/fileformats/cf.py
A step towards an alternative version of #1782 which conserves existing Python 2 behaviour : see [comment there](https://github.com/SciTools/iris/pull/1782#issuecomment-154050680)
An adjusted version of @QuLogic ["a02e863 py3k: Handle strings from netCDF consistently."](https://github.com/QuLogic/iris/commit/a02e8630f3b0d7406cd922f8d6d54ee7b1d8d628)
Decode to unicode only in Python 3.
TO TEST :
```python3 -m unittest iris.tests.test_cf``` fails before this, succeeds after
NOTE :
As the second commit effectively reverts some changes from the first one,  it probably makes good sense to squish before merging.
> Py3k unicode cf

- lib/iris/fileformats/grib/__init__.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/rules.py
- lib/iris/tests/integration/test_pp_constrained_load_cubes.py
- lib/iris/tests/unit/fileformats/rules/test_Loader.py
1. Deprecates use of `legacy_custom_rules`.
2. Gets rid of related unused bits:
- `iris.fileformats.grib._load_rules`
- `iris.fileformats.pp._load_rules`
- `iris.fileformats.pp._ensure_load_rules_loaded`
> Deprecate legacy_custom_rules

- conda-requirements.txt
- minimal-conda-requirements.txt
Switch to the new name in conda-recipes-scitools. Avoids:
```
$ conda list
...
udunits                   2.2.17                        5    scitools
udunits2                  2.2.20                        0    scitools
...
```
> Bake udunits version into package name.

- docs/iris/src/userguide/cube_statistics.rst
- lib/iris/coords.py
- lib/iris/cube.py
Adds a note on partially collapsing multi-dimensional coordinates to the userguide &sect;9.1, `iris.cube.Cube.collapsed` and `iris.coords.Coord.collapsed`.
> DOC: Note about collapsing multi-dimensional coordinates

- lib/iris/etc/pp_save_rules.txt
- lib/iris/fileformats/pp_rules.py
- lib/iris/tests/integration/test_pp.py
- lib/iris/tests/unit/experimental/fieldsfile/test__convert_collation.py
- lib/iris/tests/unit/fileformats/pp/test_save.py
- lib/iris/tests/unit/fileformats/pp_rules/test__convert_scalar_vertical_coords.py
- lib/iris/tests/unit/fileformats/pp_rules/test__convert_vertical_coords.py
- lib/iris/tests/unit/fileformats/pp_rules/test_convert.py
This PR fixes a known current issue with UM model output incorrectly populating PP field attributes for deep soil level (vertical coordinate LBVC=6).
Rather than being an unbounded, dimensionless vertical soil model level (lblev), it should be a bounded ([brsvd[0], brlev]) vertical model depth (blev) in units of metres.
> Deep soil level/depth coordinate.

- lib/iris/analysis/__init__.py
A minor change to make explicit that weights passed to this function are not normalized internally. This is to remove some confusion following feedback from users.
> iris.analysis.SUM docstring change

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2015-Dec-16_subset-scalar-coordinates.txt
- lib/iris/cube.py
- lib/iris/tests/integration/test_subset.py
- lib/iris/tests/unit/cube/test_Cube.py
Subset throws an exception if you pass it a scalar co-ordinate: `len(coord.points) == 1` and `coord in aux_coords == True`.
This is (I think) a fix to that problem. Comments? - The integration test I added should probably not go in..
Thanks,
Gray.
> Subset self exception

- lib/iris/tests/unit/fileformats/grib/test_save_messages.py
I have updated known error codes for grib save unit test, so that it works with v12 and v14 of the grib API.
These tests do very little, I would be happy to just remove them, I think they add nothing to our test coverage.
However, if they are felt to be worth keeping, this at least gives us some more grib api version independence.
> error types for different api versions

- lib/iris/tests/__init__.py
- lib/iris/tests/integration/test_grib2.py
Updated testing strategy for GRIB2 integration tests
The dependency on the exact text of grib_dump is removed, with individual testing in code preferred
I would like to get this pattern adopted so I can use it to address issues with the
lib/iris/tests/test_grib_save.py
module, which has a fragile grib_api version dependency
> G2 int test strat

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Jan-20_check-aux-coords-before-concatenating.txt
- lib/iris/_concatenate.py
- lib/iris/cube.py
- lib/iris/tests/integration/concatenate/test_concatenate.py
Currently, for concatenation, only AuxCoord metadata is being checked. This allows two cubes with different AuxCoord points to be concatenated. For an example case, see the integration test I added.
This PR ensures the AuxCoords match before the concatenation can happen.
> Check aux coords match before concatenating

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Jan-20_add-__deepcopy__-to-DimCoord.txt
- lib/iris/coords.py
- lib/iris/tests/test_analysis_calculus.py
- lib/iris/tests/test_cdm.py
The points and bounds properties of the `DimCoord` class are intended to be read-only. However, when a `DimCoord` object is deepcopied, the underlying numpy arrays have their 'writeable' flag set to True by `np.ndarray.__deepcopy__(...)`.
This fix adds an implementation of `__deepcopy__(...)` to `DimCoord`s which resets these flags to False. It also modifies some unit tests which were failing due to the fix.
> Add __deepcopy__ to DimCoord

- lib/iris/fileformats/grib/_grib_cf_map.py
- lib/iris/fileformats/um_cf_map.py
GRIB2 precipitation_amount
and
implied height for stash m01s03i227
replaces #1924 
derived from
https://github.com/metarelate/metOcean/issues/61
https://github.com/metarelate/metOcean/issues/70
> new translations

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Feb-10_correct-curl-sign.txt
- lib/iris/analysis/calculus.py
- lib/iris/tests/test_analysis_calculus.py
The sign of the r component of the curl function is wrong when using spherical coordinates. This change reverses the sign.
This needs to be checked by someone who understands the maths better than I do.
> Correction to curl function

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Feb-10_add-month-coord.txt
- lib/iris/fileformats/pp_rules.py
- lib/iris/tests/unit/fileformats/pp_rules/test__all_other_rules.py
- lib/iris/tests/unit/fileformats/pp_rules/test__convert_scalar_time_coords.py
This change fixes a bug with a class of pp files with lbyr == 0, where the date would cause errors when converting to a datetime object (e.g. when printing a cube).
When processing a pp field with lbtim = 2x, lbyr == lbyrd == 0 and lbmon == lbmond, a numeric 'month' coordinate is created instead of 'time'.
> Add 'month' coord instead of 'time' in pp_rules when lbyr=0 and lbtim.ib==2

- lib/iris/coord_categorisation.py
- lib/iris/tests/unit/coord_categorisation/test_add_hour.py
Cubes can now have an 'hour' coordinate added by calling `iris.coord_categorisation.add_hour(<cube>, <time-coord>)`.
> Add add_hour function to coord_categorisation

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Feb-18_fix-cube-data.txt
- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube__operators.py
In certain cases, `Cube.data` fails to return an array. This is due to the underlying biggus array sometimes returning a numpy numeric type when evaluated (see https://github.com/SciTools/biggus/issues/175). `Cube.data` then returns the underlying buffer of this object.
This fix ensures an `np.ndarray` is returned by `Cube.data`
> Fix Cube.data, ensure it always returns an np.ndarray

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Feb-18_fix-determining-units.txt
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/results/netcdf/netcdf_save_ndim_auxiliary.cdl
- lib/iris/tests/results/netcdf/netcdf_save_wcoord.cdl
- lib/iris/tests/test_netcdf.py
Make coords with standard name 'latitude' and 'longitude' which have no coordsystem to be saved with units 'degree_north' and 'degree_east' respectively in netcdf files. Remove other unsafe unit changes.
Change some unit test expected output to recognise these changes.
> Fix to automatic deriving of units when saving in netcdf format

- docs/iris/src/whatsnew/contributions_1.10/deprecate_2015-Dec-01_pp-custom-save-rules.txt
- docs/iris/src/whatsnew/contributions_1.10/deprecate_2016-Feb-25_logging.txt
- docs/iris/src/whatsnew/contributions_1.10/deprecate_2016-Feb-25_text_rules.txt
- lib/iris/config.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/rules.py
- lib/iris/tests/test_cube_to_pp.py
Replaces #1869
Note the proof-of-principle for replacing the pp-save-rules with a Python equivalent
- https://github.com/pp-mo/iris/pull/18
Issues from there, remaining to address :
Note: to make this useful, we may want to cut an intermediate release including these deprecations, so we can then remove the functions (ideally, in Iris 2.0).
See : [@rhattersley on releases](https://github.com/SciTools/iris/pull/1869#issuecomment-163568785)
> Deprecate the whole pp 'custom save rules' api.

- lib/iris/plot.py
- lib/iris/tests/unit/plot/__init__.py
- lib/iris/tests/unit/plot/test_contour.py
- lib/iris/tests/unit/plot/test_contourf.py
- lib/iris/tests/unit/plot/test_outline.py
- lib/iris/tests/unit/plot/test_pcolor.py
- lib/iris/tests/unit/plot/test_pcolormesh.py
- lib/iris/tests/unit/plot/test_plot.py
- lib/iris/tests/unit/plot/test_points.py
- lib/iris/tests/unit/plot/test_scatter.py
This PR makes it possible to pass an existing matplotlib ``Axes`` object to the various plotting functions in the plotting module. I realize that in PR #1112 drawing directly onto the axes was disabled, instead always drawing to the axis that is currently open using the ``plt`` function calls. While that is a good fix for users using the ``plt`` interface, which is useful for simple usage, when building more complex plots the object-oriented approach is the way to go. This is crucial for some of the functionality we're building as part of the [cube-explorer](https://github.com/CubeBrowser/cube-explorer) project integrating Iris functionality within [HoloViews](http://holoviews.org).
It's a fairly small set of changes but not being familiar with the code I may have missed something. I …
> Added handling of axes to regular plotting functions

- docs/iris/src/whatsnew/contributions_1.10/deprecate_2016-Mar-15_ff_module.txt
- lib/iris/experimental/fieldsfile.py
- lib/iris/experimental/um.py
- lib/iris/fileformats/__init__.py
- lib/iris/fileformats/_ff.py
- lib/iris/fileformats/ff.py
- lib/iris/fileformats/um/__init__.py
- lib/iris/fileformats/um/_ff_replacement.py
- lib/iris/tests/test_ff.py
- lib/iris/tests/unit/fileformats/ff/test_ArakawaC.py
- lib/iris/tests/unit/fileformats/ff/test_ENDGame.py
- lib/iris/tests/unit/fileformats/ff/test_FF2PP.py
- lib/iris/tests/unit/fileformats/ff/test_FFHeader.py
- lib/iris/tests/unit/fileformats/ff/test_Grid.py
- lib/iris/tests/unit/fileformats/ff/test_NewDynamics.py
- lib/iris/tests/unit/fileformats/ff/test__ff_equivalents.py
- lib/iris/tests/unit/fileformats/um/test_um_to_pp.py
The intention is to deprecate everything in ```fileformats.ff```, to give us some space to replace all the usage of the old FieldFile support (FFHeader, FF2PP etc) with mule, at some future time.
Thus:
*  ```fileformats.ff``` has become ```fileformats._ff```.
* all internal usage has been re-routed to there.
* there is a *new* ```fileformats.ff```, which is a thin wrapper to everything (public) in the old one, but also issues a deprecation warning whenever you instantiate the classes or call the functions.
* there are 3 new functions in ```fileformats.um``` which preserve the (still supported) functions of fetching PPFields and cube-lists from a FieldsFile.
* these are also re-cast as operations on "UM files", because
Some of the fussy detail is about getting the docs output to look …
> Deprecate ff

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Apr-01_regrid_masked_circular.txt
- lib/iris/analysis/_interpolation.py
- lib/iris/tests/test_interpolation.py
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py
Addresses a reported problem whereby regridded data came out with large values instead of the expected masked points.
There was already a longstanding workaround for this, related to a known problem with numpy 'append', but it had a bug in its own logic.
I replaced the earlier fix with one using either np.concatenate or np.ma.concatenate, as required.  This seemed necessary to ensure the required result type, i.e. masked-for-masked-input and also unmasked-for-unmasked-input.
> Regrid fix circular extend

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Apr-07_nearest_types.txt
- lib/iris/analysis/_regrid.py
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py
Stumbled on this while refactoring regridding code.
I want Nearest() to behave sensibly so I can use it to replace the usage of the obsolete methods we are deprecating.  Refer : https://github.com/pp-mo/iris/pull/20
> Fix the 'Nearest' scheme to return the same datatype as the input.

- lib/iris/tests/test_coding_standards.py
The tests still run after building the docs !
The existing testing problem relates to the 'future imports test', ```iris.test.test_coding.standards.TestFutureImports```.
This test is _already_ excluded from checking the example code files, in {{"\*/docs/iris/example_code/*/*.py"}}.
However, building the docs copies ```/docs/iris/example_code/*``` to ```/docs/iris/src/examples```, and the test is checking + failing them there.
> Prevent a docs build from breaking the tests.

- lib/iris/analysis/calculus.py
@pp-mo @rhattersley @marqh @pelson 
The documentation for this function was very vague and unclear, so I have added paragraphs which should make it more clear and understandable.  It now states the type of units that need to be on the cube data and what the different results will be when the k-component cube is and is not used.  It also states which coordinate systems will lead to the spherical calculus being used.
Please tell me if this documentation is clear and makes sense.  I would be very keen to hear feedback and suggestions.
> Curl docs change

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Mar-06_scalar_cell_method.txt
- lib/iris/fileformats/rules.py
- lib/iris/tests/test_coding_standards.py
- lib/iris/tests/unit/fileformats/test_rules.py
While doing some other work I noticed that scalar_cell_method() in lib/iris/fileformats/rules.py didn't check its coord_name argument, which I've now fixed.
> scalar_cell_method now checks coord_name

- lib/iris/__init__.py
- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_Coord.py
- lib/iris/tests/unit/test_Future.py
Using `Coord.guess_bounds()` on a latitude coordinate which extends too close to the poles gives rise to "silly" bounds that extend beyond the range [-90, 90]. (e.g. The sample data `GloSea4/ensemble_001.pp`.)
This PR checks for a latitude coordinate, and if all the _points_ are inside the range [-90, 90] then it clips the guessed bounds to [-90, 90].
NB. Because this is a backwards-incompatible change of behaviour I've controlled it via an `iris.FUTURE.clip_latitudes` flag.
> Clip guessed latitude bounds to [-90, 90].

- docs/iris/src/developers_guide/deprecations.rst
Since the switch to semver the old two-release-or-six-months rule doesn't really make sense. This change simplifies it to just a one-release minimum.
(When someone chooses to _install_ a major release is an independent question.)
> Update deprecation rules

- docs/iris/example_code/Meteorology/wind_speed.py
1. Sphinx splits the code when it sees `plt.show` which creates invalid syntax for code with this kind of structure. We use `qplt.show` to avoid that, as for the other examples.
2. Because sphinx doesn't get to do its splitting thing, we have to explicitly create a new figure after each show().
Fixes #1979.
> Fix the plot rendering within sphinx.

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Mar-05_set_lbproc_for_minimum.txt
- lib/iris/etc/pp_save_rules.txt
- lib/iris/tests/unit/fileformats/pp/test_save.py
This fixes a problem where LBPROC is not set when saving a minimum to a PP file. It also sets the IA component of LBTIM when saving a maximum or a minimum.
I have really struggled with the unit tests for these fixes. I have one for LBPROC, although this creates 84 warnings when run. I can't write a unit test for the LBTIM fix. When using the mock approach that other tests in the unit test module use, LBTIM is always set to an integer and so the IA, IB and IC components can't be set. I tried creating an additional mock for LBTIM that replaced it with an object with these components, but this was overwritten with an integer.
I also looked at the approach used in tests/integration/test_pp.py but got an error: "TypeError: 'NoneType' object has no attribute '__getitem__'" when I called …
> Save rules for maximum and minimum values corrected

- docs/iris/src/whatsnew/contributions_1.10/deprecate_2016-Apr-21_analysis_interpolate_module.txt
- docs/iris/src/whatsnew/contributions_1.10/deprecate_2016-Apr-21_cube_regridded.txt
- lib/iris/_deprecation_helpers.py
- lib/iris/analysis/_interpolate_private.py
- lib/iris/analysis/interpolate.py
- lib/iris/analysis/trajectory.py
- lib/iris/cube.py
- lib/iris/fileformats/ff.py
- lib/iris/fileformats/grib/__init__.py
- lib/iris/fileformats/rules.py
- lib/iris/tests/analysis/test_interpolate.py
- lib/iris/tests/integration/test_regrid_equivalence.py
- lib/iris/tests/test_coding_standards.py
- lib/iris/tests/test_interpolation.py
- lib/iris/tests/test_regrid.py
- lib/iris/tests/unit/analysis/interpolate/test_linear.py
- lib/iris/tests/unit/fileformats/ff/test__ff_equivalents.py
Deprecation of ```cube.regridded``` and the whole of ```iris.analysis.interpolate``` module.
We basically want all of these older methods updated to the new scheme-based "cube.regrid" and "cube.interpolate".
It's a bit noisy, partly unavoidable due to renames.
It should be clearer from the individual commits.
> Deprecate interpolate

- lib/iris/io/__init__.py
This explicit import should not be needed - the import is [intended to be deferred](https://github.com/rhattersley/iris/blob/20d3a7841b9d80aa7dfcc0fbb9c8910d22cf8ba4/lib/iris/io/__init__.py#L229-L242).
> Remove obsolete import of iris.fileformats.dot

- INSTALL
For security reasons they've switched the hosted docs from `.org` to `.io`.
> Update readthedocs domain

- .travis.yml
- conda-requirements.txt
- lib/iris/experimental/regrid_conservative.py
- lib/iris/tests/experimental/regrid/test_regrid_conservative_via_esmpy.py
Some ***very*** simple fixes to make our old "regrid_conservative_via_esmpy" routine work with ESMPy v7.0.0
For now, this is getting its ESMPy from scitools
See [conda-recipes-scitools#149](https://github.com/SciTools/conda-recipes-scitools/pull/149)
> Small changes to ESMF api; add ESMPy as dependency, for Travis tests.

- lib/iris/fileformats/_ff.py
- lib/iris/fileformats/ff.py
- lib/iris/tests/unit/fileformats/ff/test__ff_equivalents.py
As @rhattersley pointed out yesterday, the previous effort is over-complicated in it's attempt to provide runtime deprecation warnings for everything in the interface.
We need only ensure that importing "iris.fileformats.ff" itself produces a warning :  The others are not needed, which makes it all much simpler.
It has proved awkward in several of these deprecation efforts to ensure the Sphinx documentation is still equivalent.
I think this still achieves that, but you may want to check it out.
> Simplify the deprecation of 'iris.fileformats.ff'.

- lib/iris/cube.py
This is a proposed fix in respect of https://github.com/SciTools/iris/issues/1758
The behaviour of aggregated_by has been tested, and it doesn't affect the results whether the identical values are consecutive or otherwise. So, I propose to remove the "Todo..." line.
> Edit of aggregated_by docs

- lib/iris/fileformats/um/_fast_load_structured_fields.py
This code is no longer experimental so this comment should be updated.
> Remove 'experimental' from description in iris/fileformats/um/_fast_load_structured_fields.py

- docs/iris/src/userguide/saving_iris_cubes.rst
- lib/iris/io/__init__.py
I noticed a slight error in the "Customising the save process" code example. This fixes ` message` to be `grid_message`
Whilst I was on the page, I also noticed something (admittedly very minor) that I don't like in the first code example block:
```python
import iris
filename = iris.sample_data_path('uk_hires.pp')
cubes = iris.load(filename)
cube = cubes[0]
iris.save(cubes, '/tmp/uk_hires.nc')
```
I don't like the fact that a cube is indexed from the cubelist, but then the next line is saving the original cubelist. Someone would never do this so it shouldn't be example code.
I understand that the indexing is done as, further down, there are examples that use `cube` to demonstrate that a single cube can also be saved. Instead, I propose that the indexing should be done at the point of …
> Fix userguide save process customisation example

- docs/iris/src/developers_guide/deprecations.rst
- lib/iris/__init__.py
- lib/iris/_deprecation.py
- lib/iris/analysis/_interpolate_private.py
- lib/iris/analysis/calculus.py
- lib/iris/analysis/interpolate.py
- lib/iris/analysis/maths.py
- lib/iris/aux_factory.py
- lib/iris/cube.py
- lib/iris/exceptions.py
- lib/iris/fileformats/cf.py
- lib/iris/fileformats/ff.py
- lib/iris/fileformats/grib/__init__.py
- lib/iris/fileformats/grib/load_rules.py
- lib/iris/fileformats/netcdf.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/pp_packing.py
- lib/iris/fileformats/rules.py
- lib/iris/proxy.py
- lib/iris/unit.py
- lib/iris/util.py
A helpful step towards #1989 :  To check for Iris deprecations within example tests.
The idea is to give all the Iris deprecation warnings a common class they inherit from, so we can filter on it.
Mostly humdrum (if noisy),
but note : tweaked iris.exceptions to remove a circular import.
> Give all Iris deprecation warnings a common identity.

- lib/iris/fileformats/grib/__init__.py
- lib/iris/tests/unit/fileformats/grib/test_as_messages.py
This function was removed by #1941, when it should just have been deprecated.
The test ```iris.tests.unit.fileformats.grib``` test "test_as_messages" is not reinstated, as "test_as_pairs" covers it.
As a complete aside, I also spotted the ECMWF link in the module header was broken + fixed that.
> Reinstate grib as_messages.

- docs/iris/src/userguide/loading_iris_cubes.rst
The user guide entry for loading iris cubes (see here http://scitools.org.uk/iris/docs/latest/userguide/loading_iris_cubes.html#constrained-loading ) currently contains the following code example:
filename = iris.sample_data_path('uk_hires.pp')
level_10_or_12_fp_6 = iris.Constraint(model_level_number=[10, 16], forecast_period=6)
cubes = iris.load(filename, level_10_or_16_fp_6)
It looks like level_10_or_12_fp_6 should actually be level_10_or_16_fp_6. So, this proposed change is an edit to make this correction.
> Edit to loading cubes code snippet in the user guide

- docs/iris/src/whatsnew/contributions_1.10/newfeature_2016-May-13_plot_anonymous.txt
- lib/iris/plot.py
- lib/iris/quickplot.py
- lib/iris/tests/unit/plot/__init__.py
- lib/iris/tests/unit/plot/test_contour.py
- lib/iris/tests/unit/plot/test_contourf.py
- lib/iris/tests/unit/plot/test_outline.py
- lib/iris/tests/unit/plot/test_pcolor.py
- lib/iris/tests/unit/plot/test_pcolormesh.py
- lib/iris/tests/unit/plot/test_points.py
- lib/iris/tests/unit/quickplot/test_contour.py
- lib/iris/tests/unit/quickplot/test_contourf.py
- lib/iris/tests/unit/quickplot/test_outline.py
- lib/iris/tests/unit/quickplot/test_pcolor.py
- lib/iris/tests/unit/quickplot/test_pcolormesh.py
- lib/iris/tests/unit/quickplot/test_points.py
This PR extends the capability of the `iris.plot` and `iris.quickplot` functions:
- contour
- contourf
- outline
- pcolor
- pcolormesh
- points
to plot cubes with anonymous dimensions. This is done via the `coords` kwarg, which can now take the offset of the anonymous dimension that represents the required plot axis e.g.
```python
>>> print cube
air_temperature / (K)               (latitude: 73; -- : 96)
Dimension coordinates:
latitude                           x        -
Scalar coordinates:
forecast_period: 6477 hours, bound=(-28083.0, 6477.0) hours
forecast_reference_time: 1998-03-01 03:00:00
pressure: 1000.0 hPa
time: 1998-12-01 00:00:00, bound=(1994-12-01 00:00:00, 1998-12-01 00:00:00)
Attributes:
STASH: m01s16i203
source: Data from Met Office Unified Model
Cell methods:
mean within …
```
> Support anonymous dimension plotting.

- lib/iris/fileformats/grib/_load_convert.py
- lib/iris/fileformats/grib/_save_rules.py
- lib/iris/tests/integration/test_grib2.py
- lib/iris/tests/unit/fileformats/grib/load_convert/test_product_definition_template_40.py
- lib/iris/tests/unit/fileformats/grib/save_rules/test_product_definition_template_40.py
This adds support for product definition template 40.
The only difference between pdt 0 and 40 is the inclusion of "constituent type". 
Grib does have a mapping for the constituent type value (e.g. 0 is ozone) but for now this mapping hasn't been implemented. Instead this PR just sets the value as an attribute of the cube.
Saving to pdt 40 to come in the next commit...
> Add GRIB product definition template 40

- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/integration/test_pp.py
A couple of integration test classes seem to have missed their skip_data decorators, so I've added them.
I also slightly refactored one of the tests to add a `setUp` method and pull common setup code into it.
> Added missing `tests.skip_data` decorators

- lib/iris/_deprecation.py
Otherwise all deprecation warnings appear to come from a line in ```iris._deprecation.py```
Turns something like:
```...lib/iris/_deprecation.py:36: IrisDeprecation: the`auto_regularise` kwarg is deprecated...```
into:
```...lib/iris/fileformats/grib/__init__.py:945: IrisDeprecation: the`auto_regularise` kwarg is deprecated ...```
> Fix warn_deprecation to display where it was called from.

- .travis.yml
- docs/iris/src/whatsnew/contributions_1.10/newfeature_2016-May-24_add_mercator_projection.txt
- lib/iris/coord_systems.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/results/coord_systems/Mercator.xml
- lib/iris/tests/results/netcdf/netcdf_merc.cml
- lib/iris/tests/results/unit/fileformats/netcdf/Saver/write/mercator.cdl
- lib/iris/tests/results/unit/fileformats/netcdf/Saver/write/mercator_no_ellipsoid.cdl
- lib/iris/tests/test_coordsystem.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_mercator_coordinate_system.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_has_supported_mercator_parameters.py
This change supports loading and saving NetCDF files with a Mercator projection with some parameters restricted (`false_easting == false_northing == 0, scale_factor_at_projection_origin == 1`). This allows some support for Mercator projections without needing to modify Cartopy.
This pull request requires additional test data (https://github.com/SciTools/iris-test-data/pull/42).
> Add support for loading NetCDF files with Mercator projections

- .travis.yml
- docs/iris/src/whatsnew/contributions_1.10/newfeature_2016-May-24_stereographic_projection_netcdf.txt
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/results/coord_systems/Stereographic.xml
- lib/iris/tests/results/netcdf/netcdf_stereo.cml
- lib/iris/tests/results/unit/fileformats/netcdf/Saver/write/stereographic.cdl
- lib/iris/tests/results/unit/fileformats/netcdf/Saver/write/stereographic_no_ellipsoid.cdl
- lib/iris/tests/test_coordsystem.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_stereographic_coordinate_system.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_has_supported_stereographic_parameters.py
Add support for loading stereographic grid mappings from netCDF files where the scale factor at projection origin is 1
> Add support for loading stereographic grid mappings from netCDF files

- lib/iris/tests/__init__.py
This PR is to support [iris-grib](https://github.com/SciTools/iris-grib) testing.
We want the convenience to reuse all of the `iris.tests.IrisTest` behaviour but also to be able to point the `iris.tests._RESULT_PATH` to an iris-grib specific directory.
The problem is that `iris.tests.get_result_path` function (which uses `iris.tests._RESULT_PATH`) is local to that module, and also that this module level function is referenced by several `iris.tests.IrisTest` methods.
Currently, the only way to re-direct `iris.tests._RESULT_PATH` somewhere other than the `IrisTest` default, is to **overwrite** `iris.tests._RESULT_PATH`, which may not be desirable nor appropriate.
Defining `iris.tests.get_result_path` as an `iris.tests.IrisTest` static-method, allows light-weight sub-class specialization to …
> IrisTest method subclass specialisation.

- INSTALL
- conda-requirements.txt
- lib/iris/tests/unit/cube/test_Cube__operators.py
- minimal-conda-requirements.txt
Updates the minimum version of biggus to v0.13 to help users avoid SciTools/biggus#166. I've also added a unit test that checks masked addition. This will fail with biggus < v0.13, and I've taken the unusual step of explaining this to the end user. This is felt to be necessary due to the possible mode of failure, where a masked array would lose its mask silently, endangering the correctness of scientific results. See #2034 for background and the basis for this new test.
Ping @matthew-mizielinski
> Biggus version requirement update

- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test_save.py
I hit an issue trying to save cubes with variable attributes including 'name', which is related (but not the same as #1167) when using netcdf4>=1.2. This is a test which reproduces the problem and an associated fix.
> Fix for setting protected attributes on NetCDF variable objects

- INSTALL
A user has reported a crash (which I've also replicated) when combining lazy evaluation and a non-thread-safe build of HDF5.
To re-create:
```python
import iris
path = '/path/to/a/tens_of_MB_cube.nc'
cubes = [iris.load_cube(path) for i in range(3)]
total = sum(cubes)
result = total.data  # This line triggers the lazy evaluation and the subsequent seg fault
```
> Add warning about HDF5 thread-safety.

- lib/iris/_concatenate.py
- lib/iris/tests/unit/concatenate/test_concatenate.py
This PR fixes a bug reported in #2021. The problem arises when we concatenate a list of cubes where the first one has a singleton dimension and one of the others doesn't. The dimension ordering determined by the `_ProtoCube` would be based only on the first cube, and be set to `_CONSTANT`. This later implies sorting coordinate points in ascending order, which is only correct if the non-singleton dimension is ascending.
This PR addresses the issue by ensuring a `_ProtoCube` with a `_CONSTANT` dimension order checks the dimension order of subsequently registered cubes and chooses the first non-constant one it finds for the dimension order. This ultimately ensures that the sorting is done in the correct order and the cubes will concatenate as expected.
> Fix concatenation with singleton dimensions

- docs/iris/src/whatsnew/contributions_1.10/newfeature_2016-Jun-13_lazy_new_axis.txt
- lib/iris/tests/integration/test_new_axis.py
- lib/iris/tests/unit/util/test_new_axis.py
- lib/iris/util.py
Make `iris.util.new_axis` work without loading a deferred data payload. I've used `iris.cube.Cube.lazy_data()` for this, I didn't use a check to see if the cube actually has lazy data, it seems not to matter, but advice is welcome.
> Make iris.util.new_axis handle lazy data

- lib/iris/etc/pp_save_rules.txt
- lib/iris/tests/integration/test_pp.py
This is a fix to correctly set the LBPROC upon saving as a pp file for zonal mean data.  I have not included a test - if you can point me in the direction of where the tests should be for a pp_save_rules fix, I'd be grateful.  
For a bit of context, the closest test I could find was [here](https://github.com/SciTools/iris/blob/master/lib/iris/tests/test_cube_to_pp.py#L265)  However, that is acting on zonal mean being set in a particular cube attribute rather than the cube cell methods.  Simplifying that test down to just time and longitudinal mean yields this:
> cube = stock.lat_lon_cube()
cube.attributes["ukmo__process_flags"] = ['Time mean field', 'Zonal mean field']
temp_filename = iris.util.create_temp_filename(".pp")
iris.save(cube, temp_filename)
result = …
> Added zonal (i.e. longitudinal) mean support to LBPROC save rule

- .travis.yml
- conda-requirements.txt
- docs/iris/src/whatsnew/contributions_1.10/deprecate_2016-Jun-16_sample_data_dir.txt
- lib/iris/__init__.py
- lib/iris/config.py
- lib/iris/tests/__init__.py
- lib/iris/tests/unit/test_sample_data_path.py
This PR addresses the [comment](https://github.com/SciTools/iris/pull/2047#discussion_r66404539) raised by @pp-mo on PR #2047, and deprecates the use of `iris.config.SAMPLE_DATA_DIR` in favour of using the newly packaged and importable `iris_sample_data`.
**Caveat emptor** - Merging this PR means that we are committed to bundling `iris_sample_data` with iris and an update to the iris conda recipe is required, otherwise a deprecation warning will always be raised on using the `iris.sample_data_path` function ... (see discussion thread below)
To do
> Add SAMPLE_DATA_DIR deprecation warning.

- lib/iris/tests/__init__.py
If you try to run the Iris tests via the command-line with _no_ GUI available at all (for example when using SSH) then the tests will fail:
```python
======================================================================
ERROR: Failure: RuntimeError (could not create GdkCursor object)
----------------------------------------------------------------------
...
File "/.../lib/iris/tests/__init__.py", line 73, in <module>
import matplotlib.pyplot as plt
...
File "/.../matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_gtk.py", line 58, in <module>
cursors.MOVE          : gdk.Cursor(gdk.FLEUR),
RuntimeError: could not create GdkCursor object
```
It looks like pyplot tries to set a GUI cursor thing at import time, assumedly because it defaults …
> Prevent tests failing to run with no GUI

- lib/iris/fileformats/rules.py
- lib/iris/tests/integration/test_pp.py
Fixes a bug (see #2052) where the `IgnoreCubeException` was not being respected in loading the loading of PP files with a user callback.
No tests yet, primarily because there are no tests for this behaviour at all (which is probably why this slipped through in the first place).
Closes #2052
> Fix PP callback bug

- lib/iris/unit.py
There is a note in the `Unit.convert` docstring that says "Conversion is done *in-place* for numpy arrays". However, this appears not to be the case. Using the example in the docstring:
```
% python2.7
Python 2.7.6 (default, Jan  3 2014, 16:42:21) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cf_units as unit
>>> import numpy as np
>>> c = unit.Unit('deg_c')
>>> f = unit.Unit('deg_f')
>>> a32 = np.arange(10, dtype=np.float32)
>>> c.convert(a32, f)
array([ 32.        ,  33.79999924,  35.59999847,  37.40000153,
39.20000076,  41.        ,  42.79999924,  44.59999847,
46.40000153,  48.20000076], dtype=float32)
>>> a32
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.], dtype=float32)
```
This pull …
> Remove incorrect note from Unit.convert method

- lib/iris/experimental/regrid.py
- lib/iris/tests/unit/experimental/regrid/test__CurvilinearRegridder.py
- lib/iris/tests/unit/experimental/regrid/test_regrid_weighted_curvilinear_to_rectilinear.py
Adapt PointInCell regridder to make it work for cross-coordinate-system regridding, including non-latlon systems.
NOTE: this removes certain input requirements, but also adds some, so is not totally backwards-compatible :
**requirements removed:**
* source and target must have the same coordinate system
* coord systems must be latlon
* source data X and Y coords must be 2d (can now have any dimensionality)
**requirements added:**
* source and target must both have a **defined** coord-system
* previously 'None' was acceptable, but that is problematic now it isn't limited to latlon systems
* source data X and Y coordinates must now have **the same** cube dimensions
* previously they had to be 2d, and the same size, but could have different dimension ordering
**I think these changes are …
> Extend point in cell

- lib/iris/tests/test_util.py
- lib/iris/util.py
A minor fix for `as_compatible_shape`.
Sometimes Cube dimensions are transposed by the operation.  If an AuxCoord spans these dimensions, we need to either transpose the AuxCoord's points or rearrange its associated dims.  I went for the latter, making it consistent with the `cube.transpose()` treatment.
> Fix as_compatible_shape for transposed auxcoords

- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test_parse_cell_methods.py
Some slightly unfinished business from #2039
The docs enhancement is a bit hurried : suggestions to improve ?
> Remove redundant arg from parse_cell_methods.

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Jul-22_cell-method-coord-name.txt
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/results/netcdf/netcdf_cell_methods.cml
- lib/iris/tests/results/trajectory/tri_polar_latitude_slice.cml
@pp-mo Previously the name used for Cell Methods was the var_name, but this was causing some human confusion and there was also a discrepancy between the name used in different ways:
```
precipitation_flux / (kg m-2 s-1)   (time: 30; latitude: 144; longitude: 192)
Dimension coordinates:
time                           x             -               -
latitude                       -             x               -
longitude                      -             -               x
Auxiliary coordinates:
forecast_period                x             -               -
Scalar coordinates:
forecast_reference_time: 1988-09-01 00:00:00
Attributes:
Conventions: CF-1.5
source: Data from Met Office Unified Model
um_version: 10.3
Cell methods:
mean: time_0 (1 hour)
```
```
In [24]: CellMethod('mean', …
```
> naming type for CellMethod changed

- lib/iris/fileformats/_ff.py
The warning for a lack of FF subgrid is moved to a place where it will only warn if it is to be used.
This avoids raising warnings about code which is not being used
> move ff warning

- docs/iris/src/developers_guide/deprecations.rst
- docs/iris/src/developers_guide/release.rst
- docs/iris/src/installing.rst
- docs/iris/src/userguide/change_management_goals.txt
- docs/iris/src/userguide/code_maintenance.rst
- docs/iris/src/userguide/index.rst
- docs/iris/src/whatsnew/index.rst
- docs/iris/src/whitepapers/change_management.rst
- docs/iris/src/whitepapers/index.rst
Suggestions for clarifying change management from the user POV
= releases + versions, deprecations, iris.FUTURE
This is mostly for discussion at this point.
It is now pretty much complete + correct to my original conception.
However, @rhattersley already suggested that this information might with advantage be a bit "generalised" and then "pushed back" onto the SemVer project https://github.com/mojombo/semver.
As I was most of the way toward providing this a standalone Iris docs, I've just carried on with that for this first draft. 
This issue is mentioned as a possible for 1.10, #1948 
which would be nice as we are targetting a lot of deprecations in 1.10.
While may be relevant there, it certainly isn't essential.
> Userguide section and whitepaper on user change management.

- docs/iris/src/whatsnew/contributions_1.10/newfeature_2016-Aug-02_netcdf_valid_range_attribute.txt
- lib/iris/_cube_coord_common.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/results/trajectory/tri_polar_latitude_slice.cml
- lib/iris/tests/test_cf.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_cube.py
Self described PR name.  This PR simply removes these three attributes from the list of special attributes we are not normally allowed to save from iris.
The driver for this ticket is in describing logical data in a NetCDF file (i.e. specifying a valid range of [0, 1] as an attribute on the cube).  It can also be used for saving unsigned integer NetCDF4-classic fields too.
**Information:**
http://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html
http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_data_types
> ENH: Enable writing valid_range valid_min and valid_max on NetCDF save

- docs/iris/src/whatsnew/1.9.rst
the last changes from 1.9.2 were not merged back onto master.  
These should be in 1.10, which will be merged back onto master following the release
> 1.9.2 docs

- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py
dtypes should be specified with number of bytes, not bits. 'f1' is not a thing.
> Fix numpy dtype specifications in test_RectilinearRegridder

- lib/iris/experimental/regrid.py
- lib/iris/tests/unit/analysis/test_WPERCENTILE.py
In Numpy1.10, you cannot use in-place operators on arrays where the RHS cannot be upcast to the LHS, e.g., `int += float`
> Fix issues where +=, -= were being used on arrays with incompatible dtypes

- lib/iris/coords.py
Iris 1.10 deprecated `iris.analysis.interpolate.nearest_neighbour_indices` in favour of `iris.coords.Coord.nearest_neighbour_index`, which was a nice step forward in deprecating the interpolate module. The docs for the interpolate function contained a usage example, however, that was not ported to the docs for the new function. This PR addresses that oversight.
> DOC: usage example for nearest_neighbour_indices

- lib/iris/pandas.py
This fixes the issue that now the `_assert_shared` function can't detect when a pandas object shares its data with a numpy array.
I'm not really happy with this solution. There's nothing in the pandas documentation that says `values` returns the original data object (indeed, in 0.16.2 it doesn't). But I can't find another way.
As an aside, a note in the doctring of ~~`_assert_shared`~~ `as_series` states
>     .. note::
>
>        Pandas will sometimes make a copy of the array,
>        for example when creating from an int32 array.
>        Iris will detect this and raise an exception if copy=False.
This doesn't appear to be the case any more. At least, `values` always seems to return the original array, and the buffer objects of a `pandas.Series` and the NumPy array from which it was …
> Fix _assert_shared

- lib/iris/tests/unit/fileformats/pp_rules/test_convert.py
A unit test was passing a mock object to `cf_units.date2num`, and failing with the changes in https://github.com/SciTools/cf_units/pull/68. This change ensures that actual `datetime` objects are passed to that function.
The unit test in question doesn't care about the values returned by the function, so the datetimes passed are essentially arbitrary.
> Fix unit test failing due to change in cf_units

- lib/iris/__init__.py
Simply update the version number on master. Doesn't matter if it ends up being 2.0.0, this will do for now, the crucial thing is that v1.10.0 already left the building so the version number on master must be increased.
> Update version number on master

- lib/iris/fileformats/pp.py
Issue is [here](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp.py#L2445/commit/098a87e).
```python
def as_fields(cube, field_coords=None, target=None):
...
-    return (field for cube, field in as_pairs(cube, field_coords=field_coords,
target=target))
+    return (field for cube, field in save_pairs_from_cube(cube,
field_coords=field_coords, target=target))
```
This means that our users are currently being issued a warning about using deprecated behaviour when they are not (made worse by the fact that warnings do not give a traceback).
> BUG: as_pairs usage removal within iris

- docs/iris/src/whatsnew/contributions_1.11/bugfix_2016-Oct-06_is_circular.txt
- lib/iris/tests/results/grib_load/ineg_jneg.cml
- lib/iris/tests/results/grib_load/ineg_jpos.cml
required update to 
#2164 (already merged :/)
> is_circular: grib load tests and what's new

- lib/iris/tests/test_whatsnew_contributions.py
Remove unnecessary use of `shell=True`, and use the correct Python interpreter (i.e., the same one that's running the tests.)
> Fix portability of whatsnew test.

- lib/iris/tests/unit/util/test_new_axis.py
- lib/iris/util.py
iris.util.new_axis cannot handle masked constants, so this is a check to turn masked constants into scalar masked arrays, at which point they can be handled correctly.
This fix is checked by a test in PR#2130: https://github.com/SciTools/iris/pull/2130
> fix for MaskedConstant errors

- docs/iris/src/whatsnew/contributions_1.11/bugfix_2016-Oct-06_netcdf_string_unicode.txt
- lib/iris/fileformats/netcdf.py
An alternative approach to #2133.
> Heuristically determine if saving a NetCDF attribute as a string or unicode.

- lib/iris/tests/results/imagerepo.json
This PR is associated with https://github.com/SciTools/test-images-scitools/pull/5, which contains the required images to support mpl 1.5.1 for all iris image tests and iris documentation example tests.
In total 139 new images are proposed to be added in https://github.com/SciTools/test-images-scitools/pull/5
This is the result of image changes for 125 iris image tests, and 22 documentation example tests. This is reflected in the 125 + 22 = 147 changes to `imgagerepo.json` in this PR.
Note that, only 139 new images are required to support this PR, as 8 images are duplicates.
> Update imagerepo for mpl 1.5.1

- lib/iris/tests/results/imagerepo.json
We have graphical test cases that perform more than one graphical test per test case.
These additional urls are for those outstanding multi-graphic test cases.
Also see https://github.com/SciTools/test-images-scitools/pull/6
> Additional mpl 1.5.1 graphic test urls

- docs/iris/src/whatsnew/contributions_1.11/newfeature_2015-Aug-06_lambert_azimuthal_equal_area.txt
- lib/iris/coord_systems.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/results/netcdf/netcdf_laea.cml
- lib/iris/tests/unit/coord_systems/test_LambertAzimuthalEqualArea.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
Depends on https://github.com/SciTools/iris-test-data/pull/37 and https://github.com/SciTools/cartopy/pull/619
> Add lambert azimuthal equal area coord_system

- lib/iris/unit.py
There were doctest failures in the Travis build, noticed in PR#2124.  These were popping up because of a precision change due to a change in numpy versions.  This has been fixed for cf-units, but not for iris.units (because it is being deprecated).  There is no point running the doctests on examples which are not going to be used, so I have just taken them out.
> examples removed from date2num and num2date

- lib/iris/__init__.py
- lib/iris/tests/unit/fileformats/pp_rules/test_convert.py
1.10.x merge back to master
please ensure commit history is maintained: do not hit 'squash and merge'
> Merge back v1.10.x

- .gitignore
- conda-requirements.txt
- lib/iris/tests/idiff.py
- minimal-conda-requirements.txt
Extend the capability of the iris developer `idiff.py` tool to assist with graphical test differences and updating the `imagerepo.json` store.
Note that, `idiff.py` will consistently update the `imagerepo.json` store if a graphic test image change is accepted **and** place the new `<hash>.png` file into the `iris/tests/resuts/visual_tests` directory in preparation for the developer to add to the  [test-images-scitools](https://github.com/SciTools/test-images-scitools) repo as a new PR
> Refactor idiff for imagerepo.json capability.

- lib/iris/tests/test_image_json.py
This is a followup to my comments on #2162. The number of threads does not need to be so high, and if the hostname is invalid, we should not even bother to make the request.
> Hash corrections

- conda-requirements.txt
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
fix to make #2158 functional for newer netcdf4-python
i am not convinced this catch all potential cases, only the ones we test
a few words prior to merge would be helpful
> catch setting of coordiantes and bounds for netcdf saver (string typing)

- lib/iris/unit.py
Follow-up to recent fix for doctest failures.  This is an example using the new numpy version with different precision, needs to be removed along with those that were removed in PR#2180(https://github.com/SciTools/iris/pull/2180).
> removed utime example

- lib/iris/analysis/cartography.py
It was noted that the docstrings for `iris.analysis.cartography.rotate_pole` and `iris.analysis.cartography.unrotate_pole` were pretty terse. This change adds more detail to the two docstrings, including noting that the source arrays in both cases must be of equal lengths.
> Make docstrings less terse

- lib/iris/tests/test_basic_maths.py
This test was dividing an integer array by another integer array and then failing when it found that it has floats in its resulting array.  This only occurs in the Python3 function 'itruediv' (the previously used Python2 function 'idiv' rounded to answer to an integer, so didn't encounter the casting error).
The change here catches the event of itruediv being used, and casts the arrays to float arrays rather than integers so that it can quite happily produce a floating point array as a result.
I have tested this with Python3 and numpy1.10 with success.
> idiv vs itruediv test fixed

- lib/iris/fileformats/pp_rules.py
possible fix for netcdf4-python behaviour change
in pp_rules date time calculations used to return floats, and still do in python2 but not in python3
https://github.com/SciTools/iris/blob/1c195e01ad5638e06910f2862662ac8c731aeea4/lib/iris/fileformats/pp_rules.py#L486
this manifested as a change in a doctest, but looks like a widespread issue where cubes are created using 
`hours_from_t1_to_t2`
and such like
https://github.com/SciTools/iris/blob/1c195e01ad5638e06910f2862662ac8c731aeea4/lib/iris/fileformats/pp_rules.py#L507
this work around may fix the problem
> netcdf4-python datetime casting

- lib/iris/tests/__init__.py
temporary work around for unknown and occasional non-repeatable check_graphic test failure
if it fails, try again, mostly it works second time round
masks #2195 does not fix it
> image hash work around

- lib/iris/tests/__init__.py
The missing part of the new image test work-flow, to allow developers to create missing/new image test expected result files and associated entries in the `imagerepo.json` file.
> Check graphic create missing

- .travis.yml
- docs/iris/example_tests/extest_util.py
- docs/iris/example_tests/test_atlantic_profiles.py
- lib/iris/plot.py
- lib/iris/tests/__init__.py
- lib/iris/tests/experimental/test_animate.py
- lib/iris/tests/idiff.py
- lib/iris/tests/integration/plot/test_colorbar.py
- lib/iris/tests/results/imagerepo.json
- lib/iris/tests/runner/_runner.py
- lib/iris/tests/test_coordsystem.py
- lib/iris/tests/test_hybrid.py
- lib/iris/tests/test_image_json.py
- lib/iris/tests/test_mapping.py
- lib/iris/tests/test_plot.py
- lib/iris/tests/test_quickplot.py
This PR provides a more stable and scalable approach to the new graphic testing framework, replacing cryptographic sha based image hashes with perceptual image hashes.
It relies on the support of the new perceptual image hash repository [test-iris-imagehash](https://github.com/SciTools/test-iris-imagehash).
Perceptual image hashes allows checking for the degree of *similarity* between images through measuring the hamming distance difference (a count of bit differences) between image hashes. 
The major benefit of this perceptual image hash approach is that it is simple, scalable (already almost halved the number of required reference images) and makes us less sensitive to scientific software stack dependency changes.
This PR also addresses the issues raised in #2195. Normally, I would have …
> Perceptual image hashing

- lib/iris/tests/results/imagerepo.json
This PR aligns the `imagerepo.json` file with https://github.com/SciTools/test-iris-imagehash/pull/8
> Update imagerepo.json for sss

- lib/iris/tests/runner/_runner.py
For the first time I've seen some `nose.plugins.multiprocess.TimedOutException` being raised on `travis-ci` ... so I've bumped up the `--process-timeout`
We might have been on the edge with the current timeout of `250` seconds and introducing the thread-safe plotting may be pushing it just over the edge (plus also given the variable load on `travis-ci`)
> Bump the nose multiprocess timeout

- lib/iris/config.py
enable test data path to be overridden at run time, via an environment variable
> override test data path

- .travis.yml
- conda-requirements.txt
- minimal-conda-requirements.txt
update travis to use imagehash from conda/scitools
> imagehash via conda

- lib/iris/tests/__init__.py
remove the behaviour, introduced in #2192, where installations without write permissions to the iris source directories are unable to run tests, due to 
```
IOError: [Errno 13] Permission denied: 'imagerepo.lock'
```
@bjlittle does this maintain your desired behaviour for developers whilst removing the installation and testing  block?
> limit filelock use

- lib/iris/tests/unit/fileformats/dot/test__dot_path.py
replaces #2220 
same code, but targeted at v1.11.x
> Prevent dot_path tests from corrupting the stored path.

- lib/iris/tests/test_cdm.py
Without this, the test fails when run in isolation,
with a couple of errors like "AttributeError: 'module' object has no attribute 'dot'".
It doesn't **usually** fail when running all tests, presumably because some other test imports it first.
However, think this error has occurred sometimes.
I believe the order of running tests is not dependable.
In any case, this is an obvious bug, as we _shouldn't_ have such dependencies.
> Dot test import

- lib/iris/tests/__init__.py
This should hopefully fix the bug introduced in #2221.
> Fix filelock bug

- .travis.yml
Unpin versions of `miniconda` in the `.travis-ci` to be the latest.
> Unpin miniconda to latest

- lib/iris/plot.py
This PR addresses the post-merge issues raised by @dkillick on https://github.com/SciTools/iris/pull/2206.
Locking at the iris plot level will not guarantee to the user thread-safe plotting. In certain circumstances there is still the possibility of an iris plot using an mpl figure from a different thread. In the case of https://github.com/SciTools/iris/pull/2206, the implementation introduced a locking mechanism at the iris plotting api level, which is in fact at **too low** a level.
If a user insists on using iris plotting in a threaded context, then we should advocate that they take responsibility for locking themselves (which, to be fair, is pretty simple to do) in combination with creating the target mpl figure/axes (within the safety of the locked critical region).
Note that, for …
> Remove plot api locking.

- INSTALL
- previous URL points to "PythonXY Roofing Guide"
- remove extraneous backtick
> Correct Python(x,y) URL

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_CubeList.py
usability tweak to `CubeList.__str__` to print a STASH code, if it exists and otherwise 
`unknown / (unknown)` 
would otherwise be returned
> Stashcubelist

- lib/iris/coord_systems.py
- lib/iris/experimental/regrid.py
- lib/iris/tests/unit/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py
Floating point equality without tolerance within `iris.experimental.regrid._within_bounds`
Replaces #2201
> BUG: Iris AreaWeighted regrid float tolerance bug

- lib/iris/tests/__init__.py
- lib/iris/tests/idiff.py
- lib/iris/tests/runner/_runner.py
Now that https://github.com/SciTools/conda-recipes-scitools/pull/210 has been merged (thanks to @ocefpaf in https://github.com/SciTools/conda-recipes-scitools/pull/211) we can now use the shiny new `v3.1` of `imagehash` which has the fix required to `imagehash.hex_to_hash` for variable `hash_size`'s.
> Use v3.1 imagehash.hex_to_hash

- lib/iris/tests/test_cdm.py
The really big 'rtol' values bothered me, so here I've reduced them, just so far as allows it to succeed with both numpy 1.10 and 1.11.
I think we **_still**_ have a problem with the collapse calculations (see below).
However, I don't know yet if that is relevant to these result differences between numpy 1.10 and 1.11.
I did also try to retest with numpy 1.8, but dependencies don't resolve so easily for the latest Iris.
(So I gave up).
I think we really don't care about 1.8 any more.
> Tighten some assertCMLApproxData rtols.

- lib/iris/config.py
- lib/iris/tests/runner/_runner.py
This PR corrects the use of the `override_test_data_repository` environment variable, and applies the standard naming convention of using upper-case environment variables :pray: 
It also fixes the broken test runner option `--no-data` to **actually** ignore the test data.
This corrects #2211 and addresses the ignored [comment](https://github.com/SciTools/iris/pull/2211#discussion_r84714014)
@dkillick and @lbdreyer
> Fix test runner override and no-data

- INSTALL
If you wish to run any of the code examples you need access to the Iris sample data, which can now be easily installed from Conda. This, however, may not be very clear to new users, so I'm proposing that we add mention of the Iris sample data to the `INSTALL` document.
Addresses part of #2232.
> DOC: mention sample data in INSTALL

- lib/iris/fileformats/pp.py
The PP load/save pipeline has been substantially changed for v1.10, with a number of old bits of functionality being deprecated. Unfortunately the deprecation messaged for two of the deprecated functions (being `add_save_rules` and `reset_save_rules`) actually pointed the user to go and use another function (`as_pairs`) that had itself been deprecated by `save_pairs_from_cubes`.
This PR corrects the deprecation warning messages to point to the non-deprecated function rather than the deprecated function.
> Correct PP deprecation notices

- docs/iris/src/conf.py
- lib/iris/io/__init__.py
Corrects the link to the grib saver in the reference documentation section on save. This link was entirely broken - it had been malformed and was pointing to the iris-grib homepage on GitHub, which is very definitely *not* documentation!
The link now points to the section on saving to GRIB2 in the (now-released) iris-grib docs on readthedocs. This has been achieved by adding a new intersphinx mapping to the Iris docs `conf.py` file.
> DOC: Correct link to GRIB saver

- lib/iris/tests/integration/test_trajectory.py
- lib/iris/tests/unit/analysis/interpolate_private/__init__.py
- lib/iris/tests/unit/analysis/interpolate_private/test__nearest_neighbour_indices_ndcoords.py
- lib/iris/tests/unit/analysis/trajectory/__init__.py
- lib/iris/tests/unit/analysis/trajectory/test_Trajectory.py
- lib/iris/tests/unit/analysis/trajectory/test_interpolate.py
Improve and extend tests for trajectory and especially trajectory nearest-neighbour interpolation.
Intended to feed into #2252, to prove it doesn't break anything.
However, that is not yet checked, so there may be more work needed to make all that work seamlessly.
> Trajectory regrid tests

- lib/iris/analysis/_interpolate_private.py
- lib/iris/analysis/trajectory.py
- lib/iris/tests/integration/test_trajectory.py
- lib/iris/tests/unit/analysis/interpolate_private/test__nearest_neighbour_indices_ndcoords.py
- lib/iris/tests/unit/analysis/trajectory/test_interpolate.py
Provides a huge speedup to trajectory interpolation.
Sorry it's so complicated : changes are staged in individual commits, which may help.
Stop Press: now rebased, good to go
> Trajectory vectorise

- docs/iris/src/whatsnew/contributions_1.10/newfeature_2016-May-20_lazy_cube_transpose.txt
- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
1. Simply utilises the capabilities of biggus to provide a transposed version of the data rather than making a copy (necessary with the sizes of data we are working with).
2. ~~Using 1, also provides in-place dimension inversion (intentionally constrained implementation).~~ - now moving to a new PR after the merge of this one.
> ENH: Lazy in-place Cube transpose

- lib/iris/fileformats/pp.py
- lib/iris/tests/unit/fileformats/pp/test__field_gen.py
If the length of a PP field's data record as specified by the field's header and the integer word that follows the header do not match, Iris very reasonably currently fails to load the whole PP file.
This PR reduces the barrier in such a case so that the PP loader pipeline will raise a warning in such a case and then exit, returning all successfully loaded fields up to this point. This at least means that Iris users can get to most of a PP file rather than none of it.
This PR very much follows the approach introduced in #1444 for relaxing loading of bad PP headers.
~~Note: no testing.~~
> Relax data length constraint in PP load

- lib/iris/analysis/__init__.py
- lib/iris/analysis/_area_weighted.py
Just to clarify the usage scope of 'AreaWeighted'.
Existing notes are a bit wrong, it looks like they were copied from Linear/Nearest, which work in a different way and are not specific to X/Y dimensions.
> Add scoping to docs.

- lib/iris/tests/__init__.py
I'm proposing this because I think it's always better to use relative tolerances than absolute in a general values check -- as otherwise you are assuming the general 'size' of the values tested.
Hence, **this is changing "5 decimal places" to "6 significant figures"**.
As it was, the routine was testing everything to +/-0.00001 (or maybe half that),
so E.G.  0.0001 +/- 0.00001 would be only to 10%,
but 10000 +/- 0.00001 must match to about 0.001ppm
As it happens, all the (few) places where we ***currently*** use this have values of magnitude greater than 10.0, so this is effectively relaxing all those testing levels.
I think that is ok for now.
Otherwise, I think ArrayShapeStats is a great idea, and certainly loads better than assertCML for a whole lot of purposes !
> Replace absolute with relative tolerance.

- lib/iris/experimental/regrid.py
My editor (Eclipse/PyDev) does some static analysis and it flags up [this line](https://github.com/SciTools/iris/blob/f10eb54d527cdf094c5f38179a800a68e0c9e19f/lib/iris/experimental/regrid.py#L1539) as a bug, because 'six' is not imported.
I guess this has never actually been exercised ?
I s'pose, ideally, all codepaths would be tested ...
> Fix import bug.

- lib/iris/fileformats/um/_fast_load.py
Suggested as a good idea for #2241, but it got forgotten.
Retry of #2269, now targetting v1.12.x
> Link callback rewrite example into structured-load docstring.

- lib/iris/tests/test_image_json.py
an attempt to reduce the sporadic incidence of 
```
======================================================================
FAIL: test_resolve (iris.tests.test_image_json.TestImageFile)
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/Iris-1.12.0.dev0-py3.4-linux-x86_64.egg/iris/tests/test_image_json.py", line 95, in test_resolve
self.assertEqual(deque(), exceptions)
AssertionError: deque([]) != deque([ConnectionError(MaxRetryError("HTTPSConne[372 chars]),)])
----------------------------------------------------------------------
```
e.g. #2267 
ping @lbdreyer
> reduce http get overhead

- lib/iris/analysis/__init__.py
- lib/iris/analysis/_interpolate_private.py
- lib/iris/analysis/trajectory.py
- lib/iris/tests/integration/test_regridding.py
- lib/iris/tests/unit/analysis/trajectory/test_UnstructuredNearestNeighbourRegridder.py
A few functional changes / fixes.
A lot of documentation and testing enhancements.
> Unstructured regridder : usage tidying

- lib/iris/fileformats/um/_fast_load_structured_fields.py
- lib/iris/tests/integration/fast_load/test_fast_load.py
This should allow structured-loading to work with most files where pseudo-levels are used.
If 'ordinary' levels (LBLEV values) and 'pseudo-levels' (LBUSER5) both vary at once, this rather inelegant solution could still have problems, potentially producing 2 vertical coordinates.
But only if that occurs ***within*** a phenomenon, which we think is probably not realistic ?
Note: 
Possibly needs tidying a bit further.
? Should I remove that commented-out 'fixed' failure code in ```tests.integration.fast_load.MixinProblemCases.test_FAIL_pseudo_levels``` ?
I have left it, assuming it is a useful statement of what the key problem actually is.
> Structured load pseudolevels

- docs/iris/src/whatsnew/contributions_1.12/newfeature_2017-Jan-05_experimental_scipy_regridder.txt
- lib/iris/experimental/regrid.py
- lib/iris/tests/__init__.py
- lib/iris/tests/integration/experimental/test_regrid_ProjectedUnstructured.py
This PR adds the linear scheme of the regridder that uses `scipy.interpolate.griddata`.
I have also added some more tests for the nearest-neighbour scheme as source cubes with aux_factories weren't being tested, as highlighted by @pp-mo in #2263 
Note the test data doesn't have much variation in the data within the layers themselves (between the layers there's quite a difference, hence the large values for the standard deviation which is calculated for the **_whole_** cube), so I was getting similar values for mean and standard deviation, regardless of whether I used the linear or nearest (see the test `TestProjectedUnstructured.test_use_default_rtol`, which I do intend to remove, I just added it to prove what I had found).
I have solved this problem by allowing the tolerance to be set …
> Add linear scipy projected regridder

- lib/iris/analysis/_interpolate_backdoor.py
- lib/iris/analysis/interpolate.py
In response to : #1982 (comment)
It seems when we deprecated the iris.analysis.interpolate functions, we also stopped building docs for them, which is unhelpful + was really not intended.
Retry of #2270, now targetting v1.12.x
> Tidy wrapper imports and reinstate docs for iris.analysis.interpolate.

- docs/iris/src/whatsnew/contributions_1.12/deprecate_2016-Nov-09_experimental_fieldsfile.txt
- docs/iris/src/whatsnew/contributions_1.12/newfeature_2016-May-20_lazy_cube_transpose.txt
- docs/iris/src/whatsnew/contributions_1.12/newfeature_2016-Nov-09_structured_um_loading.txt
I think this fixes a problem introduced by #2286
These changes were proposed before recent releases, but only now merged, so the whatsnew contributions now belong to 1.12.
Actually, I think it would be better if we did ***not*** include the version in the name of the contributions directory, but just had a fixed name for it.  Then we wouldn't need to destroy + recreate it either.
It's not a trivial change though, so I've made a separate issue to cover it : #2289
> Reinstated lost whatsnew items, now to appear in the 1.12 whatsnew.

- lib/iris/analysis/_interpolate_backdoor.py
- lib/iris/analysis/interpolate.py
> Fix header dates.

- docs/iris/src/developers_guide/documenting/whats_new_contributions.rst
- docs/iris/src/developers_guide/graphics_tests.rst
- docs/iris/src/developers_guide/tests.rst
This is just a temporary hint for the RC1 tag,
in lieu of a proper account, which is still being worked on under #2185
> Basic hints about new graphics testing, pending a full account.

- docs/iris/src/whatsnew/contributions_1.12/newfeature_2017-Jan-09_unstructured_scheme.txt
- lib/iris/analysis/__init__.py
- lib/iris/experimental/regrid.py
Add whatsnew, and explain difference to ProjectedUnstructuredNearest.
Addresses one of the items in #2280.
That should be good enough for us to cut an RC1.
> More docs for UnstructuredNearest

- lib/iris/tests/test_image_json.py
hopefully this will mitigate the risk that github api calls return a 403 forbidden
the docs suggest this should always have happened, if you read them a certain way
https://developer.github.com/v3/#user-agent-required
so i'm not sure this is the cause/fix for intermittent 403s, we shall see
> github api user agent

- lib/iris/fileformats/um/_fast_load.py
- lib/iris/fileformats/um/_fast_load_structured_fields.py
Just explains the temporary solution introduced in #2274
> Document pseudo-level support in structured um loading.

- docs/iris/src/userguide/plotting_examples/cube_contour.py
The example in the userguide section for [plotting a contour of a cube](http://scitools.org.uk/iris/docs/latest/userguide/plotting_a_cube.html?highlight=clabel#cube-contour) is not correct. The are spurious horizontal lines across the image.
Not being terribly familiar with how clabel works, I suspect that this is due to clabel removing some of the contour near where it wants to put the label, so that the label is more visible.
By setting inline to be False, clabel does not remove any of the contour so it renders correctly but it does make it a little harder to see
This is not an iris issue, I think the issue is in matplotlib itself. Below I have plotted the data in the cube using just matplotlib and I still get an error with missing contours
> Set clabel inline=False to fix contout plot

- docs/iris/src/developers_guide/graphics_tests.rst
- docs/iris/src/developers_guide/pulls.rst
- docs/iris/src/developers_guide/tests.rst
First cut at documenting new graphics test arrangements + workflow.
**NOT yet complete**
> Graphics tests docs

- lib/iris/tests/test_image_json.py
Reverts SciTools/iris#2326
this is not a useful change and will conflict with better implementations
> Revert "github api management"

- lib/iris/tests/test_image_json.py
improvement on #2326 (reverted by #2327)
only use anonymous github api get if there are rate limit calls remaining
risk:  an image not added to the image repo is referenced in a new test and missed; likelihood: low, this isn't going to happen often and will likely be caught quickly
benefit: the majority of PRs, which have no impact on this test coverage, will try to run this test, but only run it if it will not fail due to github's harsh rate limiting controls for an IP
the `tests.skip_data` ensures this doesn't run in minimal test mode, so the number of calls from a single test set run is 2, not 4
> github api care

- docs/iris/src/whatsnew/1.12.rst
- lib/iris/analysis/cartography.py
- lib/iris/experimental/regrid.py
- lib/iris/tests/test_analysis.py
- lib/iris/tests/unit/analysis/cartography/test__quadrant_area.py
This PR changes the computation of area weights to a more numerically stable form. The previous form converted latitude to colatitude and used difference of cosines in the cell area computation. This formulation uses latitude and difference of sines. The conversion from latitude to colatitude at lower precision causes errors when computing the cell areas (see [this google group thread](https://groups.google.com/forum/?fromgroups=#!topic/scitools-iris/yTw387ZXRAk)). This should be considered a bug fix in my opinion.
I've provided 2 new tests, the 32-bit test fails with the old formulation but passes with the new one. All the existing tests still pass.
> More stable area weights computation

- .mailmap
In an attempt to sanitise the git author log, I have added the appropriate mailmap file.
Happy to adjust this in any way - remember this information is all stored in the git-log anyway, I'm just trying to map multiple "git authors" to individuals....
https://git-scm.com/docs/git-shortlog#_mapping_authors
> Added a mailmap to tidy up git commit authors.

- lib/iris/fileformats/cf.py
I am hitting a 
```python
TypeError: sequence item 0: expected str instance, bytes found
```
with my dataset and I believe that, based on the logic in https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/cf.py#L705, this should be `b' '`  here too,
> Fix 1-dim label data

- lib/iris/tests/__init__.py
- lib/iris/tests/unit/test_skip_biggus.py
Add @skip_biggus for dask development
> Dask skip biggus

- lib/iris/tests/__init__.py
- lib/iris/tests/unit/tests/test_IrisTest.py
This was producing unhelpful messages when a tested result is unexpectedly *not* a masked array.
This should make it consider an unmasked array "equal to" a masked one with an empty mask.
Applies to ```assertMaskedArrayEqual``` and ```assertMaskedArrayAlmostEqual```
( n.b. *we don't have* an "```assertMaskedArrayAllClose```" )
**NOTE:** in dask work, but targetting master
> Make assertMaskedArrayXxx with nonmasked results.

- conda-requirements.txt
- lib/iris/_lazy_data.py
- lib/iris/tests/unit/lazy_data/__init__.py
- lib/iris/tests/unit/lazy_data/test_as_concrete_data.py
- lib/iris/tests/unit/lazy_data/test_as_lazy_data.py
- lib/iris/tests/unit/lazy_data/test_is_lazy_data.py
- minimal-conda-requirements.txt
**DO NOT MERGE**
Still in development..
This is a starting point for replacing all Iris' explicit use of biggus concepts with something more detached from the implementation.
( Which I think should be better than explicitly referencing dask everywhere instead. )
At present there is no recognition here that realisation with 'as_concrete_array' *might* need to make some distinction whether the result should be a masked array (as biggus API does).
For the cube.data property (getter), this is the existing Iris behaviour anyway.
> Generic lazy data handling.

- lib/iris/tests/__init__.py
- lib/iris/tests/test_cell.py
- lib/iris/tests/test_cf.py
- lib/iris/tests/test_coding_standards.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/test_io_init.py
- lib/iris/tests/test_plot.py
- lib/iris/tests/test_pp_module.py
- lib/iris/tests/test_std_names.py
- lib/iris/tests/test_util.py
- lib/iris/tests/unit/analysis/maths/test_add.py
- lib/iris/tests/unit/analysis/maths/test_divide.py
- lib/iris/tests/unit/analysis/maths/test_multiply.py
- lib/iris/tests/unit/analysis/maths/test_subtract.py
- lib/iris/tests/unit/fileformats/grib/message/test_GribMessage.py
- lib/iris/tests/unit/merge/test_ProtoCube.py
- lib/iris/tests/unit/tests/test_IrisTest.py
Adds the ability to spit out an execution time for tests as they run.
> Test timings

- lib/iris/tests/integration/test_pp.py
A mock replacing a PPField now behaves differently in the PPField.data call (in pp.py).
It _used_ to have ```isinstance(data, biggus.Array)```, to which Mock replies 'False'.
Now has ```is_lazy_data(data)```, which translates to ```hasattr(data, 'compute')```, to which Mock replies True.
It seems that np.array(mock) is ok, but ```np.ma.masked_array(mock)``` does something nasty.
> Mocked PPFields need a useable _data property.

- lib/iris/analysis/maths.py
- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py
- lib/iris/tests/experimental/regrid/test_regrid_conservative_via_esmpy.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/integration/test_regrid_equivalence.py
- lib/iris/tests/integration/test_trajectory.py
- lib/iris/tests/test_aggregate_by.py
- lib/iris/tests/test_analysis.py
- lib/iris/tests/test_basic_maths.py
- lib/iris/tests/test_cdm.py
- lib/iris/tests/test_ff.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/test_pandas.py
- lib/iris/tests/test_peak.py
- lib/iris/tests/test_plot.py
- lib/iris/tests/test_pp_cf.py
- lib/iris/tests/unit/analysis/cartography/test_project.py
- lib/iris/tests/unit/analysis/interpolate/test_linear.py
- lib/iris/tests/unit/analysis/maths/test_divide.py
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py
- lib/iris/tests/unit/analysis/stats/test_pearsonr.py
- lib/iris/tests/unit/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py
- lib/iris/tests/unit/experimental/regrid/test_regrid_weighted_curvilinear_to_rectilinear.py
- lib/iris/tests/unit/fileformats/grib/save_rules/test_data_section.py
Currently unsure whether the tests in 'lib/iris/tests/experimental/regrid/test_regrid_conservative_via_esmpy.py' pass, because they are all skipped due to not having esmpy.
If they pass the Travis tests, I will remove them.  Otherwise, I will replace them.
> passing tests unskipped

- lib/iris/fileformats/_ff.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/rules.py
- lib/iris/fileformats/um/_fast_load_structured_fields.py
- lib/iris/tests/integration/test_pp.py
- lib/iris/tests/unit/fileformats/pp/test__create_field_data.py
- lib/iris/tests/unit/fileformats/pp/test__field_gen.py
- lib/iris/tests/unit/fileformats/pp/test__interpret_field.py
In at least one place (`iris.fileformats.pp._make_cube()`) there is code to handle an object which may be either a `PPField` or a `FieldCollation`. The code in `_make_cube()` does this with try/except on the existence of a `_data` attribute, which is only present on PPField and is intended to be either lazy or not, akin to `Cube._my_data`. As mentioned in a code comment, this is causing tests using `MagicMock`s to magically pass.
The code on the current dask_timed branch doesn't function correctly in the non-lazy case; the `_data` attribute is always wrapped up as a dask array before being passed into the `Cube` constructor.
This PR adds a `core_data` property to both the `PPField` and the `FieldCollation` classes, which behaves similarly to `Cube.core_data` in the `PPField` case, and …
> PPfield core_data

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/fileformats/grib/message/test_GribMessage.py
- lib/iris/tests/unit/fileformats/netcdf/test_save.py
- lib/iris/tests/unit/util/test_new_axis.py
This is not a complete fix for cube.intersection, this is just a first little attempt I have made at swapping out Biggus.  Not convinced that all the tests will pass, but it's a good start at the very least.
> Replace intersection

- lib/iris/cube.py
There were a few inconsistencies in the `cube` + `dask` code, and instead of noting them down for further discussion, I thought I'd make a vessel for discussion (that is, this PR).
A retargetting of #2415 to the base `dask_timed`.
> Coding standards tweaks to daskified cube code

- docs/iris/src/developers_guide/dask_interface.rst
This quite large diff masks some small changes, primarily structural, to the developer guide section on the Iris-dask interface. Notably:
* bulleted sections are spaced so that they render as bulleted sections
* where there are cross-links to be made into docstrings, these have been added as sphinx markdown (note these don't work yet as the docs building has been temporarily disabled on this branch - but these are added for their future value)
* code element describing words (such as `ndarray`) have been formatted so they will appear as pre-formatted text
* a few changes to the actual text to correct terminology or improve legibility.
> Polish dask dev guide section

- lib/iris/_lazy_data.py
- lib/iris/_merge.py
- lib/iris/cube.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/um/_fast_load_structured_fields.py
- lib/iris/tests/integration/test_trajectory.py
- lib/iris/tests/unit/analysis/interpolation/test_RectilinearInterpolator.py
- lib/iris/tests/unit/analysis/test_MEAN.py
- lib/iris/tests/unit/analysis/test_STD_DEV.py
- lib/iris/tests/unit/analysis/test_VARIANCE.py
- lib/iris/tests/unit/aux_factory/test_AuxCoordFactory.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/fileformats/um/fast_load_structured_fields/test_FieldCollation.py
- lib/iris/tests/unit/lazy_data/test_as_lazy_data.py
- lib/iris/tests/unit/lazy_data/test_is_lazy_data.py
- lib/iris/tests/unit/util/test_new_axis.py
The return of the `as_lazy_data` function, which acts as Iris' interface to `da.from_array`. I've added tests for the function and changed the Iris code and tests so that it always uses the new function and does not call `da.from_array` directly.
> Reinstate `as_lazy_data`

- lib/iris/plot.py
- lib/iris/tests/unit/plot/test_plot.py
When doing a 1d plot on a map, the line connecting consecutive points will always remain within the 0-360 range, even if a shorter line could be plotted across the 'edge' of that range. This PR fixes that.
> Wrap 1d map plot

- lib/iris/fileformats/name_loaders.py
- lib/iris/tests/results/name/NAMEIII_trajectory.cml
- lib/iris/tests/results/name/NAMEIII_trajectory0.cml
Added code to allow the reading of NAME trajectories stored by time instead of by particle number. This results in a cube with a dimension coordinate of ppindex (c.f. trajectories stored by particle number will produce a cube with a dimension coordinate of time). Also added some of the file header information into the cube attributes.
> Trajectories by time

- lib/iris/tests/__init__.py
When an image hash check fails, a `ValueError` is raised, causing unit tests to register as errors rather than failures. This PR changes `ValueError` to `AssertionError`.
> Make image has tests register as failures rather than errors

- lib/iris/_lazy_data.py
- lib/iris/fileformats/netcdf.py
- lib/iris/fileformats/pp.py
- lib/iris/tests/results/unit/merge/ProtoCube/register__CubeSig/noise.txt
- lib/iris/tests/unit/lazy_data/test_array_masked_to_nans.py
I think that `array_masked_to_nans` should _always_ return a `numpy.ndarray` and not a `ma.core.masked_array` as used to happen. This means we don't have to call `data = data.data` after every time we use `array_masked_to_nans` in Iris code.
I've also removed the optional `mask` argument from `array_masked_to_nans` as it was only used once and ran the risk of confusing the usage of the function. At its worst, it would have been possible to pass a masked array and an unmatched mask, at which point the function would have returned an array that was not completely filled with `nan`s.
> Tighten purpose of `array_masked_to_nans`

- lib/iris/_lazy_data.py
- lib/iris/analysis/__init__.py
- lib/iris/analysis/_interpolation.py
- lib/iris/analysis/_regrid.py
- lib/iris/cube.py
- lib/iris/etc/pp_save_rules.txt
- lib/iris/experimental/raster.py
- lib/iris/fileformats/cf.py
- lib/iris/fileformats/grib/_load_convert.py
- lib/iris/fileformats/grib/_save_rules.py
- lib/iris/fileformats/grib/grib_save_rules.py
- lib/iris/fileformats/netcdf.py
- lib/iris/fileformats/pp.py
- lib/iris/pandas.py
- lib/iris/tests/__init__.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/util.py
Consistency! And using part of an API for what it was meant for (in this case checking that an object is of a certain type).
To wit, anything that looks like the former will now look like the latter:
* `if isinstance(thing, ma.core.MaskedArray)` --> `if ma.isMaskedArray(thing)`
* `if thing is ma.masked` --> `if ma.is_masked(thing)`
> Consistent check for masked array types

- lib/iris/_lazy_data.py
- lib/iris/_merge.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/fileformats/pp.py
- lib/iris/tests/unit/analysis/test_MEAN.py
- lib/iris/tests/unit/analysis/test_STD_DEV.py
- lib/iris/tests/unit/analysis/test_VARIANCE.py
- lib/iris/tests/unit/lazy_data/test_as_concrete_data.py
- lib/iris/tests/unit/lazy_data/test_as_lazy_data.py
- lib/iris/tests/unit/lazy_data/test_convert_nans_array.py
- lib/iris/tests/unit/lazy_data/test_is_lazy_data.py
- lib/iris/tests/unit/lazy_data/test_multidim_lazy_stack.py
> Replace dask 'compute()' usage with a common realisation call. (#2)

- lib/iris/_concatenate.py
- lib/iris/_lazy_data.py
- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/lazy_data/test_array_masked_to_nans.py
Fix to support `dtype.kind` to also check for `uint` and `bool` cases (as well as `int`).
> Fix for dtype.kind

- lib/iris/_lazy_data.py
- lib/iris/cube.py
- lib/iris/tests/unit/concatenate/test_concatenate.py
- lib/iris/tests/unit/cube/test_Cube__operators.py
Remove the final biggus imports (and usages) from the codebase*.
In essence, this means:
* delete a couple of spurious (and unused!) biggus import statements,
* sort out some test modules, and
* tidy up the lazy data API where the tests very pleasingly showed up a couple of gaps in it.
Fixes #2443.
&nbsp;
\* Well, not _quite_: I explicitly **haven't** dealt with grib here - we'll [do](https://github.com/SciTools/iris/issues/2342) that [later](https://github.com/SciTools/iris/issues/2306).
> Remove the last bits of biggus

- lib/iris/coords.py
I goofed the previous merge when I mis-edited the commit message + then manually corrected it.
It seems I inadvertently added back [this change](https://github.com/SciTools/iris/pull/2440/commits/5c97da0fc0aa783f784e50960e1db01bf9407d7b), which I thought I'd excluded but I probably squashed together in error.
This fixes.
> Minor pep8 fix.

- .travis.yml
- conda-requirements.txt
Run Travis tests using the conda-forge channel. Will fail until https://github.com/SciTools/iris/pull/2440 is merged.
> adopt conda-forge

- lib/iris/tests/integration/test_trajectory.py
Simply remove a reference to biggus in a test case comment.
> Remove biggus from test comment.

- lib/iris/_lazy_data.py
- lib/iris/tests/unit/lazy_data/test_iris_dask_defaults.py
A much simplified replacement for #2462 and thus also a fix for #2403.
Instead of having a highly complex Iris option class that places an Iris API around the "non-API" of `dask.set_options` and potentially tying ourselves into a very tight coupling to `dask.set_options`, this PR just calls `dask.set_options` from within `iris._lazy_data` at import time. The call to `dask.set_options` is conditional on the user having not already specified dask options so that importing Iris does not change dask options that are not the default.
The only dask option that may be set by Iris is setting the `get` function to the synchronous scheduler `dask.async.get_sync`. This scheduler only runs on a single thread, which matches to the requirement suggested in #2403. In testing this scheduler was shown to …
> Dask options for Iris processing

- lib/iris/_constraints.py
this doc string is non-functional
```
AttributeError: 'STASH' object has no attribute 'endswith'
```
> doc string bug

- lib/iris/coords.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/unit/coords/test_Coord.py
While considering #2490 I noticed that a sliced Coord (an AuxCoord, at least) can be linked to the original.
This is exactly what we found when working on #2513, and fixed in [this line in that PR](https://github.com/SciTools/iris/pull/2513/files#r113925900)
I think this is a simple bug, as concluded for the CellMeasures.
Obviously though, a behaviour change in coords could be a bit more dangerous.
There were some very old tests that check the exact opposite behaviour (i.e. indexed coords share data with their originals), so I got rid of those.
Otherwise, it didn't break any existing tests ! :crossed_fingers: 
Note that this modified `Coord.__getitem__` code will simplify nicely when we get rid of `LazyArray`s.
Currently we must still support LazyArray-s for points and bounds data, as aux …
> Prevent sliced coords sharing data with their parent coord.

- lib/iris/_merge.py
- lib/iris/aux_factory.py
- lib/iris/coords.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/tests/integration/test_aggregated_cube.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/test_hybrid.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/test_pickling.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_reorder_bounds_data.py
In the past the coord `LazyArray` class was used to defer loading of all coords, but now it is only used to defer calculation of derived coordinates. However, there was still some `LazyArray` logic hanging around in the wider coords codebase, which was getting in the way of integrating the `DataManager` with coords. We have decided to remove the `LazyArray` class entirely to help this all along.
Note that doing this does not prevent derived coords from being calculated, but it does mean that the calculation is (currently) not deferred. When we come to [integrating derived coords with the `DataManager`](https://github.com/SciTools/iris/issues/2495) we can look to correcting this change, if by using dask deferral rather than by using the `LazyArray` class.
> Remove `LazyArray` class from coords

- lib/iris/analysis/maths.py
- lib/iris/tests/unit/analysis/maths/__init__.py
- lib/iris/tests/unit/analysis/maths/test_add.py
- lib/iris/tests/unit/analysis/maths/test_divide.py
- lib/iris/tests/unit/analysis/maths/test_multiply.py
- lib/iris/tests/unit/analysis/maths/test_subtract.py
- lib/iris/tests/unit/analysis/stats/test_pearsonr.py
When two cubes have coordinates which do not match, an error should be raised if a user tries to perform arithmetic operations on them.  These cases are caught by the add and subtract operators, but not the multiply and divide operators.
This PR contains tests for all the operators on a) a pair of cubes with totally non-matching coordinates and b) a pair of cubes with one coordinate array reversed.
It also extends the behaviour of add and subtract to apply to multiply and divide.
> Badmaths tests and fixes

- lib/iris/cube.py
- lib/iris/tests/results/analysis/aggregated_by/multi_missing.cml
- lib/iris/tests/results/analysis/aggregated_by/single_missing.cml
- lib/iris/tests/results/analysis/last_quartile_foo_3d_masked.cml
- lib/iris/tests/results/analysis/proportion_foo_2d_masked.cml
- lib/iris/tests/results/analysis/regrid/linear_subset_masked_1.cml
- lib/iris/tests/results/analysis/regrid/linear_subset_masked_2.cml
- lib/iris/tests/results/analysis/regrid/nearest_subset_masked_1.cml
- lib/iris/tests/results/analysis/regrid/nearest_subset_masked_2.cml
- lib/iris/tests/results/experimental/analysis/interpolate/LinearInterpolator/orthogonal_cube_with_factory.cml
- lib/iris/tests/results/netcdf/netcdf_cell_methods.cml
- lib/iris/tests/unit/cube/test_Cube.py
This PR is a follow-on action from #2492 and detailed in #2516 and allows the `cube.fill_value` to be set from the `fill_value` of concrete masked data being passed to `cube.data` setter.
All of the CML changes are due to either tests directly setting `cube.data` with a masked array, or tests that use testing stock cubes that set `cube.data` directly with a masked array ... thus populating the `cube.fill_value` and thus bleeding thru to the CML. This is the behaviour that we want to see.
If data passed to the `cube.data` setter is not masked data, then the `cube.fill_value` will be clear, as before.
This PR also neatly completes the circle with `fill_value` and masked arrays wrt the cube, in that the `cube.data` getter will set the `fill_value` of any masked array returned to the user …
> Populate cube.fill_value thru cube.data setter.

- lib/iris/_concatenate.py
- lib/iris/_merge.py
- lib/iris/tests/results/concatenate/concat_2y2d.cml
- lib/iris/tests/results/concatenate/concat_masked_2x2d.cml
- lib/iris/tests/results/concatenate/concat_masked_2y2d.cml
- lib/iris/tests/test_concatenate.py
- lib/iris/tests/test_merge.py
This PR refines the approach taken with handling the `cube.fill_value` by merge and concatenate.
This PR extends the expected behaviour of `numpy` with regards to how it manages the `fill_value` when combining masked arrays and/or ndarrays to cubes (it is valid for a cube to have a `fill_value` even though it has a ndarray payload).
In summary, when combining cubes via merge or concatenate, the resultant cube will have:
* a `fill_value` that is non-`None` **iff** all cubes have the same non-`None` `fill_value`
* a `fill_value` that is `None`, if:
* at least one cube has a `fill_value` of `None`, or
* the candidate cube and the proto-cube have a different `fill_value`
This simply means that, 
* if the `cube.fill_value` is set to a non-`None` value, and the cube has a masked payload, then …
> Dask merge concat fill value

- lib/iris/__init__.py
- lib/iris/_merge.py
- lib/iris/aux_factory.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/tests/unit/util/test__slice_data_with_keys.py
- lib/iris/util.py
This is a useful preliminary to replacing lazy/real array data with DataManager in Coords code.
It reduces the indexing code in those 3 areas to suspiciously similar usages, with the bulk of the common code in a new private utility routine `iris.utils._slice_data_with_keys` :  I think that code can usefully go inside `DataManager.__getitem__` in future.
In future, in addition to rebasing all these 3 areas onto DataManager, I would also move the coord points and bounds accessors into `Coord` as generic methods, and make DimCoord extend the generic calls with its extra checks and tweaks.  The new similarities of handling make this attractive, but it is better left undone because (a) it makes this PR simpler and (b) it will be simpler when the underlying data objects are all DataManager-s. …
> Unify getitem code between Cube, Coord and CellMeasures.

- lib/iris/tests/unit/util/test__coord_regular.py
- lib/iris/util.py
The existing checks for whether a coord is regular in `iris.util` quite reasonably only works on coords. However in #2527 I need to check whether just a set of _points_ is regular, which the existing functionality could not achieve.
To deal with this I have added a new function, `iris.util.points_step`, which checks whether there is a regular step between a set of points (a NumPy array). This function represents the part of `iris.util.regular_step` that dealt with checking the incoming coord's points. I've also added tests for the `iris.util` functions `is_regular`, `regular_step`, and `points_step`.
Note: #2527 now depends on this PR.
> Update regular coord checking

- lib/iris/tests/integration/test_PartialDateTime.py
replaces #2337 which is failing to set up the test environment properly
> test partial datetime

- lib/iris/_data_manager.py
- lib/iris/analysis/__init__.py
- lib/iris/cube.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/data_manager/test_DataManager.py
Push the handling of `fill_value` down into the `DataManager`, as this is a generic capability that should be handled by the `DataManager` and not by the owning container.
> Move fill-value handling into DataManager.

- lib/iris/_merge.py
- lib/iris/aux_factory.py
- lib/iris/coords.py
- lib/iris/tests/integration/test_aggregated_cube.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/test_hybrid.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/unit/aux_factory/test_AuxCoordFactory.py
This starts the process of integrating the `DataManager` with coord classes. Specifically, this adds the `DataManager` to the abstract coord class `iris.coords.Coord`. This is done as the initial step to fully integrating the `DataManager` with `DimCoord` and `AuxCoord`.
Still a work in progress:
* I haven't touched `Coord.__getitem__` as there is still outstanding work in this area in #2519.
* I've only done a light touch on `Coord.copy` as the copy code will need to be thought about in the context of `DimCoord` and `AuxCoord`.
* I haven't even looked at the tests (and it is likely that many will now fail). I think the tests will be easier to deal with at the same time as tackling `DimCoord` and `AuxCoord`.
> Integrate DataManager with Coord, DimCoord, and AuxCoord

- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_Coord.py
There is currently the potential for a `RuntimeWarning: overflow encountered in int_scalars` which is missed during collapsed calculations, which can trip up unwary users of limited data types, such as int32 for very large numbers (e.g. seconds since 1970)
This PR pushes the casting, which already occurs, into the individual values, to limit the chance of overflow.  
The chance is still there, it is the responsibility of data creators to use appropriate data types.  this is a point fix which will help some users
> avoid runtime overflow

- .travis.yml
- docs/iris/src/whatsnew/contributions_1.13/newfeature_2017-May-10_NZ_dateline.txt
- lib/iris/plot.py
- lib/iris/tests/integration/plot/test_nzdateline.py
this is a work around for a long standing bug related to New Zealand model output and Cartopy extents
Cartopy defines the extent of a RotatedPole as -180 <= lambda < 180 and this is immutable
New Zealand modellers use a rotated pole CRS with an extent from 0 <= lambda < 360 with the area of interest around 180
The result is a map with a small strip of data on each side and a massive missing section in the middle
This work around in the shared plotting code identifies this condition and requests an adapted projection space from Cartopy to ensure a sensible map extent is set
> plotting NZ rotated pole extents

- lib/iris/_data_manager.py
- lib/iris/tests/results/analysis/aggregated_by/multi_missing.cml
- lib/iris/tests/results/analysis/aggregated_by/single_missing.cml
- lib/iris/tests/results/analysis/last_quartile_foo_3d_masked.cml
- lib/iris/tests/results/analysis/proportion_foo_2d_masked.cml
- lib/iris/tests/results/analysis/regrid/linear_subset_masked_1.cml
- lib/iris/tests/results/analysis/regrid/linear_subset_masked_2.cml
- lib/iris/tests/results/analysis/regrid/nearest_subset_masked_1.cml
- lib/iris/tests/results/analysis/regrid/nearest_subset_masked_2.cml
- lib/iris/tests/results/experimental/analysis/interpolate/LinearInterpolator/orthogonal_cube_with_factory.cml
- lib/iris/tests/unit/data_manager/test_DataManager.py
Ensures that when a masked array is passed to the `DataManager.__init__` or the `DataManager.data` setter, the masked array `fill_value` is correctly propagated to the `DataManager.fill_value`.
Note that, the default numpy `fill_value` for a `dtype` is never used to set the `DataManager.fill_value`, rather `None` is used instead. This ensures that when the `DataManager.data` getter is called and the realised result is a masked array, it is set with the default numpy `fill_value` for the `dtype` when the `DataManager.fill_value = None` (done automatically, when setting a masked array `fill_value` to `None`), otherwise the returned masked array is set to the non-`None` `cube.fill_value`.
Also addresses [comment](https://github.com/SciTools/iris/pull/2524#issuecomment-299241938).
> Dask data manager propagate

- lib/iris/_concatenate.py
- lib/iris/tests/integration/concatenate/test_concatenate.py
This PR adds three new unittests (two of which fail), demonstrating how concatenation behaviour in the presence of anonymous dimensions is sensitive to which dimension mapping the concatenation occurs along (note this is not about concatenation along the anonymous dimension itself).
> BUG: Concatenation with anonymous dimensions sensitive to dimension mapping

- lib/iris/tests/unit/fileformats/test_rules.py
I have updated this PR so it only deals with the removal of the biggus skipper from:
unit/fileformats/test_rules.py
> Remove skip_biggus from unit/fileformats/test_rules.py

- lib/iris/tests/results/abf/load.cml
- lib/iris/tests/results/unit/fileformats/grib/load_cubes/load_cubes/reduced_raw.cml
- lib/iris/tests/test_abf.py
- lib/iris/tests/test_pp_module.py
- lib/iris/tests/unit/fileformats/grib/test_load_cubes.py
- lib/iris/tests/unit/fileformats/pp/test_PPField.py
These tests had biggus skippers in place but the tests were largely passing. The tests that weren't passing needed updated CML to reflect changes elsewhere in Iris code, primarily to `DataManager`.
> Remove a few more biggus skippers

- lib/iris/_merge.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_aux_factory.py
- lib/iris/tests/unit/merge/test_ProtoCube.py
The CF conventions state that certain `formula_terms` terms may be omitted and assumed to be zero (http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#dimensionless-v-coord). This logic is implemented in the various `AuxCoordFactory` sub-classes in Iris, but when constructing factories from data loaded from a netCDF file an error is raised if a term is missing. This PR allows factories to be constructed with missing terms.
The change has the perhaps undesirable side effect that if a formula term refers to a variable which doesn't exist, or one which has been ignored because it wasn't valid, the factory will still be constructed with that coordinate omitted. Previously this would result in an error caused by a dependency coordinate not being present in an `AuxCoordFactory` …
> Ignore missing formula terms when constructing aux factories

- lib/iris/fileformats/grib/__init__.py
proposed replacement for #2468
targeting master for the 1.13 release
> Corrected use of deprecated numpy behaviour. Necessary for numpy 1.12

- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
- When indexing a cube when the data is reaslised (not lazy), a view of the original array is returned where possible (subject to the rules when slicing in numpy).
- When indexing a cube when the data is not reaslised (lazy), realising the data on one will still not realise the data on the other.
- Optimisation of coord copy when replacing the points is to shallow copy the points and bounds before replacing them to avoid unnecessary copies.
- Existing behaviour is that slicing coordinates returns views of the original points and bounds (where possible).  This was likely chosen behaviour on the basis that DimCoords at least is not writeable.  This is not the same however for Auxiliary coordinates and likely raises the likely case for this being a bug (i.e. one can modify AuxCoord object …
> ENH: Shared data between cube slices

- lib/iris/tests/results/cube_io/pickling/theta.cml
- lib/iris/tests/test_coding_standards.py
- lib/iris/tests/test_pickling.py
Fix a cube pickling roundtrip test that was not preserving lazy data and causing a spurious test failure. Bonus: test module now pep8 compliant!
Fixes part of #2398
> Fix pickle test

- .travis.yml
- lib/iris/_lazy_data.py
- lib/iris/fileformats/grib/__init__.py
- lib/iris/fileformats/grib/message.py
- lib/iris/fileformats/netcdf.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/rules.py
- lib/iris/fileformats/um/_fast_load_structured_fields.py
- lib/iris/tests/integration/test_pp.py
- lib/iris/tests/results/integration/netcdf/TestSaveMultipleAuxFactories/hybrid_height_cubes.cml
- lib/iris/tests/results/netcdf/int64_data_netcdf3.cml
- lib/iris/tests/results/netcdf/netcdf_monotonic.cml
- lib/iris/tests/results/netcdf/netcdf_units_0.cml
- lib/iris/tests/results/netcdf/netcdf_units_1.cml
- lib/iris/tests/results/netcdf/uint32_data_netcdf3.cml
If a Dask array is created from an array-like with a `dtype` attribute which is different from the dtype of an array returned by its `__getitem__`, this can cause problems, notably with `concatenate` and `stack`.
This PR ensures that the dtype attribute of `NetCDFDataProxy` and `PPDataProxy` objects can be promoted to from the actual dtype of the arrays returned by `__getitem__`, or that an error is raised if not. In practice this means that if the attribute is of kind int, uint or byte, and during a `__getitem__` call masked data is discovered (which would be convered to NaNs with a dtype of f8), an error is raised.
I've made changes so that when constructing a `NetCDFDataProxy`, the actual expected dtype of the arrays returned by `__getitem__` should be passed in. For `PPDataProxy`, the …
> Ensure declared dtype of data proxy objects matches returned dtype

- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/unit/coords/test_DimCoord.py
This refactors the inheritance organisation of the `points` and `bounds` property code amongst Coord  / AuxCoord / DimCoord.
At present, `DimCoord` and `AuxCoord` both provide their own *independent* implementations of points+bounds getters+setters, but there is quite a lot of duplication in that code.
This refactor removes the code duplication, by ...
* most of the relevant code is relocated by "pushing it up" from `AuxCoord` into `Coord`.
* `AuxCoord` then becomes an almost trivial descendant of `Coord`, 
* `DimCoord` is now a 'specialised' form that inherits + extends those implementations, adding realisation and DimCoord-specific validity testing.
* the 'from_coord' routine has also been generalised in a similar way.
I think this structure makes more sense than the existing.
The …
> Coord points and bounds inheritance.

- lib/iris/tests/unit/fileformats/netcdf/test__load_cube.py
Unskipped some more tests that were previously reliant on biggus.
Specifically, this means removing excessive mockism of some NetCDF tests and updated them to reflect changes to `cube` / `DataManager` API.
Fixes part of #2398
> Fix a few more tests

- lib/iris/tests/unit/fileformats/rules/test__make_cube.py
Remove another biggus skipper, this time on a test that was causing a segfault. It appears the segfault was being caused when creating the cube with `core_data` described by an empty mock object.
I've also removed some needless mockism from the wider test that was being used to capture a raised warning. I've replaced the mockism with the warning capture and check code used widely elsewhere within Iris tests.
Part-fixes #2398.
> Fix rules test for _make_cube

- lib/iris/_data_manager.py
- lib/iris/analysis/maths.py
- lib/iris/tests/test_basic_maths.py
- lib/iris/tests/unit/analysis/maths/__init__.py
- lib/iris/tests/unit/analysis/maths/test__get_dtype.py
- lib/iris/tests/unit/analysis/maths/test__inplace_common_checks.py
- lib/iris/tests/unit/analysis/maths/test__output_dtype.py
- lib/iris/tests/unit/analysis/maths/test_add.py
- lib/iris/tests/unit/analysis/maths/test_multiply.py
- lib/iris/tests/unit/analysis/maths/test_subtract.py
Numpy operations which result in a scalar masked array return an instance of `np.ma.core.MaskedConstant` that always has a dtype of `np.float64`. This means that in cube arithmetic the dtype information can be lost.
This PR is an attempt to rectify that. The idea is to run the operation on dummy arrays with the input dtypes and use the dtype of the result to fix up the dtype of the cube in the scalar masked array case.
This approach doesn't work for arbitrary functions (i.e. instances of `iris.analysis.maths.IFunc`), because (1) the dtype can depend on kwargs, and (2) the function may fail if the arguments don't meet particular requirements (e.g. shape), and it's not possible to determine these requirements for arbitrary functions. It might be worth handling the limited case where the …
> Handle MaskedConstant in cube maths

- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_has_supported_mercator_parameters.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_has_supported_stereographic_parameters.py
- lib/iris/tests/unit/fileformats/rules/test__make_cube.py
In contrast to what I said [here](https://github.com/SciTools/iris/pull/2557#discussion_r117057815), there *is* a point to using six.assertRegex,
as otherwise assertRegexpMatches in Python 3 gives "DeprecationWarning: Please use assertRegex instead."
> Use six.assertRegex to avoid Python 3 test method deprecation.

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
In some cases (notably when calling `cube.slices` with slice dims specified in a different order to their order on the cube), `cube.transpose` could be called with a NumPy array specifying the `new_order` kwarg. This is not supported by `dask.array.transpose`.
This PR ensures that `new_order` is **always** a list, which the previous checks did not ensure, and adds tests for this behaviour.
Fixes #2579 and required for #2460/#2576 to proceed.
> Ensure cube.transpose functionality

- .travis.yml
- docs/iris/src/userguide/interpolation_and_regridding.rst
- lib/iris/__init__.py
Now that we are approaching the end of dask we need to restart doctests and extests on Travis, not least to ensure we haven't broken all of the docs on the dask branch!
Fixes #2460
> Restart doctests and example tests

- lib/iris/cube.py
addressing concerns raised in
https://github.com/SciTools/iris/pull/2549#discussion_r118005791
> share data flag behaviour

- lib/iris/aux_factory.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/unit/aux_factory/test_AuxCoordFactory.py
This is a new PR to replace https://github.com/SciTools/iris/pull/2588.  This entails the one-line change which fixes the realization of derived coord lazy bounds upon printing the cube, along with a test to ensure its effectiveness.
> Lazy bounds test

- docs/iris/src/userguide/index.rst
- docs/iris/src/userguide/real_and_lazy_data.rst
In this new page of the user guide, I have attempted to cover:
- What is real and lazy data?
- When does my lazy data become real?
- What is 'core data'?
- Different methods of changing a cube's data (cube maths, copy, replace) and their respective consequences
- Some dask processing options and what they might be useful for (very briefly of course, because I don't fully understand myself...)
- Some links to the dask and distributed docs.
> Dask docs, first draft

- lib/iris/coords.py
Certain error  messages refer to a coordinate's 'coordinate system', but the docstring for the Coord class only refers to coord_system, which can make it hard for users to search for relevant information in the documentation. This is a minor change to help fix that.
> Refer to coordinate system in docstrings for Coord class

- docs/iris/src/userguide/loading_iris_cubes.rst
When loading multiple files with a single call to iris.load, the cubes returned are not in the same order as the input list of filenames.
I could find nothing in the documentation to explain this, hence this PR which simply adds 2 lines to the documentation.
> added Note to documentation about iris.load

- docs/iris/src/_templates/layout.html
- docs/iris/src/conf.py
Tested to include the year when building.
> Update the documentation's copyright year... it's 2017.

- INSTALL
- conda-requirements.txt
- lib/iris/_lazy_data.py
- minimal-conda-requirements.txt
> Add dask to install docs.

- lib/iris/cube.py
- lib/iris/tests/test_mapping.py
- lib/iris/tests/test_merge.py
Removal of deprecated methods/keywords from `iris.cube`. Handles all deprecations from #1592, except for the last one which needs further discussion.
> Remove cube deprecations

- .travis.yml
NOTE: this targets the new iris branch `dask_mask_array`
This adds instructions in the travis set up to get dask from the branch in the [Dask PR](https://github.com/dask/dask/pull/2301) that adds masked array support.
> Use the branch from dask PR#2301 in travis

- lib/iris/_concatenate.py
- lib/iris/_data_manager.py
- lib/iris/_lazy_data.py
- lib/iris/_merge.py
- lib/iris/analysis/__init__.py
- lib/iris/analysis/_interpolate_private.py
- lib/iris/analysis/_interpolation.py
- lib/iris/analysis/_regrid.py
- lib/iris/analysis/calculus.py
- lib/iris/analysis/cartography.py
- lib/iris/analysis/trajectory.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/etc/pp_save_rules.txt
- lib/iris/experimental/regrid.py
- lib/iris/fileformats/grib/__init__.py
- lib/iris/fileformats/grib/_save_rules.py
- lib/iris/fileformats/grib/message.py
- lib/iris/fileformats/netcdf.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/rules.py
- lib/iris/util.py
This is pointing at the `dask_mask_array` feature branch.
This contains just the code changes that I think require to be done to integrate the dask masked array support into Iris.
This will obviously break a bunch of tests but we can address that later.
> Integrate dask masked array support (just code changes, no tests fix)

- lib/iris/_data_manager.py
- lib/iris/_lazy_data.py
- lib/iris/tests/unit/data_manager/test_DataManager.py
- lib/iris/tests/unit/lazy_data/test_as_lazy_data.py
Fix all tests in lib/iris/tests/unit/data_manager/test_DataManager.py so that they all pass.
I have had to remove/change some tests that used the old API (e.g. cube.fill_value).
I have also had to make some fixes to handling of masked constants which hopefully makes sense
> Fix lib/iris/tests/unit/data_manager/test_DataManager.py tests

- lib/iris/tests/test_analysis.py
- lib/iris/tests/test_basic_maths.py
Some of the parts of the tests that try to set the cube.fill_value which no longer exists
> Remove some cube.fill_value usages

- lib/iris/tests/results/netcdf/int64_data_netcdf3.cml
- lib/iris/tests/results/netcdf/netcdf_units_0.cml
- lib/iris/tests/results/netcdf/uint32_data_netcdf3.cml
- lib/iris/tests/test_pickling.py
- lib/iris/tests/unit/analysis/test_MEAN.py
> A few small test fixes that fell out of the integration of dask masked array support

- lib/iris/_lazy_data.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/lazy_data/test_lazy_masked_fill_value.py
Enables lazy masked `fill_value` retrieval for NetCDF save.
Dask exposes no mechanism for retrieving the fill value of a lazy masked array (indeed, arguably this is currently not a soluble problem). This PR proposes a workaround for this problem, exposes the workaround as a function in `iris._lazy_data` and integrates the function into the NetCDF saver.
Specifically, the workaround realises the smallest possible slice of the lazy masked data array that, when realised, contains the required fill value. Turns out the smallest possible slice is actually an empty slice:
```python
>>> m = np.ma.masked_array([0, 1, 2], mask=[1, 0, 1], fill_value=9999)
>>> dm = da.from_array(m, chunks=(3,), asarray=False)
>>> dm[:0].compute().fill_value
9999
```
Fixes #2703.
> Lazy masked fill_value retrieval for NC save 

- .travis.yml
Fix to get the tests passing while we investigate why there are now so many time-outs.
> Run Travis tests in serial

- lib/iris/fileformats/grib/__init__.py
- lib/iris/tests/test_grib_load_translations.py
- lib/iris/tests/unit/fileformats/grib/message/test_GribMessage.py
- lib/iris/tests/unit/fileformats/grib/message/test__DataProxy.py
Closes #2710
Closes #2709 
Relatively straightforward:
- Fixed the bug where the data array of a `GribWrapper` wasn't being assigned to, and unskipped relevant tests
- Removed uses of `nans_replacement` in other unit tests.
- Removed a duplicate unit test which only differed on the dtype of the data. It was testing the "realised dtype" and "nans_replacement" code.
> Fixes for GRIB unit tests

- lib/iris/tests/__init__.py
Recently when running the Iris tests locally, I have had a lot of errors of the form `AssertionError: Image comparison failed: Bad phash`.  It took me a while to realise that this was because I've set `image.cmap` and `axes.prop_cycle` in my `matplotlibrc` file, so the colours were wrong according to the plotting tests.
This very minor change forces the tests to use the matplotlib default settings, so the above issue doesn't come up.
> Use matplotlib default settings for tests

- lib/iris/analysis/__init__.py
- lib/iris/tests/results/analysis/first_quartile_foo_1d_fast_percentile.cml
- lib/iris/tests/results/analysis/first_quartile_foo_2d_fast_percentile.cml
- lib/iris/tests/results/analysis/first_quartile_foo_bar_2d_fast_percentile.cml
- lib/iris/tests/results/analysis/last_quartile_foo_3d_notmasked_fast_percentile.cml
- lib/iris/tests/results/analysis/third_quartile_foo_1d_fast_percentile.cml
- lib/iris/tests/test_analysis.py
Replacement for PR #2682 (np.percentile method as an alternative to scipy.mstats).
Now for Iris V2.
Introduction of a numpy.percentile method to the percentile aggregator for the purposes of providing a fast alternative (approx 50 times faster).
* Accessed with kwarg percentile_method="numpy_percentile" passed to cube.collapsed method.
* Existing unit tests duplicated with call to fast method, where masked data will result in an error.
* Ran test cases and found fractional differences of order 1E-16 between two methods.
* scipy.stats.mstats.mquantiles method remains important for dealing with masked data.
I have rewritten the unit tests across the section of interest. I have (possibly unwisely) removed the contentious assertCML tests (see comments on #2682). Instead I have added a simple …
> Fast percentile method in Iris V2.

- lib/iris/analysis/calculus.py
- lib/iris/analysis/maths.py
- lib/iris/cube.py
> Remove deprecated ignore args

- .travis.yml
Use Python 3.6 for the Python 3 Travis tests due to[ issues using python 3.5](https://github.com/SciTools/iris/pull/2769#issuecomment-335147830).
> Bump travis python version 3.5 to 3.6

- lib/iris/fileformats/rules.py
Closes https://github.com/SciTools/iris/issues/2679
> Removed deprecated calculate_forecast_period

- conda-requirements.txt
- lib/iris/fileformats/pp.py
- lib/iris/tests/test_pp_stash.py
Attempts to fix #2624.
However, some of the `test_pp_cf.py` tests fail because the test files (located [here](https://github.com/SciTools/iris-test-data/tree/master/test_data/PP/cf_processing)) now have invalid STASH codes; `002000000000.44.101.131200.1920.09.01.00.00.b.pp` and `008000000000.44.101.000128.1890.09.01.00.00.b.pp` have a STASH code of `44101` (`ValueError: Expected STASH code MSI string "mXXsXXiXXX", got u'm??s44i101'`) and `st0fc942.b.pp` and `st0fc699.b.pp` have a STASH code of `0` (`ValueError: Expected STASH code MSI string "mXXsXXiXXX", got u'm02s00i???'`)
Would it be possible for someone to help? What should I do now?
> Correct STASH regular expression

- .travis.yml
**DO NOT MERGE UNTIL..**
https://github.com/dask/dask/pull/2654 is merged.
Because we were temporarily using a "jcrist/masked-array" branch of dask
-- which is now merged.
See https://github.com/SciTools/iris/pull/2747#issuecomment-327003711
> Use conda-forge for Dask in Travis (not special branch download) 

- lib/iris/__init__.py
- lib/iris/config.py
- lib/iris/tests/unit/test_sample_data_path.py
Closes https://github.com/SciTools/iris/issues/2654
> Remove references to SAMPLE_DATA_DIR

- lib/iris/analysis/__init__.py
- lib/iris/tests/unit/analysis/test_MEAN.py
- lib/iris/tests/unit/analysis/test_STD_DEV.py
> Dask masked-data stats

- lib/iris/fileformats/rules.py
This is very similar to pull requests I've made to other comparable issues, hopefully there are no conflicts. 
Closes #2669.
> Remove debug string

- lib/iris/pandas.py
- lib/iris/tests/test_pandas.py
Trying to convert an iris cube to a pandas dataframe currently fails if the `copy=False` argument is used and the cube data is a view.  The data is correctly shared between the cube and the dataframe.  However, the check that the data is shared fails to account for the cube data being a view and throws an error.  First commit here demonstrates the failure (error is thrown when creating the dataframe), and the second is the fix.
I've not investigated why loading the data that triggered this error resulted in a cubelist where the individual cubes had a view for the data rather than the base array.
> Fix for pandas.as_dataframe when cube data array is a view

- lib/iris/experimental/animate.py
I have amended the documentation for the iris animate tool to make it explicitly clear which functions it will accept.
> Iris animate docs

- lib/iris/fileformats/rules.py
This is to address issue #2672 . Wanted to see how this fairs against the Travis tests, further changes may be necessary.
> Removed class iris.fileformats.rules.CoordAndDims

- lib/iris/analysis/_interpolate_backdoor.py
- lib/iris/analysis/_interpolate_private.py
- lib/iris/tests/integration/test_regrid_equivalence.py
Removes deprecated function `iris.analysis.interpolate.regrid`. Closes #2664.
Also removes deprecated function `iris.analysis.interpolate.extract_nearest_neighbour`, which was blocked until `regrid` was removed, as `regrid` made use of `extract_nearest_neighbour`. Closes #2662.
*Update:* also removes `iris.analysis.interpolate.nearest_neighbour_indices`, as this is a dependency of `extract_nearest_neighbour`. Closes #2661.
> Remove analysis.regrid and extract_nearest_nbr

- lib/iris/tests/results/usecases/pp_to_cf_conversion/from_netcdf/integer.b_0.cml
- lib/iris/tests/results/usecases/pp_to_cf_conversion/from_pp/integer.b.cml
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/000003000000.03.236.000128.1990.12.01.00.00.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/000003000000.03.236.004224.1990.12.01.00.00.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/000003000000.03.236.008320.1990.12.01.00.00.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/000003000000.16.202.000128.1860.09.01.00.00.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/001000000000.00.000.000000.1860.01.01.00.00.f.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/002000000000.44.101.131200.1920.09.01.00.00.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/008000000000.44.101.000128.1890.09.01.00.00.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/12187.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/HadCM2_ts_SAT_ann_18602100.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/aaxzc_level_lat_orig.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/aaxzc_lon_lat_press_orig.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/aaxzc_lon_lat_several.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/aaxzc_n10r13xy.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/aaxzc_time_press.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/aaxzc_tseries.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/abcza_pa19591997_daily_29.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/abcza_pa19591997_daily_29.b_1.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/abcza_pa19591997_daily_29.b_2.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/abxpa_press_lat.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/integer.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/model.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/ocean_xsect.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/st0fc699.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/st0fc942.b_0.cdl
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/st30211.b_0.cdl
- lib/iris/tests/test_pp_cf.py
> Fixes for tests failing on mismatched CML files

- lib/iris/coords.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/unit/coords/test_DimCoord.py
Setting DimCoord points/bounds to an array that doesn't meet the requirements raises an exception, but the points/bounds array is still set on the coordinate. This PR stops that happening by doing the requirements checks _before_ modifying the coord with the new array.
I've modified the functions `_new_points_requirements()` and `_new_bounds_requirements()` so that they check the slightly more lenient requirements of the array which is passed in, rather than those of the actual array assigned, i.e, the points value passed can be a scalar, and the bounds value can be 1D if there is only a single point.
> Check DimCoord poins and bounds before setting

- docs/iris/src/whatsnew/contributions_v2.0.0/incompatiblechange_2017-Oct-19_remove-cube-kwargs.txt
- docs/iris/src/whatsnew/contributions_v2.0.0/incompatiblechange_2017-Oct-19_remove-cube-methods.txt
- docs/iris/src/whatsnew/contributions_v2.0.0/incompatiblechange_2017-Oct-19_remove_regridded.txt
Covers #2695, in which only one deprecation was public API, I believe.
> What's New entry for Cube deprecations [ci skip]

- .travis.yml
It seems that some time ago we stopped Travis reporting various test errors, 
- it happened at #2610 
- see [this comment](https://github.com/SciTools/iris/pull/2610/files#r145707816) and [this one](https://github.com/SciTools/iris/pull/2610/files#r145707951)
The problem is that the various test operations occur in groups of commands joined by ";" and Travis only checks the final RC value.  So by wrapping a test in cd-in and -out commands 
( e.g. `"cd my/inner/dir; test; cd ../../.."` )
we have masked any errors that the test raises !
So, this fixes that.
At present we are failing on both a doctest and the whatsnew-aggregation check.
Those need fixing separately.
So ***it will make sense to merge this with the "doctest" check failing***
**P.S.**
I also changed the order of the test …
> Fix Travis doctests error handling.

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Feb-23_cell-comparison.txt
- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_Cell.py
Since `iris.coords.Cell` inherits from `tuple`, comparisons with NumPy numeric types produce unexpected results. For example:
```
from iris.coords import Cell
c = Cell(1.)
f = np.float64(2.)
print f < c
```
outputs:
`[False False]`
Setting an [`__array_priority__`](http://docs.scipy.org/doc/numpy-1.10.1/user/c-info.beyond-basics.html#ndarray.__array_priority__) class variable to a number greater than 0.0 causes the `Cell` comparison operators to override those of NumPy types.
I'm not sure if this is the right fix to the problem, but I'm hoping something will come out of the discussion.
> Add __array_priority__ to Cell to fix comparison with numpy types

- docs/iris/src/userguide/interpolation_and_regridding.rst
Closes https://github.com/SciTools/iris/issues/2837
The test result has been reverted to pre-nans-as-masks code.
> Fix interpolation example doc test

- docs/iris/example_code/Meteorology/COP_1d_plot.py
- docs/iris/src/userguide/cube_statistics.rst
- docs/iris/src/userguide/loading_iris_cubes.rst
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-23_cell-datetime-objs.txt
- lib/iris/__init__.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/tests/integration/test_PartialDateTime.py
- lib/iris/tests/test_constraints.py
- lib/iris/tests/test_merge.py
- lib/iris/tests/unit/coords/test_Coord.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/test_Future.py
This is my attempt at making all the alterations regarding the :`iris.Future` option `cell_datetime_objects`. This Pull Request Closes #2831 .
> Deprecate cell_datetime_objects in iris.Future

- lib/iris/tests/integration/um/test_fieldsfile.py
Closes #2822 , and relates to some other current issues ...
* #2818 documentation of iris.fileformats.um.load_cubes is seriously misleading
* #2816 some test classes, including this one are not running under Travis
(neither of which are fixed here, or yet)
> Remove tests loading PP via um.load_cubes, which is not correct usage.

- lib/iris/io/__init__.py
- lib/iris/tests/__init__.py
- lib/iris/tests/unit/io/test_expand_filespecs.py
I noticed that #2014 didn't quite make it over the line, but what it was attempting to fix is two rather quite an annoying Iris bugs.
* The first bug (and the one I'm less bothered about) relates to the fact that if you load a cube from a relative path, and then change CWD, lazy data will be read from the wrong place. Fix: make the paths absolute.
* The second bug is that we currently ignore the order of filenames that is passed to the ``iris.load`` functions. Imagine that we needed two files in order to be able to reference a HybridHeight coordinate appropriately. We might do ```iris.load([file_with_orog, file_that_needs_orog_to_reference])```, but this only works if the **filename** in ``file_with_orog`` sorts before ``file_that_needs_orog_to_reference``.
> Filespecs sorted absolute

- lib/iris/tests/integration/test_cube.py
Maybe this test isn't necessary... it feels very specific. It's kind of annoying if this behaviour goes away accidentally though.
Addresses https://github.com/SciTools/iris/issues/2773.
> Add integration test to check that cube data fill value is modifiable

- lib/iris/experimental/regrid.py
Up to >3x speedup when regridding few time points, or similar resolutions by using `numpy.average` instead of `numpy.ma.average` if no values are masked. 
`numpy.ma.average` has a large constant overhead compared to `numpy.average`.
> Speedup area weighted regridding

- lib/iris/coords.py
- lib/iris/tests/unit/coords/__init__.py
- lib/iris/tests/unit/coords/test_AuxCoord.py
- lib/iris/tests/unit/coords/test_DimCoord.py
Historically it's always been the case that the points and bounds arrays of a DimCoord haven't been modifiable from outside the class. Recently this has slipped.
There are two changes in this PR. ~One I consider an obvious bug: when converting the argument to the points/bounds setter to a numpy array, a flag is created which determines whether to make a copy. Currently this flag is set if the input is lazy, but this is the wrong way around. If the input argument is already a numpy array, the points will be modifiable via the original array passed in. Conversely, if a lazy array is passed in then we can safely use the array returned by `as_concrete_data` as the actual points array, since there's no way a user could have a reference to it.~ Edit: I've realised that even if the input array …
> Restore readonly DimCoords

- docs/iris/src/whatsnew/2.0a0.rst
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/exceptions.py
- lib/iris/tests/unit/coords/test_Coord.py
- lib/iris/tests/unit/cube/test_Cube.py
Fix for #1977.  If the units on a cube are unknown, the `convert_units` method should raise an exception.  I consider the current behaviour of just setting the units to be a bug.  If a user has not realised the metadata in the data file is incomplete, then the cube could end up with spurious data values.
A couple of things I'm not sure of:
1. I couldn't figure out if the class definitions in `iris.exceptions` were in any particular order, so just put the new one at the end.
1. Did I put the whatsnew in the right place?
> convert_units: raise exception when unit is unknown

- docs/iris/src/whatsnew/2.0a0.rst
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-24_convert-unknown-units.txt
Raised in followup to #2700. In there, the whatsnew entry had been added directly to the compiled what's new rst document, meaning they had missed the whatsnew builder process, and were being recorded in the whatsnew for a release within which the changes they pointed to were not actually released (!). 
Rather than hold up #2700 any further, this PR removes them from the Iris v2.0a0 what's new document and adds them verbatim to a new whatsnew entry for the Iris v2.0 full release.
> Move whatsnew entries to best location

- lib/iris/cube.py
If you want to use cube.regrid then both your source and target cubes have to have coordinate systems on them.  This is not explained in the docstring so I have added a note to point it out, because it was tripping some people up.
> coord system requirement added to regrid docstring

- docs/iris/example_code/General/SOI_filtering.py
- docs/iris/example_code/General/anomaly_log_colouring.py
- docs/iris/example_code/General/cross_section.py
- docs/iris/example_code/General/custom_aggregation.py
- docs/iris/example_code/General/inset_plot.py
- docs/iris/example_code/General/orca_projection.py
- docs/iris/example_code/General/polynomial_fit.py
- docs/iris/example_code/General/projections_and_annotations.py
- docs/iris/example_code/General/rotated_pole_mapping.py
- docs/iris/example_code/Meteorology/COP_1d_plot.py
- docs/iris/example_code/Meteorology/TEC.py
- docs/iris/example_code/Meteorology/hovmoller.py
- docs/iris/example_code/Oceanography/atlantic_profiles.py
- docs/iris/src/userguide/interpolation_and_regridding.rst
- docs/iris/src/userguide/real_and_lazy_data.rst
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-24_netcdf-promote.txt
- lib/iris/__init__.py
- lib/iris/fileformats/cf.py
- lib/iris/tests/integration/test_cube.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/system_test.py
- lib/iris/tests/test_cf.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/test_plot.py
- lib/iris/tests/unit/aux_factory/test_AuxCoordFactory.py
- lib/iris/tests/unit/fileformats/cf/test_CFReader.py
- lib/iris/tests/unit/test_Future.py
With Iris v2.0, "the future has arrived". This PR swaps the behaviour of the FUTURE flag `netcdf_promote` so that the future behaviour is on by default. As the old behaviour is deprecated I've also removed the old behaviour, and `Future` will now raise an error if a user tries to set the `netcdf_promote` flag (to either `True` or `False`). Tests and docs are updated and I've added a whatsnew entry as well.
Fixes #2845.
> Change FUTURE flag netcdf_promote behaviour

- docs/iris/src/userguide/code_maintenance.rst
- docs/iris/src/whitepapers/index.rst
A pretty minimal change to address #2692.
It hides the 'change management whitepaper' altogether for now, pending a proper rewrite.
Instead, I have slightly extended the section in the Userguide to explain what is different about major releases.
I haven't actually removed 'change_management.rst', but it is no longer reachable from the main body.
I also moved the content of 'change_management_goals.rst' into the Userguide section and freely rewrote, so that is also no longer referenced in visible pages.
> Temporary minimal changes to change-management statements.

- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-18_remove-exp-ff.txt
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-18_remove-ff.txt
- lib/iris/fileformats/um/__init__.py
- lib/iris/fileformats/um/_ff_replacement.py
> Document replacement of "iris.fileformats.ff" and "iris.experimental.fieldsfile".

- lib/iris/_lazy_data.py
- lib/iris/_merge.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/fileformats/um/_fast_load_structured_fields.py
- lib/iris/tests/unit/lazy_data/test_as_lazy_data.py
This is a simple solution, supposed to address the problems in #2840
As the change is general in 'as_lazy_data' it can in principle apply elsewhere,
but in practice no single data fields ever get that big, so it only kicks in for large NetCDF variables.
~**Do not merge** until we can confirm that it definitely solves the known problem in  #2840 .~
#2839 tests the fix -- looking good.
> Nc simple chunks

- .travis.yml
This is still a temporary measure ...
When we have iris-grib v0.11.0 in conda-forge, we need to revert to testing with the latest release from conda-forge.
That means : 
* remove this section of `.travis.yml`, and 
* put iris-grib as an "optional dependency" in `conda-requirements.txt`
* **N.B.** for dask-mask support, we must state that as "iris_grib>0.11"
> Travis uses iris-grib from a specific version tag.

- lib/iris/tests/__init__.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
- lib/iris/tests/unit/fileformats/pp/test_PPField.py
- lib/iris/tests/unit/test_Future.py
It's confusing that `assertGivesWarning` can be used to assert that no warning is raised. I've refactored the code into separate methods.
> Refactor assertGivesWarning into separate methods

- lib/iris/_lazy_data.py
- lib/iris/tests/unit/lazy_data/test_as_concrete_data.py
This is a workaround for https://github.com/dask/dask/issues/2823 (now fixed on dask/master), identified in https://github.com/SciTools/iris/pull/2861.
> Fix scalar as_lazy_data

- docs/iris/src/userguide/regridding_plots/interpolate_column.py
Closes https://github.com/SciTools/iris/issues/2880
The new behaviour causes the reference surface to be loaded as a separate cube, so the `load_cube()` call fails.
> Fix doctest failing due to change in 'netcdf_promote' future behaviour

- lib/iris/tests/results/imagerepo.json
An entry was added into the imagerepo.json file in https://github.com/SciTools/iris/pull/2838 with no corresponding addition to https://github.com/SciTools/test-iris-imagehash. It turns out the tests pass without this entry anyway.
> Remove unneeded image repo url

- .travis.yml
- conda-requirements.txt
- lib/iris/io/__init__.py
- lib/iris/tests/integration/format_interop/test_name_grib.py
- lib/iris/tests/integration/test_grib_load.py
- lib/iris/tests/test_grib_save.py
- lib/iris/tests/test_grib_save_rules.py
This won't work until a new iris-grib>=0.12 is available on conda-forge
I'm assuming that will have masked dask support AND eccodes
There are changes here specific to the eccodes transition, ported across from #2607
> Get working with iris-grib-with-eccodes; Python 3 included.

- lib/iris/__init__.py
- lib/iris/tests/unit/test_Future.py
Changed the behaviour of the 'error' level for `iris.FUTURE` options so that if a user sets them to `True` a warning is raised rather than an error.
(As an aside, I'm only able to test this behaviour because we currently have an option which is at 'error' level.)
> Change behaviour of 'error' level

- .travis.yml
- lib/iris/tests/runner/_runner.py
Given we are far more parallelised now in iris (thanks to our new-found dask abilities) we don't need to use as many processes in parallel when testing. I didn't do any particularly sophisticated analysis of the "sweet spot", but leave that as an exercise for the interested reader...
In summary: we don't need to flood the machine with processes, and anything is better than what we currently do...
On Travis (where the numbers are extremely erratic), using 8 processes appears to take a similar amount of time to using 3. On my laptop (4 core), using 1 process takes about the same amount of time as 3.
> Reduced the number of processes used by default when testing.

- .travis.yml
- docs/iris/src/_templates/index.html
This is necessary because we still have mpl 1, not 2.
In addition, I was finding that the image scroller on the homepage was showing a black background for unusually shaped images. I fixed this by setting the background to white - it would be awesome to have a thorough refresh of the docs' styling, but I didn't get around to doing that yet.
> Set the documentation build to use viridis as the default colormap

- docs/iris/src/userguide/real_and_lazy_data.rst
- docs/iris/src/whatsnew/2.0.rst
Fixes #2882 and addresses the first two points of #2897.
> [DOC] Dask processing options docs updates

- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-27_grib_removed.txt
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-27_logging_removed.txt
I'm aware that it is very terse - it will need editorial along with the rest of the "what's new" items.
> Added some what's new information about #2435 and #2810.

- docs/iris/src/whatsnew/2.0.rst
Replaces #2867, which is obsolete now that the What's New document has been created.
> Small update to experimental-FF whatsnew statement

- docs/iris/src/whatsnew/2.0.rst
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-24_netcdf-no-unlim.txt
Completes the outstanding items in #2897. Specifically:
* some whatsnew items have been reclassified from 'deprecations' to 'incompatible changes',
* the text whatsnew entry for the `netcdf_no_unlimited` flag has been added to the What's New doc, and
* I've updated notes on fill-value handling, including adding a note for PP behaviour. This point addresses [this comment](https://github.com/SciTools/iris/issues/2748#issuecomment-340775540) and closes #2798.
> Updates to v2.0 What's New

- docs/iris/src/whatsnew/2.0.rst
- lib/iris/fileformats/cf.py
- lib/iris/tests/integration/test_netcdf.py
new test to check that a scalar data variable in a netcdf file will be loaded into a cube
addressing long standing bug reports, including #1427
> test_scalar_cube_load

- lib/iris/experimental/regrid.py
The oneliner comment is wrong -- coords no longer need to be orthogonal.
> Corrected usage context in description of PointInCell regrid scheme.

- .travis.yml
- MANIFEST.in
- setup.py
This PR closes #2481 by standardising the build/develop/install process used by iris' setup.
This change is necessary if we ever want ```pip install scitools-iris``` to function correctly (without the need for extra ``python setup.py pyke_rules/std_names`` calls).
I've tested this quite extensively on a python3 environment on OSX using both the source repository and a build sdist.
> Re-worked setup.py to avoid the need for separate/non-standard build commands

- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-30_axis_order_plotting.txt
- lib/iris/plot.py
- lib/iris/tests/test_mapping.py
- lib/iris/tests/unit/plot/test__get_plot_defn.py
Closes (extremely long-standing) #202.
> Use the cube dimension order to determine the plot axes.

- docs/iris/src/whitepapers/index.rst
- docs/iris/src/whitepapers/missing_data_handling.rst
Adds a whitepaper on missing data handling in Iris. This is basically the contents of https://github.com/SciTools/iris/issues/2748#issuecomment-336201947 that have been simplified and tidied up a little. Providing this gives us _something_ at least for Iris users to refer to in order to have an understanding of how Iris handles missing data.
> Missing data whitepaper

- lib/iris/analysis/cartography.py
In `iris.analysis.cartography`, there are three functions that return lons and lats. Two of them return `lon(s), lat(s)`, one returns `(lat, lon)`. This changes the order of the latter to match the order of the former. The best thing is the latter (`_get_lat_lon_coords`, which I've renamed to the now more appropriate `_get_lon_lat_coords`) is a private method, so we don't need a major release for this change.
Amazingly enough, this addresses #51.
> Consistency in lon/lat return order

- .travis.yml
A follow-on to #2889, which didn't quite do the trick...
> Use viridis cmap for doc images

- .stickler.yml
- setup.cfg
Adds stickler (not yet enabled on the repo) and a flake8 config, so that we can all run ```flake8 lib/iris``` and get a meaningful result (even if there *are* failures 😱).
Closes #2334
> Stickler config

- lib/iris/tests/results/imagerepo.json
Relates to the thing identified in https://github.com/SciTools/iris/pull/2890#issuecomment-342498165
~~Requires https://github.com/SciTools/test-images-scitools/pull/9 for this to go green.~~
Requires https://github.com/SciTools/test-iris-imagehash/pull/12 for this to go green.
> Handled the recent update to conda-forge for testing, perhaps relating to GEOS update.

- INSTALL
- docs/iris/src/_templates/index.html
- docs/iris/src/whatsnew/index.rst
Including updating the install guide to:
* avoid being over-prescriptive about dependency versions
* mention setup.py develop
* reference a sensible config item
Also fixes the link on the homepage to get to the correct what's new!
> Further docs refinement for v2.0.0

- docs/iris/src/userguide/cube_maths.rst
See reference here : https://github.com/SciTools/iris/pull/1911#issuecomment-215032215
The `iris.analysis.maths.add() / subtract()` routines used to have a keyword `ignore=True`, but this has been deprecated and non-functional since (allegedly) v0.8 (!)
The keyword is finally removed in v2.0 anyway.
This is what the Userguide reference is referring to, so I just removed it.
> Remove obsolete reference from Userguide.

- lib/iris/_lazy_data.py
- lib/iris/tests/unit/lazy_data/test_as_concrete_data.py
A workaround for https://github.com/dask/dask/issues/2823 was added in https://github.com/SciTools/iris/pull/2878. The dask issue is fixed in the latest release, so this PR reverts the changes.
N.B. There is a test which will fail on master now that the Dask issue is fixed, so this needs resolving ASAP.
> Reverse 2878

- lib/iris/io/__init__.py
- lib/iris/tests/unit/io/test_expand_filespecs.py
See #2032.
I liked @pelson's suggestion of a tick and a cross at the start of each line, but comments on [this stackoverflow question](https://stackoverflow.com/questions/16676101) suggest doing this is terminal dependent (I couldn't get the suggestions to work under my ipython anyway).  So I went for a more basic - or * bullet point difference.
> Reduce exception message for loading missing files.

- lib/iris/_cube_coord_common.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/test_netcdf.py
This allows the user to set missing_value as an attribute on a
cube while ensuring that it is saved as local attribute in the
netcdf file.
This is essentially pr #2866 for master.
Fixes #1588
> Allow missing value master

- docs/iris/src/userguide/loading_iris_cubes.rst
You can't use Constraint/extract to subset a cube with a range of longitudes that cross the dateline (or meridian). You can achieve such a subset using `cube.intersection`. This adds a very short section noting this limitation and linking to the cube docs on intersection.
> [DOC]: Userguide note on intersection

- docs/iris/src/userguide/loading_iris_cubes.rst
A follow-up to #2931 that documents the general case of interest (constraining across the boundary of a circular coordinate) in preference to two specific examples (the dateline and meridian) of the general case.
> [DOC]: Update userguide note on intersection

- README.md
- docs/iris/src/whatsnew/2.0.rst
- lib/iris/__init__.py
Heads-up: It is time to cut the release candidate (OK - I accept. It is *past* time 😉 )
There have been 1 or 2 tweaks that have gone into master that there is no reason not to bring into 2.0, so I'm planning to update the upstream/v2.0.x to point to master once this is merged. I will then simply tag (on github) the release candidate, and ensure the documentation is available on the scitools page.
My own todo list:
> Planning to cut 2.0.0rc1 today.

- docs/iris/src/whatsnew/2.0.rst
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-27_grib_removed.txt
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-27_logging_removed.txt
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-30_axis_order_plotting.txt
- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2018-Jan-11_short-unit-strings.txt
- lib/iris/__init__.py
Here are the doc changes I made directly to the v2.0.x branch. If we want to change them in any way, we would need a PR to the upstream/v2.0.x branch (happy to do that, or the reviewer can do it directly).
> Bumps the version for 2.1dev + v2.0x what's new tweaks

- MANIFEST.in
- docs/iris/src/whatsnew/2.0.rst
- lib/iris/__init__.py
Follow up to #2937.
The MANIFEST change was necessary for pushing to pypi.
> Tweaked what's new, bumped version string, and updated the MANIFEST for pypi

- lib/iris/cube.py
Here's a suggestion to make the lazy data docstring clearer regarding what a "lazy array wrapper" is.
> DOC: lazy data docstring made clearer

- requirements/all.txt
- requirements/extensions.txt
Should be at least a temporary fix for the current test problems on master.
I moved it from the "all" to the "extensions" dependency-group (latter not used by Travis).
For the future, I would really like to **kick gdal out of our requirements altogether**...
It is ***only*** used by `iris.experimental.raster.export_geotiff`.
We have managed without in the internal SSS environments for some time,
if you "import iris.experimental.raster" in these, it simply fails.
Gdal seems to be a very large package of which we're only using a tiny part.
The dependencies [on conda-forge](https://github.com/conda-forge/libgdal-feedstock/blob/master/recipe/meta.yaml) are an immensely complicated + over-constrained lot.
No wonder it has caused trouble 
For instance, the latest problem is due to the move from …
> Stop testing with gdal.

- .travis.yml
- docs/iris/src/sphinxext/gen_gallery.py
- lib/iris/cube.py
> Fix the documentation building for latest version of sphinx.

- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/cf.py
- lib/iris/fileformats/netcdf.py
As of np >= 1.14 ```np.issubdtype(np.str, np.str)``` raises a warning:
```
FutureWarning: Conversion of the second argument of issubdtype from `str` to `str` is deprecated. In future, it will be treated as `np.str_ == np.dtype(str).type`.
```
Instead, we should be doing ```np.issubdtype(np.str, np.str_)```.
This is backwards compatible and works on python 2 & 3:
```
(iris-dev-py3) pelson@~/dev/scitools/iris> python -c "import numpy as np; print(np.__version__); np.issubdtype(np.str, np.str)"
1.14.0
-c:1: FutureWarning: Conversion of the second argument of issubdtype from `str` to `str` is deprecated. In future, it will be treated as `np.str_ == np.dtype(str).type`.
(iris-dev-py3) pelson@~/dev/scitools/iris> python -c "import numpy as np; print(np.__version__); np.issubdtype(np.str, …
```
> Remove FutureWarning from use of np.issubdtype(obj, np.str)

- docs/iris/src/whatsnew/contributions_2.1/newfeature_2018-Mar-08_co_realise_cubes.txt
- lib/iris/__init__.py
- lib/iris/_lazy_data.py
- lib/iris/tests/unit/lazy_data/test_co_realise_cubes.py
User code often forms multiple stats, where data may be very large.
= several small, lazy, calculated results derived from same large, lazy data 
Calculation scans the data, each time you realise one.
This can + should be done in parallel with `da.compute(*dask_stats_arrays)`.
You then need to assign those results back into Iris `cube.data` elements.
I can't find a neat Python idiom for this, so we can provide a simple utility routine.
Note: I'm proposing to put this in package `iris` itself, as I don't rate the alternatives :
* `iris._lazy_data` is private
* `iris.utils`, on inspection, I think is for "handy things you might just have written yourself"
*whereas* : this code uses knowledge of internals.
> Add cube co-realisation.

- lib/iris/coord_systems.py
Fixes currently broken tests in `iris.tests.test_co……ordsystem` :
* Test_Stereographic_as_cartopy_crs.test_as_cartopy_crs
* Test_Stereographic_as_cartopy_projection.test_as_cartopy_projection
Cartopy 0.16 has a breaking change to the API in terms of argument ordering.
( They added a new `scale_factor` arg in front of the last `globe` arg instead of after it )
Passing `globe` as a kwarg fixes it.
> Fix for changed API of cartopy.crs.Stereographic

- MANIFEST.in
Iris tests that require test data are currently being skipped in the travis-ci on `master`.
The root cause "appears" to be #2938 on the `2.0.x` branch, which was merged back into `master`. It had an explicit `exclude lib/iris/ext/site.cfg` in the `MANIFEST.in`.
This PR reverts that exclusion in the manifest.
> remove site.cfg exclude from manifest.in

- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_auxiliary_coordinate.py
The date type of a variable in a netCDF file is not necessarily the same as the dtype of the array returned by netCDF4, if a scale_factor and/or add_offset are applied. If the data is lazily loaded, we need to figure out what the actual dtype will be. This was already handled for cube data, but not for auxiliary coordinate data, which can now also be lazy. It doesn't apply to dimension coordinates which don't have lazy data.
> Fix bug with aux coords with scalefactor/add_offset

- lib/iris/__init__.py
I got the 
```     
raise ImportError("Please install the 'iris_sample_data' package to "
"access sample data.")
```
Then did `conda install -c conda-forge iris_sample_data` to get:
```
PackageNotFoundError: Packages missing in current channels:
- iris_sample_data
```
Renamed iris_sample_data to the correct package name of iris-sample-data
> Rename iris_sample_data to correct package name (iris-sample-data)

- lib/iris/tests/__init__.py
- lib/iris/tests/idiff.py
- lib/iris/tests/results/imagerepo.json
- lib/iris/tests/test_image_json.py
- requirements/test.txt
This PR addresses the issue of the `imagehash` package releasing version `4.0`, which addresses an error in the creation of hashes, see https://github.com/JohannesBuchner/imagehash#changelog
Closes #2973, #2974
> Fix imagehash hex_to_hash

- lib/iris/tests/unit/analysis/stats/test_pearsonr.py
The setup for `test_pearsonr` creates two cubes by taking different slices out of a larger cube, and therefore have different time coordinates.  This means that, since #2498, the cubes cannot be multiplied together and therefore cannot be correlated.  This was reflected in changes to two of the tests at #2498, where they were changed to expect a `ValueError`.
Since the original intention of these tests was to check the correct numbers come out of the calculation, I have modified the setup so that the time coordinates match, and reverted the above mentioned changes to the two "compatible cubes" tests.
> test_pearsonr: use compatible cubes for testing compatible cubes

- lib/iris/tests/unit/data_manager/test_DataManager.py
- lib/iris/tests/unit/fileformats/dot/test__dot_path.py
- lib/iris/tests/unit/fileformats/netcdf/test__FillValueMaskCheckAndStoreTarget.py
- lib/iris/tests/unit/fileformats/netcdf/test_save.py
- lib/iris/tests/unit/fileformats/rules/test_Loader.py
- lib/iris/tests/unit/fileformats/um/test_um_to_pp.py
- lib/iris/tests/unit/lazy_data/test_as_lazy_data.py
- lib/iris/tests/unit/test_sample_data_path.py
Our test usage of `mock` should always come from `iris.tests.mock` rather than performing an explicit `import mock`.
The `iris.tests` module provides this [in a way](https://github.com/SciTools/iris/blob/master/lib/iris/tests/__init__.py#L61) that works in both Python 2 and Python 3 - since in Python 3 `mock` is bundled within `unittest`.
This PR purges our use of `import mock` from our tests. Note that, we will only be able to purge `mock` itself from our test dependencies once we stop supporting Iris on Python 2.
> Use iris.tests.mock for Python 3

- requirements/core.txt
Until Dask 0.17.1 there was a bug where computing scalar arrays could result in errors (dask/dask#2823). We had a workaround (https://github.com/SciTools/iris/pull/2878) which we took out after a fixed version of Dask was released. We should have also updated the minimum version of Dask at that point.
> Pin Dask to >=0.17.1

- docs/iris/src/whatsnew/contributions_2.1/newfeature_2018-Jan-18_trajectory-interpolate.txt
- lib/iris/analysis/trajectory.py
- lib/iris/tests/unit/analysis/trajectory/test_Trajectory.py
When I used `iris.analysis.Trajectory` I was a bit surprised that it did not have an interpolate method. It seemed to me the obvious use of `Trajectory` was to set up points for the trajectory and then interpolate a cube along the trajectory, all in one class. Instead I found that not only could I not interpolate from the `Trajectory`, but the `Trajectory`'s points were not even in the same format as the trajectory module's interpolator function.
Given that this could easily be improved, I went out and did.  I've added `Trajectory.interpolate` that calls the trajectory module's interpolate function and a private helper method to `Trajectory` that translates the trajectory points to the format expected by the interpolate function. The interpolate method also adds a `DimCoord` to name the …
> Fill a usability gap in iris.analysis.Trajectory

- docs/iris/src/sphinxext/gen_gallery.py
Problem as seen here : https://github.com/spatialaudio/nbsphinx/issues/127
When fixed, this should re-enable master docsbuild.
**However** this has shown that failures in the Travis "doctest" target are not reported, which also needs fixing ... #2982
> Replace old sphinx function : was deprecated, now gone.

- docs/iris/src/whatsnew/contributions_2.1/newfeature_2018-Feb-04_lazy_convert_units.txt
- lib/iris/_lazy_data.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/tests/unit/coords/test_AuxCoord.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/lazy_data/test_lazy_elementwise.py
> Lazy unit conversions for cube and coord data.

- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_Coord.py
- requirements/core.txt
The `netcdftime` library does not handle time units with long time intervals (months or years). You can, however, use `UDUNITS2` to create a time coordinate with the time interval set to months or years. This gap in functionality means that it is possible that printing an Iris cube (containing a coordinate with a long time interval) will result in an exception being raised. This situation is _far from ideal_.
This PR prevents the exception being raised by gracefully falling back to printing the numerical points values for long time interval coordinates so that the exception is not raised. The check for a long time interval is made using new functionality introduced in https://github.com/SciTools/cf_units/pull/72, which this PR is dependent on. Note that this means that the tests in this …
> Gracefully handle long time intervals

- docs/iris/src/whatsnew/contributions_2.1/bugfix_2018-May-03_var_name_constraint.txt
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
This came up in #2930.
The following code:
```
import iris
cube = iris.cube.Cube([1, 2, 3])
cube.var_name = 'm??s122i123'
iris.save(cube, 'foo.nc')
```
Would previously have created the following NetCDF:
```
netcdf foo {
dimensions:
dim0 = 3 ;
variables:
int64 m\?\?s122i123(dim0) ;
// global attributes:
:Conventions = "CF-1.5" ;
}
```
This file is both invalid NetCDF, and explicitly invalid CF.
> Prevent creation of invalid CF variable names.

- lib/iris/fileformats/um_cf_map.py
updates to STASH CF translations, sourced from various metarelate contributors
> phenomenon translation updates

- docs/iris/src/whatsnew/contributions_2.1/newfeature_2018-Mar-08_co_realise_cubes.txt
- lib/iris/__init__.py
- lib/iris/_lazy_data.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_CubeList.py
Closes #3012 
I have to say though, that I find this much less obvious both in the usage and the naming.
The problem is that wrapping a bunch of cubes in a cubelist "just" in order to co-realise them seems clunky and non-obvious.  It means also that the documentation now appears in a much more obscure place.
The new name also does not sing for me : it does not highlight  what is **specifically useful** about the operation.
See the example docstring change here : https://github.com/pp-mo/iris/blob/9b24050b92559b467984bd98b57c7aeadcf2f39e/lib/iris/cube.py#L612
I think this will be typical usage, and it is a bit obscure and horrible IMO.
So frankly,  I still preferred it the way it was.
Please think on? @pelson @dkillick
> Replace iris.co_realise_cubes with CubeList.realise_data.

- lib/iris/_cube_coord_common.py
- lib/iris/aux_factory.py
- lib/iris/coords.py
Following https://github.com/SciTools/iris/pull/2874 this PR makes all docstrings/comments/exception messages refer to `var_name` as netCDF variable name.
> Amend var_name documentation

- lib/iris/config.py
> Fix configparser DeprecationWarning

- docs/iris/src/whatsnew/contributions_2.1/newfeature_2018-May-08_repr-html.txt
- lib/iris/cube.py
- lib/iris/experimental/representation.py
- lib/iris/tests/integration/experimental/test_CubeRepresentation.py
- lib/iris/tests/unit/cube/test_CubeRepresentation.py
- lib/iris/tests/unit/experimental/representation/test_CubeRepresentation.py
Add functionality to Iris cubes to produce a pretty, collapsible html representation of the cube with a jupyter notebook.
For example:
> Add _repr_html_ for Iris cubes

- docs/iris/src/whatsnew/contributions_2.1/newfeature_2018-May-03_multidim_collapse.txt
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/tests/test_analysis.py
- lib/iris/tests/unit/coords/test_Coord.py
Follow up on #3008 - Adding support for partial collapse of multi-dimensional coordinates (while keeping the current behaviour of points being the mid-points of bounds)
> Partial collapse of multi-dimensional coordinates

- .travis.yml
These two items (one for py2 and one for py3) are redundant, but do give us a quick glance at whether there was a coding issue. Mostly this comes down to the license header check, as we now have sticker to give us pep8 info.
> Remove the CODING matrix item.

- lib/iris/coord_systems.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/coord_systems/test_AlbersEqualArea.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
First take to add Albers Equal Area Projection to IRIS as per #2496.
https://github.com/SciTools/iris/issues/2496
> Add Albers Equal Area Projection and some test as per #2496

- requirements/all.txt
It is nc-time-axis on pypi: https://pypi.org/project/nc-time-axis/
But nc_time_axis on conda-forge: https://github.com/conda-forge/nc_time_axis-feedstock
Clearly, this hasn't been an issue for anybody, and it isn't tested, but nice to be correct too. 😉
> Use the correct pypi name for nc-time-axis.

- requirements/core.txt
> Add dask-array as a requirement when pip installing.

- .travis.yml
- docs/iris/src/sphinxext/gen_gallery.py
No changes from me in this PR, simply merging v1.13.x and v2.0.x into master (hence these aren't my commits). I'm pushing here for transparency and Travis testing, but am comfortable merging this myself.
Once merged, I'll go ahead and remove the v1.13.x and v2.0.x branches, which are currently at a6d2764a71f21e9c5a4a7ac897a9efc654f735ad and 70a4052299a6c135990098ccbad006a57458be70 respectively.
> Release branch close (v1.13.x, v2.0.x)

- docs/iris/src/whatsnew/2.1.rst
- lib/iris/coord_systems.py
- lib/iris/tests/results/coord_systems/Mercator.xml
- lib/iris/tests/results/netcdf/netcdf_merc.cml
- lib/iris/tests/test_coordsystem.py
- lib/iris/tests/unit/coord_systems/test_Mercator.py
Update the Mercator Iris coord system to support all the kwargs in [cartopy.crs.Mercator](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/crs.py#L938-L946). This is a prerequisite step to [supporting the Mercator projection in iris-grib](https://github.com/SciTools/iris-grib/issues/95).
> Full-featured Mercator coord system

- README.md
- docs/iris/src/_templates/index.html
A few suggested updates to the newly-lengthened introductory blurb for Iris. Nothing major here, but I have:
* tried to improve a few bits of wording
* rearranged the bullet list to an order that seemed more intuitive (to me! - very subjective)
* capitalized library names as appropriate
> [DOC] Iris Introduction updates

- README.md
- docs/iris/src/_templates/layout.html
- setup.py
The strapline for the Iris 2.1 version of the documentation was, while a better description than before, still a little clunky due to the first 'and' in the sentence. This PR changes the sentence from:
`"A powerful, format-agnostic, and community-driven Python library for analysing and visualising Earth science data."`
to:
`"A powerful, format-agnostic, community-driven Python library for analysing and visualising Earth science data."`
This has been changed in:
- `README.md`
- `docs/iris/src/_templates/layout.html`
- `setup.py`
> [DOC] Remove first 'and' from strapline to make it easier to read

- docs/iris/src/_templates/layout.html
#3057
Re-enable copybutton by switching to https.
> http -> https for copybutton.js

- lib/iris/io/__init__.py
A tiny tweak, as I found this usage was not documented.
> Explain use of saver='string' in iris.save

- docs/iris/src/developers_guide/deprecations.rst
- docs/iris/src/developers_guide/graphics_tests.rst
- docs/iris/src/developers_guide/pulls.rst
- docs/iris/src/userguide/interpolation_and_regridding.rst
- docs/iris/src/whatsnew/1.10.rst
- docs/iris/src/whatsnew/1.8.rst
- docs/iris/src/whatsnew/2.0.rst
- docs/iris/src/whitepapers/um_files_loading.rst
> Fix reStructuredText warnings

- lib/iris/fileformats/pp.py
This is a second attempt to deal with issue #3063 by branching directly from upstream/v2.1.x
> pp.py - add new example of STASH object and string comparison

- docs/iris/src/conf.py
Related to #3065 
Fixes:
iris/docs/iris/src/developers_guide/gitwash/development_workflow.rst:317: WARNING: Could not lex literal_block as "python". Highlighting skipped.
Reference:
http://www.sphinx-doc.org/en/stable/config.html#confval-highlight_language
> Fallback to no syntax hightlighting without warning.

- lib/iris/analysis/calculus.py
- lib/iris/analysis/trajectory.py
- lib/iris/cube.py
- lib/iris/experimental/stratify.py
- lib/iris/fileformats/name_loaders.py
- lib/iris/fileformats/pp.py
> Fix docstring re structured text warnings

- lib/iris/analysis/_regrid.py
- lib/iris/tests/integration/test_regridding.py
Closes #2951 
Took me a while to convince myself why it was working after this one line change.
There are two circumstances when/why this works as desired:
- The source is circular (then existing code extends data and x points - using `iris.analysis._interpolation.extend_circular_coord_and_data`).
- The source is not circular but 'linear' (default) extrapolation is used.  Existing code means that a single point is taken as a zero gradient (I assume from looking at the results) in the x, which results in the desired outcome.
- The source is not circular and linear extrapolation is not used and so values are not populated as these would now be expected points for extrapolation (as expected).
Here are plots of the new tests (source and target respectively), nicely demonstrating how the …
> ENH: Working zonal mean linear regridding for circular sources or with use of extrapolation

- lib/iris/pandas.py
This also simplifies code by being explicit about usage of "base" and "values"
for numpy and pandas objects.
More info in issue [3018](https://github.com/SciTools/iris/issues/3018)
> Avoid pandas deprecation warning.

- lib/iris/tests/unit/cube/test_Cube.py
- requirements/core.txt
A code fix, rather than a library version pin, to fix [this failing test](https://travis-ci.org/SciTools/iris/jobs/397436711#L5120-L5128), while we await a dask release containing the [bugfix](https://github.com/dask/dask/pull/3754). The code fix implemented here was suggested as a workaround in the [dask bug report](https://github.com/dask/dask/issues/3751#issuecomment-404913371).
Backs out the library version pin temporarily introduced in #3086. 
Fixes #3087.
> Workaround for dask array copy bug

- lib/iris/analysis/_grid_angles.py
- lib/iris/analysis/cartography.py
- lib/iris/tests/unit/analysis/cartography/test_gridcell_angles.py
~**WIP - DO NOT MERGE~ probably can now merge, once caveats are established
Here is a first look at the gridcell angles code.
The tests are currently a tangled mess of exploratory code + not fit for human consumption !
Eventually, I will have just the 2 new routines and proper unit tests for them.
There is a fair bit that still needs to be done, even in the main code :
* improve documentation generally
* provide for coords in alternative coord-systems, by projecting to ordinary lat-lon
* review how coords are identified (axis rather than 'longitude' + 'latitude' names)
> Gridcell rotations

- lib/iris/plot.py
- lib/iris/tests/unit/plot/test_2d_coords.py
- Reinstated a definition of coord bounds where we had accidentally removed it
- Removed a test which checked that a warning was raised, because the warning is no longer raised.
> Fix args for contiguity checks

- .travis.yml
- docs/iris/src/userguide/interpolation_and_regridding.rst
- lib/iris/analysis/geometry.py
- requirements/core.txt
Pin dask + fix minor dask usage glitch, to get tests passing again ( :crossed_fingers: ) .
Changes are basically cherrypicked from #3127 
**NASTY PROBLEM :**
Recent numpy (1.15 ?) uses different formatting for printing arrays in Python 2 + Python 3.
Alternative print solutions make the sample code very messy (as discussed offline with @lbdreyer).
I've fixed this for now by adopting the Python 3 output, and ***disabling the doctests on Python 2***
However that is pretty wasteful, as a whole row of the Travis test matrix now does almost nothing.
I expect there is some way of controlling that, but for now I don't care enough.
> Temporary dask fix

- lib/iris/analysis/_grid_angles.py
- lib/iris/analysis/cartography.py
- lib/iris/tests/__init__.py
- lib/iris/tests/stock/_stock_2d_latlons.py
- lib/iris/tests/unit/analysis/cartography/test_gridcell_angles.py
**WIP : not yet ready**
Followon work from #3096 
* more review issues : see #3114
* PLUS : tidy up + add some proper tests
~**PLEASE NOTE**~
~contents of `...tests/unit/analysis/cartography/test_gridcell_angles.py` are still mostly junk~
~Please await more commits before commenting !~
(now more sensible, though more tests still wanted)
> Vector plots 2

- requirements/core.txt
Problems have arisen with Mollweide plots since Proj4 version 5.1 has become available
[e.g. see here](https://travis-ci.org/SciTools/iris/builds/422933777?utm_source=github_status&utm_medium=notification)
(though cartopy version is still 0.16, but this is thought to have known problems with Proj4 > 5).
This branch **first** adds a dependency requirement proj5>=5, 
which should reproduce the problems recently emerging with some plots (and spin fresh tests to show it).
**Then** change to proj4<5, which should fix it...
Background : @pelson thinks that cartopy is not ready for Proj4 > 5, but this is as yet neither pinned nor tested/fixed.
Simplest for now is to pin in Iris
N.B. for now, **targetting 2d_coords branch**, where we immediately need it.
> Temporary pin to avoid problems caused by Proj4 v5.1.

- lib/iris/tests/__init__.py
- lib/iris/tests/unit/analysis/cartography/test_rotate_grid_vectors.py
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py
Previously deferred work, as noted in #3114
> Tests for rotate_grid_vectors

- lib/iris/tests/integration/plot/test_plot_2d_coords.py
- lib/iris/tests/results/imagerepo.json
Add integration test of pcolormesh plots of cube with 2d coords.
Before this gets merged, the following needs to be merged:
* Iris PR https://github.com/SciTools/iris/pull/3135
* https://github.com/SciTools/test-iris-imagehash/pull/16
> Add integration graphics tests for pcolormesh with 2d coords

- docs/iris/src/whatsnew/2.2.rst
- lib/iris/plot.py
- lib/iris/tests/integration/plot/test_vector_plots.py
- lib/iris/tests/results/imagerepo.json
Integration tests for `iris.plot.quiver` and `streamplot`
Needs https://github.com/SciTools/test-iris-imagehash/pull/18 to pass
> Vector plots 4

- docs/iris/src/whatsnew/contributions_2.2.0/newfeature_2018-Aug-14_load-nc-chunks.txt
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test__get_cf_var_data.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_cube.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_auxiliary_coordinate.py
Get chunks from a NetCDF file when loading the file as Iris cubes. In (limited) testing of a large, compressed NetCDF file this had a significant impact on load speed:
Load speed, chunks not used: 254.186s
Load speed, chunks used: 20.193s
> Use NetCDF variable's chunks on load

- lib/iris/fileformats/cf.py
This follows various user enquiries about changed behaviour.
Since the incorporation of netcdf 1.4, ***all*** cubes read from netcdf now have masked data arrays
-- for data with no masked points, the mask is now typically empty (or False), which was previously not possible.
It is also this that has caused a large increase in the occurrence of the "Gracefully filling" warnings,
as noted in #3171
> Fix for netCDF4 1.4 behaviour change.

- requirements/core.txt
Matplotlib 3 was released a few days ago. Seems pulling in latest install from conda breaks a lot of functionality due to Matplotlib 3 not being supported.  Cartopy seems to have the biggest issues but might be other issues elsewhere.
For now suggest restricting to 2.x version of Matplotlib.
> Attempt to fix Matplotlib issue by resticting to 2.x

- INSTALL
- docs/iris/src/conf.py
- docs/iris/src/whatsnew/contributions_2.2.0/bugfix_2018-Sep-19_gracefully-filling-warning-only-when-masked.txt
- lib/iris/analysis/_regrid.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/tests/integration/test_regridding.py
- lib/iris/tests/test_coordsystem.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_cube.py
- lib/iris/tests/unit/fileformats/pp/test_save.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_dimension_coordinate.py
This PR changes the behaviour of `iris.load` so that it only issues warnings about gracefully filling data and bounds if it actually does so.
> Improve gracefully filling warning

- lib/iris/pandas.py
- lib/iris/tests/results/pandas/as_cube/data_frame_multidim.cml
- lib/iris/tests/test_pandas.py
@DavidSimonin pointed out that if a 2-dimensional pandas DataFrame contains string-type column headers, then it is not currently being handled correctly.
This change treats the list of column headers as an array of strings rather than a single object, which enables subsequent operations to run without error.
> fix for pandas column object bug

- requirements/all.txt
- requirements/gen_conda_requirements.py
Reuse `CONDA_PATTERN` and align to `nc-time-axis` for both `pip` and `conda`.
> minor requirements tidy

- docs/iris/src/whatsnew/contributions_2.2.0/bugfix_2018-Aug-20_print-long-time-interval-bounds.txt
- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_Coord.py
In #2354 we added graceful handling of printing time coordinates with a long time interval (`months` or `years`). Unfortunately this was added for points only, meaning that printing such a time coordinate with bounds would still fail. This change extends the graceful handling to include bounds as well, if present, such that the literal bound numbers are printed, rather than the numbers being first converted to datetimes (which fails).
The origin of this problem is that `cftime` does not handle long time intervals, which I've [noted in the associated issue](https://github.com/SciTools/iris/issues/3098#issuecomment-412802384). This doesn't represent a fix for the problem, but it does avoid an error being thrown. Longer term a proper fix for this would be valuable – but this might need to be …
> Handle printing bounds of long time interval coords

- docs/iris/src/whatsnew/contributions_2.2.0/newfeature_2018-Oct-03_reverse_cube.txt
- lib/iris/tests/test_util.py
- lib/iris/tests/unit/util/test_reverse.py
- lib/iris/util.py
The `iris.util.reverse` [documentation](https://scitools.org.uk/iris/docs/v2.1/iris/iris/util.html?highlight=util%20reverse#iris.util.reverse) states that it can be used for reversing an array, but it works equally well for reversing a cube.  Since I use it this way in my code, I'd like to make this usage official by:
- Updating the docstring to indicate the function works on a cube.
- Adding a test for reversing a cube.
I also moved the existing array tests into `tests/unit` and swapped out `np.testing.assert_array_equal` for `self.assertArrayEqual`.
Note that for numpy arrays there is also [`numpy.flip`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.flip.html)
> iris.util.reverse on cubes

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
As per conversation with @corinnebosley , we had an issue where we were creating an orography as a standalone coordinate that wasn't attached to a cube.  Trying to use this in a hybrid height factory resulted in a hard to interpret error message.  I'm proposing adding a check when adding a hybrid height factory or other aux factory to a cube to ensure that the coordinates are present on the cube; and if not raising a hopefully more helpful error.
> Improved Aux factory error handling: better message, delivered earlier

- lib/iris/cube.py
- requirements/core.txt
Explore how much breaks if we unpin dask to use the latest master.
cc @corinnebosley @pp-mo 
Closes #3147
> [TST] Unpin dask

- lib/iris/tests/unit/plot/_blockplot_common.py
- lib/iris/tests/unit/plot/test_pcolor.py
- lib/iris/tests/unit/plot/test_pcolormesh.py
*First* commit tidies the pcolor/pcolormesh tests to combine all the common code (no functional change).
*Second* add tests that check the new 'contiguity_tolerance' kwarg is passed down from `iris.plot.pcolor` and `..pcolormesh` into the internal common routine `iris.plot._draw_2d_from_bounds`.
Closes #3164
> Test contig tol

- lib/iris/_lazy_data.py
- lib/iris/analysis/__init__.py
- lib/iris/tests/unit/analysis/test_Aggregator.py
- lib/iris/tests/unit/analysis/test_COUNT.py
- lib/iris/tests/unit/analysis/test_MAX.py
- lib/iris/tests/unit/analysis/test_MIN.py
- lib/iris/tests/unit/analysis/test_STD_DEV.py
- lib/iris/tests/unit/analysis/test_SUM.py
- lib/iris/tests/unit/lazy_data/test_non_lazy.py
Make more aggregators lazy, specifically:
* iris.analysis.SUM
* iris.analysis.COUNT
and add testing for these aggregators, and some existing aggregators that were missing lazy functionality testing.
This leaves the following aggregators non-lazy:
* GMEAN, HMEAN - probably doable, but the non-lazy integration uses scipy functionality not replicated in dask
* RMS - see #3130 
* MEDIAN, PROPORTION - not trivially lazy?
* PERCENTILE - not touched
> [ENH] More lazy aggregators

- docs/iris/src/whatsnew/contributions_2.1/newfeature_2018-Apr-12_fast_load_file_indices.txt
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/um/__init__.py
- lib/iris/fileformats/um/_fast_load.py
- lib/iris/fileformats/um/_fast_load_structured_fields.py
- lib/iris/tests/unit/fileformats/um/fast_load/test_FieldCollation.py
- lib/iris/tests/unit/fileformats/um/fast_load_structured_fields/test_BasicFieldCollation.py
- lib/iris/tests/unit/fileformats/um/fast_load_structured_fields/test_group_structured_fields.py
This intends to address problems discussed in [this comment](https://github.com/SciTools/iris/pull/2640#issuecomment-313665559) and follow-ons.
Implementation notes :
* The information is attached to the 'field' arg in the load callback, i.e. in this case a FieldCollation.
* The caller should be able to use this to annotate the multidimensional collated cubes as required :  I believe this is what the users's existing code does (using normal load to annotate each raw cube with an extra  "pseudolevel ordering" coordinate).
* the old 'FieldCollation' class is now renamed 'BasicFieldCollation' : the new, public 'FieldCollation' is a derived class which adds the location-in-input-file info.  This preserves the original, cleaner concept.
Todo:
> Provide info on pp-field indices in the file for structured um loads.

- lib/iris/tests/integration/plot/test_plot_2d_coords.py
- lib/iris/tests/results/imagerepo.json
Needs https://github.com/SciTools/test-iris-imagehash/pull/21
Closes #3167
> Integration test for iris.plot.contour with 2d coords.

- lib/iris/analysis/__init__.py
- lib/iris/tests/unit/analysis/test_RMS.py
Adds a lazy aggregation function to the RMS aggregator, which makes use of dask functionality to build the RMS equation.
Note that _currently_ this does not allow lazy weighted RMS aggregation when the input is also masked. This is in place because there appears to be [a limitation in `da.average`](https://github.com/dask/dask/issues/3846), which means the weights array is not masked to match the input data. 
Ping @niallrobinson - with thanks for raising the fact the RMS aggregator wasn't lazy, and for pairing on this update.
> Update RMS aggregator with lazy function

- lib/iris/analysis/_scipy_interpolate.py
This avoids the warning below and possible error in the future.
```
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated;
use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an
array index, `arr[np.array(seq)]`, which will result either in an error or a different
result.
```
> fix numpy deprecation warning

- lib/iris/tests/unit/coord_systems/test_Mercator.py
- requirements/core.txt
- Added `latitude_true_scale=0.0` args to expected result in mercator tests
- Pinned cftime to !=1.0.2.1 for 2.2.x branch
> fix for mercator test failures

- lib/iris/coord_systems.py
- lib/iris/tests/test_coordsystem.py
> Lambert conformal secant latitudes

- requirements/core.txt
> BLD: Pinned cftime 1.0.1

- lib/iris/fileformats/pp.py
Fixes problem triggered by numpy >= 1.16.
Can no longer simply "make" an array writeable by writing the flag.
There's actually only one place we do that.  It was probably a bit cheeky anyway ...
> Fix for numpy 1v16.

- lib/iris/fileformats/pp.py
- requirements/core.txt
> Mergeback 2.2.x

- lib/iris/analysis/__init__.py
- lib/iris/analysis/cartography.py
- lib/iris/tests/test_merge.py
This has been cropping up in our tests, [e.g. here](https://travis-ci.org/SciTools/iris/jobs/489641793#L1634).
It also reportedly affects some uses of interpolation (? though not seen in tests ?).
> Avoid numpy FutureWarning about indexing with sequence.

- requirements/core.txt
Reverts SciTools/iris#3265
Following #3274 (thanks @lbdreyer !)
Likewise part of routing these changes via v2.2.x branch instead of direct to master ...
> Revert "Test with newest cf-units: no longer called cf_units."

- requirements/core.txt
Like #3276 replaces original #3267, which was accepted + reverted by #3274 ...
So this replaces #3265, which was reverted by #3275 
Rebased + retargetted onto v2.2.x
> Test with newest cf-units: no longer called cf_units.

- .travis.yml
- lib/iris/analysis/__init__.py
- lib/iris/analysis/_interpolation.py
- lib/iris/analysis/calculus.py
- lib/iris/analysis/cartography.py
- lib/iris/experimental/stratify.py
- lib/iris/fileformats/name_loaders.py
- lib/iris/fileformats/pp.py
- lib/iris/tests/integration/plot/test_vector_plots.py
- lib/iris/tests/test_coding_standards.py
- lib/iris/tests/test_merge.py
- lib/iris/tests/test_util.py
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py
- lib/iris/tests/unit/analysis/test_Aggregator.py
- lib/iris/tests/unit/analysis/test_PROPORTION.py
- lib/iris/tests/unit/analysis/test_RMS.py
- requirements/gen_conda_requirements.py
**WIP: DO NOT MERGE (yet) !**
We seem to have lost this functionality with #3036
Since some time before that point, the run in the 'main' test sequence was giving a "SKIP: Iris installation did not look like a git repo." message [(here, for instance)](https://travis-ci.org/SciTools/iris/jobs/386110444#L4496)
I think this is because you need to be in the right directory when running the test.
> Get licence header test working again.

- lib/iris/fileformats/pp_load_rules.py
- lib/iris/tests/integration/test_pp.py
- lib/iris/tests/results/COLPEX/small_colpex_theta_p_alt.cml
- lib/iris/tests/results/grib_load/polar_stereo_grib1.cml
- lib/iris/tests/results/netcdf/netcdf_save_load_hybrid_height.cml
- lib/iris/tests/unit/fileformats/pp_load_rules/test__convert_time_coords.py
- lib/iris/tests/unit/fileformats/pp_load_rules/test__epoch_date_hours.py
- lib/iris/tests/unit/fileformats/pp_load_rules/test_convert.py
- requirements/core.txt
Hopefully, this fixes test failures resulting from changes in cftime > 1.0.1.
The test problems seem to be confined to the PP/FF loading.
Hence the approach here.
It's still possible that the problem could occur in other areas though.
(Including knock-on problems with other tests, that this will turn up...)
Addresses #3248
**Note : This ALSO unpins cftime**
> Fix cftime gt 101

- docs/iris/src/whatsnew/2.2.rst
- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-Feb-07_newaxis_copy_bug.txt
- lib/iris/tests/unit/util/test_new_axis.py
- lib/iris/util.py
It was found that adding an axis to a cube with an aux-factory had a subtle bug, which then causes errors _when you copy the result_ :
Example:
```
>>> cube
<iris 'Cube' of mass_fraction_of_ozone_in_air / (kg kg-1) (model_level_number: 63; grid_latitude: 182; grid_longitude: 146)>
>>> 
>>> # Presumably, something here is wrong ...
... cube2 = iutil.new_axis(cube, 'time')
>>> cube2
<iris 'Cube' of mass_fraction_of_ozone_in_air / (kg kg-1) (time: 1; model_level_number: 63; grid_latitude: 182; grid_longitude: 146)>
>>> 
>>> # ... but this is what actually fails :
... cube3 = cube2.copy()
File "<stdin>", line 2, in <module>
File "/opt/scitools/environments/experimental/2019_01_31-1/lib/python3.6/site-packages/iris/cube.py", line 2967, in copy
cube = …
```
> Fix problem with factories in iris.util.new_axis().

- lib/iris/util.py
Corrected a couple of references to `iris.util.mask_cube` in `find_discontiguities` docstring.  Previously incorrectly referred to `iris.util.mask_discontiguities`, which doesn't exist.
Closes #3253
> corrected mistakes in contiguity checking docstring

- lib/iris/tests/__init__.py
When running our AT's ,we import 'IrisTest' from 'iris.tests'. Our tests run on the HPC which has restricted or no internet access, which causes the 'requests.get' call to hang indefinitely. 
In this PR, I've added a 1 second timeout to the 'requests.get' call to stop the call hanging.
Testing on the HPC:
The following call will return with a 'ConnectTimeoutError' on the HPC :
'
>>> import requests  
>>> try:
...     requests.get('https://github.com/scitools/iris', timeout=1.0)
... except:
...    print('Timed out')
... 
Timed out
>>>
'
which would allow the code to continue....
However , without the timeout the following call will hang indefinitely  and has to be stopped, in this case,  with a keyboardInterrupt:
`
>>> requests.get('https://github.com/scitools/iris') …
> Added a timeout to stop requests.get hanging on platforms with no internet

- lib/iris/tests/results/imagerepo.json
HISTORY NOTE 
Used to contain a lot of trial code attempting to make 'test_image_json' work.
I've taken all that out again, as that solution now lies in #3308 
So this can now be merged ok.
https://github.com/SciTools/test-iris-imagehash/pull/22 relates, but that is now merged.
> Fix for small plot changes with freetype 2.10.

- docs/iris/src/sphinxext/custom_class_autodoc.py
Hopefully fixes the docs-build, which should get us back our :heavy_check_mark: on PRs.
> Attempt to fix Sphinx import.

- lib/iris/tests/test_image_json.py
An almost complete rewrite of `iris.tests.test_image-json`.
Instead of using the GitHub API to interrogate the test-iris-imagehash repo, we now just fetch an 'image listings file' which is basically the text of an `ls *.png`.
This is because the (unauthenticated) GitHub API access was proving very unreliable.
Note : relies on SciTools/test-iris-imagehash#23 , but that is already merged.
> Imagehash listfile for fixbranch

- .travis.yml
- lib/iris/fileformats/pp.py
- lib/iris/tests/test_pp_module.py
- lib/iris/tests/unit/fileformats/pp/test_PPDataProxy.py
- lib/iris/tests/unit/fileformats/pp/test__create_field_data.py
- lib/iris/tests/unit/fileformats/pp/test__data_bytes_to_shaped_array.py
- lib/iris/tests/unit/fileformats/pp/test__interpret_field.py
Fix the problem with landsea-masked PPFields, where the dask compute() calls PPDataProxy.\_\_getitem__, which can then make a nested 'compute()' call for the landsea-mask data.
Closes #3237
> Dask landsea masks bugfix

- docs/iris/src/userguide/cube_statistics.rst
Whilst building the docs I came across a warning complaining that the label `partially_collapse_multi-dim_coord` was undefined.
Turns out it was removed in [this PR](https://github.com/SciTools/iris/pull/3028/files) which was part of the 2.1 release.
I am adding this to the 2.2.x branch as it breaks the build of the 2.2.1 docs.
This fix will get added into master as part of a mergeback
> Fix userguide: remove out of date comment

- .travis.yml
- docs/iris/src/sphinxext/custom_class_autodoc.py
- lib/iris/analysis/calculus.py
- lib/iris/coords.py
- lib/iris/experimental/stratify.py
- lib/iris/fileformats/name_loaders.py
- lib/iris/tests/__init__.py
- lib/iris/tests/integration/plot/test_vector_plots.py
- lib/iris/tests/test_coding_standards.py
- lib/iris/tests/test_util.py
- lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py
- lib/iris/tests/unit/analysis/test_Aggregator.py
- lib/iris/tests/unit/analysis/test_PROPORTION.py
- lib/iris/tests/unit/coords/test_AuxCoord.py
- lib/iris/tests/unit/util/test_new_axis.py
- requirements/gen_conda_requirements.py
The license header check doesn't run in this branch so we missed a few copyright years that need updating.
This is needed so before we can do the mergeback of this branch (see #3316 )
> Update copyright years in license headers

- docs/iris/src/sphinxext/custom_class_autodoc.py
Similar to #3310, the latest release of sphinx has included some things moving around so our import: 
```
from sphinx.ext.autodoc import *
```
no longer imports everything we need.
> Add another missing sphinx import

- .travis.yml
- docs/iris/src/sphinxext/custom_class_autodoc.py
- docs/iris/src/userguide/cube_statistics.rst
- docs/iris/src/whatsnew/2.2.rst
- lib/iris/analysis/__init__.py
- lib/iris/analysis/cartography.py
- lib/iris/coords.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/pp_load_rules.py
- lib/iris/tests/__init__.py
- lib/iris/tests/integration/test_pp.py
- lib/iris/tests/results/COLPEX/small_colpex_theta_p_alt.cml
- lib/iris/tests/results/grib_load/polar_stereo_grib1.cml
- lib/iris/tests/results/imagerepo.json
- lib/iris/tests/results/netcdf/netcdf_save_load_hybrid_height.cml
- lib/iris/tests/test_image_json.py
- lib/iris/tests/test_merge.py
- lib/iris/tests/test_pp_module.py
- lib/iris/tests/unit/coords/test_AuxCoord.py
- lib/iris/tests/unit/fileformats/pp/test_PPDataProxy.py
- lib/iris/tests/unit/fileformats/pp/test__create_field_data.py
- lib/iris/tests/unit/fileformats/pp/test__data_bytes_to_shaped_array.py
- lib/iris/tests/unit/fileformats/pp/test__interpret_field.py
- lib/iris/tests/unit/fileformats/pp_load_rules/test__convert_time_coords.py
- lib/iris/tests/unit/fileformats/pp_load_rules/test__epoch_date_hours.py
- lib/iris/tests/unit/fileformats/pp_load_rules/test_convert.py
- lib/iris/tests/unit/util/test_array_equal.py
- lib/iris/tests/unit/util/test_new_axis.py
- lib/iris/util.py
- requirements/core.txt
There has been a fair amount of additions to the 2.2.x branch that should be merged back into master (especially since we just cut the 2.2.1 release).
To create this PR I did the following commands:
```$ git checkout upstream/v2.2.x -b 221_mergeback_rebase```
Then I did an interactive release to select the commits that were missing 
```$ git rebase -i --onto upstream/master HEAD~12```
Which were all the commits since `c3048cbf Fix for numpy 1v16. (#3257)` as this and `b0d5512b BLD: Pinning cftime to 1.0.1 (#3247)` were included in the last mergeback.
> v2.2.x branch mergeback

- lib/iris/__init__.py
See #3334.  Just removed the first merge to see if anything breaks!
> Single Merge for load_cube

- lib/iris/analysis/stats.py
Only two functions to clarify here.  This is a small one to start us off.
> added note about laziness of operations to statistical functions

- lib/iris/fileformats/pp.py
This adds documentation requested in #425. The documentation that only Cubes can be passed was already added in #1952.
> Save docs patch

- lib/iris/_constraints.py
- lib/iris/analysis/__init__.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/fileformats/cf.py
- lib/iris/io/format_picker.py
- lib/iris/iterate.py
- lib/iris/tests/test_merge.py
- lib/iris/util.py
Updates the use of collections in preparation for Python3.8, see https://github.com/python/cpython/commit/c66f9f8d3909f588c251957d499599a1680e2320 (and also avoids deprecation warnings when using iris in Python3.7).
> Update in preparation for Python3.8 deprecation of importing ABCs from collections

- lib/iris/tests/unit/fileformats/pp/test__create_field_data.py
- lib/iris/tests/unit/lazy_data/test_as_concrete_data.py
- lib/iris/tests/unit/lazy_data/test_co_realise_cubes.py
- requirements/core.txt
This PR undoes the temporary workaround implemented by PR https://github.com/SciTools/iris/pull/3350, which pinned `dask<2`.
The latest version of `dask` version `2.1.0` (only a few days old now) resolves the outstanding `stack overflow` issues avoided by our pin. 
Also see https://github.com/ESMValGroup/ESMValTool/issues/1188 for further details.
> Unpin dask

- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-Apr-03_partial_collapse_bounded_coords.txt
- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_Coord.py
> Partial Collapse of Multidimensional Auxcoords with Bounds

- lib/iris/_constraints.py
- lib/iris/analysis/__init__.py
- lib/iris/analysis/maths.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/fileformats/cf.py
- lib/iris/io/format_picker.py
- lib/iris/iterate.py
- lib/iris/tests/test_basic_maths.py
- lib/iris/tests/test_merge.py
- lib/iris/util.py
Replaces #3366,
just so we can resolve in @bjlittle absence
Original head
> This PR fixes the iris travis-ci tests after moving to the latest numpy 1.17.0 - and it also follows-up from #3320 to dress the naked try...excepts with an ImportError
Closes #3365  (ref [old comment](https://github.com/SciTools/iris/pull/3366#issuecomment-519952864))
> Dress naked excepts #2

- docs/iris/src/userguide/loading_iris_cubes.rst
- lib/iris/__init__.py
As requested in #3314, there is now a mention in the documentation of the unordered state of loaded CubeLists.
> Mentioned random CubeList order in the docs

- lib/iris/_lazy_data.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/analysis/test_RMS.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/fileformats/netcdf/test__get_cf_var_data.py
- lib/iris/tests/unit/lazy_data/test_as_lazy_data.py
- lib/iris/tests/unit/lazy_data/test_is_lazy_data.py
Revised chunking policy, which will mostly affect loading from netcdf files.
Key change : allows multiplying up as well as dividing chunks, mainly to fix the #3357.
Closes #3357 #3362
> Chunk control

- requirements/core.txt
Simply replaces #3353, which was over-complicated by a different issue
Relates to (but no longer closes)  #3154 
There is a chance we'll have to exclude proj4 >= 6.0 (newly out I think).
But I think cartopy dependencies should sort that out for us.
Here goes ...
> Replace version pin on proj4 to permit proj 4 v5.

- lib/iris/tests/unit/coords/test_Coord.py
As noted at #3363, when an AuxCoord with lazy points is collapsed, the points are currently realised in the process.  This was inadvertently fixed by #3302, but I thought it worth adding a test as well.
Once #3302 is merged, I can rebase and then this new test should pass.
> Coord.collapsed:  lazy points should stay lazy

- lib/iris/plot.py
- lib/iris/tests/integration/plot/test_vector_plots.py
> Fix circular quiver plots

- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-Aug-29_abf_abl_cube_names.txt
- lib/iris/fileformats/abf.py
- lib/iris/tests/results/abf/load.cml
The abf/abl file loader was setting the name of the cubes incorrectly.
On [this page](http://wap.sciencenet.cn/home.php?mod=space&mobile=1&do=blog&id=889834&id=889834) explaining the LAI3g & FPAR3g datasets it states that:
abl <- LAI3g
abf <- FPAR3g
as opposed to what we currently have
> Fix naming of cubes from abf/abl files

- lib/iris/fileformats/um_cf_map.py
- tools/gen_translations.py
translation updates from metarelate
> metadata translations may 2019

- lib/iris/experimental/representation.py
- lib/iris/tests/unit/experimental/representation/test_CubeRepresentation.py
Fixes the bug with #3351.
Previously, if a cube had an attribute which was a string containing '\n', attempting to get the html_repr of that cube would cause an exception.  This pull request would instead add what is in that new line to a new row of the html_repr.
A cube whose string representation looks like:
```
sea_water_potential_temperature / (degC) (-- : 148; -- : 180)
Auxiliary coordinates:
latitude                           x         x
longitude                          x         x
Scalar coordinates:
depth: 4.999938 m, bound=(0.0, 10.0) m
time: 0001-01-01 12:00:00
Attributes:
Conventions: CF-1.5
history: Wed Jul 10 11:00:19 2019: ncks -A -v LON surface_20150112.nc 1997_mon06.nc4
...
Cell methods:
mean: time
```
will now have a html_repr which creates a table looking something …
> Fix bug with html_repr

- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2019-Sep-04_move_experimental_point-in-cell_regridder_to_analysis.txt
- lib/iris/analysis/__init__.py
- lib/iris/analysis/_regrid.py
- lib/iris/experimental/regrid.py
- lib/iris/tests/unit/analysis/regrid/test_PointInCell.py
- lib/iris/tests/unit/analysis/regrid/test__CurvilinearRegridder.py
- lib/iris/tests/unit/analysis/test_PointInCell.py
Addresses issue #2732
Moved the PointInCell regridder and associated code from  iris/experimental to the core of Iris (in this case to iris/analysis) in order to make the PointInCell regridding scheme public.
Moved associated tests across from iris/tests/experimental to iris/tests/unit/analysis 
Added an exception to raise to users when they attempt to use the PointInCell functionality that has been migrated from experimental to the core of Iris.
Added a whatsnew file to briefly describe the changes
> Make PointInCell regridding scheme public (#2732)

- .travis.yml
- README.md
- docs/iris/src/_templates/index.html
- docs/iris/src/_templates/layout.html
- docs/iris/src/whatsnew/aggregate_directory.py
- docs/iris/src/whatsnew/index.rst
Closes #3396 
NOTE: I have made version changes (2.2 --> 2.3)  to the .RSTs in 3 places :
* `docs/iris/src/_templates/index.html`
* `docs/iris/src/_templates/layout.html`
* `docs/iris/src/whatsnew/index.rst`
In future, to make this scheme work properly (so branch docs are properly readable, especially the whats-new), we really need to move these on _just after a new release, when we bump the version in master_.
That is, exactly as we do to the iris version string.
> Auto branch docs

- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2019-Sep-02_standard_name_modifiers.txt
- lib/iris/_cube_coord_common.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/cf.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/unit/cube_coord_common/test_CFVariableMixin.py
- lib/iris/tests/unit/cube_coord_common/test_get_valid_standard_name.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_cube_metadata.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_get_names.py
CF conventions support a set of standard_name modifiers.  See [3.3. Standard Name](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#standard-name) for more details, specifically:
> A standard name is associated with a variable via the attribute standard_name which takes a string value comprised of a standard name optionally followed by one or more blanks and a standard name modifier (a string value from Appendix C, Standard Name Modifiers).
This PR modifies the CFVariableMixin standard_name setter (and the pyke rules) to support standard name modifiers. 
I found there wasn't much testing of cube/coord names so I have split this PR into two commits:
1. The first commit has no functional changes. It just adds testing of the pyke rules to show that they …
> Support Standard Name Modifers (not units!)

- lib/iris/plot.py
In code that was running in batch mode and not using matplotlib.pyplot, I came across a failure that was a direct result of pyplot being invoked to identify the figure and axes I was working on. If the figure was not created with pyplot then pyplot cannot find the figure and hence the axes.
In this particular case the call to _invert_yaxis from _draw_1d_from_points does not include the axes argument hence _invert_yaxis tries to identify the active axes using pyplot. Adding `axes` to the _invert_yaxis call prevents this and also matches the behaviour in _draw_2d_from_points and _draw_2d_from_bounds.
> Added axes to _invert_yaxis call in _draw_1d_from_points

- README.md
This PR creates documentation badges to link to both the stable released versions of Iris e.g., scitools, and the lastest development version of Iris e.g., master 
Example of the rendered `README.md` can be seen [here](https://github.com/bjlittle/iris/tree/readme-docs-badges).
> update readme.md docs badges

- lib/iris/experimental/representation.py
Made the `_make_shapes_row` generate more proper html, the initial `<tr ...>` is now closed by `</tr>` rather than `</td>`.
> Fix _repr_html_, close tags appropriately

- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2019-Mar-08_remove_cell_measure_by_name.txt
- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
Although labelled as a bug I don't think #3081 is a bug strictly speaking. As far as I can tell its behaviour is as expected from the reference docs at https://scitools.org.uk/iris/docs/latest/iris/iris/cube.html#iris.cube.Cube.remove_cell_measure.  In as much as the argument to the method is documented as having to be a CellMeasure instance (not a name of a cell measure).
Having said that it could be a bit misleading as other public Cube methods such as Cube.cell_measure take either a CellMeasure object OR the name of a cell measure (https://scitools.org.uk/iris/docs/latest/iris/iris/cube.html#iris.cube.Cube.cell_measure), and currently if you attempt to pass in the name of a cell measure to be removed it isn't removed, silently
So although maybe not a bug in the strict sense it seemed a …
> Removal of a cube's cell measure by name (#3081)

- lib/iris/coords.py
- lib/iris/tests/results/netcdf/netcdf_tmerc_and_climatology.cml
Follow-up from #3395, adding changes to support the `climatological` property in our `cml` test output.
> Climatological xml

- lib/iris/analysis/__init__.py
- requirements/core.txt
Closes #3129
Note that this does require at least version 1.1.0 of dask, I'm not sure if that is something you want.
> Make MEAN with weights lazy

- lib/iris/coords.py
- lib/iris/fileformats/pp.py
- lib/iris/palette.py
This PR follows-up from the review of #3395 and more specifically this [comment](https://github.com/SciTools/iris/pull/3395#discussion_r327686889), to move away from using this property pattern:
```python
def _thing_getter(self):
...
def _thing_setter(self, ...):
...
thing = property(_thing_getter, _thing_setter)
```
to using this property pattern:
```python
@property
def thing(self):
...
@thing.setter
def thing(self, ...):
...
```
for reasons discussed in the #3395 [comment](https://github.com/SciTools/iris/pull/3395#discussion_r327686889).
> use @property everywhere

- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-Sep-20_vp_coordsystem_definition.txt
- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2019-Sep-20_geostationary_coordsystem.txt
- lib/iris/coord_systems.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/plot.py
- lib/iris/tests/results/integration/grib2/TestImport/gdt90_with_bitmap.cml
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/unit/coord_systems/test_Geostationary.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_geostationary_coordinate_system.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_verticalp_coordinate_system.py
- lib/iris/tests/unit/plot/test__check_geostationary_coords_and_convert.py
> Correct handling of NetCDF VerticalPerspective and Geostationary coordinate systems

- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2019-Jul-11_lazy-aggregated_by.txt
- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
Closes #3280
Signed-off-by: Klaus Zimmermann <klaus.zimmermann@smhi.se>
> Adds lazy version of aggregated_by routine to Cube.

- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2019-Sep-27_cell_measure_integer_data.txt
- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_CellMeasure.py
Currently, we do not allow the creation of cell measures with non-float data as it is claimed that this is not supported until CF1.7
As of #3406 we are now committed to CF1.7 so we can now support this.
It is worth mentioning that I struggled to find reference to the 
> Non-floating cell measures are not valid up to CF v1.7
in the CF documenstation. But regardless, we can remove this restriction now.
> Allow non-float cell measures

- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-Oct-01_cube_transpose_cell_measures.txt
- lib/iris/cube.py
- lib/iris/tests/unit/coords/test_CellMeasure.py
- lib/iris/tests/unit/cube/test_Cube.py
Currently cell measures are not handled when you do a transpose of a cube. 
```
>>> c = Cube(np.arange(6).reshape(2,3), 'x_wind')
>>> cm = CellMeasure(np.arange(6).reshape(2,3), measure='area')
>>> c.add_cell_measure(cm, (0,1))
>>> print(c._cell_measures_and_dims)
[[CellMeasure(array([[0, 1, 2],
[3, 4, 5]]), measure=area, standard_name=None, units=Unit('1')), (0, 1)]]
>>> c.transpose()
>>> print(c._cell_measures_and_dims)
[[CellMeasure(array([[0, 1, 2],
[3, 4, 5]]), measure=area, standard_name=None, units=Unit('1')), (0, 1)]]
```
Where I would expect the last line to return:
```
>>> print(c._cell_measures_and_dims)
[[CellMeasure(array([[0, 1, 2],
[3, 4, 5]]), measure=area, standard_name=None, units=Unit('1')), (1, 0)]]
```
i.e. the dims swapped, as it does with auxiliary coords.
This PR …
> Fix handling of cell measures during transposes of cubes

- docs/iris/src/whatsnew/2.2.rst
- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-Oct-02_boolean_data_compare.txt
- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2019-Oct-02_cube_equality_tolerance.txt
- lib/iris/tests/unit/cube/test_Cube.py
- requirements/core.txt
Resolve some problems resulting from #3431 ...
* whatsnew entry moved
* needs dask>=1.2 (see #3433)
* tests for new data-equality behaviour
* whats new for behaviour change
> Boolean data compare - additional fixes

- lib/iris/__init__.py
Bump the `master` version to `3.0.dev0` :tada: 
Note that, the version isn't `3.0dev0` nor `3.0.0dev0` not even `3.0.0.dev0`. 
Patch versions don't appear on `master`, those are for `X.X.x` branches. The `master` branch is reserved for major and minor versions (and cycling `dev` appropriately, not that we ever have)
Also it's `3.0.dev0` instead of `3.0dev0` otherwise `setuptools` complains with:
```
setuptools/dist.py:472: UserWarning: Normalizing '3.0dev0' to '3.0.dev0'
```
> bump version to 3.0.dev0

- .travis.yml
- requirements/all.txt
- requirements/extensions.txt
- requirements/gen_conda_requirements.py
This PR removes Python2 `travis-ci` testing :tada: 
As a part of technical debt, the appropriate changes are now in place within the `.travis.yml` to commence `iris-grib` tests.... however, there are 5 errors and 10 failures that require to be addressed.
I'll raise a separate issue to cover this, see https://github.com/SciTools/iris/issues/3447.
> disable python2 travis-ci

- lib/iris/analysis/calculus.py
Whilst looking for deprecations that needed removing in the Iris 3 release, I came across what looks like something that shouldn't be deprecated?
I'm not sure! So I thought I would raise it.
It was originally a regular warning, but #1993 changed it to a deprecation warning
> Undo deprecation warning - should be regular warning?

- lib/iris/analysis/calculus.py
This is a minimal improvement to the problems identified in #3449 with the error + warning messages produced by `iris.analysis.calculus._construct_midpoint_coord`.
Frankly there's a lot more that's wrong with this + I almost wish I hadn't bothered :  
* the use of this private routine as a utility in the tests for another routine (_construct_delta_coord) is pretty horrible
* the optional use of the 'circular' keyword is *only* used by the test code, not the main iris codebase : So it could, and  should be much simpler !
* the routine raises an error if called with circular=True when coord.circular does not exist, but it only emits a *warning* if coord.circular==False  ((arrrrgh!))
> Improve warning and error messages for old routine.

- lib/iris/analysis/__init__.py
This fixes a problem I found with the 2.3.0rc0 release candidate ...
The new public PointInCell scheme did not appear in the docs (and the link in the whatsnew was broken), because it is not public : 
Because `iris.analysis.__init__` defines an '__all__', the PointInCell must be added to that list too, to be "public".  
As Sphinx also respects that, it didn't appear in the docs either.
> Make PointInCell a public member of iris.analysis.

- docs/iris/src/whatsnew/contributions_3.0.0/deprecate_2019-Oct-14_remove_deprecated_future_flags.txt
- lib/iris/__init__.py
- lib/iris/coords.py
- lib/iris/tests/unit/test_Future.py
Removes the deprecated flags from iris.Future (while keeping the skeleton of Future as a template).
This addresses several of the deprecations in #3443.
> deprecated future flags

- lib/iris/tests/unit/lazy_data/test_co_realise_cubes.py
- requirements/core.txt
As per #3356, iris.tests.unit.lazy_data.test_co_realise_cubes no longer tests on versions of dask less than 2. dask>=2 is added as a requirement.
> Drop Dask 1 (tidy up test_co_realise_cubes)

- lib/iris/analysis/__init__.py
- lib/iris/tests/test_analysis.py
Since Iris 2 was introduced all cube data arrays have become MaskedArray type, though by default no mask is set. The fast_percentile_method implemented in analysis uses the test ```isMaskedArray``` to determine if the input cube is masked, which precludes use of the fast percentile method, however this is overly restrictive. The now default MaskedArray type used for cubes does not by default have a mask set (instead it is simply ```mask=False```). If no mask is set, the faster numpy method works fine and remains orders of magnitude faster that the scipy equivalent.
This PR changes the test to use ```np.ma.is_masked``` which differentiates between a MaskedArray with and without an applied mask. This enables the use of the fast_percentile_method once again for most cubes.
Tests have been …
> Analysis percentile method - update applicability test for fast_percentile_method

- docs/iris/src/whatsnew/contributions_3.0.0/deprecate_2019-Oct-14_remove_deprecated_future_flags.txt
- lib/iris/tests/unit/test_Future.py
Emerging from #3459, which I merged prematurely !!
Points I'm intending to address :
1. none of the skipped tests were adding anything anymore, as the generic code looks identical, so I removed them
1. we didn't test the setting of a key option that is not deprecated
1. setting the 'deprecated_options' key in `patched_future` was unsafely modifying the actual Future class.
> Fix for review changes missed

- .travis.yml
- lib/iris/tests/__init__.py
- lib/iris/tests/integration/test_grib2.py
- lib/iris/tests/integration/test_grib_load.py
- lib/iris/tests/test_grib_load_translations.py
- lib/iris/tests/test_grib_save.py
As per #3447, this allows Travis to test all grib tests except the ones currently failing/erroring.
> Have Travis test with iris-grib, remove problem tests

- lib/iris/tests/__init__.py
The [facility to time tests that are run](https://github.com/SciTools/iris/blob/v2.3.0rc0/lib/iris/tests/__init__.py#L944) was broken by changes to introspection in Python 3.
> Fix test timings for Python 3.

- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Oct-14_cf_ancillary_data.txt
- lib/iris/_concatenate.py
- lib/iris/_merge.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/exceptions.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/unit/coords/test_AncillaryVariable.py
- lib/iris/tests/unit/coords/test_CellMeasure.py
- lib/iris/tests/unit/coords/test_Coord.py
- lib/iris/tests/unit/cube/test_Cube.py
This includes the functionality to represent CF Ancillary variables on a cube.
This PR also includes a restructuring of dimensional metadata objects (coords, cell measures and ancillary dataset) in a hope to avoid code duplication.
Below is a rough diagram of the new structure:
> Include AncillaryVariables and restructure Cube metadata.

- lib/iris/tests/integration/test_pickle.py
Locally the grib roundtrip pickle-unpickle fails for me.  I'll wait to see what happens on travis says before I post details.
Extends #2569 to check that we can unpickle.
> TEST: Extends #2569 to unpickle

- lib/iris/coords.py
This simple PR aligns the `iris.coords.AncillaryVariable` doc-string with it's `__init__` formal arguments i.e., use `data` not `values`.
> Fix AncillaryVariable doc-string

- lib/iris/_concatenate.py
- lib/iris/_deprecation.py
- lib/iris/aux_factory.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/fileformats/_structured_array_identification.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/um/_fast_load.py
- lib/iris/tests/__init__.py
- lib/iris/tests/experimental/test_animate.py
- lib/iris/tests/integration/plot/test_colorbar.py
- lib/iris/tests/integration/plot/test_vector_plots.py
- lib/iris/tests/integration/test_pickle.py
- lib/iris/tests/integration/test_regridding.py
- lib/iris/tests/test_coding_standards.py
- lib/iris/tests/test_grib_load_translations.py
- lib/iris/tests/test_hybrid.py
- lib/iris/tests/test_mapping.py
- lib/iris/tests/test_plot.py
- lib/iris/tests/test_quickplot.py
- lib/iris/tests/unit/coords/test_AuxCoord.py
- lib/iris/tests/unit/coords/test_DimCoord.py
- lib/iris/tests/unit/fileformats/um/fast_load/test_FieldCollation.py
- lib/iris/tests/unit/plot/__init__.py
- lib/iris/tests/unit/plot/test_plot.py
- lib/iris/tests/unit/plot/test_scatter.py
- lib/iris/tests/unit/quickplot/test_plot.py
- lib/iris/tests/unit/quickplot/test_scatter.py
- lib/iris/util.py
As requested in #3457, `super` use has been simplified.
> Remove unnecessary super arguments

- lib/iris/_constraints.py
- lib/iris/analysis/__init__.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/fileformats/cf.py
- lib/iris/io/format_picker.py
- lib/iris/iterate.py
- lib/iris/tests/test_merge.py
- lib/iris/tests/unit/analysis/maths/test__output_dtype.py
- lib/iris/tests/unit/analysis/maths/test_divide.py
- lib/iris/util.py
As requested in #3457, Python 2 specific code has been removed.
> Remove python 2 specific code

- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_CellMethod.py
- lib/iris/tests/unit/coords/test_Coord.py
This addresses #3410 by making `__init__` in `Coord` an `abstractmethod`.
> Make Coord abstract

- .github/CONTRIBUTING.md
This PR aligns the URL used to reference the entry point to the `development guide` in the `CONTRIBUTING.md` and the `README.md`.
> Align development guide URLs

- lib/iris/experimental/regrid.py
In _regrid_area_weighted_array:
Move `axes` creation before the main for loop.
`x_dim` and `y_dim` values do not change, thus the axis tuple should remain constant.
Therefore it can be calculated prior to the main computation loop.
> _regrid_area_weighted_array: Axes creation before loop

- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Oct-17_unpin_mpl.txt
This PR is a follow-up to https://github.com/SciTools/iris/pull/3468, and adds a `whatsnew` entry highlighting that our `matplotlib` dependency is now unpinned.
> what's new entry for unpinning mpl

- lib/iris/experimental/regrid.py
This PR tidies `iris.experimental.regrid._refrid_area_weighted_array` to drop legacy code that supported `numpy<1.7`.
Note that, now `iris` has the following `numpy` requirement:
https://github.com/SciTools/iris/blob/77adc28ccb2786f32d09ea8fd25195b065d79b25/requirements/core.txt#L13
> Purge iris.experimental.regrid np<1.7 support

- docs/iris/src/userguide/merge_and_concat.rst
- docs/iris/src/whatsnew/contributions_3.0.0/incompatiblechange_2019-Nov-13_move_experimental_equalise_cubes.txt
- lib/iris/experimental/equalise_cubes.py
- lib/iris/tests/unit/experimental/equalise_cubes/__init__.py
- lib/iris/tests/unit/util/test_equalise_attributes.py
- lib/iris/util.py
This PR moves the `iris.experimental.equalise_cubes.equalise_attributes` function to `iris.util.equalise_attributes`.
Reference #3515
> Move experimental equalise_attributes

- lib/iris/coord_systems.py
- requirements/core.txt
This PR tidies `iris.coord_systems` to drop legacy code that supported `cartopy<0.12`
> Purge cartopy<0.12 support

- lib/iris/tests/unit/coords/test_Coord.py
This PR renames a recent, new unit test class to ensure that `iris.coords.Coord` is abstract.
> Fix unit test_Coord class name

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
> __getitem__ gets ancillary variables

- lib/iris/config.py
This PR raises the minimum bar and commits `iris` to supporting `python` from at least `3.6.0`.
Note that, this PR is also in support of:
- PR #3527 
- PR #3533
both of which incorporate the use of `f-strings`, which were introduced in [python 3.6.0](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals)
In `travis-ci` we currently test `python` at `3.6` and `3.7` (and shortly `3.8` when the ecosystem catches up). We can pin `python` to be `>=3.6` on `conda-forge`... so this PR is really more of a declaration rather than enforcing a minimum requirement i.e., it doesn't make sense to add `python>=3.6` to our `requirements`.
> Support at least python>=3.6

- lib/iris/analysis/maths.py
This PR adopts the use of `functools.lru_cache` instead of our own memoize approach for maths operation `dtype` caching.
> Use functools.lru_cache for maths dtype caching

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
This pull request currently shows an approach to solving #3529 which, while failed, I think is still instructive.
I tried comparing `_ancillary_variables_and_dims` and `_cell_measures_and_dims` in a way which would ignore their order as lists. This first attempt involved simply turning these lists into sets. This failed because the objects inside the lists are not viable elements of a set.
One idea I am coming around to, if such a comparison is deemed necessary, is to use the code in this function: https://github.com/SciTools/iris/blob/a05424137f1f19c26b815c104808f4f563f88812/lib/iris/analysis/__init__.py#L189 perhaps creating a generic version which compares generic aspects of a cube, then having `coord_comparison` and something like `ancil_comparison` wrap this generic function. I'm …
> Fix equality

- .gitignore
This PR includes the `.ipynb_checkpoints` directory in the `.gitignore`.
> Update .gitignore for .ipynb_checkpoints

- lib/iris/coords.py
- lib/iris/tests/unit/coords/test_AncillaryVariable.py
- lib/iris/tests/unit/coords/test_CellMeasure.py
- lib/iris/tests/unit/coords/test_Coord.py
The idea of this is to enable writing code that handles _DimensionalMetadata objects in a generic way.
For example, it will avoid the need for [the extra method keyword here](https://github.com/SciTools/iris/blob/c0c715849602f2d98c7b23f5f2f36304389a6989/lib/iris/fileformats/netcdf.py#L1695).
> Generic 'cube_dims' function for all _DimensionMetadata objects.

- docs/iris/src/whatsnew/contributions_3.0.0/bugfix_2019-Nov-19_cell_measure_copy_loss.txt
- lib/iris/analysis/__init__.py
- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
> Fix copy to include Ancillary variables and Cell measures

- docs/iris/src/userguide/loading_iris_cubes.rst
- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Oct-15_nameconstraint.txt
- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Oct-15_names_property.txt
- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Oct-15_relaxed_name_loading.txt
- lib/iris/__init__.py
- lib/iris/_constraints.py
- lib/iris/_cube_coord_common.py
- lib/iris/tests/test_constraints.py
- lib/iris/tests/unit/constraints/__init__.py
- lib/iris/tests/unit/constraints/test_NameConstraint.py
- lib/iris/tests/unit/cube_coord_common/test_CFVariableMixin.py
This PR introduces the `names` property to both cubes and coordinates - a property that returns a tuple of the `standard_name`, `long_name`, `var_name` and `STASH`.
This property is needed as a means to support more flexible `name` loading i.e., a `iris._constraints.Constraint._coordless_match` that will succeed for a match on either of the `names` property values, rather than depending on the behaviour of the `iris._cube_coord_common.CFVariableMixin.name` method. Note that, this also applies to `iris.cube.Cube.extract` and `iris.cube.CubeList.extract` et al.
This PR also introduces the `iris.NameConstraint` for more specific control of `names` related matching.
----
Closes #3407
> Add NameConstraint with relaxed name loading

- docs/iris/src/whatsnew/contributions_3.0.0/incompatiblechange_2019-Nov-26_remove_coord_comparison.txt
- lib/iris/analysis/__init__.py
- lib/iris/analysis/calculus.py
- lib/iris/analysis/maths.py
- lib/iris/cube.py
- lib/iris/tests/test_analysis.py
- lib/iris/tests/test_cdm.py
Replaces #3558 
Following discussions there, I'm proposing to *remove* the original, public 'coord_comparison' function.  Replaced with an augmented, private version for internal use only.
In offline discussions with @bjlittle @lbdreyer , we agreed this was always rather over-complicated and under-explained for a user public method.  Plus, the key `_CoordGroup` class it relies on was always private anyway.
Since it was practically impossible to understand or use with confidence, without also reading the sourcecode, we decided to simply retire it rather than providing an enhanced public function (or functions).
> Remove 'iris.analysis.coord_comparison' from public API.

- lib/iris/fileformats/netcdf.py
- lib/iris/tests/results/netcdf/TestNetCDFSave__ancillaries/aliases.cdl
- lib/iris/tests/results/netcdf/TestNetCDFSave__ancillaries/fulldims.cdl
- lib/iris/tests/results/netcdf/TestNetCDFSave__ancillaries/multiple.cdl
- lib/iris/tests/results/netcdf/TestNetCDFSave__ancillaries/partialdims.cdl
- lib/iris/tests/results/netcdf/TestNetCDFSave__ancillaries/shared.cdl
- lib/iris/tests/test_netcdf.py
Saving ancillary variables, with some testcases based on CDL comparisons.
~There is some unfinished business here where the tests might be improved,~
~if and when they can use other aspects of ancillary support :~
**UPDATE:**
FIxed that.
Nearly good to go?
> PI-3473: Netcdf saving of ancillary variables

- lib/iris/experimental/regrid.py
Move the indices variable nearer to its use within the main code, making it easier to read
> _regrid_area_weighted_array:  move indices variables

- tools/gen_translations.py
Came across a license header that needed updating now that both iris and iris-grib have simplified their license headers
> Update license header in translation tool

- lib/iris/experimental/regrid.py
Reorder some of the variables to be nearer their use in the code.
This is preparatory work for refactoring weighting calculations.
> Tweak area weighting regrid: reorder variables

- .travis.yml
This intends to re-instate automatic docs build for the Github branches
Closes #3542
I think this is now correct.
I have left in a debug line that echoes the control variables, including the 'ORG' organisation identity (from the Travis SLUG), as I think this is generally useful to see in the logs.
> Fix problems with export and echo command.

- .travis.yml
Replaces #3578, where tests where failing for unknown reasons. 
Hopefully spurious ones..
> Pushdocs fix2

- lib/iris/experimental/regrid.py
- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py
Optimise the averaging in the _regrid_area_weighted_array.
This is achieved by refactoring the weights calculation, collating the data and the weights in a single array, then finally computing the weighted mean as a whole-array-manipulation.
Calculating the weights first is necessary because the size (i.e. number of elements) of the weights and source data region varies per target grid point. In order to record all the values in a single array, the maximum size of the weights array needs to be established, so the single array can be setup. Therefore we first computing the weights and record the maximum weight-array size, hence we have refactored the weights calculation too.
> PI-2472: Tweak area weighting regrid move averaging out of loop

- lib/iris/experimental/regrid.py
This pull request refactors the contents of [regrid_area_weighted_rectilinear_src_and_grid](https://github.com/ehogan/iris/blob/refactor_regrid_area_weighted/lib/iris/experimental/regrid.py#L738). Tests for the `__prepare` and `__perform` functions will be considered in a future pull request related to updating [AreaWeightedRegridder ](https://github.com/ehogan/iris/blob/refactor_regrid_area_weighted/lib/iris/analysis/_area_weighted.py#L14).
> Split regrid_area_weighted_rectilinear_src_and_grid into prepare and perform

- docs/iris/src/whatsnew/contributions_3.0.0/bugfix_2019-Nov-21_cell_measure_attributes.txt
- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Nov-21_netcdf_ancillary_data.txt
Covers changes from #3550 and #3556
**NOTE: why this targets the 'launch_ancils' feature branch** 
We are still reserving the right to ***not*** announce ancillary variables in Iris 3.0, in which case this will be deferred from merging to master :  see [comment here](https://github.com/SciTools/iris/pull/3556#issue-343470988).
> PI-3473: Whatsnews relating to ancillary load + save.

- docs/iris/src/whatsnew/contributions_3.0.0/bugfix_2019-Dec-02_cell_measure_concatenate.txt
- lib/iris/_concatenate.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/tests/integration/concatenate/test_concatenate.py
- lib/iris/tests/test_concatenate.py
- lib/iris/tests/unit/concatenate/test_concatenate.py
Addresses the concatenate half of #3552.
> PI-3552: Add concatenate support for Ancilary Variables and Cell Measures

- lib/iris/tests/unit/analysis/area_weighted/test_AreaWeightedRegridder.py
This pull requests adds some tests for [AreaWeightedRegridder](https://github.com/ehogan/iris/blob/area_weighted_regridder_test/lib/iris/analysis/_area_weighted.py#L14).
The `test_multiple_src_on_same_grid` test creates two source cubes on the same grid with different values. One of the sources cubes is used to instantiate `AreaWeightedRegridder`, then both source cubes are regridded. This test will ensure the regridding still works as expected once the refactoring (including caching the weights) is complete.
> Test for AreaWeightedRegridder

- lib/iris/_merge.py
- lib/iris/tests/test_merge.py
Addresses half of #3552. Now `merge` treats Ancillary Variables the same as Cell Measures.
> PI-3473: Add Ancillary Variable support to merge

- lib/iris/cube.py
An attempt to explain how merge + concatenate are affected by dimensional metadata (aux-coords, cell-measures and ancillary-vars).
NOTE: I thought about targetting the 'launch_ancils' feature branch instead, but I don't think the descriptions get in the way of releasing _without_ ancils if we need to :  The changes have been made (on master) + it all applies equally to aux-coords and cell-measures.
> Explain merge+concat behaviour with dimensional metadata.

- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/tests/results/unit/cube/Cube/xml/ancils.cml
- lib/iris/tests/results/unit/cube/Cube/xml/cell_measures.cml
- lib/iris/tests/unit/cube/test_Cube.py
Add cell-measures and ancillary-variables sections to cube xml reprs.
Pretty simple, but should do the job.
> Cube-xml for cell measures and ancils.

- lib/iris/analysis/_area_weighted.py
- lib/iris/analysis/_regrid.py
- lib/iris/tests/unit/analysis/area_weighted/test_AreaWeightedRegridder.py
This pull request refactors `AreaWeightedRegridder` to call the relevant `__prepare` and `__perform` functions.
I've not come across `mock.sentinel` before, so I've had to comment out one assert that I can't get to work.
> PI-2472: Refactor AreaWeightedRegridder

- lib/iris/experimental/regrid.py
This pull request moves the calculation of the area weights from `__perform` to `__prepare`.
> Move calculation of area weights from perform to prepare

- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Dec-20_cache_area_weights.txt
- lib/iris/experimental/regrid.py
This pull request adds a docstring and a what's new for the area weighted regridding work.
> Add docstring and what's new

- lib/iris/analysis/stats.py
This addresses the concern which is the **last remaining unticked todo in #3554**.
We are currently still uncertain what the exact behaviour of cube arithmetic will be in Iris 3.0.
In the absence of #3478, we have currently [enabled `cube.copy()` to replicate cell measures](), which means that certain operations no longer discard cell measures (or ancillaries).
This creates possible problems for some existing user code, and some internal code including this `pearsonr` routine.
In principle, #3618 will also fix this problem, but we may yet choose #3478 over that and we're not yet sure exactly what that will do.
So this change is a definite resolution of this small problem, irrespective of what we eventually choose to do about cube arithmetic generally.
> Fix cube-arith possible problem in  'pearsonr'.

- lib/iris/experimental/regrid.py
This pull request removed unused variables after moving the weights calculation from `__perform` to `__prepare`.
> Remove unused variables in regridding code

- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_aux_factory.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_cube.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_auxiliary_coordinate.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_dimension_coordinate.py
During work on #3556, it became clear to me that the use of `engine.provides` within the pyke rules, and in a few places within `iris.fileformats.netcdf` is confusing :  Because this term collides with the special reserved meaning of "provides" within Pyke rules, as seen in the repeated usage of `facts_cf.provides(..)` in most of our Pyke rules.
In fact, although `engine` is a Pyke object,  `engine.provides` is just a monkey-patched additional property attached by our netcdf code, to keep track of cube component objects created during rules evaluation (coordinates, cell-measures and ancillaries).
So, this PR just renames it to something less confusing. 
This should produce **no functional change.**
> PI-3473 Rename "engine.provides"

- lib/iris/analysis/_regrid.py
- lib/iris/tests/unit/analysis/area_weighted/test_AreaWeightedRegridder.py
This pull request fixes the issue originally reported via [#3606](https://github.com/SciTools/iris/pull/3606#issuecomment-567450435).
When regridding a source cube that was used to create the regridder, the comparisons performed in `copy_coords` using `is` are True. However, when regridding a source cube that was not used to create the regridder, the comparisons are False, leading to cubes that have `latitude` and `longitude` coordinates without names (see [test failure for 6f2dcda](https://travis-ci.org/SciTools/iris/builds/628723295)).
The solution is the one proposed in [#3606](https://github.com/SciTools/iris/pull/3606#issuecomment-567450435).
> PI-2472: Fix issue related to comparison / equality in regridding code

- lib/iris/analysis/_area_weighted.py
- lib/iris/tests/unit/analysis/area_weighted/test_AreaWeightedRegridder.py
Alter the area-weighted regridder to accept multidimensional src cubes (i.e. data other than 2D lat-lon data.), identifying the x-y coordinates corresponding to src grid.
Update the regridder to only cache the vital regridding information (i.e. target grid info and the weights information.
Fix bug in the tests so that the prepare and perform functions are called sequentially.
Update "test_mismatched_data_dims" to accept multidimensional data, with dimensions in differing orders.
> PI-2472:  Update area weighted regridder to accept different dim data

- requirements/test.txt
Discovered in course of #3628 that graphics tests have broken.
Explained here : https://github.com/SciTools/test-iris-imagehash/issues/28
> Pin pillow to make graphics tests work again.

- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Dec-20_cache_area_weights.txt
- lib/iris/analysis/_area_weighted.py
- lib/iris/analysis/_regrid.py
- lib/iris/experimental/regrid.py
- lib/iris/tests/unit/analysis/area_weighted/test_AreaWeightedRegridder.py
This pull requests is for the regridding feature branch :) :tada:
> PI-2472: Area weighted regridding

- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2020-Jan-06_relax_geostationary.txt
- lib/iris/coord_systems.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_geostationary_coordinate_system.py
Closes #3626 
Targetting master for now, although this *may* be redirected to Iris 2.4 if we choose to go down that route.
> Allow some 'key=None' args in Geostationary creation.

- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py
- lib/iris/tests/unit/analysis/cartography/test_project.py
Inputting non-int `num` arguments for [numpy.linspace](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) has been [deprecated since Numpy v1.12](https://github.com/numpy/numpy/pull/7328).
Support has now been [entirely removed](https://github.com/numpy/numpy/pull/14620), and a few of Iris' tests were deliberately leaning on Numpy's attempted `int()` conversion. These tests have been fixed.
> Removed non-int arguments for linspace num parameter

- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py
- lib/iris/tests/unit/analysis/cartography/test_project.py
Inputting non-int `num` arguments for [numpy.linspace](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) has been [deprecated since Numpy v1.12](https://github.com/numpy/numpy/pull/7328).
Support has now been [entirely removed](https://github.com/numpy/numpy/pull/14620), and a few of Iris' tests were deliberately leaning on Numpy's attempted `int()` conversion. These tests have been fixed.
> (v2.4) Removed non-int arguments for linspace num parameter

- lib/iris/tests/system_test.py
The patch which this tests is long since gone.
From a ticket on our very old pre-github FCM project ...
```
From: Daniel Varela Santoalla [mailto:dvarela@ecmwf.int] 
Sent: 02 March 2012 17:40
To: Blay, Byron; Green, Thomas
Cc: Hodkinson, Mark; software support; advisory
Subject: Re: GRIB API bug (ref SUP-87)
Hi Byron and Thomas
This bug in the python interface was fixed some time ago and will be included
in the next release, 1.9.14, which will be released very soon. However, if you
are in an urgent need of a solution you could apply the following patch.
Index: python/grib_interface.c
===================================================================
diff -u -N -r51092 -r60810
--- python/grib_interface.c	(.../grib_interface.c)	(revision 51092)
+++ python/grib_interface.c …
```
> Remove obsolete test.

- lib/iris/tests/integration/test_grib_load.py
The latest Iris-GRIB explicity only supports the standard scanning mode configuration - that's `00000000` in the [scanning mode octet](https://apps.ecmwf.int/codes/grib/format/grib2/ftables/3/4). See [this code section](https://github.com/SciTools/iris-grib/blob/2206a46e64250a0a5e1ae4ec63075b5b558d03bb/iris_grib/message.py#L140) for the relevant check.
`tests.integration.test_grib_load.test_y_fastest` is therefore inappropriate since this needs a scanning mode octet of `00100000`. `test_y_fastest` should therefore be removed.
> Remove y_fastest Iris-GRIB test

- docs/iris/src/whatsnew/2.4.rst
- docs/iris/src/whatsnew/contributions_2.4.0/bugfix_2020-Feb-14_pp_emptyslices.txt
- docs/iris/src/whatsnew/index.rst
- lib/iris/fileformats/pp.py
- lib/iris/tests/unit/fileformats/pp/test_PPDataProxy.py
- lib/iris/util.py
Effectively a v2.4.0 mergeback.
This cherry-picks 2 commits from the 2.4.x branch.
Plus one extra commit to include the 2.4.0 whatsnew in the full-whatsnew-list.
> 2v4 mergeback picks

- docs/iris/src/userguide/subsetting_a_cube.rst
- docs/iris/src/whatsnew/contributions_3.0.0/bugfix_2020-Feb-13_cube_iter_remove.txt
- lib/iris/cube.py
- lib/iris/tests/test_cdm.py
- lib/iris/tests/unit/cube/test_CubeList.py
This change has been discussed with @lbdreyer. A TypeError with a useful message is still raised by Python if a Cube is iterated over but `isinstance(cube, collections.Iterable)` now behaves as would be expected. This behaviour is documented in https://docs.python.org/3/reference/datamodel.html#special-method-names.
> Remove cube iter

- asv.conf.json
Without this, airspeed velocity is unable to pip uninstall iris after benchmarking a commit, resulting in the same commit being benchmarked repeatedly under the names of previous commits.
Appropriate for merging once we are satisfied that the performance issues related to Dask v2.0 are addressed (e.g. #3659).
> Fixed asv project name to 'scitools-iris'.

- lib/iris/tests/integration/test_pickle.py
Companion to https://github.com/SciTools/iris-grib/pull/201
> Removed grib-specific test to iris-grib.

- lib/iris/coord_categorisation.py
[cftime PR 135](https://github.com/Unidata/cftime/pull/135) has now been released ([see v1.1.0 in the changelog](https://github.com/Unidata/cftime/blob/master/Changelog)), meaning that datetimes are `cftime.datetime` by default, instead of `datetime.datetime`.
This means that the datetimes Iris uses no longer have the `weekday()` method, but instead have the `dayofwk` attribute.
Have therefore adjusted the 3 methods that were using `weekday()` to use `dayofwk`.
Note that this will not currently pass Travis CI while #3682 remains open (which is pending some other fixes to get Travis to pass).
> Update add_weekday for latest cftime

- lib/iris/tests/results/imagerepo.json
Fixes iris.test.test_plot.TestSymbols.test_cloud_cover 
failing since matplotlib 3.2.0.
See Travis error log [here](https://travis-ci.org/SciTools/iris/jobs/658323696)
Presumably due to [this change noted in mpl whatsnew](https://matplotlib.org/3.2.0/users/whats_new.html#kerning-adjustments-now-use-correct-values)
> New image hashes for mpl 3x2

- docs/iris/src/developers_guide/graphics_tests.rst
- docs/iris/src/developers_guide/tests.rst
Hoping this is worth it, and that this actually is an improvement ..
I *think* this is needed, as I had to work out the fix process for myself, yet again, in course of #3682.
> Correct and improve dev-guide section on fixing graphics-tests.

- lib/iris/tests/__init__.py
Define a skipper for tests broken in the NG-VAT POC.
I.E. stuff that we accept is broken, but won't fix for now.
This helps us to keep automated testing functional, and also marks the technical debt of things we might still need to fix.
> Skip ngvat

- docs/iris/src/whatsnew/contributions_3.0.0/docchange_2020-Apr-03_extract_clarification.txt
- lib/iris/cube.py
This originated from a support query. The user was using cubelist.extract_strict() with a single constraint and was confused why this was returning a *cube* rather than a *cubelist*. The pertinent lines are these: 
https://github.com/SciTools/iris/blob/cbfbbb2ba9a8aff046b20e46d56810d34d6a1d11/lib/iris/cube.py#L324-L325
I think we need to highlight the fact that using strict=True and one constraint returns a single cube.
> Update docs CubeList.extract method

- docs/iris/src/whatsnew/contributions_3.0.0/docchange_2020-Apr-03_extract_clarification.txt
- docs/iris/src/whatsnew/contributions_3.0.0/incompatiblechange_2020-May-22_cubelist_extract_cubes.txt
- lib/iris/_constraints.py
- lib/iris/cube.py
- lib/iris/tests/test_constraints.py
- lib/iris/tests/test_merge.py
- lib/iris/tests/unit/cube/test_CubeList.py
Replace "cubelist.extract(..., strict=True)" and the equivalent "cubelist.extract_strict(...)" with a newer-style API.
Closes #3695
As noted there, this is more in keeping with other facilities, and also addresses the slightly quirky return-type behaviour of the old style :  The old method would return a cubelist for 0 or 2..N constraints/results, but just a cube for exactly one constraint.
> Cubelist extract strict

- docs/iris/src/whatsnew/contributions_3.0.0/incompatiblechange_2020-May-15_change_default_unit_loading.txt
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/tests/results/netcdf/int64_auxiliary_coord_netcdf3.cml
- lib/iris/tests/results/netcdf/int64_dimension_coord_netcdf3.cml
- lib/iris/tests/results/netcdf/netcdf_cell_methods.cml
- lib/iris/tests/results/netcdf/netcdf_global_xyzt_gems.cml
- lib/iris/tests/results/netcdf/netcdf_global_xyzt_gems_iter_0.cml
- lib/iris/tests/results/netcdf/netcdf_global_xyzt_gems_iter_1.cml
- lib/iris/tests/results/netcdf/uint32_auxiliary_coord_netcdf3.cml
- lib/iris/tests/results/netcdf/uint32_dimension_coord_netcdf3.cml
- lib/iris/tests/results/usecases/pp_to_cf_conversion/from_netcdf/002000000000.44.101.131200.1920.09.01.00.00.b_0.cml
- lib/iris/tests/results/usecases/pp_to_cf_conversion/from_netcdf/008000000000.44.101.000128.1890.09.01.00.00.b_0.cml
- lib/iris/tests/results/usecases/pp_to_cf_conversion/from_netcdf/st0fc699.b_0.cml
- lib/iris/tests/results/usecases/pp_to_cf_conversion/from_netcdf/st0fc942.b_0.cml
- lib/iris/tests/test_netcdf.py
The same as #3705 except it is targeting a branch specifically for changes to default units. Because of this, the test is changed to no longer require the loading of ancillary variables.
> Change default loading unit from "1" to "unknown" (correct branch)

- lib/iris/fileformats/netcdf.py
- lib/iris/tests/results/netcdf/netcdf_save_no_name.cdl
> Unify saving behaviour of "unknown" and "no_unit"

- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Dec-20_cache_area_weights.txt
As re-written for [iris 2.4](#3638), in [this commit](https://github.com/SciTools/iris/pull/3638/commits/8849a7556192c1512efa1c13f66efbb40432bff6)
> PI-2370: Improved text for whatsnew on cached area-weights

- lib/iris/_cube_coord_common.py
- lib/iris/tests/unit/cube_coord_common/test_get_valid_standard_name.py
The regex in `get_valid_standard_name` was an overkill as the function was already checking the values against a list that contained all the possible values.
This pull request replaces it with a simple split and fixes the bug that was making iris not to accept `atmosphere_optical_thickness_due_to_pm1_ambient_aerosol` as a valid standard_name
Fixes #3677
> PI-3677: Remove regex from standard names check

- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/results/netcdf/netcdf_save_no_name.cdl
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_auxiliary_coordinate.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_cube_metadata.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_dimension_coordinate.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_get_attr_units.py
- requirements/core.txt
- requirements/test.txt
Addresses #3474. Anything loaded from netCDF with a flag attribute (some attribute wich is either `flag_values`, `flag_masks` or `flag_meanings`) is explicitly given a unit of `"no_unit"` in iris. Anything in iris with a unit of `"no_unit"` is now saved to netCDF without units. This also addresses #3394.
> PI:3358 (WIP) Ensure flags load/save without units

- lib/iris/fileformats/nimrod_load_rules.py
This should fix one of the failing tests in #3731 which would change the behaviour of nimrod loading due to a change in default units upon coord creation.
> Explicitly set coords in nimrod load to have units "1"

- lib/iris/fileformats/nimrod_load_rules.py
Adds rounding to nearest-second to forecast_reference_time coord generation.
> Nimrod loader: Fix bug in forecast_reference_time

- requirements/core.txt
This PR temporarily pins back `cftime`, which is causing some unit test failures due to its most recent release, moving from `v1.1.3` to `v1.2.0`, see the [Unidata/cftime changelog](https://github.com/Unidata/cftime/blob/master/Changelog).
The following `iris.tests.unit.fileformats.pp_load_rules.test__epoch_date_hours.TestEpochHours__gregorian` unit tests fail, all of which deal with our workaround for handling dates with a year of `0` (pretty much), and all of which are now 48hrs out using `v1.2.0` of `cftime` :confused::
- `test_year_0`
- `test_ymd_0_0_0`
- `test_ymd_preserves_timeofday`
- `test_ymd_1_1_1`
> pin cftime

- lib/iris/fileformats/pp_load_rules.py
- requirements/core.txt
As mentioned in #3757, there is a test currently failing due to a number being rounded to an `int` rather than a `float`. It turns out this is not due to a change in cftime as previously thought, but due to a [change in numpy](https://numpy.org/doc/stable/release/1.19.0-notes.html#change-output-of-round-on-scalars-to-be-consistent-with-python).
Matplotlib is also being pinned here to get a separate test to pass.
> Numpy rounding fix

- .flake8
- docs/iris/gallery_tests/gallerytest_util.py
- lib/iris/_concatenate.py
- lib/iris/analysis/_area_weighted.py
- lib/iris/analysis/_regrid.py
- lib/iris/fileformats/name_loaders.py
- lib/iris/fileformats/nimrod_load_rules.py
- lib/iris/tests/unit/coords/test_CellMethod.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_auxiliary_coordinate.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_mercator_coordinate_system.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_stereographic_coordinate_system.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_has_supported_mercator_parameters.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_has_supported_stereographic_parameters.py
This PR forces `flake8` compliance on some outstanding files.
> flake8 outstanding files

- requirements/core.txt
> Unpin cftime

- ci/requirements/readthedocs.yml
Temp fix for the read the docs build to pass.
Once merged the build should pass, see https://readthedocs.org/projects/scitools-iris/builds/
Relates to #3760
> pin matplotlib<3.3 for readthedocs conda

- lib/iris/fileformats/cf.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/test_cf.py
- lib/iris/tests/unit/fileformats/cf/test_CFReader.py
**Replaces #3767** 
This PR adds flexibility to the CFReader so that variable names can be specified for exclusion.
Also refactors so that the dataset must be extracted from a file before passing to CFReader, which will allow more efficient code in situations where the excluded var names are being read by opening the file ahead of instantiating CFReader.
(initial purpose is to enable an adapted CF reader in SciTools-incubator/iris-ugrid#4)
> Allow CFReader to exclude given variables

- .readthedocs.yml
- docs/iris/Makefile
- docs/iris/src/conf.py
**Enabled the pdf creation on** the Read The Docs (RTD) service.
Note that we cannot create a pdf locally as RTD does some magic to do this.  We should not need to as the PDF is based upon the same source as the built html, which we can build locally to check.
Every time RTD creates a new version of the html it should also create a PDF one too.
This PR also covers:
- Fixing indention on a Makefile for pdf creation (not used at this time) - could be removed
- Purging all latex/man options in the **conf.py**
When his PR is merged if you view the documentation via https://scitools-iris.readthedocs.io/en/latest/, if you click on the **current version at the bottom of the sidebar** you will have an option to view the PDF for the active version.
> enabled pdf creation

- docs/iris/src/whatsnew/latest.rst
Looks like the retired **contributions_3.0.0.** folder had some old what's new entries in it meaning the **latest.rst** had entries that are also present in **v2.4**.
This PR removes the duplicate entries.
> remove duplicate whats new entries from the lastest/unreleased notes

- lib/iris/fileformats/cf.py
- lib/iris/fileformats/netcdf.py
**WIP**
still needs some tests for the new functionality.
Some extra refactoring to make `iris.fileformats.netcdf.load_cubes` and `iris.fileformats.cf.CFReader` work with the new separated code in https://github.com/SciTools-incubator/iris-ugrid
> Netcdf loader controls to support iris-ugrid.

- lib/iris/__init__.py
Label the "ugrid" feature branch with a custom version string.
This string is chosen to suit the forthcoming "iris-ugrid regrid demo" which we want to build, as we want to include a version of the iris branch in that
> Ugrid version

- docs/iris/src/whatsnew/2.3.rst
Used the **:ref:** syntax for linking to the documentation and the full **url** for the iris logo in github.
> Correct links in docs

- .travis.yml
This is not a bug, only a typo.
I believe the "**- >**" is used to show a collapsable output section on travis.
> Fixed typo

- lib/iris/etc/logging.yaml
This PR explicitly sets the `logging` level of third party dependencies that are causing `DEBUG` noise in `travis-ci`.
There may be another way of doing this, but this seems like a reasonable initial approach for now...
> set third party default logging level

- docs/iris/src/whatsnew/contributions_3.0.0/bugfix_2019-Nov-21_cell_measure_attributes.txt
- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Nov-21_netcdf_ancillary_data.txt
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_aux_factory.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_cube.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_auxiliary_coordinate.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_cube_metadata.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_dimension_coordinate.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_get_attr_units.py
Updating the `launch_ancils` feature branch to latest master (42a1964)
(Merged using the "Commit merge" to preserve the original)
Contributes to #3473
> [FB] launch_ancils:  Update merge-base to commit 42a1964

- lib/iris/fileformats/_ff.py
- lib/iris/tests/unit/fileformats/ff/test_FF2PP.py
Recently noticed that fieldsfile loading was causing a bottleneck in our iris usage with iris running under python3, profiling seemed to show that half of our runtime was being spent in parsing fieldsfile headers. With `numpy.fromfile` being the main sink of time within the loading path (Seems to be a more widely noted issue for python3 versions of numpy, https://github.com/numpy/numpy/issues/13319),
Created a rough timing script to show for some basic timing loading a specific field from a file 1000 times:
```python
import iris
import time
import os
f_size = os.path.getsize('big_fields_file')
print(f"File 'big_fields_file size': {f_size/1024**3:.2f}GB")
total_time = 0
count = 1000
for i in range(count):
if i % 100 == 0:
print(f'Run: {i}')
s_time = time.time()
cube = …
```
> Modify parsing of ff headers to avoid numpy.fromfile.
