SciTools/iris

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
See https://github.com/SciTools/iris/pull/1495
> Rolling window kwargs v1.7.x

- INSTALL
Add Conda instructions as primary installation mechanism
> Add conda to install instructions

- .travis.yml
- INSTALL
- conda-requirements.txt
> BLD: Updated biggus requirements in INSTALL

- lib/iris/fileformats/grib/_grib_cf_map.py
Adds a new grib to cf mapping following on from https://github.com/metarelate/metOcean/pull/38 being merged. This addresses part of https://github.com/SciTools/scitools.org.uk/issues/98
> new grib mapping from metarelate

- lib/iris/analysis/cartography.py
- lib/iris/tests/unit/analysis/cartography/test_area_weights.py
This PR checks the coordinate units before attempting the conversion to radians. I've not added tests as I'm unsure.
> added radians test to cartopgraphy

- lib/iris/io/__init__.py
Replacement for #1542 that targets 1.7.x
> Fix netcdf load on windows

- docs/iris/src/userguide/interpolation_and_regridding.rst
Updates the userguide chapter "Cube regridding and interpolation". This PR improves only the section on regrid; for the improvements to the interpolation section see #1548. The changes include adding a sub-section on caching a regridder for repeated use and other general changes.
> Update userguide regrid section

- lib/iris/io/__init__.py
- setup.py
@esc24 care to do the honours?
> Merge v.1.7.x onto master

- lib/iris/fileformats/grib/load_rules.py
deprecation warning for use of not_strict GRIB loading
> deprecate grib

- lib/iris/util.py
This PR should fix #1339 and #1568.
> Fix #1339 (Win64 np.int64 slices)

- conda-requirements.txt
- lib/iris/tests/unit/util/test_column_slices_generator.py
- lib/iris/util.py
> Backport of win64 np.int64 slices fix

- lib/iris/tests/unit/util/test_column_slices_generator.py
> Tests for win64 fix

- lib/iris/fileformats/name_loaders.py
- lib/iris/tests/unit/fileformats/name_loaders/test_generate_cubes.py
Small tweak to make extracted data plot with no gap at the meridian.
> Adjusted NAME loader to recognise circular longitudes.

- docs/iris/src/whatsnew/1.8.rst
- lib/iris/_concatenate.py
- lib/iris/tests/unit/concatenate/test_concatenate.py
Concatenate now supports deferred data (and a mixture of loaded and unloaded data).
> Made use of biggus in iris._concatenate

- docs/iris/src/_templates/index.html
- docs/iris/src/whatsnew/1.7.rst
- docs/iris/src/whatsnew/1.8.rst
- docs/iris/src/whatsnew/index.rst
Minor update to include new feature from #1567
> Added new feature for whatsnew 1.8

- docs/iris/src/whatsnew/1.7.rst
- lib/iris/__init__.py
A replacement for #1581 (as @pelson is mostly out of contact at the moment).
> v1.7.4rc1 what's new

- docs/iris/src/whatsnew/1.8.rst
Updates to the what's new document for Iris v1.8.0 including a showcase sub-section at the top of the features section of the document.
While this might be my commit, the work here is really only a tidy of the sterling work that @lbdreyer (#1578) and @bjlittle (#1580) first undertook.
> What' s new 1.8 updates

- lib/iris/tests/unit/fileformats/pp/test__create_field_data.py
Fixes the first problem in https://github.com/SciTools/biggus/issues/135.
> Used concrete sized in shape for PP data proxy.

- lib/iris/_merge.py
- lib/iris/aux_factory.py
- lib/iris/coords.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/tests/integration/test_aggregated_cube.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/unit/aux_factory/test_AuxCoordFactory.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_auxiliary_coordinate.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_dimension_coordinate.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_reorder_bounds_data.py
Another episode in the continuing saga of #1287 (previous episodes: #1290, #1291, and #1502).
> Lazy dtype update (again)

- lib/iris/aux_factory.py
Fixes #1593 - @ocefpaf can you confirm?
> Ensure nsigma_slice is a tuple.

- lib/iris/__init__.py
* cherry-picked master 02cdf3ede687b829cbe964c2132266983c71340e
> Bump the version for the release candidate.

- docs/iris/src/developers_guide/documenting/index.rst
- docs/iris/src/developers_guide/documenting/whats_new_contributions.rst
- docs/iris/src/whatsnew/1.8contributions/ncstreaming.txt
- docs/iris/src/whatsnew/aggregate_directory.py
- docs/iris/src/whatsnew/contributions_1.9/docchange_2015-03-19_whats-new-aggregator.txt
Good morning,
This is a very-rough first pass of the whatsnew aggregator for discussion and review of logic. There's a lot of formatting (both of my code and the output) changes needed, and a few inefficiencies to fix if the logic is useable.
The documentation is also very 'minimalist' for now, again I didn't want to spend too much time working on this if it's liable to change significantly.
Feedback welcome!
> Whats new aggregator

- lib/iris/fileformats/grib/_save_rules.py
- lib/iris/tests/unit/fileformats/grib/save_rules/test_identification.py
handle type of processed data for GRIB export
> Grib processed data

- docs/iris/src/whatsnew/1.8.rst
document move of expereimental functionality in what's new
> regrid move

- lib/iris/cube.py
See Unidata/netcdf4-python#385 for context.
> Add Cube.__orthogonal_indexing__

- lib/iris/unit.py
Fix #165
PS: This fix  is already in `cf_units` :wink:
> Catch up with upstream changes in netcdftime

- conda-requirements.txt
- docs/iris/src/sphinxext/custom_data_autodoc.py
See why here : https://bitbucket.org/bwanamarko/sphinxcontrib-matlabdomain/issue/34/cannot-import-safe_repr#comment-16878658
Hopefully this fixes, but of course there may be more problems awaiting ...
> Fix problem and remove Sphinx version limitation.

- lib/iris/tests/integration/test_FieldsFileVariant.py
- lib/iris/tests/unit/experimental/um/test_FieldsFileVariant.py
> mo_unpack test skip

- lib/iris/analysis/_regrid.py
- lib/iris/analysis/_scipy_interpolate.py
Some proof-of-concept work on faster linear interpolation.
NB. This is targeting the "decoupler" branch, which is a *temporary* branch for testing out a bunch of extensions, hacks, etc. The ones which turn out to be useful will be polished up and applied to master as usual.
> Fast interpolation

- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_get_attr_units.py
Hi all,
This is a copy of my change against Master (#1653) regarding an exception on loading a cube with unicode data in Units.
Targetting 1.8.x.
Cheers,
Gray
> Netcdf unicode 1.8.1

- lib/iris/__init__.py
1.8.1rc1
please may I have a tag following this commit?
> release candidate 1

- .travis.yml
Should start faster, and have better specs too. (See [here](http://docs.travis-ci.com/user/workers/container-based-infrastructure/).)
> Enable Travis' container based builds.

- lib/iris/io/__init__.py
'Backport' from #1683. @pelson, please could you merge?
> Added warning about data loss from overwriting a source file.

- lib/iris/analysis/_scipy_interpolate.py
Fix to allow sparse matrix interpolation over fewer dimensions than the data ndims.
> Sparse interpolation over sub-ndims.

- docs/iris/src/whatsnew/contributions_1.9/newfeature_2015-06-24_weighted_percentile.txt
What's new entry for iris.analysis.WPERCENTILE
Follows PR #1704
> Weighted percentile what's new

- docs/iris/src/whatsnew/contributions_1.9/bugfix_2015-04-08_um_fieldsfiles_large_lookups_.txt
- docs/iris/src/whatsnew/contributions_1.9/newfeature_2015-04-16_read-closed-um-fieldsfiles.txt
Couple of odd extras I noticed didn't get a whatsnew entry.
Was looking there, so I wrote them retrospectively.
> Extra whatsnew items for recent um changes.

- lib/iris/fileformats/grib/_save_rules.py
- lib/iris/tests/unit/fileformats/grib/save_rules/test__product_definition_template_8_and_11.py
- lib/iris/tests/unit/fileformats/grib/save_rules/test_product_definition_template_11.py
handling for GRIB2 product definition template 11
involves all the logic for PDT8, along with ensemble identification
> pdt11 handling

- lib/iris/fileformats/grib/_save_rules.py
- lib/iris/tests/integration/test_grib2.py
bug fix, as wrong data type was being passed to gribapi,. resulting in an exception
integration test added to test for this
> pdt11 bugfix

- lib/iris/analysis/cartography.py
This adds in the commits with the optimisation of rotate_winds from the decoupler branch.
> Optimise rotate winds

- .travis.yml
I think it should not be necessary any more.
> Remove cfchecker from Travis script.

- docs/iris/example_code/General/custom_file_loading.py
- docs/iris/src/developers_guide/gitwash_dumper.py
- docs/iris/src/sphinxext/gen_example_directory.py
- lib/iris/fileformats/dot.py
- lib/iris/fileformats/ff.py
- lib/iris/fileformats/grib/__init__.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/rules.py
- lib/iris/io/__init__.py
- lib/iris/io/format_picker.py
- lib/iris/tests/__init__.py
- lib/iris/tests/pp.py
- lib/iris/tests/test_cdm.py
- lib/iris/tests/test_pp_module.py
- lib/iris/tests/test_pp_to_cube.py
- lib/iris/tests/unit/fileformats/pp/test__field_gen.py
This is mostly independent, but there are a couple of small conflicts, so I based it on the previous PR, which makes it look a little big...
This ensures files are correctly closed by opening them in a `with` context. In Python 3, it will cause a `ResourceWarning` if you don't close files explicitly or with a context manager.
> Context-ified file IO

- docs/iris/src/whatsnew/contributions_1.9/deprecate_2015-08-07_lazyarray.txt
- lib/iris/aux_factory.py
- lib/iris/coords.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_reorder_bounds_data.py
> Deprecate LazyArray

- lib/iris/fileformats/grib/load_rules.py
added support for height level for "surface" variable in NCAR archive
> new rule for surface variable in NCAR-like archive

- .travis.yml
See:
- https://github.com/SciTools/iris/pull/1777#issuecomment-140641857
- https://github.com/ContinuumIO/anaconda-issues/issues/445
> Add libgfortran dependency workaround.

- src/iris/fileformats/pp_packing/pp_packing.c
Probably because of the `try/except`, I never noticed that the extension does not really work on Python 3. But the import error is triggered in the documentation build, so it needs some fixing.
> Python 3 compatibility for C extension

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
Accidentally rebased the refactor I made of intersection out.  This PR corrects this mistake.
Apologies for this @rhattersley 
see #1663
> BUG: Intersection unnecessary wrap

- lib/iris/fileformats/cf.py
- lib/iris/tests/unit/fileformats/cf/test_CFReader.py
- lib/iris/tests/unit/unit/test_suppress_unit_warnings.py
> Add iris.FUTURE.netcf_promote=False warning

- docs/iris/src/whatsnew/contributions_1.9/bugfix_2015-09-23_change_over_time_upward_air_velocity.txt
- lib/iris/fileformats/um_cf_map.py
- lib/iris/tests/results/usecases/pp_to_cf_conversion/from_netcdf/12187.b_0.cml
- lib/iris/tests/results/usecases/pp_to_cf_conversion/from_pp/12187.b.cml
- lib/iris/tests/results/usecases/pp_to_cf_conversion/to_netcdf/12187.b_0.cdl
returning change from 
https://github.com/metarelate/metOcean/issues/64
to the um_cf_map
> unit update

- README.md
The copyright date in the readme still said last year :scream:
> Incremented date in README copyright

- lib/iris/_cube_coord_common.py
- lib/iris/_merge.py
- lib/iris/analysis/__init__.py
- lib/iris/cube.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/plot.py
- lib/iris/tests/experimental/test_raster.py
- lib/iris/tests/integration/test_grib2.py
- lib/iris/tests/test_cdm.py
- lib/iris/tests/test_coding_standards.py
A group of changes cherry-picked from another PR.
These are benign adjustments, on the way to delivering a working Python 3 version.
See : https://github.com/SciTools/iris/pull/1782#issuecomment-154048646
> Pyk3 unicode partial

- lib/iris/fileformats/name_loaders.py
- lib/iris/tests/unit/fileformats/name_loaders/test__calc_integration_period.py
time period interpretation for name files
> time period 

- .travis.yml
- docs/iris/example_tests/test_polar_stereo.py
- docs/iris/src/sphinxext/generate_package_rst.py
- docs/iris/src/whatsnew/contributions_1.9/newfeature_2015-11-17_python3.txt
Some minor last fixups; add to Travis, fix doc build, add what's new.
> Enable Python 3

- lib/iris/experimental/regrid_conservative.py
- lib/iris/experimental/ugrid.py
- lib/iris/fileformats/netcdf.py
- lib/iris/proxy.py
> Deprecate iris.proxy

- docs/iris/src/whatsnew/1.9.rst
- lib/iris/__init__.py
Release candidate : changed version string
> Make v_1.9.0rc1

- docs/iris/src/whatsnew/1.9.rst
- lib/iris/__init__.py
release stamps
ready to tag release
> iris 1.9.0

- tools/generate_std_names.py
Closes #1876. This is a re-opening of #1877.
> Fixed unicode issue for generate_std_names.

- docs/iris/example_code/Meteorology/COP_1d_plot.py
- docs/iris/src/developers_guide/index.rst
- docs/iris/src/developers_guide/release.rst
- docs/iris/src/whatsnew/1.9.rst
- lib/iris/__init__.py
New developer guide page on release notes.
Version updated to 1.9.1 ready for release
> Release notes

- INSTALL
update install guide with python 3 compatibility
> install py3

- lib/iris/io/__init__.py
> Defer dot import

- lib/iris/cube.py
> Avoid sorting classes directly

- docs/iris/example_code/Meteorology/COP_1d_plot.py
An improvement to the clarity of a code example
re: https://github.com/SciTools/iris/pull/1892#discussion_r49204959
> improved example clarity

- docs/iris/src/whatsnew/contributions_1.10/newfeature_2016-Jan-09_cell-measure.txt
- lib/iris/_concatenate.py
- lib/iris/_merge.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/exceptions.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/test_cdm.py
- lib/iris/tests/unit/coords/test_CellMeasure.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/experimental/regrid/test_regrid_weighted_curvilinear_to_rectilinear.py
- lib/iris/tests/unit/merge/test__CubeSignature.py
Cell Measures added as Cube metadata
support for load and save for CF netCDF
> CellMeasures as cube metadata

- lib/iris/fileformats/grib/_load_convert.py
- lib/iris/fileformats/grib/_message.py
- lib/iris/tests/unit/fileformats/grib/load_convert/test_grid_definition_template_40.py
- lib/iris/tests/unit/fileformats/grib/message/test__Section.py
A new function is introduced on _Section, providing controlled access to computed keys
this makes it clear where we are using them, (currently GDT40 and GDT41)
Alternative to #1904
> careful use of computed keys

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Jan-20_check-aux-coords-before-concatenating.txt
- docs/iris/src/whatsnew/contributions_1.10/newfeature_2015-Jan-21_allow-concat-of-cubes-with-anon-dims.txt
- lib/iris/_concatenate.py
- lib/iris/cube.py
- lib/iris/tests/integration/concatenate/test_concatenate.py
- lib/iris/tests/test_concatenate.py
- lib/iris/tests/unit/concatenate/test_concatenate.py
> Allow concatenation of cubes with anonymous dimensions

- lib/iris/fileformats/grib/_load_convert.py
- lib/iris/tests/unit/fileformats/grib/load_convert/test_ensemble_identifier.py
- lib/iris/tests/unit/fileformats/grib/load_convert/test_product_definition_template_11.py
- lib/iris/tests/unit/fileformats/grib/load_convert/test_reference_time_coord.py
load product definition template 11
> grib pdt11

- lib/iris/cube.py
- lib/iris/tests/integration/test_netcdf.py
https://github.com/marqh/iris/commit/80124dbcb36fb8b068ccd9e89e98248d6b2dc145
introduced a foolish bug which prevented cube printing in some cases.  this fixes the behaviour and adds a test to protect the fix
> print cell_measure

- lib/iris/_concatenate.py
- lib/iris/tests/unit/concatenate/test_concatenate.py
> Remove warning for concatenating anonymous dimensions

- conda-requirements.txt
> grib version independence

- lib/iris/fileformats/grib/_grib_cf_map.py
- lib/iris/fileformats/um_cf_map.py
- tools/gen_translations.py
date and commit sha stamps for metarelate sourced content
as requested in #1929
> metarelate date and git sha

- docs/iris/src/whatsnew/contributions_1.10/newfeature_2015-Jan-21_allow-concat-of-cubes-with-anon-dims.txt
- lib/iris/cube.py
- lib/iris/tests/integration/concatenate/test_concatenate.py
Patrick and I tripped over this before I left on holiday, so I thought this clarification was needed.
> Clarify what's new and test of concatenating anonymous dimensions.

- docs/iris/example_code/General/SOI_filtering.py
- docs/iris/example_code/General/cross_section.py
- docs/iris/example_code/General/custom_file_loading.py
- docs/iris/example_code/General/global_map.py
- docs/iris/example_code/General/projections_and_annotations.py
- docs/iris/example_code/Meteorology/COP_1d_plot.py
- docs/iris/example_code/Meteorology/COP_maps.py
- docs/iris/example_code/Meteorology/hovmoller.py
- docs/iris/example_code/Meteorology/lagged_ensemble.py
- docs/iris/example_code/Oceanography/atlantic_profiles.py
- docs/iris/example_tests/test_COP_1d_plot.py
- docs/iris/example_tests/test_COP_maps.py
- docs/iris/example_tests/test_SOI_filtering.py
- docs/iris/example_tests/test_TEC.py
- docs/iris/example_tests/test_cross_section.py
- docs/iris/example_tests/test_custom_file_loading.py
- docs/iris/example_tests/test_deriving_phenomena.py
- docs/iris/example_tests/test_global_map.py
- docs/iris/example_tests/test_hovmoller.py
- docs/iris/example_tests/test_lagged_ensemble.py
- docs/iris/example_tests/test_lineplot_with_legend.py
- docs/iris/example_tests/test_polar_stereo.py
- docs/iris/example_tests/test_rotated_pole_mapping.py
- docs/iris/src/userguide/plotting_examples/1d_with_legend.py
- lib/iris/tests/test_coding_standards.py
For some reason, I've had this sitting around for a year and a half.
Mostly a bunch of word-wrap; this actually makes the docs look better since you don't need to scroll to the right any more.
> PEP8 doc examples

- lib/iris/_constraints.py
Gives ~5x speedup (for one particular case, reducing to ~2x speedup for smaller dataset) on the extract step when a list of values is given to a constraint:
```
cube.extract(iris.Constraint(model_level=[1, 3, 5]))
```
extract_faster:
```
import textwrap
def setup_code(bounds=False):
code = textwrap.dedent("""
import iris
from iris.cube import Cube
from iris.coords import DimCoord
def prepare_cube(n):
lat = DimCoord(np.arange(n), standard_name='latitude', units='degrees')
lon = DimCoord(np.arange(n), standard_name='longitude', units='degrees')
{}
data = np.arange(n*n).reshape(n,n)
return Cube(data, dim_coords_and_dims=[(lon, 0), (lat, 1)])
cube = prepare_cube(500)
target_vals = np.arange(20, 145)
lons = iris.Constraint(longitude=target_vals) …
```
> Identified a significant speedup for point based constraints of values.

- lib/iris/fileformats/pp.py
- lib/iris/tests/test_coding_standards.py
non-functional change to pp.py
pep8 plus removal of claims about save and as_pairs, as_fields being able to take CubeLists as inputs
> pep8 and docstring untruths

- docs/iris/src/developers_guide/gitwash/development_workflow.rst
- docs/iris/src/developers_guide/gitwash/git_install.rst
- docs/iris/src/developers_guide/gitwash/git_resources.rst
- docs/iris/src/developers_guide/gitwash/known_projects.inc
- docs/iris/src/developers_guide/gitwash/set_up_fork.rst
- docs/iris/src/developers_guide/gitwash/this_project.inc
- docs/iris/src/developers_guide/gitwash_build.sh
@ajdawson @pelson 
How about this then?  (Feeling a bit less good about myself now.)
> Patch page 404 url replaced in the correct location.

- lib/iris/fileformats/grib/_load_convert.py
- lib/iris/fileformats/grib/_message.py
- lib/iris/tests/unit/fileformats/grib/load_convert/test_grid_definition_template_20.py
grid definition template 20 for GRIB2
> gd20 polarStereo

- docs/iris/src/conf.py
- docs/iris/src/whatsnew/1.8.rst
Fixes https://github.com/SciTools/iris/pull/1990#issuecomment-216833153
> Another readthedocs.io update

- lib/iris/fileformats/um/_fast_load_structured_fields.py
> Fix header date.

- lib/iris/__init__.py
- lib/iris/tests/unit/test_sample_data_path.py
See https://groups.google.com/forum/#!topic/scitools-iris/gv7vB7VGH9M
Ping @ajdawson
> Raise error for missing sample data path.

- lib/iris/fileformats/dot.py
- lib/iris/tests/unit/fileformats/dot/__init__.py
- lib/iris/tests/unit/fileformats/dot/test__dot_path.py
> Watch out for broken `dot` installations.

- lib/iris/__init__.py
- lib/iris/tests/unit/test_sample_data_path.py
@marqh Reference https://github.com/SciTools/iris-sample-data/pull/14
> Try packaged iris-sample-data.

- .travis.yml
@ajdawson reference #2051 and  https://github.com/conda/conda/issues/2675
> Explicitly add defaults channel.

- lib/iris/tests/unit/cube/test_Cube__operators.py
Tiny fix needed as private element got moved.
> Fix test for biggus 0.14.

- docs/iris/src/whatsnew/contributions_1.10/deprecate_2016-Jul-25_grib-module.txt
- docs/iris/src/whatsnew/contributions_1.10/deprecate_2016-Jul-26_grib-future.txt
- docs/iris/src/whatsnew/contributions_1.10/newfeature_2016-Jul-25_iris-grib.txt
> Whatsnew improvements for iris_grib introduction.

- docs/iris/src/whatsnew/contributions_1.10/bugfix_2016-Jul-22_ignore_fill_value_on_merge.txt
This was missing in the original PR.
> What's new entry for #2075

- lib/iris/__init__.py
In response to #2105 
I'm not really committed to this, let's see who likes it / not.
> Add per-option explanatory string to warning for deprecated FUTURE options.

- lib/iris/analysis/__init__.py
- lib/iris/analysis/_interpolate_backdoor.py
- lib/iris/analysis/interpolate.py
My attempt to improve on @djkirkham  #2119.
TBD: which is better ?
> Import of 'iris.analysis' provides 'iris.analysis.interpolate' again.

- conda-requirements.txt
- lib/iris/plot.py
- lib/iris/tests/__init__.py
- lib/iris/tests/integration/plot/test_netcdftime.py
- lib/iris/tests/unit/plot/test__fixup_dates.py
- minimal-conda-requirements.txt
> Defer 'nc_time_axis' import, making dependency optional.

- lib/iris/__init__.py
- lib/iris/tests/unit/fileformats/pp_rules/test_convert.py
Merge changes from v1.10.x back into master, in particular this brings changes from #2144.
> Mergeback v1.10.x

- lib/iris/tests/unit/util/test__is_circular.py
- lib/iris/util.py
> is_circular bug

- lib/iris/tests/results/imagerepo.json
@marqh Yo.
Reference https://github.com/SciTools/test-images-scitools/pull/7
> updated image repo

- lib/iris/fileformats/um_cf_map.py
- tools/gen_translations.py
updates to gen_translations to target iris-grib or iris, depending on argument
> generate iris-grib translations

- .travis.yml
Reference #2227 and this [comment](https://github.com/SciTools/iris/pull/2227#discussion_r85759229)
> Move to https

- conda-requirements.txt
- docs/iris/src/_templates/index.html
- docs/iris/src/whatsnew/1.11.rst
- docs/iris/src/whatsnew/aggregate_directory.py
- docs/iris/src/whatsnew/contributions_1.11/bugfix_2016-Oct-06_is_circular.txt
- docs/iris/src/whatsnew/contributions_1.11/bugfix_2016-Oct-06_netcdf_string_unicode.txt
- docs/iris/src/whatsnew/contributions_1.11/newfeature_2015-Aug-06_lambert_azimuthal_equal_area.txt
- docs/iris/src/whatsnew/contributions_1.11/newfeature_2016-Oct-19_netcdf_packing_support.txt
- docs/iris/src/whatsnew/index.rst
- lib/iris/__init__.py
- lib/iris/config.py
- lib/iris/tests/__init__.py
- lib/iris/tests/runner/_runner.py
- lib/iris/tests/test_basic_maths.py
- lib/iris/tests/test_image_json.py
- minimal-conda-requirements.txt
Merge the tagged release `v1.11.0` from `v1.11.x` back into `master`
> Merge back v1p11

- lib/iris/analysis/_interpolate_private.py
- lib/iris/analysis/trajectory.py
- lib/iris/tests/integration/test_trajectory.py
Some odd small improvements that seemed relevant, following on from #2245
> Trajectory test tweak

- lib/iris/tests/idiff.py
> Fix import usage in idiff.

- README.md
> http changed to https on both badges

- lib/iris/fileformats/um_cf_map.py
@bjlittle 
please may you have a look at these for me?
see 
https://github.com/metarelate/metOcean/issues/75
https://github.com/metarelate/metOcean/issues/76
https://github.com/metarelate/metOcean/issues/77
> metarelate translations

- docs/iris/src/whatsnew/1.12.rst
Mostly formatting changes.  Also just proposals.  Not going to cry if they all get rejected.
Might cry a little bit...
> some small changes to v1.12 whatsnew

- lib/iris/tests/test_image_json.py
attempt to bypass github 403 for anonymous get, possibly caused by travis ip addresses hammering the API
> github api management

- docs/iris/src/_templates/layout.html
> Update template copyright year end

- lib/iris/_concatenate.py
- lib/iris/_lazy_data.py
- lib/iris/_merge.py
- lib/iris/cube.py
- lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb
- lib/iris/fileformats/netcdf.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/um/_fast_load_structured_fields.py
- lib/iris/tests/__init__.py
- lib/iris/tests/integration/test_aggregated_cube.py
- lib/iris/tests/integration/test_ff.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/pp.py
- lib/iris/tests/test_cdm.py
- lib/iris/tests/test_concatenate.py
- lib/iris/tests/test_ff.py
- lib/iris/tests/test_merge.py
- lib/iris/tests/test_netcdf.py
- lib/iris/tests/test_pickling.py
- lib/iris/tests/test_plot.py
- lib/iris/tests/test_pp_cf.py
- lib/iris/tests/test_pp_module.py
- lib/iris/tests/unit/fileformats/grib/message/test_GribMessage.py
- lib/iris/tests/unit/fileformats/netcdf/test__load_cube.py
- lib/iris/tests/unit/fileformats/pp/test__create_field_data.py
- lib/iris/tests/unit/fileformats/pp/test__interpret_field.py
- lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/test_build_auxiliary_coordinate.py
- lib/iris/tests/unit/fileformats/um/fast_load_structured_fields/test_FieldCollation.py
note to reviewers, please do not squash these commits.  If you would like a cleaned up history, please request a rebase
> dask based merge

- lib/iris/coords.py
- lib/iris/tests/unit/aux_factory/test_AuxCoordFactory.py
> Refactor AuxCoordFactory unit tests to remove biggus references

- lib/iris/cube.py
Tidy the `Cube.__init__` so that it is a good citizen and explicitly uses the `Cube.data` setter.
> Cube.__init__ uses data setter.

- lib/iris/tests/__init__.py
Addressing [this comment](https://github.com/SciTools/iris/pull/2477/files#diff-350ecfa750b99028f16446216ccbcfdbR424)
@bjlittle
> Replace np.ma with ma

- lib/iris/coords.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/unit/coords/test_CellMeasure.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
> DataManager used for cell measures

- lib/iris/_data_manager.py
- lib/iris/_merge.py
- lib/iris/analysis/maths.py
- lib/iris/coords.py
- lib/iris/cube.py
- lib/iris/fileformats/grib/__init__.py
- lib/iris/fileformats/grib/message.py
- lib/iris/fileformats/pp.py
- lib/iris/fileformats/rules.py
- lib/iris/fileformats/um/_fast_load_structured_fields.py
- lib/iris/tests/integration/test_pp.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/data_manager/test_DataManager.py
- lib/iris/tests/unit/fileformats/pp/test__create_field_data.py
- lib/iris/tests/unit/fileformats/pp/test__interpret_field.py
`core_data` should be a function, not a read-only class property.
> Dask core data

- lib/iris/pandas.py
> pandas >0.20

- lib/iris/tests/unit/cube/test_Cube.py
new unit tests for cube slices
According to http://scitools.org.uk/iris/docs/latest/iris/iris/cube.html?highlight=slices#iris.cube.Cube.slices
The order of the data in the slices, if ordered is True (default) should be the order of coords for slicing.
> test cube slices

- lib/iris/coords.py
- lib/iris/tests/unit/coords/__init__.py
- lib/iris/tests/unit/coords/test_AuxCoord.py
- lib/iris/tests/unit/coords/test_Coord.py
- lib/iris/tests/unit/coords/test_DimCoord.py
- lib/iris/tests/unit/fileformats/grib/grib1_load_rules/test_grib1_convert.py
Replaces https://github.com/dkillick/iris/pull/11
Since re-target across repos is not allowed ?
> More Coordinate tests for variously lazy/real points and bounds

- .travis.yml
After merge of https://github.com/SciTools/iris-test-data/pull/50
> Update test data sha

- docs/iris/src/_templates/index.html
- docs/iris/src/whatsnew/index.rst
- lib/iris/__init__.py
I *believe* these are the only version numbers I have to update.
> Bump version to 1.13.0

- docs/iris/src/_templates/index.html
- docs/iris/src/whatsnew/index.rst
- lib/iris/__init__.py
This merge back is incredibly light (since we only cut the `v1.13.x` branch so late) but I still think it's worth doing
I have set the new version to be `2.0.0-DEV`. Is this correct?
> Mergeback 1.13.x branch

- docs/iris/src/_templates/index.html
- docs/iris/src/userguide/real_and_lazy_data.rst
- docs/iris/src/whatsnew/2.0a0.rst
- docs/iris/src/whatsnew/index.rst
- lib/iris/__init__.py
First draft proposal for the pre-release `whatsnew` ... most likely needs some tweaking and further additions ...
> Draft whatsnew for 2.0a0.

- lib/iris/cube.py
Proposals to fix some issues I raised against #2625
> Tweaks to cube docstrings.

- docs/iris/src/whatsnew/2.0a0.rst
- lib/iris/cube.py
Addresses the outstanding actions in #2627, #2628, and #2629.
> Minor doc changes.

- README.md
Because it's useful, and I keep forgetting how to find it.
> Add link to latest-docs build.

- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/results/integration/netcdf/TestSaveMultipleAuxFactories/hybrid_height_cubes.cml
> Dask: "fix other dtype related failures"

- .travis.yml
A comparison of timings can be found here:
https://github.com/SciTools/iris/pull/2751#issuecomment-324669136
> Run Travis tests on 8 processors

- .travis.yml
@lbdreyer's changes, applied to master. I'll merge this PR.
xref: #2756
> Set nosetests to run on 8 cores on travis

- lib/iris/fileformats/rules.py
All of the tests passed locally. This should resolve issue #2671.
> Removed CMCustomAttribute and an elif which depends on it.

- lib/iris/analysis/_interpolate_backdoor.py
- lib/iris/analysis/_interpolate_private.py
> Remove deprecated function `nearest_neighbour_data_value`

- docs/iris/src/whatsnew/contributions_v2.0.0/incompatiblechange_2017-Oct-19_remove-sample-data-dir.txt
> Whats New for sample data dir [ci skip]

- docs/iris/src/whatsnew/contributions_v2.0.0/incompatiblechange_2017-Oct-19_remove-pp-packing-module.txt
- docs/iris/src/whatsnew/contributions_v2.0.0/incompatiblechange_2017-Oct-19_remove-proxy-module.txt
- docs/iris/src/whatsnew/contributions_v2.0.0/incompatiblechange_2017-Oct-19_remove-unit-module.txt
> Whats New entries for deprecated modules removed [ci skip]

- .travis.yml
Fixes bug introduced in 2fcf1c00d77e6fbfdf488518d61c4c5192c9bf8d
xref: #2833
> Fixed the directory for doctr (automatic documentation upload)

- docs/iris/example_code/Meteorology/COP_1d_plot.py
- docs/iris/example_code/Meteorology/COP_maps.py
- 2010 submission published
- add digital object identifiers
> Update documentation references

- docs/iris/src/whatsnew/contributions_2.0/incompatiblechange_2017-Oct-24_clip-latitudes.txt
- lib/iris/__init__.py
- lib/iris/coords.py
- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py
- lib/iris/tests/test_mapping.py
- lib/iris/tests/unit/analysis/geometry/test_geometry_area_weights.py
- lib/iris/tests/unit/coords/test_Coord.py
- lib/iris/tests/unit/test_Future.py
This Closes #2846. I'm uncertain about some of my changes and fully expect there'll be things I'll need to alter.
> Deprecating Futures clip_latitudes

- lib/iris/fileformats/um/__init__.py
- lib/iris/fileformats/um/_ff_replacement.py
Fix the license headers currently causing the coding standards tests to fail.
> Fix license headers for um files

- docs/iris/src/whitepapers/change_management.rst
Closes #2830 . Hopefully the small change I've made is slightly clearer.
> Rewrote backwards compatibility explanation to be clearer.

- lib/iris/__init__.py
- lib/iris/config.py
- lib/iris/etc/site.cfg.template
- lib/iris/fileformats/rules.py
- lib/iris/tests/__init__.py
- lib/iris/tests/pp.py
- lib/iris/tests/test_cdm.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/test_coordsystem.py
- lib/iris/tests/test_image_json.py
- lib/iris/tests/test_pp_module.py
This is for reference only.  In actual fact, this doesn't seem to make any functional difference.
> Switch off logging

- lib/iris/cube.py
> Ammended cube.var_name documentation.

- lib/iris/__init__.py
I've cut v2.0.x, so can bump the version on master.
> Bumped master to the v2.1 stream.

- lib/iris/_cube_coord_common.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/test_netcdf.py
Fixes outstanding test failures on master (I hope).
> Fix some header dates.

- docs/iris/src/whatsnew/contributions_2.1/newfeature_2018-Jan-04_missing_value_attr.txt
- lib/iris/_cube_coord_common.py
- lib/iris/fileformats/netcdf.py
- lib/iris/tests/test_netcdf.py
Necessary follow-up for #2892.
cc: @zklaus
> Added the what's new and updated the copyright years for 2892

- lib/iris/cube.py
- lib/iris/experimental/regrid.py
- lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py
Travis insists that the license headers of these files is out of date, but only for me. Clearly something is wrong so rather than shouting into ~~Travis~~ the void, I'm just going to grit my teeth and update these files.
> The dkillick early 2018 license header fiasco

- README.md
> Add a general zenodo link to the readme.

- requirements/core.txt
- setup.py
Resolves two issues raised in #606.
> Improved the pip installability of scitools-iris.

- lib/iris/fileformats/netcdf.py
Closes https://github.com/SciTools/iris/issues/2968
> Save calendar attribute for cube data

- .travis.yml
Make travis target fail when docs-build fails.
> Attempts to fix docs-build error reporting.

- lib/iris/tests/__init__.py
Targetting new feature branch ["2d_coords"](https://github.com/SciTools/iris/tree/2d_coords).
Establishes a basis for 2d coords work, with broken tests skipped out while WIP.
> Provide a test skipper for 2d coords WIP.

- docs/iris/src/_templates/layout.html
- docs/iris/src/whatsnew/2.2.rst
Last remaining version number change
> ORCA 2D: Change version number

- docs/iris/src/whatsnew/2.2.rst
- lib/iris/analysis/cartography.py
Getting some fixes in for the documents,
as provided for internal oceans users' approval.
> Docs fixes

- lib/iris/tests/__init__.py
No sweat, as it is already unused + possibly never was used ?
> Remove 'skip_2d' test decorator.

- lib/iris/fileformats/cf.py
As #3177 seems to have caused problems when merged.
We intend to re-introduce this when we've fixed the other problems now on master ..
> Revert nc vars masking fix (temporarily).

- requirements/core.txt
Travis failing with error message about numpy build; maybe this will fix it...
> pinned numpy to not 1.15.2 in core requirements

- etc/cf-standard-name-table.xml
> Update CF standard name table to v59

- lib/iris/__init__.py
DO NOT MERGE until #3199 is in.
> Update version string to v2.2.0

- lib/iris/__init__.py
Bump the version string to `v2.2.1dev0`.
> Maintenance branch for v2.2

- lib/iris/tests/__init__.py
Show stderr from `ncdump` in test log if `ncdump` fails. Also refactored to use output from `ncdump` directly without writing to a temporary file.
Related to #3139 
Before:
```
ERROR: test_conflicting_global_attributes (iris.tests.test_netcdf.TestNetCDFSave)
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scitools_iris-2.3.0.dev0-py2.7.egg/iris/tests/test_netcdf.py", line 779, in test_conflicting_global_attributes
('netcdf', 'netcdf_save_confl_global_attr.cdl'))
File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scitools_iris-2.3.0.dev0-py2.7.egg/iris/tests/__init__.py", line 355, in assertCDL
stderr=cdl_file, stdout=cdl_file) …
```
> TEST: Show stderr if ncdump command fails.

- lib/iris/__init__.py
- lib/iris/analysis/__init__.py
- lib/iris/coord_systems.py
- lib/iris/tests/test_coordsystem.py
- lib/iris/tests/unit/analysis/test_PROPORTION.py
- lib/iris/tests/unit/coord_systems/test_Mercator.py
This PR merges back onto `master` the `v2.2.x` branch, which is at `2.2.1dev0`
> Merge back v2.2.x

- requirements/core.txt
Test with latest cf-units.
See if this works ...
Closes #3258
> Test with newest cf-units: no longer called cf_units.

- lib/iris/analysis/__init__.py
- lib/iris/analysis/cartography.py
- lib/iris/tests/test_merge.py
This reverts commit a76afdc2be2f8fb47319eb9b1d14f9c4b7d0f19e.
The Pr targeted the wrong branch
> Revert "Avoid numpy FutureWarning about indexing with sequence. (#3267)"

- docs/iris/src/userguide/loading_iris_cubes.rst
Adding the example mentioned in #3235 to the docs.
> Adding date range time example to docs.

- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2018-Jul-25_dask_chunking.txt
Missing description,  belonging to #3361
> Whatsnew for new chunking strategy.

- .travis.yml
- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-Sep-03_self_referencing_vollcello_reading.txt
- lib/iris/fileformats/cf.py
- lib/iris/tests/integration/test_netcdf.py
> Support volcello loading even if volcello referenced in cell_measures

- docs/iris/src/whatsnew/2.2.rst
- lib/iris/cube.py
Replacing #3250 but targeting master.
> ENH: Working cube data equality

- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2019-Oct-02_cubelist_repr_html.txt
> whatsnew entry for CubeList _repr_html_

- docs/iris/src/userguide/interpolation_and_regridding.rst
- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-Oct-01_masked_dimcoords_and_auxcoords.txt
- lib/iris/analysis/_interpolation.py
- lib/iris/coords.py
- lib/iris/tests/test_coord_api.py
- lib/iris/tests/unit/coords/__init__.py
- lib/iris/tests/unit/coords/test_AuxCoord.py
- lib/iris/tests/unit/coords/test_DimCoord.py
> enforce non-masked dimension coordinate points/bounds

- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2018-Aug-28_lazy_bounds_collapse.txt
- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2018-Nov-28_lambert_conformal_secant_latitudes.txt
- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2018-Nov-29_proportion_falsemask.txt
- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-May-20_um_landsea_masked.txt
- docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2019-Oct-01_cube_transpose_cell_measures.txt
- docs/iris/src/whatsnew/contributions_2.3.0/docchange_2019-Aug-22_random_load_order.txt
- docs/iris/src/whatsnew/contributions_2.3.0/docchange_2019-Aug-27_date_range_constraints.txt
- docs/iris/src/whatsnew/contributions_2.3.0/docchange_2019-Mar-06_discontig_masking.txt
- docs/iris/src/whatsnew/contributions_2.3.0/newfeature_2018-Oct-24_lazy_rms_agg.txt
Some extra 'whatsnew' information for the 2.3 release.
Mostly covering changes that were merged without including a whatsnew contribution.
:disappointed: we should work on this !
> Additional whatsnew contributions for v2.3 release.

- docs/iris/src/_templates/index.html
- docs/iris/src/_templates/layout.html
- docs/iris/src/whatsnew/index.rst
A few little updates needed for the auto docs building now that the v2.3.x branch has been cut
For ref see #3397
> Updates for auto docs on master branch for Iris 3 release

- docs/iris/src/whatsnew/2.3.rst
Just a couple of changes to the Iris 2.3 what's new before we do the release
> A couple of edits to the 2.3 whats new

- lib/iris/cube.py
- lib/iris/tests/integration/test_netcdf.py
- lib/iris/tests/unit/cube/test_Cube.py
> Fix cube summary capitalisation

- lib/iris/aux_factory.py
- lib/iris/fileformats/pp.py
- lib/iris/tests/unit/analysis/maths/__init__.py
- lib/iris/tests/unit/merge/test_ProtoCube.py
- lib/iris/tests/unit/tests/test_IrisTest.py
- lib/iris/util.py
- tools/translator/__init__.py
> Replace deprecated abstractproperty

- lib/iris/cube.py
> Remove reference to invalid coords in cube summary

- lib/iris/coords.py
- lib/iris/tests/unit/coords/test__DimensionalMetadata.py
> Make _DimensionalMetadata abstract

- lib/iris/fileformats/um_cf_map.py
new stash to CF translations for release 2.3
> I23stashtocf mr#96

- .travis.yml
**WIP: do not merge**
Note: targetting temporary branch in master repo  (so I can merge it)
Debugging Travis PUSH_BUILT_DOCS operation
> Add travis debug line.

- .travis.yml
- lib/iris/__init__.py
**WIP: do not merge**
Testing problems with travis runs
> Pushdocs fix

- .travis.yml
> Revert to single-line command for doctr invocation.

- docs/iris/src/whatsnew/contributions_3.0.0/docchange_2019-Dec-04_black_code_formatting.txt
Responding to [comment](https://github.com/SciTools/iris/issues/3542#issuecomment-561753863)
In conjunction with #3580 , hopefully will finish #3542.
> Added whatsnew for Black.

- docs/iris/src/whatsnew/2.3.rst
Updated whatsnew, ready for 2.3.0 release
Just adds notes for new versions of standard-names and stash-translations
> Whatsnew notes for latest standard-names and stashcodes.

- lib/iris/__init__.py
**WIP: DO NOT MERGE**
includes #3611 commit
should be ok to merge after that
> Fix version 2v3v0

- docs/iris/src/whatsnew/contributions_3.0.0/bugfix_2020-Jun-15_remove_aux_factories_with_remove_coord.txt
Provides a whatsnew for #3641.
> Add whatsnew for derived coordinate removal

- .travis.yml
This PR makes a minor change to fix `travis-ci` push-built-docs job.
> fix travis-ci push-built-docs

- lib/iris/coords.py
> Address missing climatological support

- docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2020-Sep-03_lazy_regridding.txt
- docs/iris/src/whatsnew/latest.rst
> Rework whatsnew into new scheme.

- docs/iris/src/whatsnew/latest.rst
- docs/iris/src/whatsnew/latest.rst.template
This PR celebrates family... more over, welcoming and rejoicing new Iris core developers.
I think it's important to be very grateful for their time, efforts and contributions. So let's make sure to announce that to the community :grinning: 
---
> whatsnew - announcements

- docs/iris/src/whatsnew/latest.rst
"What's New" entry for #3846.
---
> "What's New" entry for #3846.

- docs/iris/src/whatsnew/latest.rst
"What's New" entry for #3681
Just checking I've got the hang of this 😁.
---
> whatsnew for #3681

- docs/iris/src/whatsnew/latest.rst
This PR updates the `whatsnew` announcement section.
---
> whatsnew - update announcement

- .pre-commit-config.yaml
This PR bumps the version of the `flake8` pre-commit hook.
---
> update pre-commit flake8 version

- .pre-commit-config.yaml
This PR adds Python [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) checking, and filename conflict checking for case-insensitive filesystems to the `pre-commit` hooks.
---
> Add additional pre-commit hooks

- docs/iris/src/whatsnew/latest.rst
Whats New entry for #3867.
---
> Whats New entry for #3867

- docs/iris/src/whatsnew/latest.rst.template
Included a common links file.
---
> Added include for common links file

- docs/iris/src/whatsnew/latest.rst
Added whats new entry for:  #3877 Docs warning promotion to errors.
---
> Added whats new for pr3877

- README.md
This PR adds our `scitools_iris` twitter badge to the `README.md`.
---
> Add twitter badge

- docs/iris/src/developers_guide/contributing_ci_tests.rst
Fix a typo and line wrapping in the docs.
---
> Fixed typo and line wrap

- docs/iris/src/installing.rst
Added reference to **WSL** in the `Installing Iris` page of the documentation. 
I have avoided adding a step by step guide as there are many on the internet.
Origin of this issue: https://github.com/SciTools/iris/issues/3883
---
> Add wsl to installing iris

- docs/iris/src/installing.rst
- docs/iris/src/whatsnew/latest.rst
added whatsnew for pr #3885
---
> added whatsnew for pr3885

- docs/iris/src/index.rst
- docs/iris/src/whatsnew/latest.rst
> added whats new for pr #3884

- docs/iris/src/whatsnew/3.0.rst
- lib/iris/__init__.py
This PR pins the `__version__ = 3.0.0` and updates the associated `whatsnew` date for release.
---
> pin v3.0.0 version and whatnew date

- docs/iris/src/whatsnew/latest.rst
- docs/iris/src/whatsnew/latest.rst.template
This PR adds the `sphinx-panels` template `dropdown` to the `latest.rst` and the `latest.rst.template`.
---
> Docs whatsnew add dropdowns to the template

- docs/src/whatsnew/latest.rst
A `whatsnew` entry to announce the arrival of @jamesp into the Iris family :beers: :tada: :partying_face: 
---
> core dev whatsnew entry

- lib/iris/experimental/ugrid.py
This PR exposes the `iris.experimental.ugrid.MeshMetadata` services.
---
> Expose MeshMetadata services

- docs/src/whatsnew/latest.rst
This PR collates the github names of first time contributors to `iris` in the `whatsnew`, pending the next release.
It costs nothing to say thank you :+1: 
---
> celebrate first time iris contributors

- lib/iris/experimental/ugrid.py
This PR adds pickle support to the `Mesh` et al.
No testing coverage yet... but that'll come soon :wink: 
---
> add mesh pickle support

- docs/src/index.rst
Add the Iris **version** to the main (index.rst) landing page.  Uses the already existing `version` variable.
This will only appear on the index, not on all pages.
Related to #3992.
---
> added iris version to index title

- docs/src/developers_guide/release.rst
This PR adds some additional references to supporting material on PyPI.
---
> docs add pypi references

- lib/iris/tests/unit/common/metadata/test_BaseMetadata.py
This PR is a follow-up to pull-request #4040.
---
> add basemetadata str unit test

- .cirrus.yml
- docs/iris/gallery_code/general/plot_anomaly_log_colouring.py
- docs/iris/src/common_links.inc
- docs/iris/src/conf.py
- docs/iris/src/developers_guide/contributing_ci_tests.rst
- docs/iris/src/developers_guide/contributing_code_formatting.rst
- docs/iris/src/whatsnew/3.0.1.rst
- docs/iris/src/whatsnew/3.0.2.rst
- docs/iris/src/whatsnew/3.0.rst
- docs/iris/src/whatsnew/index.rst
- lib/iris/__init__.py
- lib/iris/tests/test_basic_maths.py
This PR updates the `v3.0.x` release feature branch with the necessary cherry-picked `master` commits to make it functional again.
Specifically the following commits are included in this PR from `master`:
1. `79d636e` #3977 
2. `b2cef91` #4003 
3. `105af0e` #4007 
4. `55be054` #4019
There was also a degree of manual massaging required, particularly for the `whatsnew` and anything documentation related, due to #3975.
---
> Release branch prepare for v3.0.2

- lib/iris/experimental/ugrid.py
This PR adds the enumeration of valid UGRID `location` values to the `Mesh` as a convenience.
---
> add Mesh.LOCATIONS enumeration

- README.md
Super minor tweak of `README.md` to lower case the closing HTML paragraph element.
---
> fix html case

- requirements/ci/py36.yml
- requirements/ci/py37.yml
- requirements/ci/py38.yml
As a developer I'm continually leaning on `pip` when it's relevant... can't see a good reason why this isn't already part of the developer environment for `iris`.
---
> conda requirements add pip

- .pre-commit-config.yaml
This PR updates the `flake8` pre-commit git hook version
---
> update flake8 pre-commit

- .cirrus.yml
- lib/iris/fileformats/netcdf.py
This PR addresses the issue raise in https://github.com/conda/conda/issues/10596
---
> linux kernel version fix for conda 4.10+

- README.md
Add a link to the stable docs alongside the latest version on the `README.md`.
You can view the new README in my branch: https://github.com/tkknight/iris/blob/update_readme_docs_stable/README.md
Will close #3226
---
> Update readme docs stable

- .pre-commit-config.yaml
Due to the recent `cirrus-ci` vs `conda` carnage, #4081 failed... so I closed that bot generated PR and substituted it with this, as in includes the latest CI changes.
---
> pre-commit-ci update

- .github/workflows/refresh-lockfiles.yml
I read the documentation for the create pull request action incorrectly.  *Without* the `branch-suffix` setting, if a PR already exists for this action, it will be updated rather than creating a new one.  This is probably the preferred option.
---
> Removed branch suffix

- .github/ISSUE_TEMPLATE/config.yml
This PR adds a link to our `Iris GitHub Discussions` when a user chooses to create a new issue.
Hopefully this may encourage them to actively engage in a discussion rather than create an issue.
---
> github issues contact link for discussions

- lib/iris/coord_categorisation.py
Re-run of #4139 since GHA rebased over that one.
---
> Fix add_weekday.

- README.md
This PR is a `git cherry-pick` of #4006
Closes #3055
---
> update readme logo img src and href (#4006)

- docs/src/installing.rst
I fixed a typo in the installation instruction I wrote a while ago, that's all.
Max
> Typo fixed

- docs/src/userguide/merge_and_concat.rst
A fix to a typo in the merge user guide, spotted by William Ingram. Thanks William!
---
> User guide merge typo.

- lib/iris/cube.py
> Fix doc typo in cube transpose

- .cirrus.yml
- docs/src/common_links.inc
- docs/src/conf.py
- docs/src/copyright.rst
- docs/src/whatsnew/1.3.rst
- docs/src/whatsnew/3.1.rst
- lib/iris/__init__.py
- lib/iris/fileformats/abf.py
- lib/iris/fileformats/netcdf.py
Final changes prior to tagging v3.1
A docs-build is available [here](https://pp-iris.readthedocs.io/en/final_3v1/)
---
> Finalise whatsnew and version string; update CI to fix.

- docs/src/whatsnew/latest.rst
Added a line to the bugs fixed section for fixes to saving climate means to PP files
As requested in :pull:`4391` I have added a line to the release notes mentioning the fix for saving climate means to PP files.
---
> Added line to latest release notes for updates to pp_save_rules.py

- docs/src/whatsnew/latest.rst
What's new entry separate to PR to prevent too many conflicts in latest.rst
---
> What's new for pr 4387

- docs/src/whatsnew/latest.rst
What's new for #4402 
Built docs to check
---
> Updated whatsnew for PR 4402

- docs/src/whatsnew/latest.rst
> What's new PR #4400

- docs/src/whatsnew/latest.rst
> Added @wjbenfold to the core dev list

- docs/src/whatsnew/latest.rst
Added a missing colon to fix the `pp_save_rules` link.
---
> Whatsnew minor fix

- docs/src/whatsnew/latest.rst
Separated out as per docs to make merging easier
---
> Whatsnew for PR #4367

- docs/src/whatsnew/latest.rst
> Add new contributor to whatsnew

- docs/src/whatsnew/latest.rst
> Whatsnew PR 4450

- docs/src/whatsnew/latest.rst
> Whatsnew for PR 4462

- docs/src/whatsnew/latest.rst
Simple clarification in the `whatsnew` highlight entry that this is `experimental` UGRID functionality (and not core)
---
> whatsnew highlight clarification

- docs/src/installing.rst
This PR replaces #4256, originally raised by @kant, but has sadly gone stale after no response for six months.
Seems like a low hanging fruit that we can easily bank in time for the `iris` 3.2.0 release.
Particularly keen to do this as the change is motivated by a community user wanting to improve the documentation.
The rendered change of this PR is available to view in the associated built documentation [available here](https://bjlittle-iris.readthedocs.io/en/latest/installing.html#installing-from-source-with-conda-developers). 
---
> docs: installing update

- docs/src/userguide/saving_iris_cubes.rst
In response to support query - have clarified this case as it seems reasonably likely to confuse a newcomer to the functionality.
---
> Clarify that you can't append with the netcdf saver in docs

- lib/iris/tests/test_io_init.py
This PR is a follow-up to #3917.
---
> update test (#3917)

- docs/src/whatsnew/latest.rst
Extra space causes the issue link to not work.
---
> Fix whatsnew broken link

- docs/src/whatsnew/latest.rst
- lib/iris/analysis/maths.py
> Deprecate intersection_of_cubes

- docs/src/whatsnew/latest.rst
I suspect these were meant to be monospace rather than italic.
---
> Minor whatsnew formatting change

- docs/src/whatsnew/latest.rst
Missing whatsnew entry for  #4551
> Added whatsnew.

- .github/dependabot.yml
This PR enables GH `dependabot`, which will generate automated pull-requests with GHA version updates.
---
> adopt GH dependabot

- docs/src/whatsnew/3.2.rst
Add a drop down box to the 3.2 whats new for bug fixes for the 3.2.1, as was done for [3.0 ](https://scitools-iris.readthedocs.io/en/latest/whatsnew/3.0.html)
Renders:
---
> Update 3.2.rst whats new with section for bug fixes

- docs/src/whatsnew/3.2.rst
Welcoming @dennissergeev in the whatsnew.  I don't think we've had a new contributor in a patch release before, so not sure of the best place to put this.  My current suggestion renders like
---
> Whosnew v3.2.1

- .github/workflows/refresh-lockfiles.yml
> use conda-lock -k explicit

- docs/src/whatsnew/dev.rst
A small whatsnew change to get the build working.  For example of failed build, see most recent commit on `main`.
---
> Small whatsnew fix

- .gitignore
The benchmarks make a `.data` folder, I suggest that this should be git ignored
---
> Git ignore the benchmarks data folder

- docs/src/whatsnew/latest.rst
In accordance with #4705: #3901 definitely counts as a bigger change.
---
> Credit Will's epic review

- docs/gallery_code/oceanography/plot_load_nemo.py
- docs/src/whatsnew/latest.rst
* Why use four lines when you can use one?
* It took me a while to understand why the time coordinate promotion was necessary, so expanded that comment.
---
> Gallery: update NEMO example

- docs/src/whatsnew/latest.rst
Fix the numbered list formatting.
---
> fixed numbered list entry

- noxfile.py
This PR addresses the following GHA warning:
---
> address npy disable cpu features warning

- docs/src/whatsnew/latest.rst
What’s new entry for #4791.
---
> Whatnew for #4791

- lib/iris/tests/test_load.py
- lib/iris/tests/test_plot.py
- lib/iris/tests/unit/fileformats/netcdf/test_Saver__ugrid.py
We have a few tests that should have skip decorators but don't.
---
> Testing: add missing skip decorators

- docs/src/whatsnew/latest.rst
This has been on my to do list for a while now! I had forgotten to add a whatsnew entry for #4734 so I have added it in this PR.
---
> Add whats new entry for 4734

- docs/src/whatsnew/latest.rst
- lib/iris/cube.py
- lib/iris/tests/stock/__init__.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/util/test_new_axis.py
- lib/iris/util.py
Replacement for #3600 to avoid some code duplication by using a function `_handle_dimensional_metadata` and added tests.
---
> Extend new_axis to reshape _DimensionalMetadata objects

- docs/src/whatsnew/latest.rst
- etc/cf-standard-name-table.xml
As in #4483, updates the standard names in advance of 3.3 release.
> Standard names table update (v79)

- docs/src/whatsnew/latest.rst
- setup.cfg
Finishing the job of #4911 .
---
> Include shapely pin in setup.cfg

- docs/src/whatsnew/3.3.rst
Fixes some links in the whatsnew.
> Fix whatsnew

- docs/src/whatsnew/3.3.rst
Updates the whatsnew title for the v3.3 release.
---
> update whatsnew title for v3.3 release

- docs/src/whatsnew/3.3.rst
Merge the 3.3.x branch back into main after the release of 3.3.0.
---
> Mergeback v3.3.0

- docs/src/whatsnew/latest.rst
A follow up to some recent PRs to reflect changes in the `whatsnew`.
---
> docs whatsnew entry updates

- setup.cfg
Simple PR to align the PyPI trove classifiers to reflect our Python support.
---
> update pypi trove classifiers

- .github/ISSUE_TEMPLATE/config.yml
Whoops! Couldn't work out why the new link wasn't displaying, then spotted the typo :woozy_face: 
I actually tested this time, so this should now work.
---
> Typo in issue template

- docs/src/developers_guide/release.rst
[We were a bit unclear what to do about the whats new for the upcoming 3.3.](https://github.com/SciTools/iris/pull/4976#issuecomment-1253995749)1 so I thought this deserved a sentence in the developer's release guide
---
> Add short entry to release guide about what to do with the whats new for point releases.

- docs/src/whatsnew/3.3.rst
Final updates to the whatsnew before the release of 3.3.1
---
> Update whatsnew for 3.3.1 release

- docs/src/whatsnew/latest.rst
Updated what's new "glossary" entry to link to iris glossary, as opposed to python glossary
> Updated what's new "glossary" entry to link to iris glossary

- lib/iris/tests/unit/common/metadata/test_CubeMetadata.py
A preliminary to addressing #4982 
I discovered that the CubeMetadata testing really needed a refactor, before I could attempt adding a 'global_attributes' field.
So this is that.
Using Pytest parametrization allows fewer tests and (a bit) less boilerplate, while also testing **_all_** the fields (which was not the case before).
Some of the behaviours this now highlights may be questionable, but I'm going to ruthlessly ignore that here AFAP (i.e. unless something breaks).
The attributes behaviour still uses extra tests, but I think that is quite reasonable.  
In future, I hope to further parametrize the attribute tests, to cover both `global_attributes` and ("local")`attributes`
> Split-attrs: Cube metadata refactortests

- lib/iris/tests/test_constraints.py
Originally written by @bjlittle at https://github.com/rcomer/iris/pull/1, so should have been included  in #3933 but it got lost.
---
> Test for 'coord exists' constraint

- lib/iris/analysis/__init__.py
Tiny correction to some aggregator docstrings.  Looks like these changed at #2743.
I do not believe this is worth a whatsnew entry.
---
> Correct dask function in STD_DEV and VAR docstrings

- docs/src/whatsnew/latest.rst
- lib/iris/_constraints.py
- lib/iris/tests/unit/constraints/test_Constraint_equality.py
- requirements/ci/py310.yml
- requirements/ci/py38.yml
- requirements/ci/py39.yml
- setup.cfg
> Update `pandas_ndim` feature branch again.

- docs/src/whatsnew/latest.rst
> Update Pandas What's New entry

- docs/gallery_code/oceanography/plot_atlantic_profiles.py
Needed before #5086 will pass, so I'm targeting that branch.
---
> Fix plot_atlantic_profiles Flake8 E741 ambiguous variable name.

- docs/src/conf.py
- docs/src/whatsnew/3.4.rst
> Merge-back `v3.4.x` to `main`

- docs/src/whatsnew/latest.rst
As is tradition: @ESadek-MO deserves the honour of merging this one.
> Announce @ESadek-MO as a core Iris developer.

- docs/src/whatsnew/3.4.rst
Something I missed during the release process.
---
> Correct heading for v3.4 release highlights.

- docs/src/whatsnew/3.4.rst
> Cherry-pick #5110 onto `v3.4.x`

- docs/src/common_links.inc
This list is not restricted to core devs, so update the comment to reflect that.
---
> Expand scope of common contributor links

- docs/src/whatsnew/latest.rst
This PR updates the `whatsnew` to celebrate the first contribution to `iris` by @scottrobinson02 in #4415 :partying_face: 
---
> announce new contributor in whatsnew

- docs/src/whatsnew/latest.rst
Adding a whatsnew entry, that was missing from #5224. 
---
> Adding a whatsnew entry for 5224

- docs/src/whatsnew/latest.rst
- etc/cf-standard-name-table.xml
update cf standard units to latest version
> update cf standard units

- docs/src/whatsnew/3.5.rst
> fix v3.5.x typo

- docs/src/whatsnew/3.5.rst
Changed the title to reflect it is no longer a release candidate.
> Retitled WhatsNew v3.5.0

- docs/src/userguide/citation.rst
- docs/src/whatsnew/3.5.rst
Please ensure this is merged via a merge commit, and not a squash commit
> V3.5.x mergeback

- CODE_OF_CONDUCT.md
- MANIFEST.in
- README.md
- docs/src/whatsnew/latest.rst
This PR adopts a Code of Conduct (CoC) for our community.
Since I was adding a CoC badge, I decided to also reformat the badges akin to [cf-units](https://github.com/SciTools/cf-units#cf-units), [python-stratify](https://github.com/SciTools/python-stratify#stratify) and [nc-time-axis](https://github.com/SciTools/nc-time-axis/pull/129), which renders as:
[![image](https://user-images.githubusercontent.com/2051656/235265699-2b331760-f22e-464d-bd3d-9ee4207b9f27.png)](https://github.com/bjlittle/iris/tree/adopt-coc#-----)
Reference:
- GH Discussions https://github.com/SciTools/iris/discussions/5197
---
> adopt contributor covenant code of conduct

- tools/release_do_nothing.py
Minor tweak to the `release_do_nothing.py` script.
---
> update release_do_nothing script

- docs/src/userguide/citation.rst
- docs/src/whatsnew/3.6.rst
This PR is the merge-back of the `v3.6.x` release branch to `main`.
This PR must **not be squashed** and merged to `main`.
---
> v3.6.x merge-back

- docs/src/whatsnew/3.6.rst
This is the final commit in the `iris` v3.6.1 release to update the patch version and release date in the `whatsnew`.
---
> v3.6.x whatsnew version and date update

- docs/src/conf.py
- docs/src/index.rst
Not very important, but something that @tkknight and I discussed a few months ago, which I'd like to check off my personal to-do list.
---
> Minor docs `navbar` improvements

- .github/workflows/benchmarks_run.yml
- benchmarks/bm_runner.py
- #5429
- #5430 
- #5431 
- #5432
Will need `git rebase upstream/FEATURE_benchmarks` once those are merged.
- e2347c702146988c153349cd1a956dc03867efbb : Use `shlex.split()` for readable command line entries, rather than my own home-brew version
- fc12dd3ffdd01b98f3e0bf5b43d1f9c643a5b749 : Some minor documentation clarifications
No What's New entry since this is so minor and internal.
---
> Minor benchmark improvements

- lib/iris/cube.py
- lib/iris/tests/unit/cube/test_Cube.py
Closes #5305 
Units now correct when dividing a coordinate by a cube
> Units when dividing a coordinate by a cube

- docs/src/whatsnew/1.4.rst
linkcheck reports the link is broken, update to remove the "about".
---
> updated link (linkcheck fix)

- docs/src/voted_issues.rst
The statement removed is not long true as GitHub now lets you sort by emoji.
---
> update text on voted issues page

- docs/src/conf.py
Add linkcheck ignore for twitter that is currently intermittently failing.
---
> [DOCS] add linkcheck ignore for twitter

- .github/workflows/benchmarks_report.yml
- .github/workflows/benchmarks_run.yml
- .github/workflows/ci-wheels.yml
- docs/src/whatsnew/latest.rst
Grabs the changes from:
- #5641 
- #5642
In a new pull request because the `on: push` triggers were getting grumpy.
---
> Artifact upgrade

- .ruff.toml
This pull-request removes the `ruff` rules that we temporarily `ignore`, but are already compliant with.
---
> Remove compliant ignored ruff rules

- .ruff.toml
- benchmarks/benchmarks/plot.py
- lib/iris/pandas.py
- lib/iris/tests/graphics/__init__.py
- lib/iris/tests/unit/pandas/test_pandas.py
This pull-request enforces `ruff` [flake8-import-conventions (ICN)](https://docs.astral.sh/ruff/rules/#flake8-import-conventions-icn) compliance.
---
> ruff ICN rule compliance

- .ruff.toml
- lib/iris/fileformats/pp.py
- lib/iris/tests/integration/netcdf/test_delayed_save.py
- lib/iris/tests/integration/test_regridding.py
This pull-request enforces `ruff` [NumPy specific rules (NPY)](https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy) compliance. 
---
> ruff NPY rule compliance

- docs/src/whatsnew/latest.rst
Forgot to add a whatsnew to #5685, this is fixing that!
(Thanks @trexfeathers for catching!)
> Added whatsnew to warnings PR

- lib/iris/_concatenate.py
- lib/iris/_data_manager.py
- lib/iris/_lazy_data.py
- lib/iris/_merge.py
- lib/iris/analysis/_area_weighted.py
- lib/iris/analysis/_interpolation.py
- lib/iris/analysis/_regrid.py
- lib/iris/analysis/cartography.py
- lib/iris/analysis/geometry.py
- lib/iris/analysis/maths.py
- lib/iris/analysis/stats.py
- lib/iris/analysis/trajectory.py
- lib/iris/config.py
- lib/iris/util.py
Progressing numpydoc strings adoption, #4721.
---
> DOCS: numpydocs 5

- docs/src/further_topics/filtering_warnings.rst
No What's New entry as this page is still new for Iris 3.8 .
---
> Update line number references in filtering_warnings.rst .

- lib/iris/fileformats/netcdf/loader.py
Update docstring of keyword args.
---
> DOCS: Update docstring of keyword args

- docs/src/further_topics/which_regridder_to_use.rst
> Regrid docs fix

- docs/src/whatsnew/3.8.rst
Change whatsnew title for the 3.8.0 release.
> Whatsnew update for 3.8.0

- docs/src/whatsnew/3.8.rst
Updated with release changes from the v3.8.x branch
> Trial 3v8 mergeback

- lib/iris/tests/unit/common/lenient/test__lenient_client.py
> pytest migration for unit.common.lenient.test__lenient_client

- lib/iris/tests/unit/common/mixin/test__get_valid_standard_name.py
> pytest migration for unit.common.mixin.test__get_valid_standard_name

- lib/iris/tests/unit/common/mixin/test_CFVariableMixin.py
> pytest migration for unit.common.mixin.test_CFVariableMixin

- lib/iris/tests/_shared_utils.py
- lib/iris/tests/unit/cube/test_Cube.py
- lib/iris/tests/unit/cube/test_CubeAttrsDict.py
- lib/iris/tests/unit/cube/test_CubeList.py
- lib/iris/tests/unit/cube/test_Cube__aggregated_by.py
- lib/iris/tests/unit/cube/test_Cube__operators.py
> converted cube directory tests to pytest

- lib/iris/tests/unit/common/metadata/test_CubeMetadata.py
> pytest migration for unit.common.metadata.test_CubeMetadata

- lib/iris/tests/unit/common/metadata/test_CoordMetadata.py
> pytest migration of unit.common.metadata.test_CoordMetadata

- docs/src/whatsnew/latest.rst
> What's New entry for SciTools/iris#5740

- docs/src/whatsnew/3.9.rst
> `v3.9.x` mergeback

- docs/src/whatsnew/latest.rst
- lib/iris/_merge.py
This removes a workaround for https://github.com/dask/dask/issues/2273, which was solved in 2017.
---
---
> Remove outdated workaround for data type issue with `da.stack`

- docs/src/whatsnew/latest.rst
Covers 3 separate developments.
> Whatsnews for some benchmark work.

- docs/src/developers_guide/contributing_benchmarks.rst
Used a note to highlight some text on the Testing page.
---
---
> DOCS: Used a note to highlight some text on the Testing page

- docs/src/whatsnew/latest.rst
- requirements/py310.yml
- requirements/py311.yml
- requirements/py312.yml
Should fix the plotting problems in #6029
See https://github.com/matplotlib/matplotlib/issues/28567
> Pin matplotlib != 3.9.1

- docs/src/whatsnew/latest.rst
> Update cf_table v85

- lib/iris/experimental/geovista.py
> DOCS: fix typo for class reference

- docs/src/whatsnew/3.10.rst
> Whats new updates for v3.10.0 .

- docs/src/whatsnew/3.10.rst
> v3.10.0 merge-back

- requirements/py310.yml
- requirements/py311.yml
- requirements/py312.yml
- requirements/pypi-core.txt
> Add dask pin

- docs/src/whatsnew/3.11.rst
Please double check:
- all references of release candidate are removed
- all relevant dates have been adjusted
- no necessary pins or bugfixes are missing from main
- all documentations renders well
> V3.11.x.updates

- docs/src/further_topics/ugrid/other_meshes.rst
See https://github.com/SciTools/iris/pull/6295#issuecomment-2609540187
> Revert "Fix broken link. (#6246)"

- .github/workflows/ci-linkchecks.yml
> Added link checker workflow.

- docs/src/conf.py
I meant to include this in #6386, but it got left out
> Remove obsolete link-check config.

- docs/Makefile
- docs/src/Makefile
Missing part of #6386 (#6392 and #6394).
---
---
> docs: purge linkcheck within makefile

- docs/src/whatsnew/3.12.rst
Please preview the documentation as part of the review
> Whats new updates for v3.12.1

- docs/src/community/iris_xarray.rst
Closes SciTools/iris#6427
@pp-mo you've made the link-check process so much less painful. Chapeau 🎩
---
---
> Fix broken link SciTools/iris#6427

- docs/src/whatsnew/3.12.rst
- docs/src/whatsnew/latest.rst
**Please merge via merge-commit** (not squash)
---
---
> 3.12.1 mergeback

- docs/src/whatsnew/3.12.rst
- lib/iris/fileformats/netcdf/saver.py
- lib/iris/tests/integration/netcdf/test_delayed_save.py
- lib/iris/tests/integration/netcdf/test_general.py
- lib/iris/tests/unit/fileformats/pp/test__interpret_field.py
> 3.12.2 mergeback

- .github/workflows/ci-linkchecks.yml
- .lycheeignore
Not sure how to test this without merging. Maybe we just give it a go?
- #6442 
- #6443 
- #6444 
- #6446 
- #6447 
- #6449 
- #6450
- #6454
---
---
> Fix linkcheck failures

- tools/release_do_nothing.py
An action on me from a previous release.
> Some do-nothing reminders about the next release

- docs/src/whatsnew/latest.rst
- lib/iris/__init__.py
> Whatsnew for derived-bounds 

- docs/src/whatsnew/latest.rst
- lib/iris/tests/integration/netcdf/test_attributes.py
> Add round trip test for calendar attribute

- docs/src/whatsnew/latest.rst
- lib/iris/tests/unit/util/test_make_gridcube.py
- lib/iris/util.py
> Added make_gridcube utility.

- docs/src/developers_guide/contributing_pytest_conversions.rst
Added some minor changes to the conversion guide, after spending some time using the checklist ourselves.
> Updated the PyTest conversion guide 

- docs/src/whatsnew/3.13.rst
This pull-request is the `iris` v3.13.0 release merge-back.
:exclamation: Please use a **MERGE** commit, **not** a squash commit :exclamation:
---
---
> whatsnew updates for v3.13.0

- lib/iris/tests/unit/fileformats/cf/test_CFUGridAuxiliaryCoordinateVariable.py
- lib/iris/tests/unit/fileformats/cf/test_CFUGridConnectivityVariable.py
- lib/iris/tests/unit/fileformats/cf/test_CFUGridMeshVariable.py
The other content in the directory has already been converted.
> Convert `tests/unit/fileformats/cf` mesh content to PyTest

- lib/iris/tests/unit/constraints/test_Constraint_equality.py
- lib/iris/tests/unit/constraints/test_NameConstraint.py
> Converted all unit/constraints tests into pytest

- lib/iris/tests/unit/analysis/test_Linear.py
- lib/iris/tests/unit/analysis/test_MAX.py
- lib/iris/tests/unit/analysis/test_MAX_RUN.py
- lib/iris/tests/unit/analysis/test_MEAN.py
> PYTEST: Linear, MAX, MAX_RUN, MEAN

- lib/iris/tests/unit/time/test_PartialDateTime.py
> Converted all unit/time tests into pytest

- lib/iris/tests/unit/test_Future.py
- lib/iris/tests/unit/test_sample_data_path.py
> Converted all unit/root tests into pytest

- lib/iris/tests/unit/analysis/test_MEDIAN.py
- lib/iris/tests/unit/analysis/test_MIN.py
- lib/iris/tests/unit/analysis/test_Nearest.py
- lib/iris/tests/unit/analysis/test_PERCENTILE.py
> PyTest: MEDIAN, MIN, Nearest, PERCENTILE

- lib/iris/tests/unit/analysis/test_MEDIAN.py
> Action review comments from #6644

- lib/iris/tests/unit/analysis/test_MAX_RUN.py
- lib/iris/tests/unit/analysis/test_MEAN.py
- lib/iris/tests/unit/analysis/test_PROPORTION.py
- lib/iris/tests/unit/analysis/test_PercentileAggregator.py
- lib/iris/tests/unit/analysis/test_PointInCell.py
- lib/iris/tests/unit/analysis/test_RMS.py
- lib/iris/tests/unit/analysis/test_STD_DEV.py
- lib/iris/tests/unit/analysis/test_SUM.py
- lib/iris/tests/unit/analysis/test_VARIANCE.py
- lib/iris/tests/unit/analysis/test_WPERCENTILE.py
- lib/iris/tests/unit/analysis/test_WeightedPercentileAggregator.py
- lib/iris/tests/unit/analysis/test__axis_to_single_trailing.py
> Converted remainder of unit/analysis/root into pytest

- docs/src/whatsnew/3.13.rst
> Whats new updates for `v3.13.1`
