lib/iris/coords.py
Adds some detail about the args and kwargs to the `DimCoord.__init__` docstring.  I noticed this omission this morning while helping an inexperienced user who needs to create a `DimCoord` from scratch.
I've given some thought to the descriptions for `points`, `bounds` and `circular`, but everything else is a direct copy/paste from the equivalent `Coord` docstring.  I also tweaked the description for `points` in the `Coord` version, as this way scans better in my head.
A couple of things I'm not sure of:
* I've used "numpy array-like" in the new points description.  Is this a concept that we can assume users are familiar with, or is there a better way of saying it?  If this is the best way, should I also use it for bounds, and for points and bounds in the `Coord.__init__` docstring?
* …
=> Populate `DimCoord.__init__` docstring

docs/iris/src/userguide/cube_maths.rst, docs/iris/src/userguide/navigating_a_cube.rst, docs/iris/src/whatsnew/contributions_3.0.0/docchange_2020-Aug-25_clarify_unit_handling.txt
Given that we have clarified our position on units, as detailed in #3708, our interpretation of units should be made clear somewhere in the documentation. I have done this as part of a discussion on the functional effect units have on arithmetic within the user guide, which was also missing and is probably also worth documenting.
=> Clarify unit handling

lib/iris/common/resolve.py
This PR fixes the case where free dimension flipping of the src to tgt mapping was not constrained to the case of src and tgt cubes of equal dimensionality.
Testing will follow as a separate task, as per all new code introduced for the cube arithmetic over-haul.
=> [FB] [PI-3478] Fix resolve free flip of src/tgt mapping

docs/iris/src/whatsnew/latest.rst
This PR adds a few `whatsnew` entries relevant to cube arithmetic.
=> [FB] [PI-3478] cube arithmetic whatsnew entries

docs/iris/src/index.rst
Added a note at the top of the main index page to highlight the legacy documentation.
Minor layout tweaks to ensure readability.
=> Legacy doc notice

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/issue.md
This PR performs some minor tidying of the repo GitHub `Issues` templates. 
Changes include...
Renaming the template files to remove leading dashes, which cause major headaches. Just for reference, I used the following command to do this e.g.,
```shell
> git mv -- `---bug-report.md` bug-report.md
```
For reference, the following [resource](https://www.cyberciti.biz/faq/linuxunix-move-file-starting-with-a-dash/) was pretty useful.
Changed and aligned some of the spacing and wording for the bug, feature and documentation templates.
Added a new `config.yml` to turn-off blank issues, and force users to use the new `issue.md` template, which adds the `New: Issue` label to the issue - so now **all** issues raised by the community will have a `New` label, which makes it easier for core …
=> tidy issue templates

ci/requirements/readthedocs.yml, docs/iris/src/whatsnew/latest.rst
=> Add "What's New" entries for unpinning Cartopy, Matplotlib, Proj

lib/iris/quickplot.py
This PR uses `packaging.version` to safely parse version strings.
See here for a [fuller](https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python) (opinionated) discussion.
=> Parse with packaging version

docs/iris/src/userguide/cube_maths.rst, docs/iris/src/whatsnew/contributions_3.0.0/bugfix_2019-Nov-21_cell_measure_attributes.txt, docs/iris/src/whatsnew/contributions_3.0.0/docchange_2020-Aug-25_clarify_unit_handling.txt, docs/iris/src/whatsnew/contributions_3.0.0/incompatiblechange_2020-May-15_change_default_unit_loading.txt, docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2019-Nov-21_netcdf_ancillary_data.txt, docs/iris/src/whatsnew/latest.rst
This PR tidies some valid `whatsnew/contrabutions` entries from the legacy and semi-automated mechanism, into the current and manual `whatsnew/latest`:
- bug-fix contribution from #3800
- doc-change contribution from #3803 
- incompatible-change contribution from #3795 
- new-feature contribution from #3800, #3801 
These contributions are from older feature branches using the then valid legacy approach to documenting `whatsnew` entries, which were then merged to `master`.
=> move whatsnew contributions

.github/labeler.yml, .github/workflows/labeler.yml
This PR uses the GitHub [actions/labeler](https://github.com/actions/labeler) to automate the process of labelling pull-requests.
For further information and reference material, also see:
- `actions/labeler` [example](https://selleo.com/til/posts/iumvmfrkhn-automate-pull-request-labels-via-github-actions)
- GitHub [Configuring and managing workflows](https://docs.github.com/en/actions/configuring-and-managing-workflows)
- [A curated list of awesome things related to GitHub Actions](https://github.com/sdras/awesome-actions)
=> Automate pull request labels

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
This PR adds a collapsible markdown section to the **Additional context** section of the **Bug Report** and **Feature Request** issue templates.
Having collapsible markdown sections is particularly handy for user issues that have verbose content, e.g., see the **Additional context** section of https://github.com/SciTools/iris/issues/3821, which inspired this PR.
For further details on collapsible markdown sections, see [here](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab).
Also, see [here](https://github.com/bjlittle/iris/issues/new/choose) for how this PR change is rendered in markdown, on my own forked `master` branch.
=> Add template collapsible markdown sections

docs/iris/src/index.rst
**SciTools** is never mentioned in the docs apart from the Iris gituhb url https://github.com/SciTools/iris.
A link has been added in the landing page for the documentation.
=> Added link to scitools.org.uk on the main index.

docs/iris/src/userguide/regridding_plots/regridding_plot.py, docs/iris/src/whatsnew/latest.rst, lib/iris/common/metadata.py
This PR adds the `whatsnew` entry for #3812.
It also addresses several minor documentation issues that have unfortunately crept in :thinking: 
We need to fix the `sphinx` logger issue #3789
=> whatsnew entry for dependencies

docs/iris/src/userguide/interpolation_and_regridding.rst, docs/iris/src/userguide/real_and_lazy_data.rst, docs/iris/src/whatsnew/contributions_3.0.0/newfeature_2020-Sep-03_lazy_regridding.txt, lib/iris/_lazy_data.py, lib/iris/analysis/__init__.py, lib/iris/analysis/_area_weighted.py, lib/iris/analysis/_regrid.py, lib/iris/cube.py, lib/iris/experimental/regrid.py, lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py, lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py, lib/iris/tests/unit/lazy_data/test_map_complete_blocks.py
This pull request implements lazy regridding for the Linear, Nearest, and AreaWeighted regridders.
Closes #3700
=> Lazy regridding with Linear, Nearest, and AreaWeighted

lib/iris/common/__init__.py, lib/iris/common/lenient.py, lib/iris/common/metadata.py, lib/iris/common/mixin.py, lib/iris/common/resolve.py
This PR adds doc-strings and doc-tests primarily for `iris.common.resolve.Resolve`
Note that, full test coverage for `Resolve` is to follow as part of the roadmap for cube arithmetic - as agreed offline with other core devs
=> [FB] [PI-3478] Add resolve doc-strings

docs/iris/src/whatsnew/latest.rst, lib/iris/analysis/trajectory.py, lib/iris/tests/results/trajectory/tri_polar_latitude_slice.cml
When ```iris.analysis.trajectory.interpolate()``` creates AuxCoords for the coordinates interpolated along, it doesn't give them a ```var_name```.  This causes an error if the coordinates differ in var_name only, because Iris doesn't like having two identical coordinates on the same Cube.
Use case: I had a Cube which was a 2D histogram, with the two coordinates being some diagnostic on day _n_ and the same diagnostic on day _n+1_, so they were the same thing physically and therefore differed in ```var_name``` only.  When I tried to use ```trajectory.interpolate()``` it crashed with "ValueError: Duplicate coordinates are not permitted.".
=> var_name in AuxCoord created by trajectory.interpolate()

docs/iris/src/whatsnew/latest.rst
Bring #3804 "What's New" in line with format changes from #3838.
---
=> Bring #3804 "What's New" in line with format changes from #3838.

docs/iris/src/developers_guide/documenting/whats_new_contributions.rst, docs/iris/src/whatsnew/latest.rst
This PR makes a simple change to the **latest** `whatsnew` to opt to using and citing pull-request authors using their GitHub ID.
On reflection, this might be a better long term approach as:
- It's one less step for the person writing the `whatsnew` entry, as they no longer have to "look up" the authors profile to determine whether their GitHub name matches their GitHub ID
- The GitHub ID is how people are commonly referred to within the GitHub community, so it's easy to cross-reference the GitHub ID with their work on GitHub or locally within a repo, but this is not true for the GitHub name
- We are less likely to make an error when citing the GitHub ID
A built version of this pull-request is available on `readthedocs`, to easily view the rendered changes:
- [latest …
=> whatsnew - using the author github id

.github/ISSUE_TEMPLATE/feature-request.md, docs/iris/src/developers_guide/documenting/whats_new_contributions.rst, docs/iris/src/whatsnew/latest.rst, docs/iris/src/whatsnew/latest.rst.template
This PR adds icon branding to the `whatsnew` section headers.
Some of the icons align with those already chosen for the associated [issues icon templates](https://github.com/SciTools/iris/issues/new/choose).
If and when #3850 is merged, I'll align the `Announcements` section appropriately.
To help reviewers, the rendered `readthedocs` changes of this PR are available:
- [latest whatsnew](https://my-iris.readthedocs.io/en/latest/whatsnew/latest.html).
- [Contribution categories](https://my-iris.readthedocs.io/en/latest/developers_guide/documenting/whats_new_contributions.html#contribution-categories)
---
=> whatsnew - branded section icons

lib/iris/tests/__init__.py
I was following @tkknight's nice new instructions for [installing and running tests](https://github.com/SciTools/iris/blob/3e9a09482658199092dbc57937d0d7de4dd4dbe5/docs/iris/src/installing.rst#running-the-tests), but got a bunch of errors and failures from `assertBoundsTickLabels` and `assertPointsTickLabels` on the [TestGraphicStringCoord](https://github.com/SciTools/iris/blob/3e9a09482658199092dbc57937d0d7de4dd4dbe5/lib/iris/tests/unit/plot/__init__.py#L18) class.  The errors look like this:
```
File "[git-path]/iris/lib/iris/tests/unit/plot/test_plot.py", line 57, in test_xaxis_labels_with_axes
self.assertBoundsTickLabels("xaxis", ax)
File "[git-path]/iris/lib/iris/tests/unit/plot/__init__.py", line 45, in assertBoundsTickLabels
actual = …
```
=> Image tests: set agg backend after rcdefaults

docs/iris/src/whatsnew/latest.rst, lib/iris/plot.py, lib/iris/tests/unit/plot/__init__.py
Addresses #3848 (and the duplicate issue #3821).
The replacement formatter is not designed to be an exact copy of IndexFormatter since it seems that IndexFormatter can be considered bugged. Specifically, IndexFormatter would add a duplicate of the label at the 0 tick to the -1 tick. This behaviour was being accounted for by our tests, which have been changed to reflect the new behaviour. The new behaviour also relies on ticks being located precisely on integers (the IndexFormatter would perform some rudimentary rounding operations). This should always be the case since the locator is `MaxNLocator(integer=True)`.
=> Replace deprecated IndexFormatter

docs/iris/src/whatsnew/latest.rst
This PR adds some minor consistency changes to the `whatsnew`
- use double-backticks around package versions
- use link aliases for `iris-grib`, `dask` and `cartopy`
---
=> whatsnew - links and versions

docs/iris/src/whatsnew/latest.rst, docs/iris/src/whatsnew/latest.rst.template
This PR removes the `sphinx` `contents` directive from the `whatsnew`, as its unnecessary to have these section page links rendered.
Users can navigate using the section page links in the LHS sidebar instead.
---
=> whatsnew - remove contents directive

docs/iris/src/whatsnew/latest.rst
A really tiny improvement : I was checking out the new whatsnew format + I noticed that these API refs were subtly wrong + don't function as links.
=> Fix whatsnew api links.

docs/iris/src/whatsnew/latest.rst
Proposed enhancements to the whatsnew feature section on Ancillary Variables.
As noted in [this comment](https://github.com/SciTools/iris/pull/3856#issuecomment-694132458) + replies
=> Link to new classes and methods in the Ancillary variables whatsnew.

etc/cf-standard-name-table.xml
As part of any release, we should ideally also update the CF standard name table to the latest version.
This PR updates the table currently available in iris (v70, released 10 December 2019) to the latest version (v75, released 15 September 2020).
The latest version was only release a couple of days ago, so I suspect that it's unlikely they will do another release before we cut the rc.
=> Update CF standard name table to v75

docs/iris/src/whatsnew/latest.rst
Documenting possible changed behaviour in netcdf loads.
But it really only applies to files that were "wrong".
=> Whatsnew for effects on aux factories of units defaulting to 'unknown'.

docs/iris/src/developers_guide/contributing_documentation.rst, docs/iris/src/whatsnew/1.0.rst, docs/iris/src/whatsnew/1.1.rst, docs/iris/src/whatsnew/1.10.rst, docs/iris/src/whatsnew/1.11.rst, docs/iris/src/whatsnew/1.12.rst, docs/iris/src/whatsnew/1.13.rst, docs/iris/src/whatsnew/1.2.rst, docs/iris/src/whatsnew/1.3.rst, docs/iris/src/whatsnew/1.4.rst, docs/iris/src/whatsnew/1.5.rst, docs/iris/src/whatsnew/1.6.rst, docs/iris/src/whatsnew/1.7.rst, docs/iris/src/whatsnew/1.8.rst, docs/iris/src/whatsnew/1.9.rst, docs/iris/src/whatsnew/2.0.rst, docs/iris/src/whatsnew/2.1.rst, docs/iris/src/whatsnew/2.2.rst, docs/iris/src/whatsnew/2.3.rst, docs/iris/src/whatsnew/2.4.rst
Remove all **local table of contents** in the documentation.  This aligns with the `latest.rst` approach.  Users can use the **side bar** for navigation instead.
---
=> Remove all local table of contents

docs/iris/src/conf.py
Added 2 urls to be **ignored** when running the **linkcheck** to avoid spamming github when running a **linkcheck**.
Since we have started to use the pull and issue directives:
```
:issue:`9999`
:pull:`9999`
```
... in the **what's new** that is later substituted for a full url, when running the **linkcheck** from **travis** the host (github) may **refuse the connection** as it is essentially being hit frequently from many different travis jobs.  This will show as a **warning/error** and fail the linkcheck travis task.
The ignore urls only covers Iris **pull** and **issue**, it will still check links to **blobs** (source code).
---
=> linkcheck ignore for iris pull and issue url

docs/iris/src/whatsnew/latest.rst
Added whats new for #3873.
Also added an include for common links which will be useful going forward.
I will make a separate PR to add the common links to the ``latest.rst.template``.
---
=> Added whats new for pr3873

docs/iris/src/conf.py, lib/iris/analysis/maths.py, lib/iris/io/__init__.py, requirements/ci/py36.yml, requirements/ci/py37.yml, requirements/docs.txt
This PR **enables adoption** (but does not force) of **numpy docstrings**.  This solves  https://github.com/SciTools/iris/issues/3841
Enabling [napolean ](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/sphinxcontrib.napoleon.html) sphinx extension to allow for **google style docstrings** and now also **numpy style docstrings**.
Just by enabling this extension causes build warnings due to existing incorrectly formatted docstrings.  A couple of files needed to be updated to allow for a clean build.  
- `lib/iris/io/__init__.py` - Correct formatting is now applied when rendered.  
- Live: https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/io.html#iris.io.save
- This PR: https://iris-test-doc.readthedocs.io/en/latest/generated/api/iris/io.html#iris.io.save
- …
=> Use napolean extension in docs to handle numpy docstrings too

docs/iris/src/Makefile, docs/iris/src/developers_guide/contributing_documentation.rst, docs/iris/src/userguide/real_and_lazy_data.rst
Configured **sphinx-build** to promote **warnings to errors** when building the documentation via ``make html``.
Updated the **Makefile** to use two new arguments:
- ``-W``. Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
- ``--keep-going``. With -W option, keep going processing when getting warnings to the end of build, and sphinx-build exits with exit status 1.
Also updated the ``contributing to the documentation`` in the Iris docs to state that warnings are promoted to errors.
For more info see https://www.sphinx-doc.org/en/master/man/sphinx-build.html?highlight=--keep-going#cmdoption-sphinx-build-W
Before the overhaul of the Iris docs (https://github.com/SciTools/iris/pull/3752), there were many warnings in the …
=> Docs warning to error

docs/iris/src/common_links.inc, docs/iris/src/conf.py, docs/iris/src/developers_guide/contributing_getting_involved.rst, docs/iris/src/index.rst, requirements/ci/py36.yml, requirements/ci/py37.yml, requirements/docs.txt
Added some panels and use of badges on the documentation index, in order to make it more visible to users.
- The link to the legacy docs was in a note, now moved to lower on the page and uses a badge link instead.
- Added panels using the [sphinx-panels](https://sphinx-panels.readthedocs.io/en/latest/) extension.
- Made the index on the main body hidden, now it only appears in the sidebar.
- Added the dependency for `sphinx-panels`.
- Moved the `Iris API` link in the sidebar to the Reference section
You can view all rendered changes at https://iris-test-doc.readthedocs.io/en/latest/ for the lifetime of this PR.
---
=> Documentation homepage, use of panels for visibility to users

docs/iris/src/conf.py, docs/iris/src/developers_guide/contributing_getting_involved.rst, docs/iris/src/developers_guide/gitwash/index.rst, docs/iris/src/further_topics/index.rst, docs/iris/src/further_topics/lenient_maths.rst, docs/iris/src/further_topics/lenient_metadata.rst, docs/iris/src/further_topics/metadata.rst, docs/iris/src/index.rst, docs/iris/src/techpapers/index.rst, docs/iris/src/techpapers/missing_data_handling.rst, docs/iris/src/userguide/cube_maths.rst, docs/iris/src/userguide/real_and_lazy_data.rst, docs/iris/src/userguide/saving_iris_cubes.rst, docs/iris/src/userguide/subsetting_a_cube.rst, lib/iris/common/__init__.py, lib/iris/common/lenient.py, lib/iris/common/metadata.py, lib/iris/common/mixin.py, lib/iris/common/resolve.py, lib/iris/coords.py
This PR adds the supporting documentation for the common metadata API, and the lenient infrastructure for metadata and cube maths to `master` from the feature branch `cube-arithmetic-docs`.
---
=> Cube arithmetic docs to master

docs/iris/src/conf.py
Add a linkcheck ignore for http://cfconventions.org.  This is due to the url often failing during the linkcheck.
```
(line    9) ok        http://cfconventions.org
(line   40) ok        https://scitools.org.uk/
(line   34) redirect  http://www.numpy.org/ - permanently to https://numpy.org/
(line   14) redirect  https://github.com/SciTools/cf_units - permanently to https://github.com/SciTools/cf-units
(line   40) ok        https://scitools.org.uk/iris/docs/v2.4.0/
(line   34) redirect  https://dask.pydata.org/en/latest/ - with Found to https://docs.dask.org/en/latest/
(line   14) broken    http://cfconventions.org/standard-names.html - HTTPConnectionPool(host='cfconventions.org', port=80): Max retries exceeded with url: /standard-names.html (Caused by …
```
=> linkcheck ignore http://cfconventions.org

docs/iris/src/further_topics/index.rst, docs/iris/src/whatsnew/latest.rst
This PR adds various missing `whatsnew` entries relevant to the pending `iris` 3.0.0rc0 release.
The rendered `whatsnew` including this PRs changes are available [here on readthedocs](https://my-iris.readthedocs.io/en/latest/whatsnew/latest.html).
---
=> whatsnew additions

docs/iris/src/whatsnew/latest.rst, lib/iris/util.py
The PR marks the `iris.util.as_compatible_shape` function for deprecation from `iris` in a future release, in preference for using an instance of the `iris.common.resolve.Resolve` class.
---
=> Deprecate iris.util.as_compatible_shape

docs/iris/src/index.rst
This PR hides the new `Further topics` TOC from the documentation main page, but keeps it in the sidebar.
Thanks @tkknight :eyes: 
---
=> hide the further topics toc

docs/iris/src/whatsnew/3.0.rst, docs/iris/src/whatsnew/index.rst, docs/iris/src/whatsnew/latest.rst, lib/iris/__init__.py
This PR bumps the `master` version to `3.1.dev0` and pins the `latest` for the `whatsnew` to `v3.0`, and also replaces the `latest.rst` with the `latest.rst.template` (empty template), in readiness for lots of lovely `3.1` contributions :smile: 
Once this PR is merged the `v3.0.x` release branch can be cut...
---
=> bump whatsnew latest and version to 3.1.dev0

docs/iris/src/whatsnew/3.0.rst
This PR adds the missing `whatsnew` entry for the associated pull-request #3791.
See the rendered changes of this PR on [readthedocs](https://my-iris.readthedocs.io/en/latest/whatsnew/3.0.html#internal). 
---
=> add #3791 whatsnew entry

docs/iris/src/whatsnew/3.0.rst
This PR orders the `Release Highlights`, with some minimal rewording.
The rendered changes of this PR is available in [readthedocs](https://my-iris.readthedocs.io/en/latest/whatsnew/3.0.html). 
---
=> reorder release highlights

docs/iris/src/further_topics/lenient_metadata.rst, docs/iris/src/whatsnew/3.0.rst
Fixed a couple of  **typos**.
Note this PR is for the **v3.0.x branch.**
---
=> Fix spelling

docs/iris/src/developers_guide/release.rst
Some changes to the release documentation, identified while working through the Iris 3.0 release process.
---
=> Release Docs Improvements

requirements/setup.txt
This PR targets the `v3.0.x` release branch, and relaxes the requirements used by `setup.py`.
This is the result of `conda build` issues for `iris` as is. The building of `pyke` is performed as part of `PEP517` and `PEP518` using the PyPI proxy package `scitools-pyke`, as per the `pyproject.toml`.
---
=> Relax setup.py setup requirements

lib/iris/fileformats/netcdf.py
As mentioned : https://github.com/SciTools-incubator/iris-ugrid/pull/24#discussion_r511917499
I think this is desirable, to enable iris-ugrid to represent unstructured data with a new derived class `Ucube(Cube)`.
By allowing the post-modify action to return a new object, the iris-ugrid loader can replace Cube-s with Ucube-s, instead of [patching a cube instance](https://github.com/SciTools-incubator/iris-ugrid/blob/25ba11b03a88702fb502836cf33cfa2129cbfca3/iris_ugrid/ugrid_cf_reader.py#L214).
Apart from being cleaner, I think it will eventually prove essential for unstructured cubes to belong to a specialised subclass of `Cube`, so that we can use inheritance and overriding to efficiently extend features.
See for example #3914, which assumes we will use a `Ucube(Cube)` class to extend …
=> Allow cube-adjust to return a new cube.

lib/iris/cube.py, lib/iris/experimental/representation.py, lib/iris/tests/unit/cube/test_Cube.py
Now with no specific reference to ugrid.
This is now an extensive refactor of the Iris Cube `summary` and `_repr_html_` methods.
Including changes needed to enable the forthcoming iris-ugrid `UCube`s to produce "extended" cube summmaries.
I have added testing for the new factored-out helper methods.  But I haven't provided any test of how modifying these can produce extended cube summaries, as its not really an "API" + the requirement is hard to generalise.
That usage will eventually get tested by the specifics in iris-ugrid.
Meanwhile, you should see that all the existing tests simply pass. :bow_and_arrow: 
Proposals for the specific use of this in iris-ugrid are here : https://github.com/SciTools-incubator/iris-ugrid/pull/26
=> Cube print respin

requirements/ci/py36.yml, requirements/ci/py37.yml, requirements/core.txt
This PR pins `cftime<1.3.0`. The `iris` tests are broken with the latest released version `1.3.0`, which pulls from [PyPI](https://pypi.org/project/cftime/).
Pinning will give us time to investigate and either fix `iris` and/or feedback to the `cftime` developers.
---
=> pin cftime<1.3.0

docs/iris/src/userguide/saving_iris_cubes.rst, docs/iris/src/whatsnew/3.0.rst, lib/iris/fileformats/cf.py, lib/iris/fileformats/netcdf.py, requirements/ci/py36.yml, requirements/ci/py37.yml
The User Guide and `iris.fileformats.netcdf.save()` docstring have been updated with the correct version of the CF version that netCDF files are saved with.
=> Updated CF saver version in User Guide and docstring

docs/iris/src/conf.py, docs/iris/src/userguide/plotting_a_cube.rst
Add `http://effbot.org` to the list of URLs to ignore during documentation link checking, as its service availability is variable and caused sporadic CI link check failures.
Also removed `python2.7` reference in User Guide, thanks to @rcomer :eyes: ([great spot](https://github.com/SciTools/iris/pull/3924#issuecomment-733634993))
---
=> ignore url for doc link check

docs/iris/src/whatsnew/3.0.rst
Having inserted `units=1` all over my user code where I'd created coordinates from scratch, I realised I couldn't see this change in the whatsnew.  Obviously it was the same change as the NetCDF loading behaviour, but a user doesn't need to be loading NetCDF to trip over it.
---
=> whatsnew for coord default units

docs/iris/src/whatsnew/3.0.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py
I started looking at this method with a view to fixing #3921, but once I looked couldn't ignore the fact that this method seemed a bit inefficient: we ultimately only want the elements of `vary` that exist as keys in `coord`'s attributes dictionary, so I think we should only loop through those keys to begin with.
I've added one simple test for the #3921 case.  Note there is also one existing test for this method in the [legacy tests](https://github.com/SciTools/iris/blob/v3.0.x/lib/iris/tests/test_cdm.py#L329).
I'd like to get this into Iris v3 if possible, as I believe lenient cube arithmetic will increase the prevalence of Frankencubes*.  So this method will get called more often.  And the change is only small :innocent: 
Closes #3921.
---
***Frankencube** _noun_: a cube with multiple …
=> Cube._summary_coord_extra: efficiency and bugfix

docs/iris/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py
Resolves #3602 
I have just started to work on this, and after adding a short test I get 5 failures when testing `lib/iris/tests/unit/cube/test_Cube.py`, all `AssertionError`s similar to:
```
AssertionError: CML do not match: /home/gcaria/github/iris/lib/iris/tests/results/unit/cube/Cube/xml/checksum_ignores_masked_values.cml
```
which don't seem to be related to the test I've added. I've followed the instructions for [running the tests](https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_running_tests.html) so I'm not sure what I'm missing.
=> Add string arguments for Cube methods

docs/iris/gallery_code/meteorology/plot_lagged_ensemble.py, docs/iris/src/whatsnew/latest.rst
Iris has moved on _a lot_ since many of the gallery examples were added.  This PR simplifies the seasonal forecast example as well as dropping the old school "%s" string formatting.
---
=> Gallery: update seasonal ensemble example

docs/iris/gallery_code/oceanography/plot_atlantic_profiles.py, docs/iris/src/userguide/regridding_plots/interpolate_column.py, docs/iris/src/whatsnew/latest.rst, lib/iris/plot.py, lib/iris/quickplot.py, lib/iris/tests/results/imagerepo.json, lib/iris/tests/unit/quickplot/test_plot.py
Take two of #2901, this time with requisite changes to target image-hashes. Have removed references to previous acceptable image-hashes in [`imagerepo.json`](https://github.com/SciTools/iris/pull/3906/files#diff-4ba82ce2a2dffedb75f4ffcbf4c1053c374a6cd07215bcd64b5c96f07bf97acd) since this is a complete change in expected plot rather than just a minor shift.
Twin PR: SciTools/test-iris-imagehash#37.
---
=> Put cube data on the x axis if plotting just a cube against a vertical or y coordinate

noxfile.py, requirements/ci/py36.yml, requirements/ci/py37.yml
This PR drops the use of `pip` packages from the `conda` CI requirements and uses the `conda` equivalent packages instead.
This PR also extends `nox` to offer `python` sessions for both `3.6` and `3.7`, and opting to use `pip install --editable .` for `iris` instead of `python setup.py develop`, but with `--no-deps` (as all the package dependencies are satisfied by `conda` and therefore not required to be checked by `pip`)
---
=> CI requirements drop pip packages

docs/iris/src/whatsnew/3.0.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py
Stop Cube.collapse from re-forming a weights array when it is 1-dimensional.
This allows to pass a 1-D weights array relating to a (single) collapse dimension, instead of the weights always having to be the 
shape of the whole cube.
This is supported by the API of functions like `np.average` (and `da.average`), so this provides access to those features.
(N.B. to make this work as expected with **_lazy_** data, we also need to pass a simple integer as the axis. instead of a "list of one axis", because the underlying numpy  + dask  functions require this when passing a 1D weights array.)
Closes #3707
=> Add support for 1-d weights in collapse.

lib/iris/cube.py
Removed the warning that `Cube.convert_units` will load lazy data.  Looks like this has not been true since #2964.
```python
In [1]: import iris
In [2]: import dask.array as da
In [3]: import numpy as np
In [4]: cube = iris.cube.Cube(da.from_array(np.arange(5)), units='m')
In [5]: cube.has_lazy_data()
Out[5]: True
In [6]: cube.convert_units('feet')
In [7]: cube.has_lazy_data()
Out[7]: True
```
Since the change is tiny, I'm targeting the v3 branch.  Happy to switch to `master` though.
---
=> Remove warning for convert_units on lazy data

docs/iris/src/common_links.inc, docs/iris/src/developers_guide/contributing_ci_tests.rst
Remove references to `stickler-ci` in the documentation.
See #3928, where `sticker-ci` was dropped as a service, and replaced by use of a dedicated `nox` session.
---
=> drop stickler references in docs

docs/iris/src/common_links.inc, docs/iris/src/developers_guide/contributing_ci_tests.rst, docs/iris/src/developers_guide/contributing_documentation.rst, docs/iris/src/developers_guide/contributing_graphics_tests.rst, docs/iris/src/developers_guide/contributing_pull_request_checklist.rst, docs/iris/src/developers_guide/documenting/whats_new_contributions.rst, docs/iris/src/whatsnew/3.0.rst
Update the documentation to replace `travis-ci` references with `cirrus-ci`.
---
=> update docs for travis-ci to cirrus-ci

docs/iris/src/developers_guide/contributing_running_tests.rst
This PR adds a section to the documentation for testing with `nox` for `iris` developers.
---
=> docs for nox

docs/iris/src/conf.py, lib/iris/common/resolve.py, lib/iris/tests/unit/common/resolve/__init__.py, lib/iris/tests/unit/common/resolve/test_Resolve.py
This PR adds the missing unit test coverage for the `iris.common.resolve` module.
**To-do**
Unit test coverage is required for the following `iris.common.resolve.Resolve` methods:
---
=> Resolve test coverage

docs/iris/src/installing.rst, docs/iris/src/userguide/citation.rst, docs/iris/src/userguide/cube_maths.rst, docs/iris/src/whatsnew/latest.rst
As mentioned in Issue 3949, installation of Iris on Ubuntu was very difficult. I described an easy way to install Iris on Ubuntu without conda in the installation file in the documentation.
=> Extended the installation description

docs/iris/src/installing.rst
This is a simple change to capitalise a heading in the Iris installation instructions - aligning the content of #3958 with the changes in #3940 (they are misaligned due to the merge-back timing).
---
=> Capitilise installation heading

docs/iris/src/conf.py, docs/iris/src/whatsnew/3.0.1.rst, docs/iris/src/whatsnew/index.rst, lib/iris/__init__.py, lib/iris/aux_factory.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/unit/aux_factory/test_HybridPressureFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSg1Factory.py, lib/iris/tests/unit/aux_factory/test_OceanSg2Factory.py, lib/iris/tests/unit/aux_factory/test_OceanSigmaFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSigmaZFactory.py, lib/iris/tests/unit/fileformats/netcdf/test__load_aux_factory.py
This PR adds graceful behaviour to the creation of auxiliary factories, such that formula terms that have `units` of `unknown` but **must** be dimensionless (`1`), have their `units` promoted from `unknown` to `1`.
This concession in behaviour is the result of real-world examples where NetCDF files missing an appropriate `units` attribute on formula terms variables, cause the failure of the expected auxiliary factory (and derived coordinate) to appear on the cube.
Previously, `iris` 2.4.0 loaded such files as expected, but as a result of #3795, `iris` 3.0.0 (advertised this as breaking behaviour) fails to behave as `iris` 2.4.0.
This PR alleviates this breaking change somewhat for the community, as it would cause major issues that are not easily avoidable. 
---
[Consult Iris pull request …
=> Promote unknown units to dimensionless in aux factories

docs/iris/src/conf.py, docs/iris/src/whatsnew/3.0.1.rst, docs/iris/src/whatsnew/index.rst, lib/iris/aux_factory.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/unit/aux_factory/test_HybridPressureFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSg1Factory.py, lib/iris/tests/unit/aux_factory/test_OceanSg2Factory.py, lib/iris/tests/unit/aux_factory/test_OceanSigmaFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSigmaZFactory.py, lib/iris/tests/unit/fileformats/netcdf/test__load_aux_factory.py
This PR is the merge back from `v3.0.x` to `master`, containing the outstanding changes banked for the recent `iris` 3.0.1 release.
---
=> Merge back v3p0p1

docs/iris/src/developers_guide/documenting/whats_new_contributions.rst, docs/iris/src/whatsnew/3.0.1.rst, docs/iris/src/whatsnew/3.0.rst, docs/iris/src/whatsnew/latest.rst, docs/iris/src/whatsnew/latest.rst.template
This PR changes the default use of bullet points in the documentation whatsnew (excluding the `Highlights` dropdown) for enumerated lists.
This helps to easily quantify the number of entries per section, but more importantly it provides a more precise way to reference entries e.g., when referencing a whatsnew entry with users in a written discussion, instead of:
```
See the fifth bullet point down of the Incompatible Changes section...
```
we now have something like:
```
See Incompatible Changes section, entry [5].
```
Also, it's easier to find a numbered entry rather than forcing users to count bullet points... you kinda get the gist :wink: 
These changes have been applied to the `latest.rst`, `latest.rst.template`, `3.0.1.rst` and `3.0.rst`. For convenience, see the rendered results:
* …
=> Docs whatsnew enumerated lists

docs/iris/src/common_links.inc
This PR adds the `@github` name of the `iris` core developers (in alphabetical order) to the documentation common links.
It also organises the existing common resource links (in alphabetical order) as a separate category (and removing a duplicate in the process).
I attempted to use the `rst` `only` directive (see #3971) as a comment heading for each category, but his caused the following warning:
```shell
checking consistency... /net/home/h05/itwl/projects/git/iris/docs/iris/src/techpapers/change_management.rst: WARNING: document isn't included in any toctree
```
which causes the CI docs build to fail. Never mind.
After this PR is merged (and #3971), we can rationalise the `whatsnew` to remove core developer links.
--- …
=> reorganise docs common links + add core devs

docs/iris/src/whatsnew/latest.rst, docs/iris/src/whatsnew/latest.rst.template, lib/iris/coords.py
This PR clarifies in the documentation that `iris.coords.Coord` is an abstract base class (ABC) as of `iris` 3.0.0, and therefore users cannot create an instance of it.
It also organises the end section of the `whatsnew` into two categories, one for entry author names, and the other for entry resources, using the `rst` `only` directive, see [here](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/conditions.html).
---
=> document that iris.coords.Coord is an ABC

docs/iris/src/whatsnew/latest.rst, docs/iris/src/whatsnew/latest.rst.template
This PR realises the value of #3972, and removes the explicit `rst` URL references of `iris` core dev names from the `latest.rst`.
Also, tweak the `latest.rst` and `latest.rst.template` comment titles.
---
=> remove explicit URLs for core dev names from latest.rst

docs/iris/src/common_links.inc, docs/iris/src/whatsnew/latest.rst, lib/iris/tests/test_basic_maths.py
test_incompatible_dimensions used a ragged array for the test, which has been deprecated in numpy, and now fails if dtype is anything other than object.  This test appears to be checking that the addition of a [2x4] masked array to a [2x3] masked cube, iris should raise a ValueError. This commit fixes the creation of `data3` object to be a [2x4] non-ragged array, preventing the *different* ValueError raised by numpy!
---
=> Fix test_incompatible_dimensions test

docs/src/whatsnew/latest.rst
Small correction to the **ReStructuredText** syntax in the **latest.rst** to ensure it becomes a link to the API.
---
=> Corrected ReStructuredText syntax

docs/src/conf.py, docs/src/developers_guide/release.rst, docs/src/whatsnew/latest.rst, docs/src/whatsnew/latest.rst.template
This PR automates the discovery of the `iris` version for the `whatsnew`, and also the `python` version used to build the documentation via the `sphinx` [rst_epilog](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_epilog).
These are available in all `rst` files via `|iris_version|` and `|python_version|` directives.
The rendered version of the `whatsnew` generated by this PR is available [here](https://bjlittle-iris.readthedocs.io/en/latest/whatsnew/latest.html).
The rendered version of the `release` documentation changes from this PR are available [here](https://bjlittle-iris.readthedocs.io/en/latest/developers_guide/release.html#release-steps).
P.S. the `|build_date|` directive is now also available to automate the `whatsnew` release/build date.
---
[Consult …
=> automate docs discovery of iris and python versions

lib/iris/_representation.py, lib/iris/tests/unit/representation/__init__.py, lib/iris/tests/unit/representation/test_representation.py
A simple replacement for #3952
* now based on current "master"
* commits squashed
With this, I'm intending to bank what is now on #3952.
I still think there are some small improvements outstanding, but we can fix those later, along with adding my new cube summary code -- all in subsequent PRs.
So I'm now intending to **put this onto master** (as originally suggested by @bjlittle), 
Future plans... 
Subsequently when adding my new cube-summary code, I will find a quick way not to break the existing `_repr_html_` implementation.
I **think** I can make the string summary close enough in form that I can also make the existing `_repr_html_` code work with minimal changes.  If not, I will leave the existing cube summary code in place, under a different name, until we find time to fix it …
=> Add abstract cube summary

lib/iris/common/metadata.py, lib/iris/coords.py, lib/iris/tests/unit/common/metadata/test_ConnectivityMetadata.py, lib/iris/tests/unit/common/metadata/test_metadata_manager_factory.py, lib/iris/tests/unit/common/mixin/test_CFVariableMixin.py, lib/iris/tests/unit/coords/test_Connectivity.py
Adds the `Connectivity` and accompanying `ConnectivityMetadata` classes - the first of many steps to allow Iris' core data model to represent the [CF-UGRID unstructured mesh format](https://ugrid-conventions.github.io/ugrid-conventions/) in addition to the existing CF structured grid format. Note this is targeting the new [`mesh-data-model`](https://github.com/SciTools/iris/tree/mesh-data-model) feature branch.
'Connectivity' name chosen since the most faithful interpretation of the [UGRID conventions](https://ugrid-conventions.github.io/ugrid-conventions/) is that a topology is made up of one or more self-contained connectivities.
Implemented as another member of [`iris.coords`](https://github.com/SciTools/iris/blob/master/lib/iris/coords.py), since `Connectivity`  benefits from …
=> Connectivity Class (AVD-1595)

.cirrus.yml, docs/src/developers_guide/contributing_running_tests.rst, docs/src/whatsnew/latest.rst, noxfile.py
This PR rationalises the `noxfile.py` of boiler plate code, but also displays the `conda` environment package contents and environment info of the `nox.session`.
This is akin to the same level of detail that was provided on the retired `travis-ci` testing.
---
=> add nox session conda list

docs/src/_templates/footer.html, docs/src/conf.py, docs/src/developers_guide/contributing_documentation.rst, docs/src/installing.rst, docs/src/whatsnew/latest.rst
Add explicit statement of which version Python is used when building the documentation.  This includes:
* Using the Python version as defined in the variable **build_python_version**.  This builds upon the changes from #3981.
* Updating the installing page to state the Python version in the note.
* Added the **build_python_version** to the **html_context** variable in **conf.py** to allow it to be used in the templating for the **footer.html**.  
For the lifetime of this PR the docs can be seen here: https://tkknight-iris-test-doc.readthedocs.io/en/latest/index.html.  Note:
* https://tkknight-iris-test-doc.readthedocs.io/en/latest/installing.html
* https://tkknight-iris-test-doc.readthedocs.io/en/latest/developers_guide/contributing_documentation.html#building
* An updated footer on …
=> Added text to state the Python version used to build the docs.

lib/iris/__init__.py
This PR normalises the `__version__` to the expected [PEP-0440 implicit development release number](https://www.python.org/dev/peps/pep-0440/#implicit-development-release-number) i.e., we can drop the implied `0` point release part - which makes sense as point releases equate to patch releases from a release feature branch e.g., `v3.0.x`
It also avoids `setuptools` issuing the following warning:
```shell
> python setup.py build
<snip>/lib/python3.7/site-packages/setuptools/dist.py:458: UserWarning: Normalizing '3.1.0dev0' to '3.1.0.dev0'
```
---
=> normalise version to implicit development release number

docs/gallery_code/meteorology/plot_COP_maps.py, docs/src/whatsnew/latest.rst
Some bits of this example weren't doing what its comments said it was doing.  Other bits just didn't make sense to me:
* The callback function was supposed to get the "experiment" from the directory name, but the files are all in the top level `sample_data` directory, so this added coordinate was the same regardless of file.  Part of the reason this hasn't been noticed before was probably because the "experiment" coordinate never got used after it was added.  I've updated the callback to get the experiment out of the filename.  Also loaded the two files together, then extracted the cubes in a loop.  This is a little contrived, but gives us an excuse to use the coordinate we went to the trouble of adding with the callback.  It's also the first time I've used `CubeList.extract_cube` (new at …
=> Gallery: update COP maps example 

docs/gallery_code/meteorology/plot_deriving_phenomena.py
A simple one:  I think the days of worrying about Matplotlib v1.2.x should be over.
Given how minor this change is, I'm unconvinced it warrants a whatsnew.
---
=> Gallery: don't support mpl v1.2

lib/iris/_representation.py, lib/iris/tests/unit/representation/test_representation.py
Some small improvements I thought worthwhile.
As a preliminary to adding the new "table based summary" code, as  previewed in #3982
---
=> Cubesummary tidy

.cirrus.yml, docs/src/_templates/footer.html, docs/src/common_links.inc, docs/src/conf.py, docs/src/developers_guide/contributing_documentation.rst, docs/src/developers_guide/contributing_running_tests.rst, docs/src/further_topics/metadata.rst, docs/src/installing.rst, docs/src/whatsnew/latest.rst, lib/iris/__init__.py, lib/iris/_representation.py, lib/iris/coords.py, lib/iris/cube.py, lib/iris/tests/__init__.py, lib/iris/tests/unit/representation/__init__.py, lib/iris/tests/unit/representation/test_representation.py, noxfile.py, requirements/ci/iris.yml, requirements/ci/py38.yml
This PR updates the `mesh-data-model` feature branch with the latest commits from `master`.
---
=> Update feature branch mesh-data-model

lib/iris/experimental/ugrid.py
This PR is the initial stub content to support the API for `iris.experimental.ugrid.Mesh` et al.
This is targeting the `ng-vat-mesh-api` feature branch, which was forked from the `mesh-data-model` feature branch.
The intent is to merge the `ng-vat-mesh-api` feature branch back to the main `mesh-data-model` feature branch.
---
=> [add ugrid mesh-api stubs

docs/gallery_code/general/plot_anomaly_log_colouring.py, docs/src/common_links.inc, docs/src/conf.py, docs/src/whatsnew/3.0.1.rst, docs/src/whatsnew/3.0.rst, docs/src/whatsnew/latest.rst
This PR updates the documentation `intersphinx_mapping` and addresses `matplotlib` URL issues that were causing the documentation `linkcheck` to fail.
---
=> update intersphinx mapping and matplotlib urls

README.md, docs/src/whatsnew/latest.rst
This PR adds the `pypi` version badge ![PyPI](https://img.shields.io/pypi/v/scitools-iris?color=orange&label=pypi%7Cscitools-iris) to the `README.md`.
It unifies the colour of the `conda-forge` version badge ![Conda](https://img.shields.io/conda/v/conda-forge/iris?color=orange&label=conda-forge%7Ciris) with that of the `pypi` version badge, but also highlights the different package name of Iris from each package distribution.
It also exchanges the `tag` github badge ![GitHub tag (latest by date)](https://img.shields.io/github/v/tag/scitools/iris) for the `release` github badge ![GitHub release (latest by date)](https://img.shields.io/github/v/release/scitools/iris).
Also branded the `twitter` badge ![Twitter Follow](https://img.shields.io/twitter/follow/scitools_iris?color=yellow&label=twi …
=> update readme badges

README.md
This PR updates the `README.md` logo `href` to link directly to `readthedocs`, rather than indirectly via `scitools.org.uk`.
More importantly, the Iris logo image is sourced from `readthedocs`, which means that it will render correctly on `PyPI` instead of the `alt`ernative text which is displayed at present i.e.,
---
=> update readme logo img src and href

setup.py
This PR updates the `setuptools` `description` to keep it inline with our migration from using the word `library` -> `package` in the Iris tag line.
This is most notable on PyPI for `scitools_iris`:
---
=> update setuptools description

.cirrus.yml, docs/src/whatsnew/latest.rst
This PR enables use of the free SciTools Organisation compute credits from `cirrus-ci` for non-draft pull-requests by collaborators on the `SciTools/iris` `master` branch.
---
=> cirrus-ci compute credits

docs/src/developers_guide/release.rst
This PR iterates on the documentation release process, in light of `iris` 3.0.x
---
=> update release process

lib/iris/experimental/ugrid.py
This PR adds additional stubs and a few clarifications
---
=> add additional mesh stubs

README.md, docs/gallery_code/general/plot_anomaly_log_colouring.py, docs/gallery_code/meteorology/plot_COP_maps.py, docs/gallery_code/meteorology/plot_deriving_phenomena.py, docs/src/common_links.inc, docs/src/conf.py, docs/src/whatsnew/3.0.1.rst, docs/src/whatsnew/3.0.rst, docs/src/whatsnew/latest.rst, lib/iris/_representation.py, lib/iris/tests/unit/representation/test_representation.py, setup.py
This PR updates the `ng-vat-mesh-api` feature branch with the latest updates from the main `mesh-data-model` feature branch.
---
=> Update ng-vat-mesh-api branch

lib/iris/common/metadata.py, lib/iris/experimental/ugrid.py, lib/iris/tests/unit/experimental/ugrid/test_MeshMetadata.py
Implemented the `MeshMetadata` class and tests, in readiness to support the `Mesh` class.
---
=> MeshMetadata class.

docs/src/whatsnew/latest.rst, lib/iris/_constraints.py, lib/iris/analysis/__init__.py, lib/iris/analysis/_regrid.py, lib/iris/experimental/regrid.py, lib/iris/fileformats/_ff.py, lib/iris/fileformats/pp.py, lib/iris/fileformats/pp_load_rules.py, lib/iris/tests/__init__.py, lib/iris/tests/experimental/regrid/test_regrid_conservative_via_esmpy.py, lib/iris/tests/test_cell.py, lib/iris/tests/test_concatenate.py, lib/iris/tests/test_merge.py, lib/iris/tests/unit/analysis/cartography/test_rotate_winds.py, lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py, lib/iris/tests/unit/aux_factory/test_OceanSFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSg1Factory.py, lib/iris/tests/unit/aux_factory/test_OceanSg2Factory.py, lib/iris/tests/unit/aux_factory/test_OceanSigmaFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSigmaZFactory.py, lib/iris/tests/unit/common/metadata/test_BaseMetadata.py, lib/iris/tests/unit/common/metadata/test__hexdigest.py, lib/iris/tests/unit/experimental/regrid/test_regrid_weighted_curvilinear_to_rectilinear.py, lib/iris/tests/unit/fileformats/cf/test_CFReader.py, lib/iris/tests/unit/fileformats/pp/test_PPField.py, lib/iris/tests/unit/fileformats/pp/test__data_bytes_to_shaped_array.py, lib/iris/tests/unit/lazy_data/test_lazy_elementwise.py
This PR removes deprecated NumPy aliases of builtin types, which is required to avoid warnings starting with NumPy 1.20.0.
---
=> Stop using deprecated aliases of builtin types

lib/iris/experimental/ugrid.py
@trexfeathers Here's my first draft punt at the `_Mesh1DCoordinateManager` and `_Mesh2DCoordinateManger` classes, warts and all...
Still needs testing and doc-strings et al, there are still a few known `TBD`s... but it's at the point where there's value eyeballing it pre-review review, if you know what I mean :wink: 
---
=> Mesh api coord manager

docs/src/_static/theme_override.css, docs/src/_templates/layout.html, docs/src/common_links.inc, docs/src/conf.py, docs/src/whatsnew/latest.rst, requirements/ci/py37.yml
For a better user experience it would be useful for the documentation to clearly state when you are viewing the **latest** unreleased docs (from master).
This change uses the `_templates/layout.html` to add extra content, in this case to the `document` block (the "body" content of every page on the docs).
The rendered documentation for this PR: https://tkknight-iris-test-doc.readthedocs.io/en/latest/ (may change until this PR is out of draft)
This is a part solution to #3992.
When the docs are built on the Read the Docs service there is a shell environment variable named  `READTHEDOCS_VERSION` that should be set to: `latest` / `stable` / `v3.0.1`/ etc.  This variable is pulled into `conf.py` and then passed into the sphinx build via the `html_context variable`.
The banner/notice will …
=> Docs unreleased banner

lib/iris/cube.py
This PR drops the use of the Python2 `__unicode__` method.
This method is no longer required in Python3, and since `iris` is no longer supported on Python2, it's time to purge it
This method was only present on `iris.cube.Cube.__unicode__`.
---
=> drop __unicode__ method usage

.cirrus.yml, docs/src/common_links.inc, docs/src/developers_guide/contributing_ci_tests.rst, docs/src/developers_guide/contributing_code_formatting.rst, docs/src/whatsnew/latest.rst
This PR adds `only_if` conditional task execution hooks to `cirrus-ci` to allow developers to easily disable one or more `cirrus-ci` tasks, as a convenience, during development.
For further details see [Cirrus-CI Conditional Task Execution](https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution).
Also, see [here](https://bjlittle-iris.readthedocs.io/en/latest/developers_guide/contributing_ci_tests.html#skipping-cirrus-ci-tasks) to view the rendered changes to the documentation from this PR.
---
=> cirrus-ci conditional tasks

docs/src/whatsnew/latest.rst, lib/iris/_representation.py, lib/iris/common/metadata.py, lib/iris/tests/unit/common/metadata/test_hexdigest.py
This PR makes the `iris.common.metadata._hexdigest` function public i.e., `iris.common.metadata.hexdigest`.
Originally this function was written to solely support the needs of the common metadata API. However, it is already being used elsewhere within `iris`, and there are plans to leverage its benefit in other parts of `iris`.
Additionally, it may be of use to the `iris` community.
---
=> make iris.common.metadata._hexdigest public

.cirrus.yml
This PR rationalises the `cirrus-ci` `data_cache` support for `iris-test-data` in the relevant tasks by using a template.
In addition, we've moved to using a **formal release tag** of the `iris-test-data` rather than a commit sha. For reference see https://github.com/SciTools/iris-test-data/pull/58.
That is, if new data is added to the `iris-test-data` repo, then bump the `version.txt` (for humans) and tag a release of the `master` commit.
---
=> cirrus-ci uses iris-test-data release version

lib/iris/common/metadata.py, lib/iris/experimental/ugrid.py, lib/iris/tests/unit/common/metadata/test_metadata_filter.py
This PR follows up on #4017 to address some minor issues.
---
=> minor fixes

docs/src/userguide/cube_statistics.rst, lib/iris/common/metadata.py, lib/iris/cube.py, lib/iris/exceptions.py, lib/iris/experimental/ugrid.py, lib/iris/tests/unit/common/metadata/test_metadata_filter.py, lib/iris/tests/unit/experimental/ugrid/test_MeshMetadata.py
Brings all the `Mesh` API goodness into the main `mesh-data-model` feature branch. Tests and docstrings will be added next, straight into the `mesh-data-model` feature branch.
---
=> Mesh API Merge-Back

lib/iris/experimental/ugrid.py
This PR adds minimalist `__eq__` support for the `iris.experimental.ugrid.Mesh` and its container managers.
Testing and doc-strings are to follow...
---
=> add minimalist mesh __eq__ support

lib/iris/experimental/ugrid.py, lib/iris/tests/unit/common/lenient/test_Lenient.py, lib/iris/tests/unit/common/metadata/test_CellMeasureMetadata.py, lib/iris/tests/unit/common/metadata/test_CubeMetadata.py, lib/iris/tests/unit/experimental/ugrid/test_ConnectivityMetadata.py, lib/iris/tests/unit/experimental/ugrid/test_MeshCoordMetadata.py
Adds MeshCoordMetadata class (with tests)
Preliminary to creating a MeshCoord
Note: also fixed some problems I stumbled over in existing metadata testing.
Some of which  had already been copied into other tests! ...
There **_is_** a lot of boilerplate here : 
much of the  code in `lib/iris/tests/unit/experimental/ugrid/test_MeshCoordMetadata.py` is a total copy 
of that in `lib/iris/tests/unit/experimental/ugrid/test_ConnectivityMetadata.py` (i.e. ultimately from #3968)
As we are in a hurry, we are resolved to fix that "later"... 
---
=> MeshCoordMetadata [AVD-1629]

lib/iris/experimental/ugrid.py, lib/iris/tests/unit/experimental/ugrid/test_Connectivity.py
This PR adds `__str__` and `__repr__` support for the `Mesh` et al.
Note that, for the managers and `Connectivity` I've opted to make the `__repr__` unambiguous, whereas the `__str__` is a slicker summary of content.
For the `Mesh`, which is metadata and data rich, I've not made this distinction i.e., only implemented `Mesh.__repr__`, hence `str(mesh)` will return the same result as `repr(mesh)`.
---
=> add mesh __str__ and __repr__ support

lib/iris/experimental/ugrid.py, lib/iris/tests/unit/experimental/ugrid/test_Mesh.py
Adds a suite of tests for the `Mesh` class.
---
In agreement with @bjlittle (and with tentative support from @pp-mo), these tests are written in a different style that is unit-esque, but focuses on being easier to write and read. You might call them **"pragmatic tests"** or some-such. The basic idea:
* Write tests that look more similar to how a user/developer would use the functionality in the real world.
* Avoid the difficult process of abstracting every test to definitely only test one thing.
* Consider re-using objects for multiple assertions in one test.
* May achieve more readable, concise testing.
* Reduces possible resource-bloat caused by the reduced abstraction.
Cons
* Less granular information on failures.
So an error takes more investigation.
But not much more, and errors …
=> Mesh tests

docs/src/common_links.inc, docs/src/developers_guide/release.rst, docs/src/whatsnew/latest.rst
This PR adds post-release instructions on how to update `scitools-iris` on PyPI.
---
=> docs post-release update pypi howto

docs/src/whatsnew/latest.rst, lib/iris/common/metadata.py
Suppose I make, for example, a coordinate, and print it
```python
coord = iris.coords.DimCoord(range(3), long_name='foo', units='m')
print(coord)
```
I get info about what it contains:
```
DimCoord(array([0, 1, 2]), standard_name=None, units=Unit('m'), long_name='foo')
```
However, if I just print the metadata,
```python
print(coord.metadata)
```
I see all the unset stuff too, which I'm not really interested in:
```
DimCoordMetadata(standard_name=None, long_name='foo', var_name=None, units=Unit('m'), attributes={}, coord_system=None, climatological=False, circular=False)
```
For differences, it's hard to see at a glance what is actually different:
```python
coord2 = iris.coords.DimCoord(range(3), long_name='foo', units='m', attributes=dict(bar=1), var_name='wibble') …
```
=> metadata string reduction

lib/iris/common/metadata.py, lib/iris/coords.py, lib/iris/cube.py, lib/iris/experimental/ugrid.py, lib/iris/tests/unit/util/test_reverse.py
This PR adds the doc-strings to the public API methods of the class `iris.experimental.ugrid.Mesh` et al.
To view the rendered doc-strings for this pull-request, see [here](https://bjlittle-iris.readthedocs.io/en/latest/generated/api/iris/experimental/ugrid.html).
---
=> add mesh public doc-strings

.cirrus.yml
This PR simply removes the unused `IRIS_REPO_DIR` from the `.cirrus.yml`.
---
=> remove unused cirrus-ci variable

.cirrus.yml
This PR adds the `PYTHON_VERSION` to the fingerprint of the `pip_cache` of the `lint_task` for `cirrus-ci`. This will be required to discriminate whenever the base Python version of the container changes, and thus should result in invalidating the `pip_cache`.
This PR also fully qualifies the use of environment variables and normalises the use of strings. 
---
=> cirrus-ci add python version to lint task fingerprint

.cirrus.yml
This PR ensure that the `CONDA_CACHE_PACKAGES` are part of the `conda_cache` fingerprint.
---
=> cirrus-ci conda cache packages part of fingerprint

lib/iris/experimental/ugrid.py, lib/iris/tests/unit/experimental/ugrid/test_MeshCoord.py
Adding MeshCoord.
Notes: 
1. the characteristic points and bounds indexing calculations are **_not_** yet implemented here.
I have other code prototyped for that, but this PR is simpler if I leave it out for now.
2. the implementation isn't quite minimal, but I have chosen to control copying and slicing to make it a 'good citizen' within a cube (i.e. not blocking cube copy or slicing).
3. there is as yet no sensible `__str__` or `__repr__`.  We have another task pending to address that.
---
=> MeshCoord class [AVD-1591]

docs/src/sphinxext/generate_package_rst.py
This PR fixes the automagical generation of the `iris` API.
Currently `modules` will only be generated iff the `exclude_modules` is populated. If the `exclude_modules` is empty, then a reference to the module is created, but not populated, resulting in `TOC` errors. 
---
=> fix sphinxext api generate

lib/iris/experimental/ugrid.py, lib/iris/tests/unit/experimental/ugrid/test_Mesh.py, lib/iris/tests/unit/experimental/ugrid/test_MeshCoord.py
A minor refactor of the `Mesh.coord`, `Mesh.coords`, `Mesh.connectivity`, and `Mesh.connectivities` API to align with `Cube.coord` and `Cube.coords`, in that a single instance or a `list` containing zero or more instances is returned, rather than a `dict`. 
---
=> align mesh api with cube

lib/iris/experimental/ugrid.py, lib/iris/tests/unit/experimental/ugrid/test_MeshCoord.py
Functional lazy calculations for lazy points+bounds of MeshCoord
These calcs contain snapshots of the data content of the relevant Mesh components when the MeshCoord is created, but are not able to dynamically track Mesh contents, as originally envisaged.
However they should work with either real or lazy data content.
---
=> Better calculations for MeshCoord lazy/real points and bounds. [AVD-1590]

lib/iris/experimental/ugrid.py, lib/iris/tests/unit/experimental/ugrid/test_MeshCoord.py
Added string representations for MeshCoord
Waiting until #4053 is in :  Which this is based on.
(so it won't merge into the target branch, as yet)
I have made the str/repr versions slightly different, following discussion with @bjlittle 
I'm still a little uncertain that the results are the most useful, though:
* if you enter a MeshCoord at the command line, you get "repr", which shows a mesh as `<Mesh object at 0x{address}>`, 
* whereas the "str" form attempts a more human-readable account of the Mesh, as `Mesh('name')`
* This  corresponds with the "standard" Python usage ...
* ... **_but_**,  for a cube, the "repr" version is the *short form*, whereas print(cube) gives full details.
* .. so making repr the "more precise and less human" is **_against_** what we do for cubes.  
--- …
=> Meshcoord printout [AVD-1592]

.cirrus.yml
This PR relaxes the criteria for our use of `cirrus-ci` compute credits i.e., allow then to be spent also on non-`master` branches.
---
=> cirrus-ci credits for non-master

README.md, docs/src/common_links.inc, docs/src/developers_guide/contributing_ci_tests.rst, docs/src/whatsnew/latest.rst
This PR adds the `pre-commit.ci` badge to the `README.md` and also adds some docs support to highlight the service to `iris` developers.
The documentation changes associated with this PR are rendered [here](https://bjlittle-iris.readthedocs.io/en/latest/developers_guide/contributing_ci_tests.html#pre-commit-ci).
Also, see [here](https://github.com/bjlittle/iris/tree/add-pre-commit-ci-badge) for a preview of the new `README.md` with the badge.
---
=> add pre-commit.ci badge and doc support

lib/iris/cube.py, lib/iris/experimental/ugrid.py, lib/iris/tests/unit/cube/test_Cube.py, lib/iris/tests/unit/experimental/ugrid/test_MeshCoord.py
Adding a 'mesh_coords' keyword to Cube.coords.
Behaves mostly like the existing `dim_coords` keyword.
(This is a simple preliminary to adding the more complex cube api to come :
* `cube.mesh` and `.location`
* `cube.__eq__` should compare mesh and location
* various checks that any MeshCoord-s in a cube are always compatible.
)
---
=> Cube.coords mesh_coords key [AVD-1662]

lib/iris/cube.py, lib/iris/tests/stock/mesh.py, lib/iris/tests/unit/cube/test_Cube.py, lib/iris/tests/unit/experimental/ugrid/test_MeshCoord.py
Adding additonal mesh-specific Cube support:
* add `cube.mesh()` and `cube.location()` access methods
* make `cube.__eq__` compare mesh + location
* adjust all cube creation + coord management to ensure any/all MeshCoords are always inter-compatible
Reference #4063.
---
=> Support for cube mesh api [AVD-1663]

README.md
This PR rationalises the `README.md` badges to:
* remove the `downloads` and `contributors` badges (personally they don't have that much value and take up real estate) and 
* add the `discussions` badge
See [here](https://github.com/bjlittle/iris/tree/add-github-discussions-badge#-----) for the rendered `README.md` of this pull-request.
---
=> Add GitHub discussions badge

.cirrus.yml, lib/iris/tests/integration/experimental/test_ugrid_load.py, lib/iris/tests/results/experimental/ugrid/2D_72t_face_half_levels.cml, lib/iris/tests/results/experimental/ugrid/3D_1t_face_full_levels.cml, lib/iris/tests/results/experimental/ugrid/3D_1t_face_half_levels.cml, lib/iris/tests/results/experimental/ugrid/3D_snow_pseudo_levels.cml, lib/iris/tests/results/experimental/ugrid/3D_soil_pseudo_levels.cml, lib/iris/tests/results/experimental/ugrid/3D_tile_pseudo_levels.cml, lib/iris/tests/results/experimental/ugrid/3D_veg_pseudo_levels.cml, lib/iris/tests/results/experimental/ugrid/surface_mean.cml
Adds various integration tests to prove Iris can load the required types of files.
---
=> More UGRID Loading Integration Tests (AVD-1517, AVD-1679, AVD-1680, AVD-1681, AVD-1683)

MANIFEST.in, lib/iris/tests/stock/__init__.py, lib/iris/tests/stock/file_headers/README.md, lib/iris/tests/stock/file_headers/xios_2D_face_half_levels.cdl, lib/iris/tests/stock/file_headers/xios_3D_face_full_levels.cdl, lib/iris/tests/stock/file_headers/xios_3D_face_half_levels.cdl, lib/iris/tests/stock/netcdf.py, lib/iris/tests/unit/tests/stock/__init__.py, lib/iris/tests/unit/tests/stock/test_netcdf.py
For original review, see SciTools-incubator/iris-ugrid#38.
I'm keen in future to extend this beyond UGRID-NetCDF files, as the pattern is very useful for good benchmark coverage.
---
=> Migrate synthetic data generation from iris-ugrid

docs/src/developers_guide/release.rst
This PR adds some additional minor instructions to the developer when building an `sdist` and `bdist_wheel` of `iris` for PyPI.
---
=> update docs pypi instructions

docs/gallery_code/general/plot_anomaly_log_colouring.py, docs/src/whatsnew/latest.rst, lib/iris/tests/results/imagerepo.json
=> Fix cirrus ci and mpl

README.md
Minor candy PR to add logos to the `conda` and `pypi` badges.
See [here](https://github.com/bjlittle/iris/tree/update-badges#-----) for how these badges will render.
---
=> add logo to conda and pypi badges

.cirrus.yml, .pre-commit-config.yaml, README.md, docs/gallery_code/general/plot_anomaly_log_colouring.py, docs/src/common_links.inc, docs/src/developers_guide/contributing_ci_tests.rst, docs/src/developers_guide/release.rst, docs/src/index.rst, docs/src/sphinxext/generate_package_rst.py, docs/src/whatsnew/latest.rst, lib/iris/common/metadata.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/results/imagerepo.json, lib/iris/tests/unit/common/metadata/test_BaseMetadata.py, requirements/ci/py36.yml, requirements/ci/py37.yml, requirements/ci/py38.yml
This PR merges the latest changes from `master` to the `mesh-data-model` feature branch.
---
=> Merge master to mesh data model

lib/iris/__init__.py
This PR sets the `iris` version to 3.1a0 in preparation for an internal engineering tag on the `mesh-data-model` feature branch.
---
=> ng-vat v0.2 is iris v3.1a0

lib/iris/experimental/ugrid/__init__.py, lib/iris/tests/integration/experimental/test_ugrid_load.py, lib/iris/tests/stock/file_headers/minimal_bad_topology_dim.cdl
Allow "wrong" topology-dimension on a UGRID mesh, deduce "correct" value from attached connectivites.
This is just one of the pending "tolerant loading" ideas which we listed elsewhere (AVD-1723).
But this one will help with the forthcoming internal release demo.
---
=> Topology tolerance [AVD-1723]

lib/iris/experimental/ugrid/__init__.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/__init__.py, lib/iris/tests/integration/experimental/test_ugrid_load.py, lib/iris/tests/unit/experimental/ugrid/test_CFUGridAuxiliaryCoordinateVariable.py, lib/iris/tests/unit/experimental/ugrid/test_CFUGridConnectivityVariable.py, lib/iris/tests/unit/experimental/ugrid/test_CFUGridMeshVariable.py, lib/iris/tests/unit/experimental/ugrid/test_Mesh.py, lib/iris/tests/unit/fileformats/netcdf/test_load_cubes.py
Improvements to all uses of logging in `experimental.ugrid`, following recent team discoveries.
---
=> Logging fixes

lib/iris/tests/runner/_runner.py
`default_doc_path` is incorrect, docs have been moved out of subdir `docs/iris` -> `docs`.
---
=> Fix bug in gallery_tests runner

lib/iris/tests/results/imagerepo.json
Closes #4110 
Image update at https://github.com/SciTools/test-iris-imagehash/pull/42
If I've understood, we don't usually remove the old hashes.  However in this case the old ones didn't include the lake outline that should have been there so were giving us false passes.
---
=> Update hashes for gallery wind plot

docs/gallery_code/general/plot_anomaly_log_colouring.py, lib/iris/tests/results/imagerepo.json
Restores output of the anomaly log colouring gallery to pre #4087 by using a new `linscale` argument (can't go back to `linscale=0` as no longer allowed by Matplotlib).
---
=> Corrected plot_anomaly_log_colouring for new Matplotlib linscale rules.

lib/iris/tests/results/analysis/sqrt.cml, lib/iris/tests/test_basic_maths.py
This is a small change to the square root test to resolve #3993.  Instead of checking absolute equality in the floating point numbers, use an allclose test instead.
---
=> Use assertArrayAllClose for sqrt test

docs/src/whatsnew/latest.rst, lib/iris/plot.py
Resolves #4085.  Docstrings now show arguments' types on the line above their description, so they render sensibly in readthedocs.
---
=> iris.plot docstrings: separate arg types from descriptions

.cirrus.yml, docs/iris/gallery_code/general/plot_anomaly_log_colouring.py, docs/iris/src/developers_guide/contributing_running_tests.rst, docs/iris/src/developers_guide/gitwash/git_links.inc, docs/iris/src/further_topics/metadata.rst, docs/iris/src/installing.rst, lib/iris/coords.py, lib/iris/cube.py, lib/iris/plot.py, lib/iris/tests/__init__.py, lib/iris/tests/results/analysis/sqrt.cml, lib/iris/tests/results/imagerepo.json, lib/iris/tests/test_basic_maths.py, noxfile.py, requirements/ci/iris.yml, requirements/ci/py38.yml
This change pulls recent changes from master in to get the tests passing with python3.8, matplotlib 3.4.1, cartopy 0.19 and glibc 2.31.  All test are passing locally for me under python3.8.  The only conflicts I found were in the documentation and I took the simplest approach of discarding the whatsnew entries as well as the "common links" change from #3976.
---
=> Dependencies update

docs/iris/src/whatsnew/3.0.2.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py
Replacement for #4046, targetting v3.0.x
Fixes #3391 I think.  This addresses the very specific case where you request the entire 360 degrees, and one of the bounds is at the maximum/minimum threshold.  Taking @valeriupredoi's example from #3391, you would still get that negative longitude point if you did something like `cube.intersection(longitude=(0, 50))`.  I'm not sure that that makes sense but, looking at the tests, it appears to have been intentional.
I haven't added any extra comment to explain my logic, but I think it's covered by the existing:
https://github.com/SciTools/iris/blob/a9ae72fa3c420da408fb4f69bba4035c2c43f769/lib/iris/cube.py#L3178-L3180
---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_reques …
=> Intersection bounds fix (replacement PR)

docs/src/developers_guide/contributing_code_formatting.rst, lib/iris/coord_categorisation.py
See #4137 
Explicitly make the `coord_categorisation` functions always use a `cftime.datetime` instance, so that tests pass with `cf_units` v2.1.5.  I also removed the comment about `Unit.num2date` being deprecated.  That comment dated back to the days when `Unit` was part of Iris, and I can't see anything in `cf_units.__init__.py` to suggest `Unit.num2date` is deprecated.
I also fixed a link to the `black` docs.  This duplicates part of #4132, but it looks like the main tests in that PR can't pass without pulling in this change anyway.
I am on leave for the next week but happy if someone else applies any changes here if they are needed in the meantime.
---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_chec …
=> Fix coord_categorisation.add_weekday

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, docs/src/developers_guide/contributing_code_formatting.rst, docs/src/whatsnew/latest.rst
This PR addresses Discussion #4145 raised by @larsbarring
Closes #4145 
---
=> update bug and feature templates

.cirrus.yml, noxfile.py
This PR makes some minor changes to the `.cirrus.yml` and `noxfile.py`.
---
=> minor tidy of cirrus and nox

docs/src/whatsnew/latest.rst, lib/iris/plot.py, lib/iris/tests/unit/plot/test_contourf.py
Fixes #4086 
As noted at #4086, our antialiasing handling exposed a matplotlib bug for a pretty specific edge case.  Regardless of this bug, it's a bit redundant to call `pyplot.contour` when the data do not span the requested levels, so we should plausibly get a tiny efficiency gain by skipping it when not needed.
---
=> Contourf Antialias Fix

docs/iris/src/whatsnew/3.0.2.rst, lib/iris/_lazy_data.py, lib/iris/tests/unit/lazy_data/test_co_realise_cubes.py
Hopefully, addresses #4134
This significantly improves a problem with slow loading, which applies to netcdf files with lots of  variables
The change is tiny, but significant !
I think this problem has existed ever since we moved to Dask 2.0.
At that point we identified much slower loading of large PP/FF files, and fixed it [like this](https://github.com/SciTools/iris/pull/3659).
[That code is still in place](https://github.com/SciTools/iris/blob/v3.0.x/lib/iris/fileformats/pp.py#L597-L600) : in view of this new approach, that can probably now be removed -- and should be !
But as this is intended as a "quick win" for v3.0.2, I'll defer that until later.
---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_check …
=> Tweak to speed up dask wrapping of netcdf variables

.pre-commit-config.yaml, lib/iris/fileformats/netcdf.py, lib/iris/tests/integration/test_netcdf.py, lib/iris/tests/test_cube_to_pp.py, lib/iris/tests/test_file_save.py, lib/iris/tests/unit/fileformats/test_rules.py, noxfile.py, pyproject.toml, requirements/ci/py36.yml, requirements/ci/py37.yml, requirements/ci/py38.yml, requirements/test.txt
This PR updates `black` and `flake8` pre-commit hooks scripts, and `pre-commit-hooks` itself.
Also plays forward the bump in `black` version to the rest of `iris`, with minor knock-on reformatting to conform to the changed standard. 
---
=> Update black et al

docs/iris/src/whatsnew/3.0.2.rst, lib/iris/coords.py, lib/iris/cube.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/integration/test_netcdf.py, lib/iris/tests/test_basic_maths.py, lib/iris/tests/test_cube_to_pp.py, lib/iris/tests/test_file_save.py, lib/iris/tests/unit/fileformats/test_rules.py
This PR addresses issue #4000.
The `Coord` and `Cube` arithmetic behaviour regressed in #3422, and as a result caused a `NotYetImplementedError` exception to be raise whenever a `Coord op Cube` operation was attempted.
This PR addresses this, and also extends the capability to include missing reflected `Cube` arithmetic operations i.e., `iris.cube.Cube.__rsub__`, `iris.cube.Cube.__rdiv__`, and `iris.cube.Cube.__rtruediv__`. In addition to this, the `iris.cube.Cube.__neg__` dunder method has also been implemented for convenience i.e., you can now do `result = -cube`.
So in summary you can now do the following `+`, `-`, `/` and `*` operations between:
- a `Coord` and a `Cube`
- a `Cube` and a `Coord`
- a `Cube` and a `Cube`
- a `Coord` and a (`int`, `float`, `numpy.number`)
- a (`int`, …
=> Fb fix cube coord arithmetic

docs/iris/src/whatsnew/3.0.2.rst, lib/iris/fileformats/pp.py, lib/iris/tests/unit/fileformats/pp/test_PPDataProxy.py, lib/iris/util.py
This is a follow-up to #4135 and ***should not be merged before that one*** (hence draft WIP)
( and will doubtless need re-basing anyway, due to various current testing problems )
I realised that when #4135 is accepted, it also stops the `dask.array.from_array` within `iris._lazy_data.as_lazy_data()` from realising PP/FF data.
So we no longer need the previous um-data-specfic workaround from #3659.
This PR removes that code.
---
=> Pp daskfix

docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/test_cube.py, lib/iris/tests/unit/cube/test_CubeList.py
🚀 Pull Request
I had a go to resolve issue #4066 .
A method copy() was created in the CubeList class to return a CubeList object instead of a list.
---
=> Add a method to return a CubeList from CubeList.copy()

docs/iris/src/whatsnew/3.0.2.rst
This PR adds the release date to the v3.0.2 whatnew - with other minor reformatting of release notes.
---
=> add release date to v3.0.2 whatsnew

.github/workflows/refresh-lockfiles.yml, docs/src/developers_guide/contributing_ci_tests.rst
Added a step to the update lockfile workflow to first check if someone has committed to the `auto-update-lockfiles` branch since last run. If so, it will abort regenerating lockfiles.
This resolves #4156 (observed in #4137).
If you really want to run the workflow and potentially clobber anything on the branch, you can override this new check step by running from the actions panel and performing a manual workflow dispatch, setting the "clobber" value to YES.
---
=> Stop CI from clobbering commits on lockfile updates

noxfile.py, requirements/ci/py36.yml, requirements/ci/py37.yml, requirements/ci/py38.yml, requirements/test.txt
This PR updates the `black` version to the latest offering by unpinning.
I did consider removing `black` from the list of dependencies, but we do require to include `black` for those that want to test `iris` with `nox` on their local host.
Rather than continually update the specific `black` version in several places, I suggest we simply let the `black` version float to the latest version at environment package dependency resolve time, and allow the `pre-commit-bot` to notify us when a later version of `black` is available to the community.
Seems like a reasonable compromise to take here.
---
=> Bump black version

docs/src/common_links.inc, docs/src/conf.py, docs/src/developers_guide/gitwash/development_workflow.rst
This PR swaps the RTD Support links for Google Groups in favour for the GitHub Discussions.
See [here](https://bjlittle-iris.readthedocs.io/en/latest/) for a version of the rendered documentation of this PR.
In particular, see:
---
=> RTD support link update

docs/src/developers_guide/release.rst
Minor PR to update the PyPI release instructions, thanks to @stephenworsley :+1: 
---
=> update docs pypi release

docs/gallery_code/oceanography/plot_load_nemo.py, lib/iris/tests/unit/constraints/__init__.py, lib/iris/tests/unit/constraints/test_NameConstraint.py
This PR mops up some missed `__future__` and `six` references from our recent porting to Python 3 exploits.
---
=> remove __future__ and six references

.cirrus.yml, .github/workflows/refresh-lockfiles.yml, .pre-commit-config.yaml, README.md, docs/src/common_links.inc, docs/src/developers_guide/contributing_ci_tests.rst, docs/src/developers_guide/contributing_documentation.rst, docs/src/developers_guide/contributing_getting_involved.rst, docs/src/developers_guide/contributing_graphics_tests.rst, docs/src/developers_guide/gitwash/configure_git.rst, docs/src/developers_guide/gitwash/development_workflow.rst, docs/src/developers_guide/gitwash/set_up_fork.rst, docs/src/developers_guide/release.rst, docs/src/installing.rst, docs/src/whatsnew/2.3.rst, docs/src/whatsnew/latest.rst, noxfile.py, pyproject.toml
After the renaming of the `iris/master` branch to `iris/main`, this pull-request changes all relevant `master` references to be `main` within `iris`.
---
=> change master to main references

.pre-commit-config.yaml, docs/src/developers_guide/contributing_testing.rst, docs/src/userguide/saving_iris_cubes.rst, docs/src/whatsnew/1.6.rst, docs/src/whatsnew/latest.rst, lib/iris/io/__init__.py
This PR adds the `pre-commit` hook to automate the process of applying `black` to documentation code blocks.
See https://github.com/asottile/blacken-docs for further details.
---
=> pre-commit blacked docs

.cirrus.yml, .pre-commit-config.yaml, docs/src/whatsnew/latest.rst, noxfile.py, pyproject.toml, requirements/ci/py37.yml, requirements/ci/py38.yml, setup.cfg
Akin to PR #4174 and `isort`, this PR drops the `black` and `flake` package dependencies from both our `conda` YAML and PyPI `setup.cfg` requirements.
We're now advocating the use of `pre-commit` for developers, which will take care of your linting needs. Additionally, developers (and users alike) can easily install these packages explicitly, if they wish.
The reason for dropping these packages is to reduce the `iris` dependency bloat, but also due to the regular cadence in version bumping that is required - hardly a major maintenance overhead, but this has cause recent difficulties, particularly with `black`.
---
=> drop black and flake8 dependencies

.pre-commit-config.yaml, lib/iris/tests/test_std_names.py, pyproject.toml
This PR plays to the strengths of `pre-commit` and filters files at the right level before running the hooks.
This configuration works for local developer commits on only the files that have changed (optimisation), and for `cirrus-ci` when `pre-commit` hooks are run against all files. In addition, the behaviour of the tools which the hooks call still honour their specific configuration.
This undoes a major regression introduced in #4181. Oops :blush: 
---
=> optimise pre-commit

lib/iris/fileformats/um/_optimal_array_structuring.py, lib/iris/tests/integration/aux_factory/test_OceanSigmaZFactory.py, lib/iris/util.py
This PR deals with some rogue `print` statements within comments and doc-strings that I stumbled across on my travels.
---
=> convert docs print statements

lib/iris/cube.py, lib/iris/tests/results/cdm/str_repr/simple.__str__.txt, lib/iris/tests/unit/cube/test_Cube.py
Fixes #4123 
NOTE: adding  the test exposed ***another*** bug in cube printout : When widening, it stopped showing the cube units !
I have fixed that as well, but it did cause a knock-on in one other test (see separate commit with results-file change).
I would really rather have tidied up first, with #3998 
-- after all, this bug has probably happened ***because of*** the unreasonable complexity of the Cube.summary code !
But this one is quite a simple fix, and if we do #3998 later it can check that it still passes this test.
And there is still a good deal of work needed to inject good levels of testing into #3998 
---
=> Widen cube printout for long ancil or cell-measure names.

.cirrus.yml
This PR consolidates the `minimal` and `full` testing for `cirrus-ci` into one task that runs the `full` tests. The `full` tests are fully inclusive of the `minimal` tests.
Running both `minimal` and `full` test tasks (for all Python distributions) is a waste of time, resource and compute credits. 
---
=> drop cirrus-ci minimal tests

.cirrus.yml, docs/src/whatsnew/latest.rst, noxfile.py
This PR consolidates the `cirrus-ci` documentation gallery task and documentation testing task into one task, with one associated `nox` session.
---
=> consolidate cirrus-ci documentation tasks

docs/iris/src/whatsnew/3.0.3.rst, docs/iris/src/whatsnew/index.rst, lib/iris/__init__.py, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py
When performing a cube.intersection, Iris sometimes has to wrap the coord bounds. As an example when the coord on the original cube is between (0,360), but someone requests an intersection of (-60, 60). This can result in split cells that straddle the wrap point. For example, your original bounds may be:
```
array([[299.7, 299.8],
[299.8, 299.9],
[299.9, 300. ],
[300. , 300.1],
[300.1, 300.2]])
```
But your wrapped bounds, with wrapping point of -60, will look like:
```
array([[299.7, 299.8],
[299.8, 299.9],
[299.9, -60. ], # straddle point!
[-60. , -59.9],
[-59.9, -59.8]])
```
Iris calculates the diff between the upper and lower bounds, for bounds *inside* the requested intersection, resulting in the variables `pre_wrap_delta` and `post_wrap_delta`, and then it compares these to find any …
=> In cube.intersection, find split cells using a tolerant equality check

noxfile.py
Hitherto we offered 'docstest-3.7' and 'docstest-3.8'.  We could still do that, but I'm choosing not to.
(since Py3.7 gives [different results in some cases](https://github.com/SciTools/iris/pull/4206#issuecomment-867465560))
Likewise, if nox is called specifying a specific _unsuitable_ python, via the PY_VER environment variable, we could still run the session, with Python3.8, but instead I chose not to allow it all.
So..
1. `nox -s doctest` now runs with Python 3.8
* whereas previously it ran "doctest-3.7", giving different results
1. `PY_VER=3.8 nox -s doctest` still works
* this is how cirrus invokes it
2. `PY_VER=3.7 nox -s doctest` now gives an error
* previously available
New behaviours demonstrated :
```
$ nox -l
Sessions defined in …
```
=> Only run docs-building sessions with Python 3.8.

docs/iris/src/whatsnew/3.0.4.rst, docs/iris/src/whatsnew/index.rst, lib/iris/cube.py, lib/iris/tests/results/cdm/str_repr/simple.__str__.txt, lib/iris/tests/unit/cube/test_Cube.py
Include the #4124 changes as a bugfix to v3
(also added whatsnew)
This is already on 'main', but there I missed off the whatsnew.
No need to address that I think, because this code has no longterm future, due to #4206 
I see we have no `whatsnew/latest.rst` on the bugfix branch.
So I hope creating a '3.0.4' whatsnew is the correct way with this.
=> Wide cubestr fix 3v0vx v2

.cirrus.yml, .pre-commit-config.yaml, noxfile.py
This PR re-instates the `pre-commit` behaviour for the `black` and `isort` hooks, whereby they will automatically correct files in-place on `git commit` rather than performing a `--check`. This means that developers no longer require to explicitly install `black` or `isort`; this will all be managed by `pre-commit`.
Subsequently, the linting `cirrus-ci` task customises the `pre-commit-config.yaml` to ensure that `black` and `isort` only perform a `--check`, and will fail when a non-compliance is detected, as required.
Closes #4226 
---
=> pre-commit isort and black --check only for cirrus-ci

docs/src/installing.rst, docs/src/whatsnew/latest.rst
Documented the ``--force`` command line option when creating a development conda environment.  This is useful if the dev is re creating the environment due to the requirements changing.
I personally find this useful, thought it would be useful to put in the docs too.
---
=> Documented the --force option on conda env create

docs/iris/src/userguide/cube_maths.rst
A couple of typos raised by one of our internal users
=> Fix some typos in the cube maths docs

docs/iris/src/whatsnew/3.0.4.rst
Fixes to already-merged #4233 
(previously) ~***NOT*** rebased (yet), in case we wanted to back that out.~
=> (More of) Wide cubestr fix 3v0vx v2

.cirrus.yml
This PR addresses `cirrus-ci` parsing issues, which appear to have resulted from a recent update on the `cirrus-ci` server-side.
---
=> rename cirrus-ci tasks with name override

docs/iris/src/whatsnew/3.0.4.rst, lib/iris/tests/system_test.py, lib/iris/tests/test_merge.py, lib/iris/tests/unit/analysis/scipy_interpolate/__init__.py, lib/iris/tests/unit/time/__init__.py, lib/iris/tests/unit/time/test_PartialDateTime.py, lib/iris/time.py
Replacement for #4192, targeting the v3.0.x branch.
This PR gets our tests running consistently under `pytest` and `nose`.  We had some `__init__.py` files missing so some tests have not been running under `nose`/`setuptools`/`nox`.  Once reinstated, three of the tests for `PartialDateTime` failed, so this PR also includes changes to address that.  See inline comments for explanations of individual changes.
I have verified that pointing `pytest` at this new branch produces 5216 passess and 22 skips.  `python setup.py test` also finds 5148 tests, but some are falling over with memory allocation errors 😕.  So let's see how the CI fairs...
---
=> Test wrangling vs v3.0.x

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/tests/unit/coords/test_Cell.py
Fixes #2914.
A simple fix to allow numpy arrays (or lists) with only one element to be compared to a Cell.
=> Allow comparison between Cell and numpy array or list of len = 1.

docs/src/installing.rst, docs/src/whatsnew/latest.rst
I adapted the from source installation instructions to the requirement `cftime>=1.5` which will be needed soon, as discussed in #4258.
=> Installation instructions adapted to the requirement cftime>=1.5.

docs/src/conf.py
It looks like this mapping object has moved.  See #4263 where it broke the linkcheck and doctests.
---
=> Fix scipy intersphinx mapping

.github/workflows/stale.yml, docs/src/installing.rst, docs/src/whatsnew/1.8.rst
This PR adds the `stale` GHA in order to help maintain a healthy issues and prs backlog.
---
=> add stale gha

.github/workflows/stale.yml
This PR updates the `stale` GHA to enforce the processing of `ascending` issues/PRs i.e., oldest first.
---
=> ascending issues/prs order for gha stale

docs/src/whatsnew/latest.rst
Adds a whatsnew entry briefly describing the contributions relating to adding UGRID support.
=> Ugrid whatsnew

docs/src/whatsnew/latest.rst, docs/src/whatsnew/latest.rst.template, lib/iris/common/metadata.py, lib/iris/tests/unit/common/metadata/test_metadata_manager_factory.py
This PR cycles back to the Common Metadata API and includes some small but significant optimisations to the `iris.common.metadata.metadata_manager_factory` function.
The `metadata_manager_factory` function leverages the benefit of creating metadata manager classes dynamically at runtime, but this is a relatively expensive operation compared to creating equivalent but static classes.
Employing a simple LRU caching strategy for the metadata manager classes created at runtime provides significant savings, along with careful avoidance of property lookups and type checking when creating instances of the dynamic classes.
The following `asv` metrics provide support for this proposed change:
In particular, note the performance gains when creating common `iris` first-class objects, such as:
* …
=> lru metadata manager factory

.github/workflows/stale.yml
This PR increases the `operations-per-run` in order to cover the outstanding stale issues backlog.
Over time this value can be hopefully reduced.
---
=> increase gha stale operations-per-run

docs/src/whatsnew/latest.rst, lib/iris/fileformats/__init__.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/integration/test_netcdf.py, lib/iris/tests/unit/fileformats/netcdf/test__translate_constraints_to_var_callback.py, lib/iris/tests/unit/fileformats/netcdf/test_translate_constraints_to_var_callback.py
An initial heads-up on a really simple way of speeding up netcdf loads ...
... with files of many variables, as in #4134 
This is actually much simpler than I imagined, but ..
**Blockers to completion**
* probably needs discussion
* intended usage might require to select multiple data-vars
* not sure how to test this
Following #4135, ESMValTool devs are reporting that iris loading is [still too slow, where you want only one from a whole lot of diagnostics](https://github.com/ESMValGroup/ESMValCore/pull/1153#issuecomment-853223610).
This example follows [what we did for UM files in similar circumstances](https://github.com/SciTools/iris/pull/1240).
It's notable that, in creating a `iris.fileformats.cf.CFReader`, we are still doing a whole-file analysis, that includes the unwanted …
=> Simple support for selective netcdf loading.

docs/src/whatsnew/latest.rst, etc/cf-standard-name-table.xml
This PR updates the CF standard name table currently available in iris (v75, released 15 September 2020) to the latest version (v77, released 19 January 2021).
=> Update CF standard name table to v77

docs/src/whatsnew/latest.rst
Missing and additional whatsnew content for the v3.1 release 
---
=> Missing whatsnew entries for 3.1 release.

docs/src/whatsnew/latest.rst
This PR clears out whatsnew/latest ready for all the upcoming v3.2 entries.  The existing whatsnew entries are all now in the 3.1 rst on that branch.  I simply
* Copied the template
* Removed the [bit about patches](https://github.com/SciTools/iris/blob/003977b474598b84eef8f16c3fde7b7690916302/docs/src/whatsnew/latest.rst.template#L10-L19) as I assume that's not needed in the next minor release
* Specified minor on [this line](https://github.com/SciTools/iris/blob/main/docs/src/whatsnew/latest.rst.template#L29)
---
=> Reset whatsnew latest

.cirrus.yml, lib/iris/experimental/ugrid/__init__.py, lib/iris/fileformats/cf.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/integration/experimental/test_ugrid_load.py, lib/iris/tests/stock/file_headers/minimal_bad_mesh_cf_role.cdl, lib/iris/tests/unit/experimental/ugrid/test_CFUGridMeshVariable.py, lib/iris/tests/unit/experimental/ugrid/test_load_mesh.py, lib/iris/tests/unit/experimental/ugrid/test_load_meshes.py
Load `Mesh`es without associated `Cube`s.
TODO:
* ~~[ ] Performance tests~~
---
=> Mesh Loading (AVD-1813)

docs/src/common_links.inc, docs/src/conf.py, docs/src/copyright.rst, docs/src/developers_guide/contributing_getting_involved.rst, docs/src/whatsnew/latest.rst
=> Include Discussions in Getting Involved.

docs/src/developers_guide/contributing_ci_tests.rst, docs/src/installing.rst
Updated the **documentation** to make clear that the **testing** we do is based on **Linux** (and not Windows or macOS).
I'm leaning to not create a what's news for this minor change.  If you think otherwise please comment.
---
=> Made clear we only test on Linux.

lib/iris/__init__.py
This PR increments the `iris.__version__` given that the `v3.1.x` release feature is now cut, and the `v3.1.0` release is imminently pending.
---
=> bump version

docs/src/common_links.inc, docs/src/userguide/interpolation_and_regridding.rst, docs/src/whatsnew/latest.rst
Pull request makes a small change to the documentation for readability
---
=> Improve styling in a minor way in docs

.github/workflows/stale.yml, docs/src/userguide/loading_iris_cubes.rst, docs/src/whatsnew/latest.rst
Added "Good First Issue" to the exempt list for both exempt-issue-labels and exempt-pr-labels so that these won't be made stale.
Based on a suggestion by @trexfeathers in Peloton today, stopping good first issues from going stale means that there's a supply of them for new developers to get involved through (particularly as there aren't a huge number of them).
---
=> Add 'Good First Issue' label to reasons an issue doesn't go stale

docs/src/whatsnew/latest.rst, lib/iris/tests/integration/test_netcdf.py
Added the skip data decorator to TestConstrainedLoad in the integration tests for NetCDF
Running the tests without access to the test data was causing test failures when they should have been skipped (specifically from the integration tests for NetCDF, in the TestConstrainedLoad class). This is no longer the case.
---
=> Skip TestConstrainedLoad if data missing

docs/src/whatsnew/3.0.rst
This PR offers an alternative to #4285 the the `v3.1.x` feature release branch.
For context see #4316 and this [comment](https://github.com/SciTools/iris/pull/4316#issuecomment-920408310).
If this approach is adopted, then I'll subsequently update the `latest.rst.template` in `main`.
The rendered `whatsnew` documentation changes for this PR are available [here](https://bjlittle-iris.readthedocs.io/en/latest/whatsnew/3.0.html).
---
=> refactor 3.0 whatsnew

docs/src/whatsnew/3.1.rst
This PR makes a minor change to the `whatsnew` for the `v3.1.0` release in the `v3.1.x` release feature branch, by adding the version to the `sphinx-panel` for the release highlights.
This is to align with the pattern adopted in #4320, in readiness for any `v3.1.x` patches.
---
=> add release version to sphinx-panel title

docs/src/whatsnew/3.1.rst, setup.cfg
This PR fixes the malformed [PyPI trove classifer](https://pypi.org/classifiers/), which is preventing the `iris` sdist and binary wheel being uploaded to PyPI due to stricter metadata checks.
The `iris` v3.1.0 release date has also been updated. We can re-tag and re-release afresh after this PR is merged.
I'll purge the existing tag on `16 Sept 2021`, which is safe to do, as we've not packaged the release yet (so no need to bump versions or perform a `post` release).
---
=> fix trove classifier

.cirrus.yml, docs/src/whatsnew/3.0.rst
This PR pulls the `cartopy_feature_download.py` script from the latest stable `cartopy` tag i.e., 0.20.0, during CI.
Closes #4306
---
=> stable cartopy feature download

docs/src/userguide/loading_iris_cubes.rst, docs/src/whatsnew/latest.rst, lib/iris/_constraints.py
Added documentation to Iris Constrained Loading docs to highlight that Constraints don't support ¦ (and explain why)
Whilst addressing a recent support request it seemed that there should be an ability to logically "or" Constraints as well as to "and" them. The reasons for this weren't immediately obvious, so documenting it seems useful for the future. I've done so.
I'd note, I'm not 100% convinced that this is an improvement to the quality of the docs, as I can see the argument that in catering for an edge case of misunderstanding the docs may become less easily understood by those without this misunderstanding (particularly as loading is likely to be one of the first bits of documentation a new user reads). Happy to discuss the merits of this and/or axe this PR on that basis.
--- …
=> Update to loading docs to cover absence of 'or' for constraints

lib/iris/fileformats/netcdf.py, lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
Initial "tidying" to routines in `netcdf.py`, to prepare for the addition of UGRID saving support.
This unifies the handling codepaths for different types of cube components, 
to make it easier to add the new ones which are coming (mesh-element coords and connectivities).
**This is a _pure refactor_ :** by design, should not change any exisiting behaviour/results.
These same code changes have been proven against extra CDL test snapshots in #4297
.. but we don't ever intend to **_merge_** that extra testing, as it is excessive and somewhat incomplete/unpolished
---
=> Refactor some netcdf save code

docs/Makefile, docs/src/Makefile, docs/src/conf.py, docs/src/developers_guide/contributing_documentation.rst, docs/src/whatsnew/latest.rst
Small quality of life change when working on improving the Iris documentation (developers use only).  I would typically comment out the iris docs sphinx extensions when editing the documentation and skip the gallery builds to allow for **faster** builds.  I would still of course do a complete **clean and full build as a final test**.
The PR introduces to new make targets for the Iris docs:
* `make html-noapi`.  This will skip the **API** doc creation
* `make html-quick`.  This will skip the **API** doc creation and also skip the **gallery** creation.
---
=> added support for make html-noapi and html-quick for the docs build

docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py
Fixes #4221, in precisely the way suggested there.
---
=> Fix intersection for range=modulus and bounds aligned with negative minimum

docs/src/whatsnew/latest.rst, lib/iris/tests/experimental/test_animate.py
Occasionally we get test failures because `assertWarns` finds a warning about animation deletion when it is expecting something else, in tests that have nothing to do with animation.  Running this single test module prior to this change shows that the warning is thrown here.  I thought it might be worth suppressing it, but obviously I have no way to check whether it will cure the problem of interfering with other tests, as it only happens sporadically.
Worth a try?
---
=> Suppress warning in animation test

docs/src/whatsnew/latest.rst
This entry was under bugfixes in the branch at #4278, but somehow got shifted.  Probably something to do with the fact that the branch hadn't been rebased since the file was reset at #4288, but I'm surprised GitHub didn't flag a conflict.
---
=> Move intersection whatsnew

benchmarks/conda_lock_plugin.py, docs/gallery_code/general/plot_projections_and_annotations.py, lib/iris/tests/integration/experimental/test_regrid_ProjectedUnstructured.py, lib/iris/tests/integration/plot/test_vector_plots.py, lib/iris/tests/results/imagerepo.json, lib/iris/tests/results/unit/analysis/cartography/project/TestAll/cube.cml, lib/iris/tests/unit/analysis/cartography/test_project.py, requirements/ci/py37.yml, requirements/ci/py38.yml, setup.cfg
This PR includes the changes to support `cartopy` 0.20 and `proj` 8.0.1.
Also see the companion PR https://github.com/SciTools/test-iris-imagehash/pull/53 for the imagehash changes, which will require to be merged for this PR to pass.
Ref: https://github.com/SciTools/cartopy/pull/1252
---
=> Support cartopy 0.20 and proj 8.1.0

docs/src/whatsnew/latest.rst
Seems worthwhile adding a `whatnew` entry to highlight the `cartopy >=0.20` minimum pin introduced by #4331 for the community.
---
=> missing whatnew entry

docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_CubeList.py
This pull request addresses issue #4342: cube method `concatenate_cube()` can produce confusing error messages, reporting that `var1 != var1` when a user (erroneously) attempts to concatenate a multi-variable cube list consisting of, e.g., multiple time steps of var1 and var2  with `cubes = [var1, var1, var2, ...]`.
The reason for this behaviour is that the error message in the method quotes the first two elements of list `names`, which can be identical in the above scenario. This pull request replaces `names` with list `unique_names` when generating the error message - the latter list is used as a criterion for `concatenate_cube()` to reject concatenation, and it is guaranteed to produce non-identical variable names.  This should give the user better feedback on why concatenation failed. …
=> Clearer error message when using concatenate_cube on multi-variable cubes list

docs/src/whatsnew/latest.rst, lib/iris/plot.py
Just tidying up after myself 😊
These lines are a workaround for https://github.com/SciTools/cartopy/issues/1780, which caused a lot of test failures in Iris (see #4125).  The issue was fixed in https://github.com/SciTools/cartopy/pull/1784, which is included in the Cartopy 0.20 release.  Since we have now pinned to Cartopy>=0.20 (#4331), this workaround is now redundant.
---
=> Remove Cartopy 0.19 workaround

lib/iris/config.py, lib/iris/experimental/ugrid/__init__.py, lib/iris/experimental/ugrid/cf.py, lib/iris/experimental/ugrid/load.py, lib/iris/experimental/ugrid/mesh.py, lib/iris/tests/unit/experimental/ugrid/cf/test_CFUGridAuxiliaryCoordinateVariable.py, lib/iris/tests/unit/experimental/ugrid/cf/test_CFUGridConnectivityVariable.py, lib/iris/tests/unit/experimental/ugrid/cf/test_CFUGridMeshVariable.py, lib/iris/tests/unit/experimental/ugrid/load/test_load_meshes.py, lib/iris/tests/unit/experimental/ugrid/mesh/test_Mesh.py
This PR is a follow-up from #4347 and configures the `iris.experimental.ugrid.logger` to be a root logger.
The descendant modules `iris.experimental.ugrid.cf`, `iris.experimental.ugrid.load` and `iris.experimental.ugrid.mesh` now all configure their loggers to propagating their messages upwards to the root logger for appropriate handling.
Raising the `level` of the `iris.experimental.ugrid.logger` root logger above `NOTSET` will filter descendant logger messages appropriately; typically, this should not be necessary. Currently, the root logger is configured to report all descendant logger messages.
Alter the descendant logger `level`, as normal, to control logging e.g.,
```python
from iris.experimental.ugrid.load import logger
logger.setLevel("DEBUG")
```
will enable …
=> propagate ugrid logger and address `np.int` deprecations

.pre-commit-config.yaml, docs/src/whatsnew/latest.rst, lib/iris/__init__.py, lib/iris/analysis/__init__.py, lib/iris/analysis/calculus.py, lib/iris/analysis/cartography.py, lib/iris/common/metadata.py, lib/iris/fileformats/pp.py, lib/iris/fileformats/um/__init__.py
This PR enables the [sort-all](https://github.com/aio-libs/sort-all) `pre-commit` hook, which automatically sorts `__all__` lists alphabetically.
Recently I've seen a few PRs where authors had to move entries manually on request by a reviewer, which is a wee bit haphazard and tiresome. There have also been debates regarding sort order etc.
This will no longer be an issue, thanks to `pre-commit` automation and the opinionated `sort-all` hook. It also means that there's one less thing for the PR author/reviewer to think about :partying_face: 
Note that, `sort-all` can be manually installed and executed from the command line, if devs so wish. However, it's only available on [PyPI](https://pypi.org/project/sort-all/) atm
--- …
=> pre-commit sort-all

docs/src/whatsnew/latest.rst, requirements/ci/py37.yml, requirements/ci/py38.yml, setup.cfg
This PR introduces a minimum pin for `numpy>=1.18` in order to honour [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html).
`numpy` is approximately 24 months old, and the latest version is 1.21, so we're supporting greater than the latest 3 minor versions.
---
=> min pin for numpy (nep29)

docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py
The first concern was that the documentation is not sufficiently specific. I think two key questions users will want answered when they read it are:
- For coordinates with bounds, how much of a cell must overlap with the range in order to be included?
- If requesting a full 0-360 degrees splits a cell, which side of the range does the cell go to?
From the code, it looks like the answers are, respectively:
- Essentially any overlap, unless a very small range is requested, in which case it might miss a cell - only bounds/points are checked, not the intersection as intervals.
- Lower, unless the requested range hits a cell bound exactly (only recently addressed, in #4059). This is always based on bounds, regardless of `ignore_bounds`, potentially taking a point out of the requested range (as …
=> Assorted improvements to `Cube.intersection`

lib/iris/fileformats/netcdf.py, lib/iris/tests/integration/test_netcdf.py, lib/iris/tests/unit/fileformats/netcdf/test_Saver.py, lib/iris/tests/unit/fileformats/netcdf/test_Saver__lazy.py
Performance testing revealed that the [recent changes to stream all lazy data in netcdf saves](https://github.com/SciTools/iris/pull/4375) didn't quite fix the problem of realising lazy coordinates, as intended
I.E. nc-save is still loading all lazy aux-coords into memory.
So this fixes that, and adds a test to ensure the behaviour.
---
=> Don't realise lazy coords in netcdf save.

lib/iris/_concatenate.py, lib/iris/tests/unit/concatenate/test_concatenate.py
Added a "reason" keyword argument to `_coordinate_differences` as currently it attaches the reason, and whilst it can diagnose some of the problem, it doesn't know if it's just been given metadata or also values to check, whereas the calling method does.
Fixes #4096
Question for reviewer:
- Is this the best place to implement this fix? Should it be shallower or deeper instead?
---
=> Make concat mismatch warning for scalar coords more accurate

docs/src/whatsnew/latest.rst, lib/iris/fileformats/name_loaders.py, lib/iris/tests/results/name/NAMEIII_field.cml, lib/iris/tests/results/name/NAMEIII_timeseries.cml, lib/iris/tests/results/name/NAMEII_field.cml, lib/iris/tests/results/name/NAMEII_timeseries.cml, lib/iris/tests/unit/fileformats/name_loaders/test__build_lat_lon_for_NAME_timeseries.py, lib/iris/tests/unit/fileformats/name_loaders/test__cf_height_from_name.py, lib/iris/tests/unit/fileformats/name_loaders/test__generate_cubes.py
I recently discovered that as part of unpinning cftime in version 3.0.4 (#4222), a bug was introduced that makes it impossible to load a NAME file that contains only one time point. (Because `np.float_(arr)` on an array with one element returns a scalar, instead of another array with one element.)
I took the opportunity to fix some long-standing annoyances that we've so far just worked around:
- Vertical coordinates were never given the attribute `positive = up`, so the "axis" was not guessed as "Z".
- Iris tries to identify lat-lon coordinates in a column header with a regex for a float, but more recent versions of NAME may not use a decimal point.
(draft while I check whether there are other small things like that)
--- …
=> NAME loader fixes

setup.cfg
In 59.0.0, on 12/11/21, setuptools introduced a [breaking change](https://setuptools.pypa.io/en/latest/history.html?highlight=description%2059%20breaking#breaking-changes) that no longer allows multi-line descriptions. This has caused `nox` to fail when running the tests with a `ValueError`.
---
=> Remove newline to satisfy setuptools

lib/iris/analysis/_area_weighted.py, lib/iris/experimental/regrid.py, lib/iris/tests/integration/analysis/test_area_weighted.py, lib/iris/tests/unit/analysis/area_weighted/test_AreaWeightedRegridder.py
Aiming to speed up the regridding of chunked data with `iris.analysis.AreaWeighted` regridder
Moving more weight construction and construction of indices to be applied to the regridded cube all into the prepare step of the regridder, rather than the perform step (which gets repeated on chunked data)
See #4280 for context
To do:
---
=> `iris.analysis.AreaWeighted` regrid speedup

docs/src/developers_guide/release.rst, docs/src/whatsnew/latest.rst
@tkknight, earlier we discussed adding a short section to the releases docs to outline what the release manager does. What do you think of this?
---
=> Add release docs sections describing the role of a Release Manager

docs/src/whatsnew/latest.rst, lib/iris/analysis/cartography.py, lib/iris/tests/unit/cube/test_Cube.py
Updated affected tests using assertArrayAllClose following #3993.
Please see #3994.
=> Removed addition of period from wrap_lons

docs/src/whatsnew/latest.rst, lib/iris/tests/integration/analysis/__init__.py, lib/iris/tests/integration/analysis/test_area_weighted.py
Running the tests under `pytest`, I got `TypeError`s from these four tests, apparently because `save` expected a string but got an int.  These tests will have been missed by `nose` within the CI because the `__init__.py` was missing.
---
=> Minor fixes for regridding tests

docs/src/whatsnew/latest.rst, setup.cfg
Small issue - spotted that the PyPI classifier incorrectly states that Iris is GPL instead of LGPL.
=> Fix license PyPI classifier

lib/iris/tests/unit/util/test__coord_regular.py, lib/iris/util.py
Causes `iris.util.points_step` to check whether there are multiple points to check before trying (thus averting a warning is caused by only one point being provided).
Fixes #4250.
- Is it better to apply the fix here, or to apply it in `coords.from_regular` and thus leave this so that it warns when called with a single point (albeit cryptically) so that people calling it are aware that they may not be doing what they meant? I personally think that the np.nan return value of avdiff (which matches the current behaviour) is sufficient.
---
=> Only try to work out the differences between points for multiple

docs/src/developers_guide/contributing_code_formatting.rst, docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/cube.py, lib/iris/experimental/ugrid/mesh.py, lib/iris/tests/unit/cube/test_Cube.py, lib/iris/tests/unit/experimental/ugrid/mesh/test_Connectivity.py, lib/iris/tests/unit/experimental/ugrid/mesh/test_Mesh.py, lib/iris/tests/unit/experimental/ugrid/mesh/test_MeshCoord.py, lib/iris/tests/unit/fileformats/netcdf/test_Saver__ugrid.py, lib/iris/util.py
Allows checking of the equality of two `Mesh`es, fully inspecting their `Coord` and `Connectivity` membership.
Due to the way `MeshCoord.__eq__` is written, this also allows us to check the equality of two `Cube`s with `Mesh`es attached.
Acceptable performance also required making the equality of `_DimensionalMetadata` and `Connectivity` preserve array laziness.
---
=> Mesh full comparison

lib/iris/experimental/ugrid/__init__.py, lib/iris/experimental/ugrid/utils.py, lib/iris/tests/unit/experimental/ugrid/utils/__init__.py, lib/iris/tests/unit/experimental/ugrid/utils/test_recombine_regions.py, lib/iris/tests/unit/experimental/ugrid/utils/test_recombine_submeshes.py
First-version for "recombining" sub-mesh information.
It's worth noting that supporting location-index-sets would make this easier, as then the sub-region cubes would simply be referred to a common mesh+location, and the awkward 'special index coords' would not be required.
Without that, though, various alternative APIs are feasible + I could still be persuaded to change.
In particular, we _could_ replace 'full_mesh_cube' with 'mesh' + 'location' args -- it's effectively more logical, as we can deduce everything else from the region cubes.
So, that might be slightly neater, but more work is required .  Where elements could map both mesh and non-mesh dims, it could get complicated.
TODOs:
=> Mesh recombine

docs/src/whatsnew/latest.rst, lib/iris/tests/results/imagerepo.json, lib/iris/tests/unit/plot/test_contourf.py
Changes to get tests passing with Matplotlib v3.5.
* New image hash for one gallery example (see https://github.com/SciTools/test-iris-imagehash/pull/56)
* The antialias tests basically check whether `plt.contour` has been called, in addition to `plt.contourf`.  The tests previously relied on the fact that the two functions added different artist types to the axes, but this is no longer the case (https://github.com/matplotlib/matplotlib/issues/20906).  So have updated these tests to use `mock` instead.
---
=> Changes for Matplotlib v3.5

.github/workflows/benchmark.yml, .github/workflows/refresh-lockfiles.yml, .github/workflows/stale.yml, docs/src/whatsnew/latest.rst
Prevents GH actions from running automatically in forks. Fixes #4441
Reviewer considerations:
* Will this have adverse effects on any GH workflows (e.g. making releases) or does this all happen in the main repo?
---
=> Disable GHA workflows on non-SciTools branches

lib/iris/tests/unit/fileformats/nc_load_rules/actions/test__hybrid_formulae.py
Fixes #4431 which highlights that the method used to construct some tests in `iris/tests/unit/fileformats/nc_load_rules/actions/test__hybrid_formulae.py` wasn't allowing them to be picked up by `nose`.  I've expanded the short method that was being used to make the tests into a repetitive setup that should be picked up by `nose`, hopefully exactly replicating the previous tests.
---
=> test__hybrid_formulae.py nose discovery

requirements/ci/py37.yml, requirements/ci/py38.yml, setup.cfg
Remove the unrequired `asv` package dependency.
---
=> remove asv package dependency

docs/src/userguide/loading_iris_cubes.rst
The userguide on loading cubes was potentially misleading in referring to a CubeList as a list of cubes. I've clarified this, whilst dropping the word count of the note it's mentioned in to reduce how much we distract from the main points being made in the section.
---
=> Clarify the return type of iris.load (AVD-1899)

docs/src/userguide/plotting_a_cube.rst
Updated a couple of Matplotlib links in the User Guide.  They were both automatically redirecting, but the `pyplot` link landed at v2.0.2 of the Matplotlib docs 😬
I'm not convinced this is big enough to warrant a whatsnew, but will add one if the reviewer disagrees.
---
=> Update Matplotlib links

lib/iris/fileformats/_nc_load_rules/actions.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/__init__.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/test__latlon_dimcoords.py
Closes #4460 
I realised that the reported problem was due to a mistake which I introduced in #4198 :
I had retained unchanged the trusted older routines, 'is_latitude/longitude' and 'is_rotated_latitude/longitude' , but changed the way in which they are used :  As written, 'is_rotated' relies on your having already ensured the truth of 'is_latitude_longitude'.
The small changes here to `iris.fileformats._nc_load_rules.actions` fix that.
Since there were no specific tests before, I have now developed a test harness for this aspect of the translation process.
Having encountered the problems described at #4469 (see below), I have only included simpler testcases, and particularly excluded some more complex ones which show potentially problematic changes in behaviour.  However, I think the …
=> Nc load latlon fix

.readthedocs.yml, docs/src/whatsnew/latest.rst
This PR adopts the latest `mambaforge` image workflow from RTD to build our documentation, replacing our previous use of the RTD [Legacy build specification](https://docs.readthedocs.io/en/stable/config-file/v2.html#legacy-build-specification).
When using the legacy RTD specification, typically I've seen documentation builds taking between `670-730 seconds`.
Using the latest `mambaforge` image, this PR built its documentation in `454 seconds`... which is quite an improvement :rocket: 
(although, this is only a sample of one :wink:)
The built documentation associated with this PR can be viewed [here](https://bjlittle-iris.readthedocs.io/en/latest/), and the raw RTD build log can be viewed [here](https://readthedocs.org/api/v2/build/15679017.txt).
--- …
=> rtd with latest mambaforge image for faster building

docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/test_pickling.py, lib/iris/tests/unit/cube/test_Cube.py
Where previously a function was defined within cube.convert_units if the cube had lazy data, now a partial object is created instead.
The definition of a function at runtime was preventing pickling of a cube that had lazy data and was awaiting a convert_units operation. This is no longer the case. (fixes #4354)
---
=> Use partial to make cube pickleable

docs/src/whatsnew/latest.rst
Fills a hole I left in #4470, [as @bjlittle suggested](https://github.com/SciTools/iris/pull/4470#issuecomment-1005520456)
=> Whatsnew entry for #4470.

docs/src/developers_guide/release.rst, docs/src/whatsnew/latest.rst, etc/cf-standard-name-table.xml, tools/generate_std_names.py
Closes #4479
Updated standard names, in advance of 3.2 release.
Was considering also the metadata translations, and https://github.com/SciTools/iris/issues/3950
But I have been reminded that standard-names is not really a part of that, so I'm going to deal with that [separately](https://github.com/SciTools/iris/pull/4484).
=> Standard names table update.

lib/iris/util.py
This PR addresses the test failures within #4480 when updating to the latest `numpy` v1.22.0.
We've now dropped support within `iris` for `py37` (#4481) but we still require to support `numpy` >= v1.19 ([NEP29 Support Table](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table)). However https://github.com/numpy/numpy/pull/19686 introduced a change that impacts `iris.util.format_array` due to our use of the internal `numpy.core.arrayprint._formatArray` function.
This PR maintains our continuing `numpy` v1.13 legacy array printing format for `py38` and `numpy` >= 1.19.
As a separate concern, it would be wise to commit to addressing #3048, by _at least_ bumping to the more recent `numpy` v1.21 legacy array printing.
--- …
=> address np printoptions pre/post v1.22

lib/iris/cube.py
Recently we had a user having trouble with regridding as they had not realised that they need to provide an _instance_ of the scheme, rather than just the class.
I.e. they did
`cube.regrid(target_grid, iris.analysis.Linear)`
rather than 
`cube.regrid(target_grid, iris.analysis.Linear())`
From the docs, we don't make it clear that we want an instance rather the class itself. And it's perfectly reasonable for a function to accept a class (and then under the hood, that function instantiates the class when/how it needs to)
I wondered if we should clarify this in the docs, specifically in the API docs (we already have examples of regrid/interpolate in the user guide).
In this PR I have proposed a simple addition for both the regrid and interpolate methods. However I note that the interpolate …
=> Clarify interpolate and regrid scheme use

docs/src/conf.py
From https://github.com/SciTools/iris/discussions/4383#discussioncomment-1917571 and replies, there seems to be a consensus that we don't want to display type annotations in the docs.  There are not many examples in Iris so far, but for [recombine_submeshes](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/experimental/ugrid/utils.html#iris.experimental.ugrid.utils.recombine_submeshes) this PR turns
into
---
=> Turn off documentation type hints

docs/src/whatsnew/latest.rst
This PR introduces a minor fix to remove additional spacing that's causing `whatsnew` `:issue:` directives to not render correctly.
i.e., fixes the following
---
=> docs: fix whatnew entries

docs/src/whatsnew/latest.rst, lib/iris/coord_systems.py, lib/iris/tests/test_coordsystem.py, lib/iris/tests/test_mapping.py, lib/iris/tests/unit/analysis/cartography/test_project.py
Fixes #4408 by passing the `GeogCS` as a globe to the `cartopy.crs.PlateCarree` constructor
---
=> GeogCS.as_cartopy_projection handling non-Earth planets

docs/src/whatsnew/latest.rst, lib/iris/experimental/raster.py
Deprecation as per #4394. If it turns out that this is used, we can reverse the deprecation or make it a plug-in.
---
=> Deprecate experimental.raster

docs/src/whatsnew/latest.rst, lib/iris/fileformats/__init__.py, lib/iris/fileformats/abf.py, lib/iris/fileformats/dot.py
=> Deprecate abf and dot

docs/src/whatsnew/latest.rst, lib/iris/fileformats/um_cf_map.py
Closes #3305.  The relevant lines of the [UM STASHmaster metadata file](https://code.metoffice.gov.uk/trac/um/browser/main/trunk/rose-meta/um-atmos/HEAD/etc/stash/STASHmaster/STASHmaster-meta.conf) read:
```
[stashmaster:code(9215)]
description=CLOUD BASE ASL COVER.GT.7.9 OCTA KFT
```
---
=> Correct long_name for STASH 9215

docs/src/whatsnew/latest.rst
This PR removes a duplicate entry for a first time contributor, who'd actually contributed for the first time in `iris` 3.1
---
=> docs: remove duplicate first contributor entry

lib/iris/experimental/raster.py
While working on deprecations for 'iris.experimental.regrid', I happened to revisit this + concluded that it really should provide a runtime message when you call the routine, so I added one.
A slight escalation of the plan, but I think is worth it.
---
=> Add deprecation on routine usage.

docs/src/conf.py
This PR resolves the following warning which is raised when building the documentation with `html-noplot` or `html-quick`
Also see:
- https://github.com/sphinx-gallery/sphinx-gallery/issues/302
- https://github.com/sphinx-gallery/sphinx-gallery/pull/304
Note that, the `plot_gallery=0` directive to `make` within the `docs/src/Makefile` ensures that the documentation gallery is not built.
---
=> docs: fix docs/conf.py plot_gallery warning

lib/iris/experimental/regrid_conservative.py
=> Deprecate regrid conservative

docs/src/whatsnew/latest.rst, lib/iris/_merge.py, lib/iris/cube.py
This PR introduces an optimisation to `iris.cube.Cube.coord_dims`, and also a lesser optimisation to merge.  
This change contributes, in part, to addressing the use case raised by issue #4538. As a result, I've seen a rough 25% speed-up of the worst case scenario given in #4538 (on my desktop) i.e., loading a 24,000 field PP file (time series) has gone from ~80secs to ~60secs. 
Essentially, a cheap win saving can be achieved by not blindly calling `iris.cube.Cube.coord` within `iris.cube.Cube.coord_dims`, particularly when the actual cube coordinate that exists within the cube is provided to the `coord_dims` method.
The philosophy of `coord_dims` is to avoid coordinate equivalence, as it is a relatively expensive operation, but rather use object identity instead, if possible.
--- …
=> minor optimisations

docs/src/further_topics/ugrid/operations.rst
Fix to make some doctests introduced by the UGRID docs (#4504) compliant with the latest `attributes` printout in `Cube` summaries (#4528) (the attributes change was made between the last update to the UGRID docs branch and the time when it was merged, so this only got caught by the post-merge CI).
---
=> Update #4504 doctests for #4528

docs/src/whatsnew/latest.rst
A few more suggested tweaks to the whatsnew, mostly just formatting.
---
=> Whatsnew minor tweaks

docs/src/whatsnew/dev.rst, docs/src/whatsnew/dev.rst.template
Similar to what was done after the v3.1.x branch was cut: https://github.com/SciTools/iris/pull/4288/files
I copied dev.rs.template -> dev.rst and then removed the part relating to patches
Also include some minor updates to the templates that are required after we changed latest.rst -> dev.rst
---
=> Reset whats new

setup.cfg
This PR includes a minor update to the PyPI Trove classifiers to drop our reference to `py37`. This should be corrected for the `v3.2.0` release.
Note that this PR is targeting the `v3.2.x` release feature branch, so once merged this change will appear in `main` on merge-back.
---
=> update trove classifiers

lib/iris/__init__.py
Now that the v3.2.x branch is cut we should update the main branch to be using version 3.3.dev0
---
=> Update version to 3.3.dev0

docs/src/whatsnew/3.2.rst, lib/iris/__init__.py, lib/iris/fileformats/netcdf.py, lib/iris/io/__init__.py, lib/iris/tests/test_load.py
This addresses two issues relating to loading files via OPeNDAP
**Fix iris.io.load_http and add extra testing**
It looks like `iris.io.load_http` broke in Iris 3.1 when we moved imports around. I have added the import (`from iris.fileformats import FORMAT_AGENT`)
Unfortunately a lack of testing meant we didn't catch it! Currently, the only OPeNDAP related testing we have is:
* we test load/load_cube/load_cubes/load_raw call iris.io.load_http
* we check that the format_picker selects the correct FormatSpecification ('NetCDF OPeNDAP'). 
You can see these two tests in [this commit](https://github.com/SciTools/iris/pull/422/commits/f1a9f0603c4b283921e99f1bec381c40bc570af1).
Testing with http files is quite difficult as we don't want to be tied to trying to access an OPeNDAP server which may …
=> Fix load_http bug, extend testing, and note to docs

lib/iris/tests/unit/fileformats/pp_load_rules/test__convert_time_coords.py
Closes #3508.  It looks to me that we just forgot to account for 1972 begin a leap year 🧐
---
=> Reinstate pp time conversion test

docs/src/whatsnew/3.2.rst, lib/iris/__init__.py
Final steps before we cut the 3.2.0 release
---
=> Finalise whatsnew and version string update

lib/iris/__init__.py, setup.cfg
A [commit that fixes the PyPI classifies](https://github.com/SciTools/iris/commit/ba77f5d08f33524bd38ea6a55df3efc50bbdd53f) which was added to v3.1.x unfortunately missed the mergeback to `main`.
I have cherry picked that commit and updated the version number
---
=> Add missing commit to v3.2.x and update version number

docs/src/conf.py, docs/src/whatsnew/3.2.rst, docs/src/whatsnew/index.rst, lib/iris/__init__.py, lib/iris/fileformats/netcdf.py, lib/iris/io/__init__.py, lib/iris/tests/test_load.py, setup.cfg
Mergeback from 3.2.x, following 3.2.0 release
---
=> Mergeback v3.2.x branch into main

.github/workflows/refresh-lockfiles.yml, .github/workflows/stale.yml
I think this makes sense, and fixes https://github.com/SciTools/iris/issues/299#issuecomment-1040858264
Before, when loaded I was getting this :
```
import yaml
>>> with open('/home/h05/itpp/git/iris/iris_main/.github/workflows/stale.yml') as fo:
...   data = yaml.full_load(fo)
... 
>>> data['jobs']['stale']['steps'][0]['with']['exempt-issue-labels'] 
'"Status: Blocked,Status: Decision Required,Peloton 🚴\u200d♂️,Good First Issue"\n'
>>>
```
So ... that string has embedded quotes, and a newline at the end.
So I _think_ this must mean that it excludes labels called :
* /"Status: Blocked/
* /Status: Decision Required/
* /Peloton 🚴\u200d♂️/
* /Good First Issue"\n/
I.E. the first + last ones don't work!
With changes here,  I now get
```
>>> …
```
=> Yaml fixes + clarifications.

lib/iris/fileformats/_nc_load_rules/actions.py, lib/iris/fileformats/netcdf.py
Just spotted that our  API docs include the class `iris.fileformats.netcdf.OrderedAddableList`, which is unintended.
This was introduced in Iris v3.1.0, when we replaced the Pyke rules, but it seems has mistakenly been published as part of the public API + appears in the API docs, e.g. :
https://scitools-iris.readthedocs.io/en/v3.1.0/generated/api/iris/fileformats/netcdf.html#iris.fileformats.netcdf.OrderedAddableList
I don't think it's a big deal to just say this was a mistake + withdraw it, i.e. no deprecation or warnings required.
"Ideally" this might be combined with a desirable reorganisation of the netcdf package #4291, 
but that is basically for developers' benefit, whereas this is about the public API, so let's keep it separate.
=> Utility class in netcdf loader should not be public.

docs/src/whatsnew/dev.rst, lib/iris/plot.py, lib/iris/tests/integration/plot/test_netcdftime.py, lib/iris/tests/unit/plot/test__fixup_dates.py, requirements/ci/py38.yml, setup.cfg
`nc_time_axis.CalendarDateTime` was deprecated at v1.4 of `nc-time-axis` and we are encouraged to pass the `cftime` objects directly, which is nicer.  Fixes the easy part of #4574.
References
https://github.com/SciTools/nc-time-axis/pull/80 new plotting functionality introduced.
https://github.com/SciTools/nc-time-axis/pull/86 `CalendarDateTime`s deprecated.
I will add a whatsnew when I know that merge is imminent.  Or in a separate PR if the reviewer prefers.
---
=> Stop using nc_time_axis.CalendarDateTime

.cirrus.yml, docs/src/whatsnew/dev.rst, lib/iris/coord_systems.py, lib/iris/fileformats/_nc_load_rules/helpers.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/results/coord_systems/Mercator.xml, lib/iris/tests/results/netcdf/netcdf_merc.cml, lib/iris/tests/results/netcdf/netcdf_merc_false.cml, lib/iris/tests/test_netcdf.py, lib/iris/tests/unit/coord_systems/test_Mercator.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_has_supported_mercator_parameters.py
Adds support for the false-easting and false-northing kwargs when creating a Mercator projection in Iris.
Closes #3107
To do:
---
=> Support false-easting and false-northing when loading Mercator-projected data

docs/src/whatsnew/dev.rst, lib/iris/plot.py, lib/iris/tests/results/imagerepo.json
Closes #4493.  Cube data should now automatically go on the x-axis of an `iplt.plot` only if plotting against a vertical coordinate.
Since this is reverting to previous behaviour, for the affected tests I just looked in #3906 for what the good hashes used to be, and reinstated those.  It seems to me a good idea to do this before @wjbenfold starts moving the image-hashing infrastructure around! 😅
---
=> Revert plotting-vs-y

docs/src/whatsnew/3.2.rst, lib/iris/analysis/cartography.py, lib/iris/tests/unit/analysis/cartography/test_rotate_winds.py
Addresses the first point in https://github.com/SciTools/iris/issues/4582 by making iris.analysis.cartography._crs_distance_differentials() use the .globe attribute of the input crs parameter instead of creating a new ccrs.Globe() object.
Apologies for messing the [previous PR](#4596). This PR repeats the necessary changes, including updates of `whatsnew`, but now on a correct branch.
---
=> (corrects the mess with branches in #4596) Use crs.globe in _crs_distance_differentials()

.github/workflows/benchmark.yml, noxfile.py
Fixes something I didn't catch during testing (presumably because I used a known commit rather than the ones that were a problem).
```
pr_number=$(git log "$commit_file"^! --oneline | grep -o "#[0-9]*" | tail -1 | cut -c 2-)
...
fatal: ambiguous argument 'b42c65da': both revision and filename
...
```
---
=> Overnight benchmarks remove ambiguity between file and commit names.

.github/workflows/refresh-lockfiles.yml, docs/src/developers_guide/contributing_ci_tests.rst
Closes #4606
Currently the no_clobber task is broken. It looks like `github.repos` is no longer returning what we expect. My best guess would be that this may need to be changed to `github.rest.repos` but I'm not sure! I struggled to find much information on this!
However, at yesterday's peloton we discussed changing our development workflow such that when a ``auto-update-lockfiles`` branch fails the tests, a developer creates a new branch with those changes, and adds the fixes onto their own branch and then we merge the new branch. 
Effectively reverts the change added in #4157
---
=> Remove no_clobber task from Refresh lockfiles Action

.github/workflows/benchmark.yml
Fixes a problem where the benchmark action attempts to assign the issue it is creating to a non-existent user (e.g. `github-actions` [as in this example](https://github.com/SciTools/iris/runs/5472430658?check_suite_focus=true#step:9:43)).
---
=> Overnight benchmarks - find a valid issue assignee

docs/src/whatsnew/3.2.rst, lib/iris/fileformats/netcdf.py, lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
Closes #4599.
Corrects a problem where bounds for a scalar coordinate - still in a 2D array - where hitting a 'broadcast ambiguity' trying to save to a 1D CF variable.
---
=> Avoid dimensionality mismatch between data array and CF variables.

docs/src/whatsnew/3.2.rst, lib/iris/__init__.py
Now that the bug fixes #4610 and #4605 are in I would to cut the v3.2.1 release. 
In this PR I updated the version string and what's new. I also made a fix to a problem with the whats new that I had introduced in #4604. Turns out that underlining your headings with `*` (aka for chapters) adds an extra link in the side panel. Below shows what the current docs build for the v3.2.x branch looks like:
Fixing the underline to be `=` (aka for sections), the build of this branch looks like:
---
=> Last steps before v3.2.1 release

benchmarks/benchmarks/import_iris.py, benchmarks/benchmarks/save.py
Closes #4633, closes #4634.
Removes another memory benchmark that was so small as to disappear behind natural noise, resulting in false positives being flagged.
A significant change to our import benchmarks:
Some of our import benchmarks results were also very small - nanoseconds - and therefore vulnerable to noise and false positives. After some lengthy experimentation I've discovered that these have not been running any imports at all! More experimentation shows that `importlib.reload()` _does_ achieve an import, with barely any overhead time beyond the expected import time, and also avoids concerns about import caching making any repetitions much faster, so I've gone with that.
It's annoying that this came up and needed fixing, but noticing the problem in the first place is precisely …
=> Improve Small Benchmark Accuracy

docs/src/conf.py, docs/src/voted_issues.rst
Updated the voted issues pages:
- Frequency is now every 30 mins for the GitHub action update (see the [other repo pr](https://github.com/SciTools/voted_issues/pull/3/files#diff-5b66dbc188123409edf84583bdd8306da438eab6c8a6d70b51c78129431401a9R8) for info)
- Changed table name in the JavaScript
---
=> Updated GHA frequency and table name for Voted Issues

docs/src/whatsnew/dev.rst, lib/iris/analysis/__init__.py, lib/iris/tests/unit/analysis/test_Aggregator.py
Fixes #3190.  Note that the examples provided there all involve 1D cubes and by the time `Aggregator.aggregate` is called, `Cube.aggregated_by`  has sliced out and passed the array for one particular section.  So the problem boils down to the issue illustrated in the new test:  if you average an entirely masked array, you get the `ma.masked` constant, whose `mask` attribute is read-only.  In this situation, there is no point doing anything extra for `mdtol` anyway, so just skip the loop.
I have verified that the three examples from #3190 all work with this change.
---
=> Fix aggregated_by mdtol/masked constant problem

docs/src/whatsnew/dev.rst, lib/iris/tests/stock/__init__.py
I can't see a reason why this function shouldn't respect the argument it accepts, so I've made it do so
---
=> Make iris.tests.stock.simple_1d respect bounds arg

.github/workflows/benchmark.yml
As discussed with @pp-mo. The current check is erroneously identifying dependabot as a valid user, when it is actually an organisation.
---
=> Improved check for valid user in overnight BM run.

docs/src/whatsnew/dev.rst, lib/iris/plot.py, lib/iris/tests/unit/plot/test__replace_axes_with_cartopy_axes.py
Fixes #1157.  The example from that issue now produces:
This fix seems almost too easy, so I am somewhat worried I'm missing something 👀 
I couldn't find any existing tests for this helper function (I guess it is well tested indirectly though), so added a new test module.
---
=> Preserve position when replacing Axes with GeoAxes

docs/src/whatsnew/dev.rst, lib/iris/_lazy_data.py, lib/iris/analysis/__init__.py, lib/iris/tests/unit/analysis/test_PERCENTILE.py, lib/iris/tests/unit/analysis/test_PercentileAggregator.py, lib/iris/tests/unit/analysis/test__axis_to_single_trailing.py, lib/iris/tests/unit/lazy_data/test_map_complete_blocks.py
Implements lazy aggregation for the `iris.analysis.PERCENTILE` aggregator.
My experience with `dask` is minimal, so I had a look at #3701 and basically used that approach as a template for the `_percentile` function implementation.  I believe I've understood the intent of the `map_complete_blocks` function but really not how it works.  So it's possible I've missed something important there.
I note that [dask.array.percentile](https://docs.dask.org/en/latest/array-api.html#dask.array.percentile) exists for 1D arrays, but I'm not clear how we'd incorporate the check for masked data if using that.
leaving as draft for now as I have an outstanding question about code structure and associated tests (see inline comments).
I realise you are all busy so I'm not expecting this to get attention …
=> Lazy Percentile Aggregator

docs/src/whatsnew/dev.rst, lib/iris/coords.py, lib/iris/tests/unit/coords/test_Coord.py
Fixes #2969.  The example given there now returns `None` as expected.
---
=> Fix nearest_neighbour_index for edge case where requested point is float and bounds are int

docs/src/developers_guide/contributing_ci_tests.rst, docs/src/whatsnew/dev.rst
Making a lock-file might include URLs routed through your proxy. I've added a note to the docs to point this out
---
=> Include note to strip out Artifactory

benchmarks/benchmarks/load/__init__.py, docs/src/whatsnew/dev.rst
Some speed issues in `.pp` and `.ff` files scale with field number, rather than field size (due to chunking strategy). This PR adds some relatively small but deep file tests to the load benchmarks.
---
=> 'Deep' benchmarks to catch scaling with field count

lib/iris/tests/unit/analysis/test_PERCENTILE.py
Follow up to #3901, with some updates to the percentile tests:
* I realized the tests for checking that our `alphap`, `betap` kwargs get passed to `scipy` weren't quite right for the lazy case because
* Passing a non-lazy array means that `map_blocks` never actually gets called!
* We _expect_ the `mquantiles` call to happen when the data is realized, so we need a call to `as_concrete_data`.  Note that the tests would currently pass without the `as_concrete_data` call, because `mquantiles` is initially applied to a 0D array, as described at #4598, but that might change at some point.
* Added basic tests to verify that `numpy.percentile` gets called as expected for fast method.
Happily, the tests all still pass 🙂
--- …
=> Update percentile tests

docs/src/conf.py, docs/src/developers_guide/gitwash/development_workflow.rst, docs/src/developers_guide/gitwash/forking.rst, docs/src/developers_guide/gitwash/git_links.inc
Linkcheck is failing on the github docs url.  This PR `ignores` that url and ensure some references are `https` and not `http`.
---
=> added link check ignore and ensured https use

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/util.py
Speed up for `pp` and `ff` file loading by caching expensive check at the start of `DimCoord` creation. I've introduced an extra array copy per `DimCoord` on a flat pp file, but I think the improvements on deep files outweighs this concern.
Benchmark results from dedicated machine:
```
All benchmarks:
before           after         ratio
[478fa635]       [c4c75aa1]
-      10.9±0.1ms      9.73±0.05ms     0.90  load.LoadAndRealise.time_load((1280, 960, 5), False, 'FF')
33.4±0.9ms       31.9±0.3ms     0.95  load.LoadAndRealise.time_load((1280, 960, 5), False, 'NetCDF')
-      12.0±0.2ms      10.6±0.05ms     0.88  load.LoadAndRealise.time_load((1280, 960, 5), False, 'PP')
-      11.1±0.3ms      9.68±0.03ms     0.88  load.LoadAndRealise.time_load((1280, 960, 5), True, 'FF')
32.0±0.6ms …
```
=> Cache regular points generation

docs/src/whatsnew/latest.rst, docs/src/whatsnew/latest.rst.template, lib/iris/fileformats/cf.py, lib/iris/tests/test_cf.py
Based on #3312 and taking @evertrol up on the offer of replicating the changes in #3336.
Rather than setting `_dataset` to `None` I've taken the approach of catching and ignoring the attribute error on file close (OSErrors etc. will still be raised).
---
=> Catch `AttributeError` from removing `CFReader._dataset` when it doesn't exist

.cirrus.yml, docs/src/whatsnew/latest.rst, docs/src/whatsnew/latest.rst.template, lib/iris/coord_systems.py, lib/iris/fileformats/_nc_load_rules/helpers.py, lib/iris/fileformats/netcdf.py, lib/iris/tests/results/coord_systems/Mercator.xml, lib/iris/tests/results/netcdf/netcdf_merc.cml, lib/iris/tests/results/netcdf/netcdf_merc_false.cml, lib/iris/tests/results/netcdf/netcdf_merc_scale_factor.cml, lib/iris/tests/results/unit/fileformats/netcdf/Saver/write/mercator.cdl, lib/iris/tests/results/unit/fileformats/netcdf/Saver/write/mercator_no_ellipsoid.cdl, lib/iris/tests/test_netcdf.py, lib/iris/tests/unit/coord_systems/test_Mercator.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/test__grid_mappings.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_mercator_coordinate_system.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_has_supported_mercator_parameters.py
Building on #4524, this PR goes further than adds support for the full set of CF parameters for a Mercator projection (see https://cfconventions.org/cf-conventions/cf-conventions.html#_mercator)
This fixes #3844 too.
I've made some choices about the defaults when making a Mercator Coord System that will change existing behaviour - currently (before #4524) on load we assume a standard parallel, but on write we ignore the standard parallel and save with a scale factor of 1 (despite these being mutually exclusive and depending on each other).
---
=> Implement full Mercator parameter support

docs/src/whatsnew/latest.rst
Giving credit where it's due
---
=> Add evertrol to whatsnew of #4646 given #4705

docs/src/common_links.inc, docs/src/whatsnew/latest.rst, lib/iris/analysis/__init__.py, lib/iris/cube.py, lib/iris/tests/results/analysis/aggregated_by/easy.cml, lib/iris/tests/results/analysis/aggregated_by/multi_missing.cml, lib/iris/tests/results/analysis/aggregated_by/weighted_easy.cml, lib/iris/tests/results/analysis/aggregated_by/weighted_multi.cml, lib/iris/tests/results/analysis/aggregated_by/weighted_multi_missing.cml, lib/iris/tests/results/analysis/aggregated_by/weighted_multi_shared.cml, lib/iris/tests/results/analysis/aggregated_by/weighted_single.cml, lib/iris/tests/results/analysis/aggregated_by/weighted_single_missing.cml, lib/iris/tests/results/analysis/aggregated_by/weighted_single_shared.cml, lib/iris/tests/results/analysis/aggregated_by/weighted_single_shared_circular.cml, lib/iris/tests/test_aggregate_by.py, lib/iris/tests/test_analysis.py, lib/iris/tests/test_lazy_aggregate_by.py, lib/iris/tests/unit/cube/test_Cube.py
This pull request implements weighted `aggregated_by`, e.g.,
```py
annual_mean_cube = monthly_mean_cube.aggregated_by('year', iris.analysis.MEAN, weights=n_days_per_month)
```
The implementation allows lazy and non-lazy aggregation, and fully supports the keyword `returned=True`. I also added a large number of tests to extensively test this feature; all seems to work fine.
Closes #4581.
---
=> Weighted `aggregated_by`

docs/src/whatsnew/latest.rst, lib/iris/cube.py
In response to https://github.com/SciTools/iris/issues/4713 and several similar benchmark performance triggers, 
which seem to indicate that the time to call `iris.cube.Cube.add_aux_factory` is highly variable.
Actually, it seems on reflection that this time is unexpectedly **_long_**.
This attempts to address the speed issue, by 
Initial local testing results ...
```
$ nox --session="benchmarks(custom)" -- continuous -e --bench AuxFactory "2f9c8d0da~1..c60ff9a80"
nox > Running session benchmarks(custom)
. . .
Running ASV...
nox > cd benchmarks
nox > asv machine --yes
. . .
· Ignoring ASV setting(s): `python`. Benchmark environment management is delegated to third party script(s).
· Creating environments
· Discovering benchmarks
· Running 6 total benchmarks (2 commits * 1 environments * 3 …
```
=> Addaux speedup

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/tests/integration/merge/test_merge.py, lib/iris/tests/unit/coords/test_Cell.py
Fixes #4681 by making Cell equality handle nans in the same way as Coord equality, i.e. returning true when comparing a nan value with another value. This causes scalar coords containing nans to merge into one scalar coord rather than creating a long AuxCoord.
---
=> Change Cell equality to equate nans (fixes #4681)

lib/iris/fileformats/netcdf.py, lib/iris/tests/stock/mesh.py, lib/iris/tests/unit/fileformats/netcdf/test_save.py
A response to having encountered [this known netcdf bug](https://github.com/Unidata/netcdf-c/issues/1772)
I think this should *not* upset existing behaviour.
We might need to modify some test results, but I expect **_not_**, since any cases that trigger the code changes would have failed with the HDF error it is trying to avoid.
There is another question as to test coverage : 
I've added one test, which fails with the older code.
However, I have implemented "the fix" in multiple code locations, wherever dimensions are created -- or in the case of 'get_dim_names' method, where the names get chosen, prior to creation.
So in principle, for full coverage, I **_could_** add more tests to trigger each of those cases.
I'm not yet sure whether I think that is worth it ...
=> Netcdf saving: workaround known netcdf bug.

docs/src/whatsnew/latest.rst, lib/iris/analysis/__init__.py
`iris.analysis.MAX_RUN` hadn't made it into the API docs or what's new. This is fixed here.
Closes #4725 
Docs build here: https://www-avd/~wbenfold/iris/whatsnew/latest.html
---
=> `MAX_RUN` into docs

benchmarks/benchmarks/generate_data/um_files.py
Removes a monkey patch in the benchmarks data generation code, since the fix has now been applied to the Mule source code.
This will address the failures seen in the last three night's benchmark runs.
---
=> Remove Mule monkey patch.

docs/src/whatsnew/latest.rst, lib/iris/cube.py
Some very minor omissions that I should have noticed at #4723 
---
=> Climatology doc follow-up

docs/src/whatsnew/latest.rst, lib/iris/plot.py, lib/iris/tests/results/imagerepo.json, lib/iris/tests/test_plot.py
Closes #466, which is caused by Iris extending cubes to handle the wrapping of circular coordinates when plotting but not doing the same for additional arguments to the plot.
Still to do:
* New test image
* What's new
---
=> Plotting circular data extends args as well as the data

lib/iris/coord_systems.py, lib/iris/fileformats/_nc_load_rules/helpers.py, lib/iris/tests/integration/test_netcdf.py, lib/iris/tests/test_coordsystem.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/__init__.py
#4704 introduced a performance regression in the load process (see #4728) as the globe and cartopy crs of a `GeogCS` were being made at the time it was created, even if they were never used. This PR aims to restore performance by delaying the creation of those objects.
Additionally, @jamesp pointed out that setting attributes on `GeogCS` objects wasn't well handled by the implementation in #4704. I've now handled attribute setting in a manner that emulates the existing behaviour:
- Setting `semi_major_axis` or `semi_minor_axis` will change the globe and CRS returned by `as_cartopy_globe` and `as_cartopy_crs`.
- Setting `inverse_flattening` will not have an effect on anything except the value of that attribute.
I've also extended the behaviour so that setting the datum or a value that …
=> Datum performance improvements

lib/iris/coord_systems.py, lib/iris/tests/integration/test_netcdf.py
@jamesp pointed out that an example in the CF conventions shows a datum translation we don't yet cover - have added that.
Also took out an unnecessary comment I found whilst doing so.
There's a valid question of "what's the right value for this field to have when it's set in CF?", which I don't have a good answer for. Using `pyproj.CRS.to_cf` gives the following, which matches the existing translation (ellipsis mine):
```
>>> import pyproj
>>> crs = CRS.from_proj4("+proj=merc +datum=OSGB36")
>>> crs.to_cf()
{
'crs_wkt': ...,
'semi_major_axis': 6377563.396,
'semi_minor_axis': 6356256.909237285,
'inverse_flattening': 299.3249646,
'reference_ellipsoid_name': 'Airy 1830',
'longitude_of_prime_meridian': 0.0,
'prime_meridian_name': 'Greenwich',
'geographic_crs_name': 'unknown', …
```
=> Extra datum translation

docs/src/whatsnew/latest.rst, lib/iris/analysis/__init__.py, lib/iris/tests/unit/analysis/test_PERCENTILE.py
Closes #4735
We can't do the full check in the `PercentileAggregator.lazy_aggregate` method because we can't inspect the array to check if it's masked when it's lazy so I've left it where it was but done a check on `mdtol` out there where we know about it.
---
=> Permit fast percentile with mdtol=0

docs/src/whatsnew/latest.rst
Reviewers deserve credit too!
---
=> Credit @rcomer on PR #4755 review

benchmarks/README.md, benchmarks/benchmarks/generate_data/__init__.py, benchmarks/benchmarks/generate_data/stock.py, benchmarks/benchmarks/sperf/__init__.py, benchmarks/benchmarks/sperf/combine_regions.py, benchmarks/benchmarks/sperf/load.py, lib/iris/tests/stock/netcdf.py, noxfile.py
Various small corrections after trying out C/SPerf benchmarks in reality (not just on paper).
* Warnings about especially large test files and their location.
* Use a consistent hashing algorithm `hashlib.sha256()` when preserving file generation arguments in filenames.
Previous use of `hash()` meant a different file name each time - not what was intended when aiming for file re-use!
* Fewer time steps in SPerf test files.
* Previous parameters generated files up to `700GB` in size, and over `4TB` total for all files.
* New parameters use `400GB` total, with the largest file at `90GB`.
* Longer benchmark timeouts to allow more time for test file generation.
* Place SPerf `combine_regions` files in the standard `BENCHMARK_DATA` location - they are sizeable so using the standard temp file …
=> CPerf and SPerf Benchmark Fixes

lib/iris/tests/unit/experimental/ugrid/cf/test_CFUGridReader.py, lib/iris/tests/unit/fileformats/cf/test_CFReader.py
Some warnings in our test output are easy to get rid of.  E.g.
```
/tmp/cirrus-ci-build/lib/iris/tests/unit/experimental/ugrid/cf/test_CFUGridReader.py:60: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
```
/tmp/cirrus-ci-build/lib/iris/tests/unit/experimental/ugrid/cf/test_CFUGridReader.py:59: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. …
```
=> Test deprecation warnings: don't use np.float or np.int

lib/iris/tests/integration/test_regridding.py, lib/iris/tests/test_cdm.py, lib/iris/tests/test_coordsystem.py, lib/iris/tests/test_file_save.py, lib/iris/tests/test_util.py, lib/iris/tests/unit/analysis/scipy_interpolate/test__RegularGridInterpolator.py, lib/iris/tests/unit/cube/test_CubeList.py, lib/iris/tests/unit/fileformats/pp/test_PPField.py
Addressed some warnings in the test output.  Mostly by doing exactly what the deprecation warning messages say.
---
=> Test warnings

benchmarks/benchmarks/trajectory.py, docs/src/whatsnew/latest.rst, docs/src/whatsnew/latest.rst.template, lib/iris/analysis/__init__.py, lib/iris/analysis/trajectory.py, lib/iris/cube.py, lib/iris/tests/results/netcdf/save_load_traj.cml, lib/iris/tests/results/trajectory/constant_latitude.cml, lib/iris/tests/results/trajectory/single_point.cml, lib/iris/tests/results/trajectory/zigzag.cml, lib/iris/tests/unit/analysis/trajectory/test_interpolate.py
Moved call to cube.interpolate out of a loop in iris.analysis.trajectory.interpolate so that rather than instantiating an object every time, that object only gets made once. This leads to a significant speed improvement over the method.
The previous slow speed is noted in issue #1767. I don't think the linked #2168 is affected because that applies to a test that uses nearest neighbour rather than linear interpolation.
- Is there a reason why this wasn't done previously, and therefore shouldn't be done now?
- It seems like it should be possible to use advanced indexing, or some other form of cube manipulation, to make the cube that results from the call to cube.interpolate the right size, but I'm yet to work out how. This would obviate the need for the loop entirely.
- Are there further …
=> Increase speed of iris.analysis.trajectory.interpolate with linear interpolation

docs/iris/src/whatsnew/contributions_2.3.0/bugfix_2018-Dec-07_only_cubes_in_cubelists.txt, docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_CubeList.py
Proposed revival of https://github.com/SciTools/iris/pull/3238
I was re-inspired to do this by a(nother) user issue with confused usage of a CubeList leading to mystifying error messages.
( like `mylist = CubeList([mylist, new_cube])` )
It foundered before because we kept thinking of new possible ways (methods) to add elements.
But I discovered a section in the Python docs, which I think is more complete + definitive
["Lists implement all of the common and mutable sequence operations.  Lists also provide the following additional methods"](https://docs.python.org/3/library/stdtypes.html#list)
So that makes me feel more secure about this now.
~Draft for now to check tests ...~
Ok now for real PR, I think
=> Cubelist contain only cubes -- resurrected

.github/workflows/ci-docs-linkcheck.yml, .github/workflows/ci-docs-tests.yml, .github/workflows/ci-tests.yml, .github/workflows/composite/cartopy-cache/action.yml
This PR makes a minor fix to the `cartopy-cache` composite GHA to ensure that the required `conda` environment is activated.
This is a necessary additional step after moving to a composite action.
---
=> fix composite gha

README.md
This PR removes the retired `cirrus-ci` status badge, and replaces it with the new GHA workflow status badges.
Also see [here](https://github.com/bjlittle/iris/tree/fix-badges#-----).
---
=> add gha workflow badges

docs/src/whatsnew/latest.rst, lib/iris/tests/__init__.py, lib/iris/tests/integration/experimental/test_ugrid_save.py, lib/iris/tests/integration/test_climatology.py, lib/iris/tests/integration/test_netcdf.py, lib/iris/tests/stock/netcdf.py, lib/iris/tests/test_netcdf.py, lib/iris/tests/unit/experimental/ugrid/load/test_load_meshes.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/__init__.py, lib/iris/tests/unit/fileformats/netcdf/test_load_cubes.py
This seemed desirable because I found that certain "assertCDL"s were working fine from the command-line but failing when run in PyCharm.  The problems occurred regardless of whether running via unittest or PyTest.
It was using a really old fallback version of ncdump with slightly different flag behaviour, and output in some cases.
N.B. _no problems ever occurred in CI -- this is purely a developer convenience problem !_
This is because spawned processes don't inherit the path extensions you get from a 'conda activate'.
It quite probably applies to Eclipse too, since that also controls PATH/PYTHONPATH in non-obvious ways.
=> Ensure tests use ncgen/ncdump from the Python env; rationalise uses of ncgen.

lib/iris/fileformats/_nc_load_rules/helpers.py, lib/iris/tests/results/netcdf/netcdf_stereo.cml, lib/iris/tests/results/unit/fileformats/netcdf/Saver/write/stereographic_scale_factor.cdl, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_stereographic_coordinate_system.py, lib/iris/tests/unit/fileformats/netcdf/test_Saver.py
=> Stereographic load with scale factor

lib/iris/analysis/__init__.py, lib/iris/tests/unit/analysis/test_PERCENTILE.py
The `PERCENTILE` fast method will be more versatile if we can choose our interpolation method.
---
=> Allow passing of method keyword to numpy.percentile

.github/workflows/benchmark.yml, .github/workflows/ci-docs-tests.yml, .github/workflows/ci-tests.yml
This PR updates the CI to use the latest version of `iris-test-data` i.e., [v2.12](https://github.com/SciTools/iris-test-data/releases/tag/v2.12).
---
=> bump ci to latest iris-test-data version

docs/src/whatsnew/latest.rst, lib/iris/tests/stock/file_headers/xios_2D_face_half_levels.cdl, lib/iris/tests/stock/file_headers/xios_3D_face_full_levels.cdl, lib/iris/tests/stock/file_headers/xios_3D_face_half_levels.cdl, lib/iris/tests/stock/netcdf.py
Was previously not possible to generate NetCDF-4 files using these headers - got stuck in an infinite loop somewhere.
---
=> Fix stock CDL headers for unlimited time dimension.

lib/iris/tests/graphics/__init__.py, lib/iris/tests/graphics/recreate_imagerepo.py
This PR is a follow-up to PR #4759 (and #4826) with some minor missing review changes.
---
=> post #4759 review actions

.github/workflows/ci-tests.yml, pyproject.toml
This PR lowers the verbosity of `pytest`.
`iris` currently has `>6,000` tests, which makes for a pretty meaty test report (and that's regardless of the amount of warnings spewing to the terminal).
As a developer, I only really care about tests when they fail. When that happens I want to see the detail of the failure quickly so that I can then investigate, diagnose and fix (hopefully).
Personally, I really don't need to see the details of tests that pass, only those that fail, and I think turning down the verbosity really helps (for me, anyways).
For example,
<details>
<summary>Here is a pytest run with 1 failure...</summary>
```shell
........................................................................ [  1%]
........................................................................ [ …
```
=> pytest less verbose

docs/src/developers_guide/testing_tools.rst, docs/src/whatsnew/latest.rst, lib/iris/tests/__init__.py, lib/iris/tests/integration/test_netcdf.py, lib/iris/tests/test_cf.py, lib/iris/tests/test_coordsystem.py, lib/iris/tests/unit/experimental/representation/test_CubeRepresentation.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/__init__.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/test__grid_mappings.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/test__hybrid_formulae.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/test__time_coords.py, lib/iris/tests/unit/fileformats/netcdf/test_Saver.py, lib/iris/tests/unit/fileformats/pp/test_PPField.py, lib/iris/tests/unit/io/test_expand_filespecs.py, lib/iris/tests/unit/test_Future.py
A long time ago Iris implemented some bespoke `assert` methods to help with testing.  For two of these we now have equivalent methods in `unittest`:
* [assertMultiLineEqual](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertMultiLineEqual) (new in python3.1) appears to do the same as our [assertStringEqual](https://github.com/SciTools/iris/blob/a908a27937e4ca8eb810001ebd64f11ff75dce72/lib/iris/tests/__init__.py#L226).
* [assertWarnsRegex](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertWarnsRegex) (new in python3.2) does the same job as our [assertWarnsRegexp](https://github.com/SciTools/iris/blob/a908a27937e4ca8eb810001ebd64f11ff75dce72/lib/iris/tests/__init__.py#L564), except it additionally checks the warning type, which seems like a better …
=> Remove redundant testing assert methods

benchmarks/benchmarks/experimental/ugrid/regions_combine.py, benchmarks/benchmarks/load/ugrid.py, benchmarks/benchmarks/save.py, docs/src/whatsnew/latest.rst, lib/iris/tests/stock/file_headers/xios_2D_face_half_levels.cdl, lib/iris/tests/stock/file_headers/xios_3D_face_full_levels.cdl, lib/iris/tests/stock/file_headers/xios_3D_face_half_levels.cdl, lib/iris/tests/stock/netcdf.py
1. Removed data from CDL headers (introduced in #4827) - served no purpose
2. Used `-k3` for `ncgen` - creates a standard NetCDF-4 file ([documentation](https://linux.die.net/man/1/ncgen))
3. Reduced size of UGRID benchmarks to cope with #4834.
Have made the size consistent across all relevant benchmarks, even those that don't suffer the problem.
---
=> NetCDF Generation Adjustments

setup.cfg
This PR is a follow-up to #4826, where we forgot to remove the `pillow` pin from `setup.cfg`.
---
=> remove pillow pin from setup.cfg

docs/src/developers_guide/github_app.rst
This PR adds a clarification note to the GitHub App docs after renaming the `iris-actions` app to `scitools-ci`, as the app is now also used by `SciTools/cf-units` and is generally applicable throughout the SciTools organisation.
Decided a note was sufficient rather than re-spinning all the png assets.
---
=> update github app docs

setup.cfg
This PR resolves the `setuptools` deprecation warning being issued whenever an `sdist` or `wheel` of `iris` is built:
```
SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
```
See [setuptools v56.0.0 - deprecations](https://setuptools.pypa.io/en/latest/history.html#v56-0-0) for further details.
---
=> avoid setuptools deprecation

docs/src/whatsnew/latest.rst
This PR is a minor update to the `whatsnew` to acknowledge PR reviewers.
---
=> whatsnew update

.readthedocs.yml, docs/src/conf.py
This PR is a follow-up to PR #4841 by fixing the automatic discovery of the `iris` package version on readthedocs (RTD).
Essentially, the root cause of the issue is that when building the documentation on RTD, a **shallow clone** of the repository associated with the GitHub `push` or `pull_request` is performed i.e., RTD performs the following `git` command:
```bash
git clone --no-single-branch --depth 50 https://github.com/SciTools/iris .
```
The resulting shallow clone does not contain the **full** `git` history required by `setuptools-scm` to auto-discover the correct version of `iris`.
This can easily be remedied through RTD build customisation, see [unshallow clone](https://docs.readthedocs.io/en/stable/build-customization.html#unshallow-clone) and more generically [extending the …
=> fix rtd version

docs/src/developers_guide/contributing_running_tests.rst, docs/src/installing.rst
This is the culmination of my cunning plan from #4199!
Removes the instructions for using the deprecated `python setup.py test`, and instead gives instructions for `pytest`.
I have retained the instructions for running a module directly with e.g. `python my/test/file.py`, because I have not found a way to use our extra options (e.g. `-d` for displaying figures) under `pytest`.
Also added a little about the pros and cons of testing in your own `iris-dev` environment vs using `nox`, thanks to @bsherratt's suggestion at https://github.com/SciTools/iris/discussions/4199#discussioncomment-1447095.
See here for how this page renders:
https://www-hc/~hadru/iris-dev/developers_guide/contributing_running_tests.html
--- …
=> Recommend `pytest` in developer guide

docs/src/whatsnew/latest.rst, lib/iris/tests/__init__.py
Unless I'm missing something, `unmasked_data_as_1d_array` does the same as [numpy.ma.compressed](https://numpy.org/doc/stable/reference/generated/numpy.ma.compressed.html?highlight=compressed#numpy.ma.compressed).  So we could just replace it.
Fewer lines :+1: 
---
=> Replace testing helper function

docs/src/whatsnew/latest.rst, lib/iris/analysis/maths.py, lib/iris/tests/test_basic_maths.py, lib/iris/tests/unit/analysis/maths/__init__.py
Edit 20/07/22:
Closes #2987. During the discussion below we also established there are problems for the in-place case when the rhs object is more complex (i.e. masked or lazy) than the lhs cube’s data array.  So the current change also addresses that.
~This relates to #2987 but that issue is now fixed in numpy (see https://github.com/SciTools/iris/pull/3790#issuecomment-1184495096).  During the discussion below we also established there are problems for the in-place case when the rhs object is more complex (i.e. masked or lazy) than the lhs cube’s data array.  So the current change addresses that.  Also adds a test for the #2987 case, marked xfail until numpy 1.24 is released.~
~Although I'm targetting cube arithmetic here, this change will also have some effect on `apply_ufunc` and …
=> Cube arithmetic array type handling

.github/workflows/ci-build.yml, .github/workflows/ci-tests.yml, .github/workflows/ci-wheels.yml, .readthedocs.yml, MANIFEST.in, docs/src/conf.py, docs/src/developers_guide/release.rst, docs/src/whatsnew/latest.rst, noxfile.py, setup.cfg
This PR automates the task of building and publishing the `sdist` and `wheel` artifacts for `iris` to PyPI using a GHA.
On every PR the `sdist` and `wheel` will be built, but **only** published to Test PyPI for the `main` branch.
Only when **tagging** a release will the `sdist` and `wheel` be automatically built and published to PyPI. 
This capability simplifies the release process, and also gives us routine confidence that we're not publishing a broken release.
TODO:
- See [Including files in source distributions with MANIFEST.in](https://packaging.python.org/en/latest/guides/using-manifest-in/)
- See `setuptools` [Data Files Support](https://setuptools.pypa.io/en/latest/userguide/datafiles.html)
- See `setuptools` [Package Discovery and Namespace …
=> automate sdist and wheel build and publish

docs/src/whatsnew/latest.rst
Closes #4845 (read that for details).
---
=> Warn users of increased `recombine_submeshes` memory demand.

docs/src/conf.py, docs/src/developers_guide/contributing_documentation_full.rst, requirements/ci/py310.yml, requirements/ci/py38.yml, requirements/ci/py39.yml, setup.cfg
This PR resolves the issue of the documentation failing to build on RTD.
This is related to the recent release of `sphinx-gallery` 0.11.0.
Also see:
- https://github.com/sphinx-gallery/sphinx-gallery/pull/890
- https://github.com/matplotlib/matplotlib/pull/23514
Thanks @rcomer :+1: 
TODO:
---
=> Sphinx reset modules

lib/iris/analysis/__init__.py
I previously tried to make this docstring numpydoc compliant as part of #4791.  It didn't quite work, as I missed the `Parameters` heading.  This PR fixes that.
Before:
After:
---
=> Fix PERCENTILE docstring

lib/iris/__init__.py
Ever since we committed #4841, as developers we require the [setuptools-scm](https://github.com/pypa/setuptools_scm) generated `iris._version` file to be available to garner the `iris.__version__`.
If this file is **not** available, then the following traceback will be encountered by the developer whenever `import iris` is performed:
```bash
ModuleNotFoundError: No module named 'iris._version'
```
Thanks to our adoption of a [PEP-0518](https://peps.python.org/pep-0518/) build backend, as a developer you do **not** require to have the `setuptools-scm` package installed within your development environment to use `iris` (only do that if you care about getting the correct version). However, to generate the `iris._version` file without explicitly installing `setuptools-scm`, from the root …
=> set default 'unknown' version

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/tests/integration/merge/test_merge.py, lib/iris/tests/unit/coords/test_Cell.py
This PR reverts the fix targeting the change in behaviour of `Cell.__hash__` when dealing with NaNs due to the performance regression that it introduces.
This fix is only applicable to a change in behaviour for `py310`.
See:
- #4840 
- #4852
Reference:
- https://bugs.python.org/issue43475
- https://github.com/numpy/numpy/issues/18833
- https://github.com/numpy/numpy/pull/18908
- https://github.com/numpy/numpy/issues/21210
Closes #4843
---
=> Revert Cell.__hash__ fix

docs/src/whatsnew/latest.rst
Includes the pin to `sphinx-gallery` into the whatsnew.
=> Update whatsnew to include pins

lib/iris/util.py
I noticed a tiny problem with the recently-merged extension to new-axis, in that it is using a mutable default argument.
As it is, the routine never modifies the argument, and in fact always replaces it [here](https://github.com/SciTools/iris/blob/505dca8ca5d7fbe5b45d2e24180280cd62ebfab8/lib/iris/util.py#L1180-L1182).
But I think it's accepted that this is not good practice generally.
---
=> Avoid using mutable default.

docs/src/whatsnew/latest.rst
=> Fix some @trexfeathers What's New entries

docs/src/whatsnew/latest.rst, lib/iris/analysis/__init__.py, lib/iris/tests/unit/analysis/test_SUM.py, requirements/ci/py310.yml, requirements/ci/py38.yml, requirements/ci/py39.yml, setup.cfg
We have a few aggregators that are implemented purely in dask, and the "real" version works by converting the numpy array to a dask array, passing it through the dask functions, and then realising the data.  This appears to have been done at #3168 in response to a review request to reduce code repetition.  However, it is slow compared to just working directly with numpy.  Consider the following:
```python
import timeit
import iris.analysis
def get_array():
return np.random.random(10000).reshape(100, 100)
def over_half(a):
return a > 0.5
setup = """
import iris
from __main__ import get_array, over_half
arr = get_array()
"""
print("COUNT", timeit.timeit(
'iris.analysis.COUNT.aggregate(arr, 1, function=over_half)',
setup=setup, number=500))
print("PROPORTION", …
```
=> SUM, COUNT, PROPORTION: don't use dask on numpy arrays

docs/src/whatsnew/latest.rst, lib/iris/tests/__init__.py
Closes #4891.
I have tested locally with my `iris-dev` environment, and I do not see any errors or failures without this `setUpClass`.
---
=> Remove `setUpClass` from Iris tests.

.readthedocs.yml, docs/src/_templates/custom_sidebar_logo_version.html, docs/src/conf.py, docs/src/whatsnew/3.3.rst, pyproject.toml
* Uses the correct `version_scheme` setting for our release branch strategy.
* Properly copes with the conflict between `setuptools_scm` and Read the Docs.
* Changes the RTD version badge to better reflect all fixed-version builds.
[Here's a rendered example for the fictitious `5.6.9` version](https://trexfeathers-iris.readthedocs.io/en/5.6.9/)
Here are the five badges I'm proposing:
- ![latest development version](https://img.shields.io/badge/⚠️_version_('latest')-5.6.10dev49-gold?style=flat) - whenever RTD labels a build as `latest`.
- ![stable version](https://img.shields.io/badge/✨️_version_('stable')-5.6.9-green?style=flat) - whenever RTD labels a build as `stable`.
- ![archived version (not 'stable' or 'latest')](https://img.shields.io/badge/🔒_version_(archived)-5.6.8-red?style=?styl …
=> Better handle `setuptools_scm` versioning

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/tests/unit/coords/test_Coord.py, lib/iris/tests/unit/cube/test_Cube.py
This pull request allows collapsing coordinates with number of bounds different from 0 or 2 (e.g., mesh dimensions). For this, it first checks if `self.is_contiguous()` (that is just used to issue a warning during the collapsing of coordinates) raises an error before actually calling it. If it raises an error, issue a different warning and remove the bounds before continuing.
Closes #4672.
---
=> Allowed collapsing coordinates with `nbounds != (0, 2)`

.github/workflows/ci-tests.yml, docs/gallery_code/general/plot_zonal_means.py, docs/src/common_links.inc, docs/src/whatsnew/latest.rst, lib/iris/tests/results/imagerepo.json
Created a zonal mean example for iris docs gallery. Continues #4871, closes #4897.
=> Added zonal mean gallery example, continued from @TTV-Intrepid

docs/src/whatsnew/latest.rst, setup.py
This PR performs some minor internal hygiene to purge support for the now deprecated pattern of invoking the `iris` tests with `python setup.py test`.
As a reference, see this `pytest` "[Do not run via setuptools](https://docs.pytest.org/en/latest/explanation/goodpractices.html#do-not-run-via-setuptools)" recommended Good Integration Practices.
Thankfully, there doesn't seem to be any references to this deprecated practice within our documentation, so there's no connective tissue to purge there :+1: 
---
=> Remove deprecated 'python setup.py test' support

setup.py
This PR performs yet more `setup.py` hygiene by removing the `copy_copyright` function, which copies the `COPYING` and `COPYING.LESSER` license files down into the `iris` package source root when building the `iris` distribution.
IMHO this is unnecessary, and I don't know of any other open source packages that do this.
The license files are already packaged in our PyPI `sdist` and binary `wheels` metadata, and also as part of our conda-forge `iris` conda package tarball, as per all other open source packages which follow recommended package distribution good practice.
Additionally bundling the license files within the `iris` package root source seems unnecessary.
Reference: This change was introduced in #2891 (with no explanation/reason) and first became part of `iris` 2.0.0. To be fair, …
=> purge unnecessary setup.py copy_copyright function

setup.py
This PR adds the `editable_mode` attribute (defaulting to `True`) to the [setuptools.command.develop.develop](https://github.com/pypa/setuptools/blob/main/setuptools/command/develop.py#L14) command subclass and custom `setup.BaseCommand` command class.
Closes #4951
---
=> fix setup.py std_names building

.github/ISSUE_TEMPLATE/config.yml, setup.cfg
Part of #3860 
This is required to retire the google groups. Instead of raising questions about how to use iris on the [scitools-iris google group](https://groups.google.com/g/scitools-iris), we will instead point people at the Q&A discussions.
I did a search through the repo and couldn't find any other mention of google groups, other than the mention that it is a legacy support forum
I have also had to update the author name to the newly created scitools.pub@gmail.com
---
=> Add new Q+A issue, update author email

.github/workflows/ci-wheels.yml, .github/workflows/refresh-lockfiles.yml, tools/update_lockfiles.py
Closes #4958.
Not ideal, considering the difficulty in replicating this locally for those that can't edit their `base` environment. But hopefully the Mamba solver will be made available to vanilla Conda installs within the next year.
---
=> Use Mamba for refreshing lock-files

docs/src/developers_guide/release.rst
Adresses #4961. Adjusts the release guide to better reflect the actual process followed.
---
=> Update release guide

docs/src/whatsnew/3.3.rst, docs/src/whatsnew/latest.rst.template, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py, lib/iris/tests/unit/cube/test_CubeList.py
To address #4973 
**NOTE:** aiming this at a bugfix release, so it is derived from, and targetting '3.3.x' branch.
**TODO**:
- ( create appropriate new whatsnew/latest.rst, on v3.3.x aiming  for 3.3.1 )
=> Reinstate CubeList._repr_html_()

.github/workflows/ci-tests.yml, docs/src/whatsnew/3.3.rst, lib/iris/cube.py, lib/iris/fileformats/name_loaders.py, lib/iris/tests/results/imagerepo.json, lib/iris/tests/results/name/NAMEII_field__no_time_averaging.cml, lib/iris/tests/results/name/NAMEII_field__no_time_averaging_0.cml, lib/iris/tests/test_name.py, lib/iris/tests/unit/cube/test_Cube.py
Addresses #3288 
~Draft pending :~ 
- ~[x] tests for enhanced API~
- ~[x] whatsnew~
=> Fix name loader problem

benchmarks/benchmarks/import_iris.py, docs/src/whatsnew/latest.rst, lib/iris/palette.py, requirements/ci/py310.yml, requirements/ci/py38.yml, requirements/ci/py39.yml, setup.cfg
These changes address a Matplotlib deprecation warning, and should get the overnight benchmarks working again.
---
=> Adaptions for Matplotlib 3.6

.github/workflows/benchmark.yml, benchmarks/benchmarks/generate_data/__init__.py
* Fixes a 'missed spot' from #4803
* [Hopefully] enables manual running of the overnight benchmark GHA, starting from a custom commit.
---
=> Fix benchmarks `netcdf` import

docs/src/whatsnew/latest.rst, lib/iris/coords.py
This speeds up functions that make use of the `Coord.cells` method to generate many cells describing a time coordinate. This affects for example `Cube.extract`, `Cube.subset`, and `Coord.intersection`.
Here is a script that demonstrates this:
```python
import cf_units
import iris.cube
import iris.coords
import iris.time
time_units = cf_units.Unit('days since 1850-01-01', calendar='standard')
time = iris.coords.DimCoord(np.arange(10000, dtype=np.float64), standard_name='time', units=time_units)
cube = iris.cube.Cube(np.arange(10000, dtype=np.float32))
cube.add_dim_coord(time, 0)
pdt1 = iris.time.PartialDateTime(year=1852)
pdt2 = iris.time.PartialDateTime(year=1854)
constraint = iris.Constraint(time=lambda cell: pdt1 <= cell.point < pdt2)
%timeit cube.extract(constraint) …
```
=> Speed up operations that use the `Coord.cells` method for time coordinates

.github/workflows/benchmark.yml
In #5001 I intended to generate `first_commit` ONLY IF it was not already provided by the `workflow_dispatch`, but I got my equality the wrong way round.
=> Correct wrong type of equality check in benchmark GHA.

docs/src/whatsnew/latest.rst, lib/iris/plot.py, lib/iris/tests/test_mapping.py
`iplt.outline` contains an ancient workaround for a Matplotlib bug raised at https://github.com/matplotlib/matplotlib/issues/1302 and fixed by https://github.com/matplotlib/matplotlib/pull/18480, which was included in Matplotlib v3.4.  Since Matplotlib is now pinned to >=3.5 (#4998), we can safely remove the workaround.  I also here remove a test which expected the old behaviour, and failed when we tested against mpl v3.4.1 (#4090).
Closes #4090.
---
=> Remove `iris.plot.outline` workaround

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/tests/unit/coords/test_Cell.py
Closes #4697.  The example given there now produces
```
[Cell(point=cftime.datetime(2022, 3, 8, 12, 0, 0, 0, calendar='standard', has_year_zero=False), bound=None), Cell(point=cftime.datetime(2022, 3, 9, 12, 0, 0, 0, calendar='standard', has_year_zero=False), bound=None)]
```
The first workaround was added at #1016.  From the comments on the tests I removed, the comparisons were then falling back to comparing object ids, so presumably rich comparison was not implemented in that version of netcdftime _at all_.  It is implemented now:
https://github.com/Unidata/cftime/blob/dc75368cd02bbcd1352dbecfef10404a58683f94/src/cftime/_cftime.pyx#L1314
The second workaround was added at #2440.  The comment there says that `NotImplemented` was not always being returned by the comparison method.  If …
=> Cell comparison: remove ancient netcdftime/cftime workarounds

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/tests/test_cell.py
This speeds up `Cube.subset` / `Coord.intersect` by using a `dict` lookup instead of `list.index` to find the indices of the coordinate that should be used for subsetting the cube.
Here is some benchmark code:
```python
import iris.cube
import iris.coords
lon = iris.coords.DimCoord(np.arange(0, 360, 0.5, dtype=np.float64), standard_name='longitude')
cube = iris.cube.Cube(np.arange(720, dtype=np.float32))
cube.add_dim_coord(lon, 0)
sublon = lon[(lon.points > 60) & (lon.points < 300)]
%timeit cube.subset(sublon)
```
The current `main` branch result is:
```
93.9 ms ± 4.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
and the result of running that code with this branch is:
```
13.5 ms ± 1.54 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
--- …
=> Speed up Cube.subset/Coord.intersect

lib/iris/__init__.py
In preparation for breaking changes to be made to `iris.pandas.as_dataframe()` and `iris.pandas.as_series()` - #4669.
**QUESTION:** how should future flags be documented? The existing `datum_support` flag is not documented but that might just be an oversight?
---
=> Added pandas_ndim FUTURE flag

docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py
A simple change to error messages to address #4898.
=> Improve error messages when comparing against objects vs strings

.github/workflows/refresh-lockfiles.yml
As there is some duplication in the use of workflows across our repos, and this is likely to increase, I have been looking at implementing [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows).  
I propose we have a central repo that will contain the workflows that we can reuse across iris, iris-grib, cf-units, and more if need be.
As a first step, I have chosen to look at the simplest workflow which is the one we use to refresh lockfiles. 
This PR modifies the workflow so it instead calls a reusable workflow which is stored in a `scitools/reusable_workflows` repo which I will create soon!
=> Use reusable workflow for refresh lockfile workflow

docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube__aggregated_by.py
Addresses the remaining comments for #3637.
Does this by having all derived coordinates now derive from their equivalent coordinates in the aggregated cube.
---
=> fix aggregated_by for derived coords

docs/src/_templates/layout.html, docs/src/whatsnew/latest.rst
Ref: #5045 and https://github.com/SciTools/iris/issues/4396#issuecomment-1273592280
---
=> Reference the RTD version switcher in the docs latest warning

docs/src/whatsnew/latest.rst, lib/iris/fileformats/um_cf_map.py
STASH diagnostic 30311 is listed in the [UM STASHmaster metadata file](https://code.metoffice.gov.uk/trac/um/browser/main/trunk/rose-meta/um-atmos/HEAD/etc/stash/STASHmaster/STASHmaster-meta.conf?order=name) as "RESIDUAL MN MERID. CIRC. WSTARBAR".  I have checked with Steve Hardiman (who originally implemented these diagnostics in the UM) and Martin Andrews (who has used these diagnostics a lot more than I have) and they agree that this should map to "upward" rather than "northward" in Iris.
---
=> WSTARBAR is upward velocity

docs/src/common_links.inc, docs/src/index.rst, docs/src/whatsnew/latest.rst, docs/src/why_iris.rst, lib/iris/__init__.py, lib/iris/pandas.py, lib/iris/tests/test_pandas.py
I think the diff might render unhelpfully. Here's a summary of what I have done:
- Restored `iris.pandas.as_data_frame()`'s default behaviour from Iris `main`
- Contained the new improved behaviour within a check for `iris.FUTURE.pandas_ndim`
- Restored the testing for `iris.pandas.as_series()` from Iris `main`
- Restored the testing for `iris.pandas.as_data_frame()`'s default behaviour from Iris `main`
- Moved the tests for the new improved behaviour into their own class (`TestAsDataFrameNDim`)
- Added various warnings about the `FUTURE` switch into the code and the docstring
- Added tests for the `FUTURE` warning, and some more for deprecation warnings that I felt were missing
Currently `iris.FUTURE.pandas_ndim` only controls the behaviour of `iris.pandas.as_data_frame()` - this is the …
=> Make `iris.pandas.as_data_frame()` n-dimensional behaviour opt-in

lib/iris/tests/unit/pandas/__init__.py, lib/iris/tests/unit/pandas/test_pandas.py
=> Move `test_pandas.py` into unit tests.

docs/src/whatsnew/latest.rst, lib/iris/_constraints.py, lib/iris/tests/unit/constraints/test_Constraint_equality.py
=> Implemented constraint equality.

docs/src/whatsnew/latest.rst, requirements/ci/py310.yml, requirements/ci/py38.yml, requirements/ci/py39.yml, setup.cfg
See #5016. We're on the way to a proper fix in #5061 but in the meantime we need a netcdf4 pin that can account for future releases of the package, rather than being specific to avoiding one specific release.
---
=> More accurate netcdf4 pin `<1.6.1`.

docs/src/conf.py, docs/src/whatsnew/3.4.rst
=> Update What's New for 3.4 release.

docs/src/developers_guide/contributing_documentation_full.rst, docs/src/whatsnew/latest.rst
Since #4792, it is no longer necessary to add a test file with each new gallery entry, because we generate them using `glob`:
https://github.com/SciTools/iris/blob/dfbc5c2aef0c64918061a4e312f66d94b0beb525/docs/gallery_tests/test_gallery_examples.py#L18-L22
I also added some links from the gallery testing instructions to the image testing instructions, as I was struggling to find my way around when recently wanting to update a gallery test image file.
---
=> DOC: improve gallery test instructions

docs/src/whatsnew/latest.rst, lib/iris/tests/stock/netcdf.py
Switch order of options and parameter in the call to `ncgen` (current order leads to error on OS X). Closes #5097.
=> Switch order of options and parameter in `ncgen` command

docs/src/whatsnew/latest.rst, lib/iris/tests/__init__.py, lib/iris/tests/graphics/README.md, lib/iris/tests/test_plot.py, lib/iris/tests/unit/analysis/maths/test__arith__derived_coords.py, lib/iris/tests/unit/analysis/maths/test__arith__meshcoords.py, lib/iris/tests/unit/analysis/maths/test_add.py, lib/iris/tests/unit/analysis/maths/test_divide.py, lib/iris/tests/unit/analysis/maths/test_multiply.py, lib/iris/tests/unit/analysis/maths/test_subtract.py, lib/iris/tests/unit/merge/test_ProtoCube.py, lib/iris/tests/unit/tests/test_IrisTest.py
Here is some more Iris functionality that I did not know existed, until @pp-mo mentioned it the other day.  Described by the removed comment
https://github.com/SciTools/iris/blob/6eb0401011a8edce51a942a176e2feb06f4b3f09/lib/iris/tests/__init__.py#L940-L946
I tried to run this with `unittest discover` as the comment recommends, but got errors, particularly from [test_pandas.py](https://github.com/SciTools/iris/blob/main/lib/iris/tests/unit/pandas/test_pandas.py).  I found that this functionality can be used with `pytest -s -v`, so if we do want to keep the functionality we should probably document that.  I'm unsure if it can be made to work with `pytest-xdist`.
In any case, pytest provides its own functionality to tell you the timings of the slowest running tests via the `--durations` …
=> Remove test timings

setup.cfg
This PR temporarily resolves the existing documentation build failure on RTD i.e., see [here](https://readthedocs.org/api/v2/build/19061195.txt)
There are a couple of factors in play here:
1. The `sphinx-panels` package is no longer maintained (#5121) and is pinning back the `sphinx` package from >=v6.0.0 to v4.5.0 on `conda-forge`
2. The `pydata-sphinx-theme` is pinned to v0.8.1 (latest version available is >=v0.12.0), and this is causing the additional `pip install` step on RTD to pull the `sphinx` package **way down** to v3.5.3 which is incompatible and, I suspect, causing the following traceback:
```shell
File "/home/docs/checkouts/readthedocs.org/user_builds/scitools-iris/conda/latest/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return …
```
=> pip pin for sphinx<5

docs/src/whatsnew/latest.rst, lib/iris/analysis/__init__.py
... since PERCENTILE has lazy aggregation.
Closes #4039.  Specifically https://github.com/SciTools/iris/issues/4039#issuecomment-1324871960
> let's wait till 2023-01 if anyone really wants MEDIAN to be lazy.
IF not, add a doc note to say "it's not lazy, but percentile is"
---
=> Link PERCENTILE from MEDIAN docstring

docs/src/_templates/layout.html, docs/src/conf.py, docs/src/whatsnew/latest.rst, requirements/ci/py310.yml, requirements/ci/py38.yml, requirements/ci/py39.yml
Unpinned `pydata-sphinx-theme` and set the default to use the `light` version (not dark).
We can enable the dark mode (and the switcher) once our docs are dark mode friendly.
See https://github.com/SciTools/iris/issues/4795
---
=> Unpin theme

README.md, docs/src/whatsnew/latest.rst
At the very least, I think we should do our (minimal) bit to spread the good word for [#ShowYourStripes](https://showyourstripes.info/s/globe/)...
This is the suggested [README.md](https://github.com/bjlittle/iris/tree/readme-showyourstripes#-----) change.
Thanks @ed-hawkins et al :100: :rocket: :star_struck: 
---
=> add readme #showyourstripes

docs/src/common_links.inc, docs/src/developers_guide/gitwash/forking.rst, docs/src/developers_guide/gitwash/set_up_fork.rst, docs/src/whatsnew/latest.rst
=> Fixing typo's in Gitwash.

docs/src/common_links.inc, docs/src/community/index.rst, docs/src/community/plugins.rst, docs/src/whatsnew/latest.rst, lib/iris/__init__.py, lib/iris/io/format_picker.py, lib/iris/plugins/README.md
Plugins! cf #4798 and the older proof of concept #3657.
It uses the same approach of namespace packages, but as `iris.plugins` instead of limiting ourselves to `iris.io.plugins`, and does not try to discover which plugins are available (should it..?)
This has been successfully used to separate out the NAME loader, although that will be a separate PR once we're happy with the approach to plugins.
---
=> Plugin support

docs/src/whatsnew/3.4.rst
The only _material_ difference between `v3.4.x` and `main` is the `v3.4.1` patch section on the What's New. Everything else is just what it took to port #5095 across, get the CI passing, and resolve conflicts, so I haven't included any of that complication here.
=> `v3.4.1` 'merge-back' - What's New changes only

docs/src/whatsnew/latest.rst, lib/iris/analysis/__init__.py, lib/iris/tests/unit/analysis/test_RMS.py
Lazy aggregation with weights was not previously implemented for the RMS aggregator because of a bug in the weighted masked case reported at https://github.com/dask/dask/issues/3846 (see removed code comments).  This bug was fixed at https://github.com/dask/dask/pull/4236, and the fix included in [version 1.1.0](https://docs.dask.org/en/stable/changelog.html#v1-1-0-2019-01-18).  Iris's minimum supported version of Dask is now [2.26](https://github.com/SciTools/iris/blob/d1f3e4564e09de1e269872f5d14d4d3bf3ce5489/setup.cfg#L53).
---
=> Lazy weighted RMS calculation

.github/workflows/ci-wheels.yml, docs/src/whatsnew/latest.rst
Checks for 'SciTools' as the repository owner such that `ci_wheels.yml` does not run the `"publish to test.pypi"` step in forks, fixes #5180 
---
=> #5180 do not run publish-to-test-pypi on forks

.github/workflows/refresh-lockfiles.yml
Now that the [SciTools/workflows](https://github.com/SciTools/workflows/releases) is auto-released on PR merge, this PR uses an explicit version for the `refresh-lockfiles` GHA.
This should make it easy to pin the workflow to a last known working version in the event of a breaking release. Also, we should receive auto-updates from `dependabot` when new versions of our reusable GHAs are available.
Also see:
- https://github.com/SciTools/iris-grib/pull/331
- https://github.com/SciTools/python-stratify/pull/69
---
=> use explicit version for ci refresh-lockfiles gha

requirements/locks/README.md
This PR adds a `README.md` to the `requirements/locks` directory to highlight that the contents of this directory is auto-generated and manual changes will be overwritten.
---
=> add locks readme

docs/src/whatsnew/latest.rst, lib/iris/analysis/cartography.py, requirements/py310.yml, requirements/py38.yml, requirements/py39.yml, setup.cfg
This PR is a follow-up to #4972, which introduces the use of `dask.array.ma.empty_like` to `iris`.
This feature was available from `dask` 2022.8.1. 
I've set the min pin to be `2022.9.0`, rather than the month point release.
Kudos to @rcomer who landed https://github.com/dask/dask/pull/9378 :love_you_gesture: 
---
=> raise dask min pin

docs/src/whatsnew/latest.rst, lib/iris/_concatenate.py, lib/iris/cube.py, lib/iris/tests/integration/concatenate/test_concatenate.py, lib/iris/tests/test_concatenate.py, lib/iris/tests/unit/concatenate/test_concatenate.py
This fixes the issue that the result of `iris.cube.CubeList.concatenate` loses any derived coordinate present in the input cubes. Here, this is fixed for all derived coordinates (for those that span the concatenated dimensions and for those that don't).
Closes #2478 
---
=> Handle derived coordinates correctly in `concatenate`

docs/src/developers_guide/contributing_pull_request_checklist.rst, docs/src/developers_guide/documenting/whats_new_contributions.rst
This PR is the actionable outcome of the #5223 GHD poll.
---
=> clarity on whatsnew entry contributors

.github/workflows/ci-wheels.yml, docs/src/whatsnew/3.5.rst
=> SciTools/iris#5220 typo github.repository_owner.

benchmarks/bm_runner.py
Something I missed when creating the benchmark runner. Because of this, the overnight benchmarks have been exiting silently since last week!
---
=> Make bm_runner location agnostic and include debugging.

docs/src/developers_guide/release.rst
This PR refreshes the instructions to manually build and publish the `scitools-iris` sdist and binary wheels to PyPI.
---
=> refresh manual pypi publish instructions

.gitignore, lib/iris/tests/results/PP/extra_char_data.w_data_loaded.pp.txt
=> add missing test result data

.github/workflows/ci-manifest.yml, MANIFEST.in, pyproject.toml
This PR ensures that the assets packaged for the PyPI sdist and wheel are as expected by performing an automated GHA check of the payload manifest.
Adopts the reusable `SciTools` GHA workflow, which will be automagically updated thanks to the already configured `dependabot`.
Note that, this PR fixes several discrepancies.
---
=> automate pypi manifest checking

docs/src/whatsnew/latest.rst
This PR adds the missing `whatsnew` entry for the merged PR #5259.
---
=> add missing whatsnew entry

docs/src/whatsnew/latest.rst, lib/iris/tests/unit/common/resolve/test_Resolve.py
We dropped support for python 3.6, so this workaround is no longer needed.
---
=> Remove Resolve test workaround

.github/workflows/ci-wheels.yml, docs/src/whatsnew/latest.rst
This PR adopts the [pypa/build](https://pypa-build.readthedocs.io/en/stable/) recommended best practice to build the binary `wheel` from the `sdist`, as opposed to from the `src`.
---
=> build wheel from sdist, not src

docs/src/installing.rst, docs/src/whatsnew/latest.rst
Updated the installing instructions to use:
`pip install --no-deps --editable .`
instead of:
`python setup.py develop`
Using pip is considered better practice, also the old way shows a couple of strong warnings:
```
/home/theuser/projects/iris
$ python setup.py develop
/home/theuser/.conda/envs/iris-dev/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for [tool.setuptools] in pyproject.toml is still *beta*.
config = read_configuration(filepath, True, ignore_option_errors, dist)
running develop
/home/theuser/.conda/envs/iris-dev/lib/python3.11/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!
******************************************************************************** …
```
=> updated installing instructions to use pip

.github/workflows/benchmark.yml, benchmarks/README.md, benchmarks/asv.conf.json, benchmarks/bm_runner.py, docs/src/developers_guide/contributing_benchmarks.rst, docs/src/whatsnew/latest.rst
Enhances the `benchmark-check` GHA workflow to allow developers to request that their pull request be benchmarked for performance shifts. This is achieved by adding the https://github.com/SciTools/iris/labels/benchmark_this label.
- trexfeathers/iris#48
- trexfeathers/iris#49
- trexfeathers/iris#50
---
=> On demand pull request benchmark

docs/src/whatsnew/latest.rst, lib/iris/plot.py, lib/iris/tests/unit/plot/test__replace_axes_with_cartopy_axes.py
Closes #5282
We just needed to get hold of the SubFigure rather than the parent Figure.
---
=> Fix axes replacement on subfigures

docs/src/conf.py, docs/src/whatsnew/latest.rst, lib/iris/analysis/maths.py, lib/iris/tests/unit/analysis/maths/test__arith__dask_array.py, lib/iris/util.py
Currently, the various arithmetic functions state that their second operand may be a cube, a coordinate, a numpy array or a number.  There is nothing to stop you passing a dask array as the second operand, but it will be silently realised by the `numpy.asanyarray` call, which seems unhelpful to me.  I think it would be good to explicitly support passing a dask array, though there may be a better way to do it than my current change.
~In draft for now because a bunch of docstrings would need modifying and some tests adding, but I wanted to see if there is agreement in principle first.~
---
=> Support dask arrays in binary operations

docs/src/sphinxext/api_rst_formatting.py
Minor improvement to ensure only ``.rst`` files are processed.  Non ``.rst`` files may be present especially when performing some manual testing or some temp files are left over.
---
=> ensure only .rst files are processed

.readthedocs.yml
This PR mops up after #5262, and removes the now defunct PyPI `docs` optional dependencies reference within the `.readthedocs.yml`. 
---
=> remove extra-requirements from rtd config

lib/iris/tests/test_coding_standards.py, tools/release_do_nothing.py
This PR makes some additive tweaks to the `tools/release_do_nothing.py` script, including making it directly executable from the CLI i.e., `> ./release_do_nothing.py`.
These suggested changes are within the context of performing an initial minor release candidate e.g., `v3.6.0rc0`.
---
=> release_do_nothing script updates from v3.6.0rc0

docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube__aggregated_by.py
The code currently used for the lazy case in `aggregated_by` just needs a few tweaks to also use it for the real case.  So we can have fewer lines, and the McCabe complexity of the method is reduced from 27 to 20.
Edit: it turns out this also makes it faster (https://github.com/SciTools/iris/pull/4970#issuecomment-1263663273).
---
=> Simpler/faster data aggregation code in `aggregated_by`

docs/src/whatsnew/3.6.rst
Here's my suggestion explaining the benefits of delayed saves, and Distributed.
We _could_ consider a new UserGuide section for this, but I think we can still argue that this is a special usage + doesn't belong there.
=> Added whatsnew notes on netcdf delayed saving and Distributed support.

docs/src/whatsnew/3.6.rst
This PR includes the final updates to the `whatsnew` prior to the `iris` v3.6.0 release.
---
=> Whats new updates for v3.6.0

tools/release_do_nothing.py
This PR introduces a minor improvement to the `release_do_nothing.py` script post v3.6.0 release.
We recently enabled automatic deletion of pull request head branches i.e.,
This automation is general useful for repo branch hygiene, but will result in the release branch being purged, which isn't necessarily what we want.
The `release_do_nothing.py` script now includes an additional step to ensure the release branch is **restored** from the GH GUI with a simple one button click.
As discussed with v3.6.0 release buddy @ESadek-MO off-line 👍 
---
=> minor refinement to release-do-nothing script

lib/iris/fileformats/netcdf/loader.py, lib/iris/fileformats/netcdf/saver.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_ancil_var.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_auxiliary_coordinate.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_cell_measure.py, lib/iris/tests/unit/fileformats/netcdf/loader/test__get_cf_var_data.py, lib/iris/tests/unit/fileformats/netcdf/saver/test_Saver__lazy_stream_data.py
The basic idea : when loading from / saving to a dataset-like object (as provided by #5214), Iris can spot objects which "emulate" a netCDF4.Variable and provide direct access to a content array (i.e. not via file access).  
This allows us to directly transfer array data (real or lazy) without copying.
**TODO**: in retrospect, `_in_memory_array` is really _not_ a good choice, as it seems to imply numpy data, whereas crucially it will often be dask.  We should change the name to something better.
Maybe "_data_array".
This, along with #5214 (formerly #5024), should provide all we need to support the intended "Xarray bridge" - see #4994 .
Scheduled for  Iris 3.6
Currently ***draft/WIP***, because this will need adjustment after #5191, and it's far easier to resolve if that goes in first ! …
=> Support netcdf variable emulation

docs/src/whatsnew/latest.rst, lib/iris/_lazy_data.py, lib/iris/tests/unit/lazy_data/test_is_lazy_masked_data.py, lib/iris/tests/unit/util/test_broadcast_to_shape.py, lib/iris/util.py
Attempt to resolve #5295, following my own suggestion at https://github.com/SciTools/iris/issues/5295#issuecomment-1532791248.  It turned out I didn't need to use `da.broadcast_to` directly - this is automatic due to dask's support for NEP13/18.  We *do* still need to handle masked arrays separately because they don't (yet) support NEP13/18.
This is still not working for the case where the array is both lazy and masked (see failing new test) because the mask gets ignored by `da.broadcast_to`.  We could apply a similar approach to that for the numpy masked arrays, but you can't tell whether a dask array is masked until you realise it.  This seems like it must be a common problem.  Anyone know a solution before I attempt to re-invent the wheel?
For a simple array I found this new …
=> Simplify and lazify broadcast_to_shape

docs/src/conf.py
This PR adds a docs linkcheck ignore for `biggus` on RTD, which appears to be down or deleted.
See https://biggus.readthedocs.io/ :skull_and_crossbones: 
---
=> docs linkcheck ignore biggus rtd url

docs/src/whatsnew/3.6.rst, lib/iris/_concatenate.py, lib/iris/tests/integration/concatenate/test_concatenate.py
This PR makes sure to properly update all aux factory dependencies when concatenating cubes.
Closes https://github.com/SciTools/iris/issues/5339
---
=> Fix concatenation of cubes with aux factories

docs/src/whatsnew/3.6.rst
This PR is a follow-on to #5142.
It adds an associated `whatsnew` entry for the forthcoming v3.6.1 patch release on the `v3.6.x` feature release branch.
Ping @sloosvel - you okay with this `whatsnew` entry? :smile: 
---
=> add whatsnew for #5142

lib/iris/_concatenate.py, lib/iris/tests/unit/concatenate/__init__.py, lib/iris/tests/unit/concatenate/test__CoordMetaData.py, lib/iris/tests/unit/concatenate/test__CoordSignature.py
This PR is a follow-on to #5142.
Lazy comparison will always yield a truthy value, therefore we require to realize the comparison. In this case, we're performing either lazy indexing for a single value or comparing lazy single values. Realizing the result won't undo the intent of #5142.
Great spot @trexfeathers :eyes: 
To do:
---
=> address concatenate lazy comparison truthiness

docs/src/whatsnew/3.6.rst, lib/iris/_lazy_data.py, lib/iris/tests/unit/lazy_data/test_is_lazy_masked_data.py, lib/iris/tests/unit/util/test_broadcast_to_shape.py, lib/iris/util.py
This pull-request `cherry-pick`s the merge commit (48e3a86) of #5307 from `main` to the `v3.6.x` release feature branch.
This is required to support #5341 in the v3.6.1 patch release.
---
=> Simplify and lazify broadcast_to_shape (#5307)

docs/src/conf.py
Linkcheck is now broken because https://stickler-ci.com/ is down.
It looks like that website has now been shutdown:
=> Ignore sticklerci

docs/src/further_topics/metadata.rst, lib/iris/fileformats/_nc_load_rules/helpers.py, lib/iris/fileformats/netcdf/loader.py, lib/iris/tests/integration/test_netcdf__loadsaveattrs.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_cube_metadata.py
Changes netcdf loading code to specifically load into `cube.attributes.globals` and `cube.attributes.locals`
Since the same attributes are then appearing in 'cube.attributes', this in itself (i.e. without changes to saving) should have no effect.
-- **_Except_** in some minor corner cases, where an attribute is present as _both_ a local (variable-attribute)) + global (file-attribute).
So, I think that this is (almost) fully backwards-compatible, and **_does not require a control switch like a FUTURE flag_** (but reviewer may think differently).
( N.B. I **_am_** intending to create a FUTURE flag for the new split-attributes saving behaviour, since that will definitely change behaviour quite significantly. Covered in #4986 )
The actual changes in loading code are pretty small …
=> Splitattrs ncload

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/cube.py
To close #3945 
Adds a external hyperlink to convert_units methods for cube and coord to UDUNITS-2 documentation containing the information on what units and aliases for them are supported. 
The page in question has the information spread over 5 .xml files, but unless we want to recreate them in the cf-units documentation it's the closest we have to a list in the browser of supported units.
=> Added link to UDUNITS-2 database to convert_units docstrings

docs/src/whatsnew/latest.rst, lib/iris/plot.py, lib/iris/tests/unit/plot/test_contourf.py, lib/iris/tests/unit/quickplot/test_contourf.py
For Matplotlib v3.8 the `ContourSet` class had a re-write (https://github.com/matplotlib/matplotlib/pull/25247) and various of its attributes will be deprecated in the upcoming release.  Relevant release notes are
https://matplotlib.org/devdocs/api/next_api_changes/deprecations/25138-AL.html
https://matplotlib.org/devdocs/api/next_api_changes/deprecations/25247-AL.html
https://matplotlib.org/devdocs/api/next_api_changes/deprecations/26399-REC.html
`iplt.contourf` uses some of these attributes so this PR updates it to work with the new `ContourSet`.
---
=> Avoid using deprecated ContourSet attributes

lib/iris/_constraints.py, lib/iris/cube.py
Fixes to avoid `E721` in #5406.
---
=> Fix Flake8 `E721` errors

docs/src/whatsnew/latest.rst, lib/iris/fileformats/pp.py
Fixes #5315.
I think we only care about the `has_year_zero` keyword if the `lbyr` or `lbyrd` is zero.  Otherwise, my solution is to leave it to cftime's default.  Different calendars have different defaults, see https://unidata.github.io/cftime/api.html#cftime.datetime.
I'm not sure whether this needs a test just to assert that we now don't get a warning.  In case we do, I have identified `aPPglob1/global.pp` as a suitable file.
---
=> Avoid cftime warnings on pp-load

docs/src/installing.rst, docs/src/whatsnew/latest.rst
The installation guide is now out of date in a couple of places:
* Since v3.1 we do not provide platform-specific Conda downloads, so I do not think it is necessary to still list those platforms in the guide.
* Thanks to some outstanding work by @greglucas, Cartopy now has wheels :partying_face:, so users do not need to install any dependencies separately.  I tested the `pip` command in a new venv on my Ubuntu laptop and it Just Worked™.
I've also changed the language we use to distinguish things.
* "Users" vs "Developers" - I think we discussed previously somewhere that this distinction is a little ambiguous because users of Iris are going to be developing _something_.  In any case I might have reason to install a development version to do science and I might have reason to install a …
=> Update Installation Guide

benchmarks/bm_runner.py
Some minor improvements to `bm_runner.py`'s printing commands, which will be needed by subsequent feature branch pull requests.
No What's New entry since this is just prepping other steps.
---
=> Improve benchmark runner printing

docs/src/whatsnew/3.7.rst
This should fix a problem with the 3.7.0rc0 docs that was pointed out : the numbering of the lists of items in the whatsnew section was messed up by the insertion of anchor points for the 'feature items' para.
I think this fixes that.
We will include it in the main release, and in any subsequent bugfixes, but we won't make a bugfix release for this alone.
So for now, I'll include it here and, when this is agreed, it will also go into the v3.7.x mergeback to main.
=> Tweak indents to fix list numbering.

.github/workflows/benchmarks_run.yml, benchmarks/bm_runner.py, docs/src/whatsnew/latest.rst
- #5429 
- #5430 
- #5431 
- #5432 
- #5433 
Will need `git rebase upstream/FEATURE_benchmarks` once those are merged.
Fixes an oversight introduced when we switched away from Nox (#5215). Called process errors in `bm_runner.py` should cause an error upstream. Without this: we have had some benchmarks erroring without us knowing about it.
Also included handling to allow the overnight run to report whatever results it has, before erroring.
I have temporarily created a different default branch on my fork: [`trexfeathers:demo_20230817_main`](https://github.com/trexfeathers/iris/tree/demo_20230817_main), which can simulate what would happen on `main`.
- [Previously missed benchmark errors](https://github.com/SciTools/iris/actions/runs/5884680662/job/15959841341#step:9:116) on `SciTools:main` …
=> Set benchmark runs to error if the subprocess errors

benchmarks/asv.conf.json, benchmarks/asv_delegated_conda.py, docs/src/whatsnew/latest.rst
- #5429 
- #5430 
- #5431 
- #5432 
- #5433 
- #5434
Will need `git rebase upstream/FEATURE_benchmarks` once those are merged.
Since the `asv_delegated_conda.py` plugin is the only reason we need specified `conda_channels` (https://github.com/SciTools/iris/issues/5280#issuecomment-1525802077), I decided it was more appropriate / less misleading to hard-code the Conda channel into the plugin script itself.
No What's New entry since this is so small and internal.
---
=> Hard-code conda channel into asv_delegated_conda.py

benchmarks/benchmarks/experimental/ugrid/regions_combine.py, benchmarks/benchmarks/load/__init__.py, benchmarks/benchmarks/load/ugrid.py, benchmarks/benchmarks/save.py, docs/src/whatsnew/latest.rst
- #5429 
- #5430 
- #5431 
- #5432 
- #5433 
- #5434 
- #5435
Will need `git rebase upstream/FEATURE_benchmarks` once those are merged.
Inflates some of the data sizes for benchmarks to make sure Iris still handles them as lazy data since #5229.
- [Example of error that previously occurred](https://github.com/SciTools/iris/actions/runs/5884680662/job/15959841341#step:9:116)
- [A demo benchmark run that includes this PR's code](https://github.com/trexfeathers/iris/actions/runs/5900705016/job/16005475350) - no laziness failures
---
=> Inflate benchmark data to ensure laziness

docs/src/whatsnew/latest.rst
=> Benchmark feature branch what's new entry

.github/workflows/stale.yml
This PR exempts issues and PRs with the `Dragon 🐉` and `Dragon Sub-Task 🐉` labels from being marked as stale via the `stale.yml` workflow.
Closes #5411 
---
=> Do not run CI stale bot on Dragon-labelled issues and PRs

docs/src/further_topics/metadata.rst, docs/src/userguide/iris_cubes.rst, docs/src/whatsnew/latest.rst, lib/iris/cube.py
Resolves #4989 
This is very bare, but as @pp-mo has pointed out there just isn't currently an appropriate place to discuss NetCDF I/O. Raising the profile any further would disproportionately focus on attribute handling and read very strangely. I've made a `# TODO:` as a placeholder and should probably create an issue tomorrow.
---
=> Split attrs docs

docs/src/whatsnew/3.7.rst
Readying the whatsnew for actual release.
Note that, since v3.7.0rc0 was cut, we did merge  [some fixes to the formatting of the whatsnew document](https://github.com/SciTools/iris/pull/5427).
@HGWright **please re-check the docs build on this PR !**
=> Whats new updates for v3.7.0 .

benchmarks/bm_runner.py, docs/src/whatsnew/latest.rst
=> No longer use ASV ``--strict``

docs/src/whatsnew/latest.rst, lib/iris/experimental/ugrid/cf.py, lib/iris/experimental/ugrid/load.py, lib/iris/tests/integration/experimental/test_ugrid_load.py, lib/iris/tests/unit/experimental/ugrid/cf/test_CFUGridAuxiliaryCoordinateVariable.py, lib/iris/tests/unit/experimental/ugrid/cf/test_CFUGridConnectivityVariable.py, lib/iris/tests/unit/experimental/ugrid/cf/test_CFUGridMeshVariable.py
The development team has decided to embrace Python warnings, rather than Python logging, as the solution to user warnings.
Needed by #5472 - can't categorise warnings if they aren't warnings yet!
---
=> Remove uses of logging.warn

docs/src/whatsnew/latest.rst, lib/iris/tests/unit/experimental/ugrid/mesh/test_Connectivity.py, lib/iris/tests/unit/experimental/ugrid/mesh/test_MeshCoord.py
A number of pkg_resources warnings were being raised, these weren't all but were the only ones that seemed to be possible to change. 
Partially resolves #5491.
=> Replaced pkg_resources version parser with packager version parser.

docs/src/further_topics/filtering_warnings.rst, docs/src/userguide/index.rst, docs/src/whatsnew/latest.rst
Closes #5473 
✔ ~~Needs #5498 - I will rebase onto `main` once that is merged. The first _new_ commit of this branch is 01ead3c8c1b659e4cc982504a46671799dfcead5~~
[**Click here to view the docs page**](https://scitools-iris--5509.org.readthedocs.build/en/5509/further_topics/filtering_warnings.html)
---
=> Docs page on filtering warnings

docs/src/whatsnew/3.7.rst, tools/release_do_nothing.py
=> Ensure removal of release candidate from What's New title.

.github/workflows/stale.yml, docs/src/developers_guide/contributing_documentation_easy.rst
Closes #4628. After a discussion at the Peloton it was decided that this was all that was required as we are already notified when people open and comment on issues and PR's. The lack of ability to ping SciTools-devs doesn't seem to have been a problem up to this point, so the docs and comment the stale bot makes have been updated to remove the mention of pinging the devs.
---
=> updating docs and stale comment

.github/workflows/benchmarks_run.yml, .github/workflows/ci-tests.yml, docs/gallery_code/meteorology/plot_COP_maps.py, docs/src/whatsnew/latest.rst, lib/iris/tests/results/imagerepo.json
It was embarrassingly recent that I realised you can get Matplotlib to automatically place a colour bar across multiple axes.  Probably because I originally came to the Iris gallery to learn this sort of thing.  This PR modifies one example to show such placement rather than manually placing a colour bar axes.  Note that we also have the [GloSea example](https://scitools-iris.readthedocs.io/en/latest/generated/gallery/meteorology/plot_lagged_ensemble.html#sphx-glr-generated-gallery-meteorology-plot-lagged-ensemble-py) showing manual colour bar placement.
I have two versions of this in the two commits.  In the first commit, I created Cartopy GeoAxes up front so that I could pass the original array of axes to `colorbar`.  I the second commit, I reverted that and found a different way to get …
=> Gallery: show colour bar stealing space from multiple axes

docs/src/whatsnew/latest.rst, lib/iris/coords.py
This PR is made against https://github.com/SciTools/iris/discussions/5521
- This PR replaces the usage of `NotImplementedError` with `NotImplemented`
In file: [coords.py](https://github.com/SciTools/iris/blob/main/lib/iris/coords.py#L3122), class: CellMethod, there is a special method __add__ that raises a NotImplementedError. If a special method supporting a [binary operation is not implemented it should return NotImplemented](https://docs.python.org/3/library/constants.html#NotImplemented). On the other hand, NotImplementedError should be raised from abstract methods inside user defined base classes to indicate that [derived classes should override those methods. ](https://docs.python.org/3/library/exceptions.html#NotImplementedError)iCR suggested that the special method __add__ should …
=> Replaced `NotImplementedError` with `NotImplemented`

docs/src/whatsnew/latest.rst, requirements/py310.yml, requirements/py311.yml, requirements/py39.yml, requirements/pypi-core.txt
The pull-request bumps the minimum `numpy` version to `>1.21`, according to the [NEP29 Drop Schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule).
---
=> nep29 drop table schedule numpy>1.21

benchmarks/benchmarks/cperf/__init__.py, benchmarks/benchmarks/generate_data/stock.py, benchmarks/benchmarks/load/__init__.py, benchmarks/bm_runner.py, docs/gallery_code/meteorology/plot_COP_1d.py, docs/src/whatsnew/latest.rst, lib/iris/_deprecation.py, lib/iris/analysis/trajectory.py, lib/iris/fileformats/netcdf/saver.py, lib/iris/pandas.py, lib/iris/tests/unit/analysis/test_PERCENTILE.py, lib/iris/tests/unit/experimental/ugrid/mesh/test_Mesh.py, lib/iris/tests/unit/experimental/ugrid/mesh/test_MeshCoord.py, lib/iris/tests/unit/plot/test__check_geostationary_coords_and_convert.py
Note that, this pull-request is targeting the `SciTools:pre-commit-ci-update-config` branch (base branch of #5527)
#5527 is failing due to a `pre-commit.ci` update in `codespell` version ([github.com/codespell-project/codespell: v2.2.5 → v2.2.6](https://github.com/codespell-project/codespell/compare/v2.2.5...v2.2.6)), which now catches legitimate spelling corrections.
This pull-request addresses the typos identified by `codespell`.
i.e., see [here](https://results.pre-commit.ci/run/github/5312648/1697631292.lgG7s-vQTACMpuaD9H3TLA)
---
=> codespell fixes

docs/src/conf.py
With the recent release of pydata-sphinx-theme [v0.14.1](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.14.1) we can make some minor improvements.
Changes top navbar alignment to be `content` and not `left`.  Also disabled the **search box** as we already have one in the left sidebar, this allows for more links to be shown in full.
A whatsnew will be done in a separate PR.
---
=> updated layout of top navbar

.github/workflows/stale.yml
If we label something for a major release, it is reasonable/expected that it will hang around for a long time.  So I think it should be exempt from the stale GHA.
---
=> Exempt major release label from stalebot

docs/src/conf.py, docs/src/developers_guide/gitwash/development_workflow.rst, docs/src/developers_guide/gitwash/git_links.inc, docs/src/whatsnew/latest.rst
Addresses https://github.com/SciTools/iris/issues/5336.
Removed broken git links, the user can still link to the git docs if needed.
Built docs: https://scitools-iris--5569.org.readthedocs.build/en/5569/developers_guide/gitwash/development_workflow.html
---
=> DOCS: Removed broken git links.

docs/src/further_topics/dask_best_practices/index.rst, docs/src/further_topics/ugrid/data_model.rst, docs/src/techpapers/um_files_loading.rst, docs/src/userguide/navigating_a_cube.rst, docs/src/userguide/real_and_lazy_data.rst
Few minor styling and spacing fixes.
**OLD**: https://scitools-iris.readthedocs.io/en/latest/userguide/navigating_a_cube.html#adding-and-removing-metadata-to-the-cube-at-load-time.
**NEW**: https://scitools-iris--5572.org.readthedocs.build/en/5572/userguide/navigating_a_cube.html#adding-and-removing-metadata-to-the-cube-at-load-time
The vertical bar left of the bullet points should not be there.
No need for  whatsnew.
---
=> DOCS: fixed styling & spacing

docs/src/community/index.rst, docs/src/community/iris_xarray.rst, docs/src/community/phrasebook.rst, docs/src/whatsnew/latest.rst
Closes #5091.
Created a phrasebook for comparing similar packages. 
This is intended as a starting basis, with space for more to be added at a later date.
=> added phrasebook

lib/iris/_lazy_data.py, lib/iris/fileformats/netcdf/loader.py
Follows #5565, closes #5399 .
Implemented new modes, as discussed in a comment in aforementioned issue.
**WILL NEED REBASING ONCE PRECEDING PR IS MERGED.**
=> Chunk control modes

lib/iris/common/_split_attribute_dicts.py, lib/iris/tests/unit/util/test_equalise_attributes.py, lib/iris/util.py
=> Splitattrs equalise

lib/iris/_merge.py, lib/iris/tests/test_merge.py
Closes #5585 
During consideration of #5585 with @trexfeathers, we realised that although the way merge compares attributes is OK,  the way it constructs a report of an attribute matching failure has some subtle problems in the "new world" of split attributes.
As stated in [part of the testing code](https://github.com/SciTools/iris/pull/5590/files#diff-39daed7858abd37d34b2611a269553d5fe4533e1db7e6ced6248ea811f752b3dR1174-R1178) here,
```
```
This also affects the code where it works out which keys are different in existence ([`"cube.attributes keys differ: "`](https://github.com/SciTools/iris/pull/5590/files#diff-b0fdcae9a793b3cacb90bb52be392ea27505b46f9672389bd6885a3bd8004cafR404)) or value ([`"cube.attributes values differ for keys:"`](https://github.com/SciTools/iris/pull/5590/files#dif …
=> Split-attrs merge message

lib/iris/_lazy_data.py, lib/iris/fileformats/netcdf/loader.py
In particular, removing the possibility that `chunks` could be `None`, which has not been possible since #4716 
---
=> Chunk control minor fixes

lib/iris/cube.py, lib/iris/tests/unit/cube/test_CubeAttrsDict.py
=> Extra CubeAttrsDict methods to emulate dictionary behaviours.

docs/src/whatsnew/latest.rst, lib/iris/fileformats/netcdf/saver.py, lib/iris/tests/integration/netcdf/test_delayed_save.py, lib/iris/tests/integration/test_netcdf__loadsaveattrs.py
Although we handled the split-attrs save control, we forgot to provide a deprecation warning.
So that's what this does.
=> Splitattrs ncsave deprecation

lib/iris/tests/integration/netcdf/test_delayed_save.py
To fix #5547 problem
It seems that, when dask/distributed version 2023.9.3 --> 2023.11.0, some of our testcases trigger an additional warning about transferring large data to workers (only when using distributed).
I've confirmed that this isn't a _new_ inefficiency :  The test takes around 5 seconds via distributed, compared to 1 sec with a threaded or synchronous scheduler, and that performance hit is basically the same both before + after the version change.
So I guess it is just a new _warning_.
The tests that fail are testing the exact "data fill" warnings issued when saving to netcdf.
This PR gets the offending tests to explicitly ignore any warnings which look like that new message.
=> Fix test to ignore extra warnings from later versions of distributed.

docs/src/techpapers/index.rst, docs/src/techpapers/netcdf_io.rst, lib/iris/fileformats/netcdf/loader.py
Closes #5400. 
Added documentation, outlining the changes made in #5399 to implement further user control over chunksizes from 
netcdf files. 
***21/11*** *Note:  This is very much WIP, and will go through many changes. The commits at time of PR creation
are consciously disorganized, unclear and dysfunctional.
=> Chunk Control documentation

docs/src/techpapers/netcdf_io.rst, docs/src/whatsnew/latest.rst
=> What's New Entry

docs/src/whatsnew/latest.rst, lib/iris/fileformats/pp_save_rules.py, lib/iris/tests/unit/fileformats/pp/test_save.py
Fixes #4747 by adding some handling for the "realization" coordinate in `pp_save_rules.py`.
I followed the pattern of `_general_time_rules` in this module, and found the relevant field attribute by looking at the load code:
https://github.com/SciTools/iris/blob/e0850ebc73824c929f48d51067f88c3c2067b7fb/lib/iris/fileformats/pp_load_rules.py#L947-L950
Also updated some docstrings and comments.  There seem to have been some copypasta errors going on.
---
=> Fix pp save of realization coordinate

docs/src/userguide/index.rst
Add a link to the https://github.com/scitools-classroom repo from the user guide.
- [Current](https://scitools-iris.readthedocs.io/en/latest/userguide/index.html)
- [This PR](https://scitools-iris--5609.org.readthedocs.build/en/5609/userguide/index.html)
Addresses https://github.com/SciTools/iris/issues/5486.
---
=> DOCS: add links to scitools-classroom repo.

docs/src/userguide/citation.rst
I'm unclear whether these changes folllow the correct form, but I  suspect anyway that the existing format where it says "doi = {10.5281/zenodo.7386117}" is possibly wrong : this is not a complete valid url.
~TBD~
**UPDATE** it is a doi, should not be a url (!)
=> Possible citation updates -- not clear whether appropriate.

docs/src/conf.py, docs/src/whatsnew/1.4.rst
Should fix #5619 CI linkcheck failure
=> Use https for opendap.org link, as http no longer supported.

pyproject.toml
Ensured ruff convention is numpy, else ruff will  produce warnings for incompatible rules.
This augments https://github.com/SciTools/iris/pull/5623.
---
=> ensured ruff convention is numpy

docs/src/whatsnew/latest.rst
Add whatsnew entries for #5610 and #5621 because I forgot to do it in the pull request.
---
=> Add whatsnew entries for #5610 and #5621

.pre-commit-config.yaml, .ruff.toml, benchmarks/benchmarks/cperf/equality.py, benchmarks/benchmarks/cperf/load.py, benchmarks/benchmarks/cperf/save.py, benchmarks/benchmarks/sperf/equality.py, benchmarks/benchmarks/sperf/load.py, docs/src/common_links.inc, docs/src/whatsnew/latest.rst, lib/iris/common/resolve.py, lib/iris/tests/experimental/test_raster.py, lib/iris/tests/graphics/__init__.py, pyproject.toml
This pull-request replaces `isort` with the `ruff` implementation.
Reference: https://docs.astral.sh/ruff/settings/#isort
---
=> Replace isort with ruff

.gitignore
I built the full docs for the first time in a while and found this file left behind, presumably by Sphinx Gallery.
---
=> Add sg_execution_times.rst to .gitignore

.ruff.toml, pyproject.toml
This pull-request enforces `ruff` [flake8-commas (COM)](https://docs.astral.sh/ruff/rules/#flake8-commas-com) compliance by:
- removing the `COM` rule from the `.ruff.toml`.
- adding `COM812` and `COM819` to the permanent ignores, as these rules can interfere with the `ruff` formatter.
---
=> ruff COM rule compliance

.ruff.toml, lib/iris/tests/unit/analysis/geometry/test_geometry_area_weights.py
PR solely for fixing `D208:  Docstring is over-indented`
---
=> ruff rule D208 compliance.

.ruff.toml, lib/iris/analysis/_regrid.py, lib/iris/common/resolve.py, lib/iris/cube.py, lib/iris/fileformats/dot.py
PR solely for fixing `D411:  Missing blank line before section`
I used the `noqa` directive here as a few of the docstrings contain `Attributes:` in the docstest content and ruff thinks it is an over indented title, which it is not.  This will be a pattern for future docstrings that contains this.
---
=> ruff rule D411 compliance.

.ruff.toml, docs/gallery_code/general/plot_SOI_filtering.py, docs/gallery_code/meteorology/plot_COP_1d.py, docs/gallery_code/meteorology/plot_COP_maps.py, lib/iris/analysis/_grid_angles.py, lib/iris/analysis/_interpolation.py, lib/iris/analysis/cartography.py, lib/iris/analysis/maths.py, lib/iris/coord_systems.py, lib/iris/cube.py, lib/iris/fileformats/_nc_load_rules/helpers.py, lib/iris/fileformats/cf.py, lib/iris/fileformats/pp_load_rules.py, lib/iris/fileformats/um/_optimal_array_structuring.py, lib/iris/util.py
PR solely for fixing `D412:  No blank lines allowed between a section header and its content `
---
=> ruff rule D412 compliance.

.ruff.toml, benchmarks/benchmarks/aux_factory.py, benchmarks/benchmarks/cube.py, lib/iris/analysis/_scipy_interpolate.py, lib/iris/experimental/ugrid/mesh.py, lib/iris/tests/test_analysis_calculus.py, lib/iris/tests/test_coding_standards.py, lib/iris/tests/test_coordsystem.py, lib/iris/tests/unit/analysis/interpolation/test_RectilinearInterpolator.py, lib/iris/tests/unit/common/lenient/test__lenient_client.py, lib/iris/tests/unit/common/lenient/test__lenient_service.py, lib/iris/tests/unit/cube/test_Cube.py
PR solely for fixing:
*  `D211: No blank lines allowed before class docstring`
* `D300: triple double quotes / Use triple single quotes`
* `D403: First word of the first line should be capitalized`
---
=> ruff rule D211, D300, D403 compliance.

.ruff.toml, benchmarks/benchmarks/aux_factory.py, benchmarks/benchmarks/coords.py, benchmarks/benchmarks/cube.py, benchmarks/benchmarks/experimental/ugrid/__init__.py, lib/iris/analysis/trajectory.py, lib/iris/fileformats/_nc_load_rules/helpers.py, lib/iris/tests/integration/netcdf/test_general.py, lib/iris/tests/test_plot.py, lib/iris/tests/unit/analysis/scipy_interpolate/test__RegularGridInterpolator.py, lib/iris/tests/unit/coords/test_Cell.py, lib/iris/tests/unit/plot/test__check_bounds_contiguity_and_mask.py, lib/iris/tests/unit/plot/test__check_geostationary_coords_and_convert.py, lib/iris/tests/unit/plot/test__get_plot_defn_custom_coords_picked.py, noxfile.py
PR solely for fixing:
* `D209: Multi-line docstring closing quotes should be on a separate line`
---
=> ruff compliance for D209.

.ruff.toml, benchmarks/bm_runner.py
PR solely for fixing:
* `pycodestyle (W)` - This is the only one that needed a code change.
* `flake8-copyright (CPY)`
* `flake8-implicit-str-concat (ISC)`
* `Airflow (AIR)`
---
=> Various ruff rule compliance (W, CPY, ISC, AIR)

.ruff.toml, lib/iris/common/resolve.py, lib/iris/cube.py, lib/iris/fileformats/pp_load_rules.py, lib/iris/tests/test_concatenate.py, lib/iris/tests/unit/fileformats/netcdf/saver/test_Saver__ugrid.py
PR solely for fixing `D406: Section name should end with a newline`
---
=> ruff complliance for D406.

.ruff.toml, lib/iris/_representation/cube_summary.py, lib/iris/analysis/_area_weighted.py, lib/iris/analysis/_interpolation.py, lib/iris/analysis/_regrid.py, lib/iris/experimental/regrid.py, lib/iris/experimental/ugrid/cf.py, lib/iris/fileformats/cf.py, lib/iris/fileformats/pp_load_rules.py, lib/iris/plot.py, lib/iris/tests/__init__.py, lib/iris/tests/system_test.py, lib/iris/tests/test_coding_standards.py, lib/iris/tests/test_pp_cf.py, lib/iris/tests/unit/cube/test_Cube.py, lib/iris/tests/unit/fileformats/netcdf/loader/test__chunk_control.py
PR solely for fixing `D404: First word of the docstring should not be "This"`
---
=> ruff compliance for D404.

docs/src/whatsnew/latest.rst, requirements/py310.yml, requirements/py311.yml, requirements/py39.yml, requirements/pypi-core.txt
This pull-request enforces `nep29` and drops `numpy 1.22`, as scheduled.
See [NEP29 Drop Schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule).
---
=> nep29 drop numpy 1.22

.ruff.toml, lib/iris/fileformats/netcdf/loader.py
PR solely for fixing `D106: Missing docstring in public nested class`
---
=> ruff compliance for D106.

docs/src/conf.py, docs/src/further_topics/index.rst, docs/src/whatsnew/latest.rst
A very simple way to make it obvious in a TOC-tree that `Further Topics` is not just a page, but a subsection of its own.
I chose to edit the title itself, rather than an alias in the existing TOC-tree, so that this will also apply if included in other TOC-trees. I also kinda like the title being this way 😁
---
=> Make further topics obviously different

docs/src/whatsnew/latest.rst, lib/iris/analysis/calculus.py
=> Better documentation for Cube names in curl

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/tests/unit/coords/test_Coord.py
This avoids loading all the coordinate data from disk if only a single cell is requested.
Closes #5692 
---
=> Make the Coord.cell method lazy

docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/cube.py, lib/iris/tests/unit/util/test_array_equal.py, lib/iris/util.py
This makes the comparison of coordinates, cubes, and arrays to themselves faster.
---
=> Faster trivial equality checks for coordinates and arrays

docs/src/developers_guide/contributing_ci_tests.rst, docs/src/whatsnew/latest.rst
Add ruff section to the dev guide docs.
Closes https://github.com/SciTools/iris/issues/5688.
Build Docs: https://scitools-iris--5701.org.readthedocs.build/en/5701/developers_guide/contributing_ci_tests.html#id3
---
=> DOCS: Add ruff section to the dev guide docs

lib/iris/analysis/__init__.py, lib/iris/analysis/_area_weighted.py, lib/iris/analysis/_grid_angles.py, lib/iris/analysis/calculus.py, lib/iris/aux_factory.py, lib/iris/fileformats/pp.py, lib/iris/fileformats/rules.py, lib/iris/io/__init__.py, lib/iris/io/format_picker.py
Progressing numpydoc strings adoption, https://github.com/SciTools/iris/issues/4721.
Review past changes and update based upon new understanding of optional keywords,  few other minor changes too.
---
=> DOCS: numpydocs 4

docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/tests/unit/cube/test_Cube.py
Consider NaNs equal when comparing cubes and speed up comparing cubes to themselves.
Closes  #5705
---
=> Consider NaNs equal when comparing cubes

docs/src/conf.py
This pull-request avoids the following diagnostic issued by `pydata-sphinx-theme`:
```
The default value for `navigation_with_keys` will change to `False` in the next release.
If you wish to preserve the old behavior for your site, set `navigation_with_keys=True`
in the `html_theme_options` dict in your `conf.py` file. Be aware that `navigation_with_keys = True`
has negative accessibility implications: https://github.com/pydata/pydata-sphinx-theme/issues/1492
```
Reference:
- `pydata-sphinx-theme` [issue #1492](https://github.com/pydata/pydata-sphinx-theme/issues/1492)
- `sphinx` [HTML Theming](https://www.sphinx-doc.org/en/master/usage/theming.html).
---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checkl …
=> Disable navigation with keys for docs HTML theme

docs/src/further_topics/netcdf_io.rst, docs/src/whatsnew/latest.rst, lib/iris/coords.py, lib/iris/util.py
Closes #5589
See also #5551
---
=> Document `Coord.ignore_axis`

docs/src/whatsnew/latest.rst, lib/iris/fileformats/_nc_load_rules/helpers.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test__normalise_bounds_units.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_auxiliary_coordinate.py, lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_dimension_coordinate.py
This pull request ensures that during the NetCDF loading pipeline, coordinates are constructed with points and bounds equal to the units of the points.
This is to resolve the issue where coordinates can be constructed and attached to a cube, but the units of the points and bounds of the coordinate are encoded differently within the source NetCDF file.
The following cases are handled:
1. Bounds that have invalid units i.e., not recognised by `cf-units`, will result in a warning being raised and the bounds attached "as-is" to the coordinate. This provides the user to option to keep, remove or replace the bounds as they choose.
1. Bounds with units that are different but convertible to the units of the points will be automatically converted to the units of the points.
1. Bounds with units …
=> Normalise units of coordinate bounds

.github/workflows/benchmarks_run.yml
This avoids a bug in Airspeed Velocity's dependencies: airspeed-velocity/asv#1385
---
=> Pin ASV - airspeed-velocity/asv#1385

lib/iris/tests/unit/util/test_broadcast_to_shape.py
Fixes the `NMPY002` error in ruff.  This rule was introduced in a recent ruff release https://github.com/astral-sh/ruff/releases/tag/v0.2.2.
```
$ ruff .
lib/iris/tests/unit/util/test_broadcast_to_shape.py:24:13: NPY002 Replace legacy `np.random.random` call with `np.random.Generator`
lib/iris/tests/unit/util/test_broadcast_to_shape.py:31:13: NPY002 Replace legacy `np.random.random` call with `np.random.Generator`       
lib/iris/tests/unit/util/test_broadcast_to_shape.py:40:13: NPY002 Replace legacy `np.random.random` call with `np.random.Generator`       
lib/iris/tests/unit/util/test_broadcast_to_shape.py:59:13: NPY002 Replace legacy `np.random.random` call with `np.random.Generator`       
lib/iris/tests/unit/util/test_broadcast_to_shape.py:69:13: NPY002 Replace legacy …
```
=> RUFF: fix legacy use of np.numpy.random

docs/src/whatsnew/latest.rst
Add whatsnew for recent PRs: 
- https://github.com/SciTools/iris/pull/5762
- https://github.com/SciTools/iris/pull/5786
---
=> DOCS: Add whatsnew for recent PRs

requirements/py310.yml, requirements/py311.yml, requirements/py39.yml
This pull-request adds the [pytest-mock](https://github.com/pytest-dev/pytest-mock) package dependency to the conda YAML spec files.
It is not necessary to include this dependency for `pip`, as only `scitools-iris` core dependencies require to be configured.
When this pull-request is merged, the follow-up action is to refresh the lockfiles for the targeted `FEATURE_pytest_conversion` feature branch.
---
---
=> Add pytest-mock dependency

pyproject.toml
This pull-request configures the `pytest-mock` plugin for `pytest`, thus making the `mocker` fixture available.
See https://pytest-mock.readthedocs.io/en/latest/ for further details.
Note that, through the `mocker` fixture, we have access to vanilla `mock` module as we know and (un-)love.
---
---
=> Configure pytest-mock as pytest required-plugin

lib/iris/tests/unit/concatenate/test__CubeSignature.py, lib/iris/tests/unit/concatenate/test_concatenate.py
@pp-mo I've updated your changes so that they're `ruff check --select PT` ([flake8-pytest-style](https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt)) compliant.
---
---
=> pytest migration ruff PT compliance for unit.concatenate

lib/iris/tests/unit/common/lenient/test_Lenient.py
=> pytest migration for unit.common.test_Lenient

lib/iris/tests/_shared_utils.py
The previous implementation was flaky given we could not know where in the call stack the test actually was, and I have no idea how I could have got it working with PyTest parameters - probably something even more flaky.
This version uses publicly available attributes from the PyTest [`FixtureRequest`](https://docs.pytest.org/en/stable/reference/reference.html#pytest.FixtureRequest), which seems much safer.
=> Better implementation of `_shared_utils.results_path()` - using PyTest `request`

lib/iris/tests/unit/aux_factory/test_AtmosphereSigmaFactory.py
=> Pytests unit/aux_factory/test_AtmosphereSigmaFactory

lib/iris/tests/unit/aux_factory/test_AtmosphereSigmaFactory.py
This is a follow-on to #5834 
Following a discussion on simpler solutions to migrating setUp functions..
This effectively reverts some of the tweaks in the previous : makes fewer diffs from the original unittest form.
May be slightly pointless, but the new way will be easier to follow in the eventual feature merge-back.
=> Simplify data fixtures.

lib/iris/tests/unit/aux_factory/test_OceanSFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSg1Factory.py, lib/iris/tests/unit/aux_factory/test_OceanSg2Factory.py, lib/iris/tests/unit/aux_factory/test_OceanSigmaFactory.py, lib/iris/tests/unit/aux_factory/test_OceanSigmaZFactory.py
That is, all the "Ocean" ones.
=> Pytest convert the remainder of the aux-factory test

lib/iris/tests/unit/common/lenient/test__Lenient.py
=> pytest migration for unit.common.lenient.test__Lenient

lib/iris/tests/_shared_utils.py, lib/iris/tests/test_plot.py, lib/iris/tests/test_quickplot.py
`ruff check --select PT` ([flake8-pytest-style](https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt)) compliant
=> Convert `tests/test_plot` to PyTest

lib/iris/tests/unit/common/lenient/test__lenient_service.py
=> pytest migration for unit.common.lenient.test__lenient_service

lib/iris/tests/unit/common/lenient/test__qualname.py
=> pytest migration for unit.common.lenient.test__qualname

lib/iris/tests/unit/common/mixin/test_LimitedAttributeDict.py
=> pytest migration for unit.common.mixin.test_LimitedAttributeDict

lib/iris/tests/unit/common/metadata/test__NamedTupleMeta.py
=> pytest migration for unit.common.metadata.test_NamedTupleMeta

docs/src/whatsnew/3.8.rst
Does not need to be a merge-commit since this is a 'manual' recreation of what the merge-back should be (no features are exclusive to the release branch, only What's New content).
=> `v3.8.1` merge-back

lib/iris/tests/_shared_utils.py, lib/iris/tests/test_analysis.py, lib/iris/tests/test_analysis_calculus.py
`ruff check --select=PT` compliant
=> Make test_analysis PyTest

lib/iris/tests/unit/fileformats/abf/test_ABFField.py
In this case I went a bit beyond the brief, and have converted the roll-your-own call counting to a reasonably standard approach using Mock.
Which is not strictly a pytest change (!)
**NOTE:**
@bjlittle suggested using "mocker.spy" instead, which does sound like the nicest way.
However, I found that "mocker.spy" does not work on a `__getattr__` call, even though "mock.patch" actually did.
So it looks like the implementation of "mocker.spy" is less obvious than you might expect (probably since it now it supports async methods, etc).
For the sake of simplicity, I just removed the check that `__getattr__` is called :   I think checking that `_read` was called is good enough in itself.
=> Convert ABF test to pytest.

lib/iris/tests/unit/common/metadata/test_AncillaryVariableMetadata.py
=> pytest migration for unit.common.metadata.test_AncillaryVariableMetadata

lib/iris/tests/unit/fileformats/nimrod_load_rules/test_units.py, lib/iris/tests/unit/fileformats/nimrod_load_rules/test_vertical_coord.py
Covers all of tests/unit/fileformats/nimrod_load_rules
=> Convert to Pytest.

lib/iris/tests/unit/fileformats/rules/test_Loader.py, lib/iris/tests/unit/fileformats/rules/test__make_cube.py, lib/iris/tests/unit/fileformats/rules/test_rules.py
Also moved "test_rules.py" from /fileformats into /fileformats/rules.
=> Convert to fileformats/rules to pytest

lib/iris/tests/_shared_utils.py, lib/iris/tests/integration/plot/test_animate.py, lib/iris/tests/integration/plot/test_colorbar.py, lib/iris/tests/integration/plot/test_netcdftime.py, lib/iris/tests/integration/plot/test_nzdateline.py, lib/iris/tests/integration/plot/test_plot_2d_coords.py, lib/iris/tests/integration/plot/test_vector_plots.py, lib/iris/tests/test_mapping.py
`ruff check --select=PT` compliant
=> Convert remaining graphics tests to PyTest

lib/iris/tests/_shared_utils.py, lib/iris/tests/unit/common/metadata/test_BaseMetadata.py
=> pytest migration for unit.common.metadata.test_BaseMetadata

lib/iris/tests/unit/common/metadata/test_hexdigest.py
=> pytest migration of unit.common.metadata.test_hexdigest

lib/iris/tests/unit/common/metadata/test_metadata_filter.py
=> pytest migration of unit.common.metadata.test_metadata_filter

lib/iris/tests/unit/common/metadata/test_metadata_manager_factory.py
=> pytest migration of unit.common.metadata.test_metadata_manager_factory

lib/iris/tests/_shared_utils.py, lib/iris/tests/test_pp_cf.py, lib/iris/tests/test_pp_module.py, lib/iris/tests/test_pp_stash.py, lib/iris/tests/test_pp_to_cube.py, lib/iris/tests/test_util.py
`ruff check --select=PT` compliant
=> More root pytest

.github/workflows/ci-tests.yml, docs/src/whatsnew/latest.rst
This makes the output of pytest on GitHub Actions much more readable by breaking it up with colour.
It has to be forced on as GitHub Actions doesn't use a real TTY, which pytest uses for rich output detection.
---
---
=> Force pytest colour output on GitHub Actions

docs/src/whatsnew/latest.rst, lib/iris/fileformats/netcdf/loader.py, lib/iris/tests/unit/fileformats/netcdf/loader/test__chunk_control.py
Fixes #5864 
This supports when a netcdf variable ".chunking()" call returns `None`.
The added test fails without the fix.
=> Support NetCDF v3 files in chunking control code.

docs/src/whatsnew/latest.rst, lib/iris/fileformats/pp.py
I'm glad this function exists publicly as it was the solution to my problem today but I found the docstring confusing: because it said it could convert an iterable of cubes, I tried passing a cubelist, which failed because cubelists have no `shape` attribute.
I also note that the `target` parameter does not appear to be used for anything, but I don't think I want to pull on that thread right now...
---
=> DOC: clarify save_pairs_from_cube docstring

docs/src/whatsnew/latest.rst, lib/iris/tests/unit/util/test_broadcast_to_shape.py, lib/iris/util.py
Make it possible to specify the target chunks in [iris.util.broadcast_to_shape](https://scitools-iris--5620.org.readthedocs.build/en/5620/generated/api/iris.util.html#iris.util.broadcast_to_shape).
This function is often used to broadcast auxiliary coordinate or cell measure data or weights to the same shape as the data from a cube. If the chunks of the broadcasted data do not match that of the cube, this leads to poor computational performance. Rechunking after broadcasting is less efficient, therefore it is really useful to be able to specify the chunks directly as part of the broadcast.
Closes #5456
---
=> Add option to specify chunks in `iris.util.broadcast_to_shape`

docs/src/conf.py
Was getting repeated `broken` results in the linkcheck CI even though I could visit it manually, so would suggest there is a problem specific to the automation. In any case the link is not in a critical part of the documentation so seems safe to ignore.
---
---
=> Ignore `flaticon.com` in linkchecks

lib/iris/tests/unit/common/resolve/test_Resolve.py
=> pytest migration of unit.common.resolve.test_Resolve

lib/iris/tests/test_basic_maths.py
Possible fix for recently observed pre-commit CI failures?
---
---
=> Fix W605 error in `test_coord_op_coord_fail`

docs/src/whatsnew/latest.rst, lib/iris/_concatenate.py, lib/iris/_lazy_data.py, lib/iris/aux_factory.py, lib/iris/cube.py, lib/iris/fileformats/netcdf/_thread_safe_nc.py, lib/iris/fileformats/netcdf/loader.py, lib/iris/fileformats/pp.py, lib/iris/tests/unit/fileformats/netcdf/loader/test__chunk_control.py, lib/iris/tests/unit/fileformats/netcdf/loader/test__get_cf_var_data.py, lib/iris/tests/unit/fileformats/pp/test__create_field_data.py, lib/iris/tests/unit/lazy_data/test_as_concrete_data.py, lib/iris/tests/unit/lazy_data/test_as_lazy_data.py, lib/iris/tests/unit/lazy_data/test_co_realise_cubes.py, lib/iris/tests/unit/lazy_data/test_stack.py
Use the correct `chunktype` for Dask arrays. Closes #5800.
---
---
=> Use the correct `chunktype` for Dask arrays

docs/src/whatsnew/latest.rst, lib/iris/analysis/__init__.py, lib/iris/tests/unit/analysis/test_WPERCENTILE.py
Fixes #5777 by making the underlying `_weighted_percentile` function broadcast 1D weights if given.  Also improved the error message if `weights` is the wrong shape.
---
---
=> FIX: weighted percentile works with 1D weights

benchmarks/asv_delegated_conda.py, docs/src/whatsnew/latest.rst
See airspeed-velocity/asv#1396. The fix has been proposed in airspeed-velocity/asv#1397 but it is uncertain how quickly that might progress. We need the benchmarks working for an upcoming sprint, including in places where we cannot pin the Conda version appropriately, so I am proposing this temporary override in our existing subclass.
---
---
=> Temporary fix for airspeed-velocity/asv#1396

benchmarks/README.md, benchmarks/bm_runner.py, docs/src/whatsnew/latest.rst
#5957 demonstrates that trouble with iris-test-data is a barrier to understanding at the moment.
---
---
=> Automatically install iris-test-data for benchmark data generation

benchmarks/bm_runner.py, noxfile.py
Closes #5944
Notes: I tried to make this as foolproof and self-contained as possible. 
so it sets up DATA_GEN_PYTHON and ON_DEMAND_BENCHMARKS.
However you must still provide iris-test-data, via **OVERRIDE_TEST_DATA_REPOSITORY** (at least for most benchmarks).
If you don't, the resulting error is not that obvious (!) -- see below
You may also need to set **BENCHMARK_DATA** if you don't want to overfill your homespace or /tmp/persistent (here at MetOffice).
So, this is potentially still tricky to use, and even dangerous if you total your disk quota!
You may also provide a suitable environment, to prevent it creating one.
Omitting this does work, but can be slow as although we can build a suitable test env, we still don't have a reliable way of automatically caching + re-using them.
**If the …
=> Add bm_runner 'trialrun' subcommand.

benchmarks/benchmarks/__init__.py, benchmarks/benchmarks/merge_concat.py, benchmarks/benchmarks/regridding.py, benchmarks/benchmarks/stats.py, benchmarks/benchmarks/trajectory.py
Extends existing benchmarks by adding a version which tracks memory for functions where iris may be responsible for memory handling (e.g. by calling dask in a specific way, as resolved in #5767). Memory benchmarks are repeated so that memory leaks may be better detected.
=> Add memory benchmarks

pyproject.toml
Running the iris test suite feels a bit slow when developing. This pull request adds a pytest option that causes the 25 slowest tests to be displayed with every test run. This will make test run times more visible to developers and in that way encourage writing faster tests.
Examples
========
In CI: https://github.com/SciTools/iris/actions/runs/9186913624/job/25263500853?pr=5969#step:12:1646
Locally:
```
$ pytest lib/iris/tests/unit/cube/test_Cube.py
============================================================================ test session starts ============================================================================
platform linux -- Python 3.12.2, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/bandela/src/scitools/iris
configfile: pyproject.toml
plugins: cov-5.0.0, xdist-3.5.0
collected …
```
=> List 25 slowest tests

docs/src/whatsnew/latest.rst, lib/iris/tests/unit/cube/test_Cube.py
I looked at #5969 and couldn't resist...
These slowest running tests are testing slicing over 70 model levels.  I assert that if the slicing does not go wrong for the first 7 levels, it is unlikely to go wrong for the next 63.  So let's just test with a smaller cube.  Locally, this simple change reduces the runtime of these tests by a factor of 9.
---
---
=> Make `slices_over` tests go faster

docs/src/copyright.rst, docs/src/further_topics/dask_best_practices/dask_bags_and_greed.rst, docs/src/further_topics/netcdf_io.rst, docs/src/further_topics/ugrid/partner_packages.rst, docs/src/further_topics/which_regridder_to_use.rst, docs/src/whatsnew/3.6.rst, lib/iris/analysis/calculus.py, lib/iris/fileformats/netcdf/saver.py, pyproject.toml, tools/release_do_nothing.py
Fix the `codespell` failures raised by `pre-commit.ci` for the latest version of `codespell`.
See https://github.com/SciTools/iris/pull/5980
Note that, this PR targets the base branch of https://github.com/SciTools/iris/pull/5980, rather than `main`.
---
---
=> fix codespell failures

docs/src/installing.rst
Minor change to the installation instructions to use **tabs** in the docs.  The content under the conda and pypi tabs is the same as before, just in a tab.
Inspiration taken from the [geovista docs](https://geovista--828.org.readthedocs.build/en/828/installation.html#stable). (this is in a PR atm).
---
---
=> DOCS: Use tabs for the install info

setup.py
We were mistakenly passing a tuple into something that needed a list - needs to be a mutable object.
pypa/setuptools@2db55275f
---
---
=> Adapt setup.py for pypa/setuptools@2db55275f

requirements/py310.yml, requirements/py311.yml, requirements/py312.yml, requirements/pypi-core.txt
- [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html)
- `2024-06-22`: NumPy `>=1.24`
- 0289e5680b208d02015be3a76715e8435002c4c0
- [NumPy v2](https://numpy.org/doc/stable/release/2.0.0-notes.html)
- #6035 has proven that it will be a medium/large task to get all our tests supporting NumPy v2
- We expect to have some slots to work on this for Iris v3.11 - #5571
- So we need a pin in the meantime, and I expect also a patch release
The lock files already fit between these two pins so I have not refreshed those.
---
---
=> NEP29 and NumPy v2 pins

docs/src/whatsnew/latest.rst, lib/iris/tests/__init__.py, lib/iris/tests/test_iterate.py
These tests are very slow because they compare many cubes. Making the input cubes smaller makes them run faster. With these changes, they run about 3x faster (7 seconds instead of 20 on my laptop).
---
---
=> Shorten cube iterator tests

docs/src/whatsnew/latest.rst, lib/iris/_concatenate.py
=> Faster concatenation of cubes with `AuxCoordFactory`s

docs/src/whatsnew/latest.rst, lib/iris/fileformats/_nc_load_rules/helpers.py, lib/iris/tests/integration/netcdf/test_coord_systems.py, lib/iris/tests/integration/netcdf/test_general.py
=> Quieter datum warning

docs/src/whatsnew/latest.rst, lib/iris/experimental/geovista.py
Part of the fix for #6029. Note that this change is also backwards compatible with earlier versions of GeoVista.
---
---
=> Doctest compatibility with GeoVista v0.5

benchmarks/benchmarks/unit_style/ugrid.py, docs/src/whatsnew/latest.rst, lib/iris/experimental/ugrid/mesh.py, lib/iris/fileformats/netcdf/saver.py, lib/iris/tests/integration/experimental/test_meshcoord_coordsys.py, lib/iris/tests/unit/experimental/ugrid/mesh/test_Mesh.py, lib/iris/tests/unit/experimental/ugrid/mesh/test_MeshCoord.py
=> add location argument to mesh.coords

lib/iris/common/metadata.py
I think this should have happened in #6061 but I missed it.
=> Add mesh metas to the iris.common.metadata public API.

docs/src/installing.rst
Remove reference to `--force` when using conda.  It is only available when using mamba.
---
---
=> DOCS: remove --force option as it is not present in conda (only mamba)

docs/src/whatsnew/latest.rst, lib/iris/io/format_picker.py, lib/iris/tests/unit/io/format_picker/test_FormatAgent.py
Closes #6108.
Adds a copy method to `FormatAgent`, which creates a new `FormatAgent` from the format specs. Also adds an equality method which compares the format specs.
The use case for this is to temporarily modify the `FORMAT_AGENT` in a custom load, and then restore it so that we don't change standard `iris.load` behaviour outside of the custom load.
=> Add format agent copy and equality methods

.github/dependabot.yml
This pull-request updates the `dependabot` configuration to include coverage of our composite GHAs.
Note that, `dependabot` has not updated the [actions/cache](https://github.com/actions/cache) GHA version used by the composite actions, which has been at `v4.0.2` since 19 Mar 2024.
As a result, the composite actions have been using a deprecated version of `node.js` and forced to run on `node20`.
---
---
=> configure dependabot for github composite actions

.pre-commit-config.yaml, lib/iris/tests/__init__.py, lib/iris/tests/integration/test_netcdf__loadsaveattrs.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/__init__.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/test__latlon_dimcoords.py, pyproject.toml
=> Fix pre-commit non-compliances

docs/src/whatsnew/latest.rst, lib/iris/_concatenate.py, lib/iris/tests/unit/concatenate/test_hashing.py
The following arrays compare equal in `iris.util.array_equal`, so they should also compare equal in the hash function used by concatenate:
- `np.array([1, 2])` and `np.ma.array([1, 2], mask=np.ma.nomask)`
- `np.array([1, 2])` and `np.ma.array([1, 2], mask=[0, 0])`
- `np.ma.array([1, 2], mask=[0, 0])` and `np.ma.array([1, 2], mask=np.ma.nomask)`
---
---
=> Improve handling of masks in concatenate

docs/src/whatsnew/latest.rst, lib/iris/fileformats/cf.py
Reduce duplication in cf.py spanning checks.
In preparation for further work on #6190.
---
---
=> Reduce duplication in `cf.py` spanning checks

docs/src/developers_guide/contributing_pytest_conversions.rst
Added a translation guide, as suggested in https://github.com/SciTools/iris/issues/5690#issuecomment-1988712822.
Additionally, corrected myself; ``mocker`` has the same api as ``mock``, and can be used as a context manager. In the example I based that judgement off, it was just decided it wasn't needed. 
See https://pytest-mock.readthedocs.io/en/latest/usage.html
=> Add a pytest-unittest translator to the conversion guide  

docs/src/whatsnew/3.11.rst
The 3.11 whatsnew currently double mentions type hints and enhancements. I've removed the offending line. 
This should go into the 3.11 branch, and then a mergeback.
=> removed double reference of typehints and enhancements

benchmarks/bm_runner.py
Recent experience has shown that benchmarks run on GitHub actions are very accurate. I originally set the default of 4 rounds to compensate for an assumed _inaccuracy_ of GHA (given it's a shared resource). I would like to try with 3, and if that's still accurate I might consider dropping to 2.
---
---
=> Reduce default number of benchmark rounds

docs/src/further_topics/ugrid/other_meshes.rst
Problem has appeared here : https://github.com/SciTools/iris/actions/runs/12171348115/job/33948080471
So should unblock _at least_ https://github.com/SciTools/iris/pull/6243
(but expect further problems from it)
It does look to me like the url target has definitely changed
=> Fix broken link.

docs/src/conf.py, docs/src/index.rst
=> Remove freepik.com link due to linkcheck breakage

.github/workflows/refresh-lockfiles.yml
=> Adopt updated common refresh-lockfiles action.

docs/src/whatsnew/latest.rst, lib/iris/fileformats/pp_save_rules.py, lib/iris/tests/unit/fileformats/pp/test_save.py
Closes #6239.  String stash codes now "just work".
---
---
=> Add support for saving string stash codes to PP

docs/src/whatsnew/latest.rst, lib/iris/analysis/__init__.py, lib/iris/analysis/cartography.py, lib/iris/tests/test_analysis.py
Use cube chunks for smart weights when broadcasting is necessary.
Closes https://github.com/SciTools/iris/issues/6285.
---
---
=> Use cube chunks for weights in aggregations with smart weights

benchmarks/benchmarks/load/__init__.py, docs/src/whatsnew/latest.rst, lib/iris/cube.py, lib/iris/fileformats/cf.py
This reduces the time required to load small NetCDF files, especially those with many variables.
Using the files and timing script from #6223, this pull request speeds up loading the file with a single variable by 30% and the file with many variables by 200%.
---
---
=> Improve speed of loading small NetCDF files

docs/src/developers_guide/release.rst
`build` is now called `python-build` on conda (it is still just `build` in pip). It seems that the [feedstock was archived August '24](https://github.com/conda-forge/build-feedstock), and nothing else has broken, so I don't think this is a problem for Iris' automated processes, outside of references to it. 
This PR changes instructions in the docs for doing a manual pypi release.
=> Replace references of `conda install build` to `conda install python-build`

docs/src/whatsnew/latest.rst, lib/iris/fileformats/netcdf/saver.py, lib/iris/tests/unit/fileformats/netcdf/saver/test_Saver.py
=> Add castable check for `valid_range`, `valid_min`, `valid_max`

docs/src/conf.py, lib/iris/quickplot.py, lib/iris/tests/test_quickplot.py
Added some convenience enums to quickplot, to supplement #6247.
```Python
from iris.quickplot import Classification
qplt.contour(cube, footer=Classification.official_sensitive)
iplot.show()
```
Which offers more consistency than:
```Python
qplt.contour(cube, footer="Official-Sensitive")
iplot.show()
```
=> added classification enums to qp

docs/src/whatsnew/latest.rst, lib/iris/cube.py
This makes looking up the dimensions of derived coordinates faster by first looking if the metadata of the requested coordinate matches that of an AuxFactory instead of creating the derived coordinate and then comparing the metadata. Creating a derived coordinate is a relatively slow operation.
---
---
=> Faster dimension lookup for derived coordinates

docs/src/whatsnew/latest.rst, lib/iris/coords.py
Fixes #6347 by correcting the AuxCoord docstring.
---
---
=> Correct unit to units in AuxCoord docstring

docs/src/conf.py, docs/src/whatsnew/3.12.rst
* Whats new updates for v3.12.0 .
* Review changes: whatsnew fix.
* Add link to ignored list.
**NOTE: must use a merge commit** -- I have temporarily enabled this ...
=> Mergeback from v3.12.0 release.

lib/iris/fileformats/netcdf/loader.py, lib/iris/palette.py
Remove several `global` variable declarations that were unnecessary due to the variables never being **assigned** to in their declared scope (accessing them is not ambiguous in the namespace scope).
This was highlighted by the flake8 linter in a recent pre-commit hook update.
Unblocks: #6396
=> Remove unnecessary `global` declarations

lib/iris/tests/test_plot.py
Fixes #6393.  I assume this `fail` method existed to expand the error message but got removed somewhere along the way.  I just learned about the [add_note](https://docs.python.org/3/library/exceptions.html#BaseException.add_note) method, which seems a nice simple way to achieve this.
Failure messages now look like
`run_tests_1D`
```
E                           AssertionError: Image comparison failed: Bad phash a2ffb6127f0dc9992085d960c6748d369b121ca69d6a9b048df34ce789ff7205 with hamming distance 4 for test iris.tests.test_quickplot.TestQuickplotCoordinatesGiven.test_y.0.
E                           Draw method iris.quickplot.plot failed with coords: ['grid_latitude'].
```
`run_tests`
```
E                           AssertionError: Image comparison failed: Bad phash …
```
=> TST: make image comparison fail nicely

MANIFEST.in
MANIFEST.in should now compare nicely with [the latest template](https://github.com/SciTools/.github/blob/7363ee13d94e662d97d5a4e9f8166a09e5ccff88/templates/MANIFEST.in)
=> Realign with re-styled template.

benchmarks/asv_delegated.py, docs/src/whatsnew/latest.rst, setup.py
This is deprecated behaviour and can easily be achieved using `pip install -e .` instead.
- [Running `setuptools` commands](https://setuptools.pypa.io/en/latest/deprecated/commands.html)
- [v80.0.0 deprecations and removals](https://setuptools.pypa.io/en/stable/history.html#deprecations-and-removals)
---
---
=> Remove `setup.py develop` command

pyproject.toml, requirements/py311.yml, requirements/py312.yml, requirements/py313.yml
This pull-request complies with [PEP639](https://peps.python.org/pep-0639/) for `setuptools`, also see [license and license-files](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files).
Additionally avoids the following `setuptools` deprecation warning:
```
!!
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: BSD License
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
!!
```
--- …
=> pep639: setuptools license and license-files fields

.github/workflows/benchmarks_run.yml
The new PRs raised on the Nox GitHub suggest that this will be fixed in the next release of Nox.
The correct thing to do would be to update our dependencies and our lock files. Unfortunately we are half way through fixing a separate lock file problem (#6438) so I felt the pragmatic thing to do was only unblock the failing CI and nothing else.
---
---
=> Temporary Nox negation pin - see wntrblm/nox#961

docs/src/whatsnew/3.12.rst, lib/iris/fileformats/netcdf/saver.py, lib/iris/tests/integration/netcdf/test_delayed_save.py, lib/iris/tests/integration/netcdf/test_general.py, lib/iris/tests/unit/fileformats/pp/test__interpret_field.py
This has already been discussed on #6438, but I wanted to have a PR targetting `v3.12.x` as this makes the Git history less confusing.
=> Compatibility with Dask `2025.4`

.github/workflows/ci-linkchecks.yml, .lycheeignore
#6455 did not fix the GitHub rate limiting failures, and in the process made us more vulnerable by widening access to the `scitools-ci` token. I've investigated in more detail now; see comments below for explanations.
---
---
=> Various linkcheck fixes and improvements

lib/iris/fileformats/cf.py
Follow up to the changes in 03a5e72fe0dd33598c086a0c9063a181a59312a9 - it is not always possible to know the correct filename from the context of `CFVariable`.
---
---
=> Handle cases where `CFVariable` doesn't know its filename (e.g. NcData).

benchmarks/benchmarks/generate_data/__init__.py, benchmarks/benchmarks/generate_data/stock.py, docs/src/whatsnew/latest.rst
The current setup produces a long and confusing trace. Due to our use of `subprocess` to run a _separate_ Python instance, the information is provides is close to meaningless - a big block of text with the function definition, but no information about what went wrong when running the function.
<details><summary>Example from the current setup</summary>
```
For parameters: 2
File "/home/runner/work/iris/iris/benchmarks/.asv/env/e35ec55c4ba4ad9d53b3b315a88cda8c/delegated_env/lib/python3.13/site-packages/asv_runner/server.py", line 179, in _run_server
_run(run_args)
~~~~^^^^^^^^^^
File "/home/runner/work/iris/iris/benchmarks/.asv/env/e35ec55c4ba4ad9d53b3b315a88cda8c/delegated_env/lib/python3.13/site-packages/asv_runner/run.py", line 65, in _run
skip = …
```
=> More informative stack trace for benchmark data generation

docs/src/whatsnew/latest.rst, lib/iris/aux_factory.py, lib/iris/tests/unit/aux_factory/test_AtmosphereSigmaFactory.py, lib/iris/tests/unit/aux_factory/test_AuxCoordFactory.py
Closes #6404 
Automatic rechunking of derived coordinates
Investigation of the #6404 problem reveals that the points/bounds arrays of our derived (aka factory)  coords have arrays which are mostly single chunks, which could thus be very large.
This was due to the fact that they tend to be like a broadcast product of several simple one-dimensional coords (dim or aux), each spanning a different dim or two, which themselves are quite small and so tend to be all single chunks.  
When these are broadcast together, the result then tends to be one massive chunk, which can blow memory.
**For example:** 
a result formed like A * B * C, 
where these might have dims (T, Z, Y, X) of:
- A: (NT, 1, 1, 1),  
- B: (1, NZ, 1, 1),  
- C: (1, 1, NY, NX), 
which are all relatively small, and so can be single …
=> Rechunk derived

lib/iris/fileformats/netcdf/saver.py, lib/iris/tests/integration/netcdf/derived_bounds/test_bounds_files.py, lib/iris/tests/results/integration/netcdf/derived_bounds/TestBoundsFiles/test_save_primary_with_db.cdl, lib/iris/tests/results/integration/netcdf/derived_bounds/TestBoundsFiles/test_save_primary_without_db.cdl
Closes #6530
Note that the "proof" of the fix is to really compare 
https://github.com/SciTools/iris/blob/487cc7a96cb0e48256b48f5f9c7124e9f0dc671c/lib/iris/tests/results/integration/netcdf/derived_bounds/TestBoundsFiles/test_save_primary_without_db.cdl
with
https://github.com/SciTools/iris/blob/487cc7a96cb0e48256b48f5f9c7124e9f0dc671c/lib/iris/tests/results/integration/netcdf/derived_bounds/TestBoundsFiles/test_save_primary_with_db.cdl
so .. in the second case, we get [this magic extra line](https://github.com/SciTools/iris/blob/487cc7a96cb0e48256b48f5f9c7124e9f0dc671c/lib/iris/tests/results/integration/netcdf/derived_bounds/TestBoundsFiles/test_save_primary_with_db.cdl#L40)
-----
The main question there is, probably, more testing may be required - but **_can we think of any?_**
One thing …
=> Save derived bounds

lib/iris/cube.py, lib/iris/tests/test_pp_module.py
Follow-up to #6518
Closes #6542
---
---
=> Configure numpy printoptions legacy

.github/workflows/ci-wheels.yml, docs/src/whatsnew/latest.rst
[PyPI](https://pypi.org/) now supports **Trusted Publishing**, which is an OIDC-based "tokenless" authentication mechanism for uploading to the index from within a CI/CD workflow.
This "tokenless" flow has significant security benefits over a traditional manually configured API token, and should be preferred wherever supported and possible.
This pull-request also requires PyPI (and Test PyPI) to be configured for Trusted Publishing for the `scitools-iris` project, which has already been performed. 
Reference:
- [Trusted Publishers for all Package Repositories](https://repos.openssf.org/trusted-publishers-for-all-package-repositories.html)
- [Publishing to PyPI with a Trusted Publisher](https://docs.pypi.org/trusted-publishers/)
=> pypi: use trusted publishing for binary wheels

docs/src/whatsnew/latest.rst, lib/iris/fileformats/_nc_load_rules/actions.py, lib/iris/fileformats/netcdf/_attribute_handlers.py, lib/iris/fileformats/netcdf/saver.py, lib/iris/tests/integration/netcdf/test_load_managed_attributes.py, lib/iris/tests/integration/netcdf/test_save_managed_attributes.py, lib/iris/tests/integration/test_netcdf__loadsaveattrs.py, lib/iris/tests/test_netcdf.py, lib/iris/tests/unit/fileformats/nc_load_rules/actions/test__miscellaneous.py, lib/iris/tests/unit/fileformats/netcdf/attribute_handlers/__init__.py, lib/iris/tests/unit/fileformats/netcdf/attribute_handlers/test_GribParamHandler.py, lib/iris/tests/unit/fileformats/netcdf/attribute_handlers/test_StashHandler.py, lib/iris/tests/unit/fileformats/netcdf/attribute_handlers/test_UkmoProcessFlagsHandler.py
Closes https://github.com/SciTools/iris-grib/issues/596 and https://github.com/SciTools/iris-grib/issues/674
Ties together the handling of STASH, GRIB_PARAM and "ukmo__process_flags" attributes, 
which all require special handling on netcdf load+save.
By design, should preserve existing behaviour.
But I have tried to generalise the handling, 
( and also rationalise behaviour a wee bit, at least for "ukmo__process_flags" -- though that one is quite obscure ).
TODO:
- e.g. in place of a STASH object, can have just the string like "m01s02i123" (str form) or "STASH(model=...)" (repr form) . 
- ... and similar for the other 2 types
(but first, just let's see if it breaks anything I haven't already tried)
=> Generalise support for netcdf load+save of "special" attributes

docs/src/whatsnew/latest.rst, lib/iris/experimental/regrid_conservative.py, lib/iris/tests/experimental/regrid/test_regrid_conservative_via_esmpy.py
The module was renamed to ESMPy in version 8.4. We didn't notice because the module using is deprecated in favour of iris-esmf-regrid, and because we have a test skipper from back when ESMPy wasn't always included in the development environment.
---
---
=> Corrected import of ESMPy module

lib/iris/tests/unit/coords/test_CellMeasure.py, lib/iris/tests/unit/coords/test_CellMethod.py, lib/iris/tests/unit/coords/test__DimensionalMetadata.py
Note, this is split into multiple pull requests to make it easier to review. See #6606
=> Converted unit/coords to pytest: Part 1

lib/iris/tests/integration/netcdf/test_ugrid_load.py, lib/iris/tests/unit/tests/stock/test_netcdf.py, lib/iris/tests/unit/tests/test__shared_utils.py
Note: I have intentionally not converted `test_IrisTests`, as this is explicitly a unittest file and awaits deprecation.
I've done this integration test as changes to test/netcdf were breaking it. Originally I only wanted to change calls, but that was breaking enough that I decided to just convert the whole thing.
=> Converted all unit/tests tests into PyTest

lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py, lib/iris/tests/unit/analysis/regrid/test__CurvilinearRegridder.py
Pytest conversion for files in `unit/analysis/regrid/` comprising:
- test__CurvilinearRegridder.py
- test_RectilinearRegridder.py
Note, there is a potential for refactoring some repeated setup code and moving some functions to fixtures in `test_RectilinearRegridder.py`; details have been added to #6625
=> Pytest Conversion: unit/analysis/regrid/*

lib/iris/tests/unit/io/format_picker/test_FormatAgent.py, lib/iris/tests/unit/io/test__generate_cubes.py, lib/iris/tests/unit/io/test_expand_filespecs.py, lib/iris/tests/unit/io/test_run_callback.py, lib/iris/tests/unit/io/test_save.py
**_Note for reviewer_**: I had a bit of a mission preventing myself from refactoring. `test_expand_filespecs` might need an extra beat (or might be perfectly fine, who knows).
=> Converted all unit/io tests into pytest

docs/src/whatsnew/latest.rst, lib/iris/tests/test_coding_standards.py
Fix for https://github.com/SciTools/iris/issues/6667. Changes deprecated `git whatchanged` to `git log`. 
---
---
=> Fix for deprecated git `whatchanged`

.lycheeignore
This pull-request adds a `lychee` exception to the recently flaky `gitwash` mail-archive URL. 
Closes #6679.
---
---
=> Fix gitwash URL linkcheck

docs/src/whatsnew/latest.rst, lib/iris/tests/_shared_utils.py, lib/iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py, lib/iris/tests/test_analysis.py, lib/iris/tests/test_analysis_calculus.py, lib/iris/tests/test_basic_maths.py, lib/iris/tests/test_cdm.py, lib/iris/tests/test_name.py, lib/iris/tests/unit/analysis/cartography/test_project.py, lib/iris/tests/unit/analysis/interpolation/test_RectilinearInterpolator.py, lib/iris/tests/unit/analysis/regrid/test_RectilinearRegridder.py, lib/iris/tests/unit/cube/test_Cube.py
Removes the `assert_CML_approx_data` function.
The functionality is now provided in `assert_CML` with a new `approx_data` keyword.
Addresses the first bullet point of #6244
=> Rationalise CML
